MEASURE 'rpt_liquidity'[Liquidity_Measure] =

-- ========================================
-- LIQUIDITY REPORT TABLE - FOLLOW ASSET MATRIX TEMPLATE
-- Table: rpt_liquidity | Visual: HTML Content
-- ========================================

-- === TOTAL ROW VALUES ===
VAR _tVC = CALCULATE(SUM(rpt_liquidity[Vault Cash BNCTL]), rpt_liquidity[Branch Name] = "TOTAL")
VAR _tDCBCTL = CALCULATE(SUM(rpt_liquidity[Deposit With BCTL]), rpt_liquidity[Branch Name] = "TOTAL")
VAR _tDCBNU = CALCULATE(SUM(rpt_liquidity[Deposit With BNU]), rpt_liquidity[Branch Name] = "TOTAL")
VAR _tDCM = CALCULATE(SUM(rpt_liquidity[Deposit With Mandiri]), rpt_liquidity[Branch Name] = "TOTAL")
VAR _tDCO = CALCULATE(SUM(rpt_liquidity[Deposit With Others]), rpt_liquidity[Branch Name] = "TOTAL")
VAR _tHLA = CALCULATE(SUM(rpt_liquidity[Total Highly Liquid Assets]), rpt_liquidity[Branch Name] = "TOTAL")
VAR _tOC = CALCULATE(SUM(rpt_liquidity[Outstanding Credit]), rpt_liquidity[Branch Name] = "TOTAL")
VAR _tDD = CALCULATE(SUM(rpt_liquidity[Demand Deposit]), rpt_liquidity[Branch Name] = "TOTAL")
VAR _tHNF = CALCULATE(SUM(rpt_liquidity[Deposit Hau Nia Futuru]), rpt_liquidity[Branch Name] = "TOTAL")
VAR _tTD = CALCULATE(SUM(rpt_liquidity[Time Deposit]), rpt_liquidity[Branch Name] = "TOTAL")
VAR _tOD = CALCULATE(SUM(rpt_liquidity[Others Deposit]), rpt_liquidity[Branch Name] = "TOTAL")
VAR _tDEP = CALCULATE(SUM(rpt_liquidity[Total Deposit & BG]), rpt_liquidity[Branch Name] = "TOTAL")
VAR _tLIA = CALCULATE(SUM(rpt_liquidity[Total Liabilities]), rpt_liquidity[Branch Name] = "TOTAL")
VAR _tLR = CALCULATE(SUM(rpt_liquidity[Liquidity Ratio]), rpt_liquidity[Branch Name] = "TOTAL")
VAR _tLDR = CALCULATE(SUM(rpt_liquidity[LDR Ratio]), rpt_liquidity[Branch Name] = "TOTAL")

-- === HEADER WITH LOGO ===
VAR ModernHeader =
    "<div style='background-color: #003366; padding: 16px 20px; border-bottom: 4px solid #f0a500; display: flex; align-items: center; gap: 20px;'>" &
        "<img src='https://i.ibb.co/rWhBLgw/image-2026-04-21-094244962.png' alt='BNCTL Logo' style='height: 90px; width: auto; flex-shrink: 0;' />" &
        "<div style='flex: 1;'>" &
            "<div style='color: #ffffff; font-family: Segoe UI; font-size: 16px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 4px;'>" &
                "BANCO NACIONAL DE COMERCIO DE TIMOR LESTE" &
            "</div>" &
            "<div style='color: #f0a500; font-family: Segoe UI; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 4px;'>" &
                "LIQUIDITY REPORT BY BRANCH" &
            "</div>" &
            "<div style='color: #cbd5e1; font-family: Segoe UI; font-size: 11px;'>" &
                "As of: September 30, 2025" &
            "</div>" &
        "</div>" &
    "</div>"

-- === HEADER ROW 1 - GROUPED ===
VAR HeaderRow1 =
    "<tr style='background-color: #004680; color: white; height: 45px;'>" &
        "<th rowspan='2' style='padding: 12px 10px; text-align: left; position: sticky; left: 0; top: 0; background-color: #004680; z-index: 300; min-width: 160px; border-right: 2px solid #003366;'>Branch Name</th>" &
        "<th colspan='6' style='padding: 8px; text-align: center; position: sticky; top: 0; background-color: #004680; z-index: 100; border-left: 2px solid #003366;'>HIGHLY LIQUID ASSETS</th>" &
        "<th colspan='1' style='padding: 8px; text-align: center; position: sticky; top: 0; background-color: #1a5276; z-index: 100; border-left: 2px solid #003366;'>CREDIT</th>" &
        "<th colspan='5' style='padding: 8px; text-align: center; position: sticky; top: 0; background-color: #004680; z-index: 100; border-left: 2px solid #003366;'>DEPOSITS</th>" &
        "<th colspan='3' style='padding: 8px; text-align: center; position: sticky; top: 0; background-color: #003366; z-index: 100; border-left: 2px solid #003366;'>LIABILITIES & RATIOS</th>" &
    "</tr>"

-- === HEADER ROW 2 - SUB COLUMNS ===
VAR SubHdrStyle = "padding: 6px 4px; text-align: center; font-size: 11px; position: sticky; top: 45px; background-color: #f2f2f2; z-index: 90; white-space: nowrap; color: #333; border-bottom: 2px solid #004680;"
VAR SubHdrStyleBorderL = "padding: 6px 4px; text-align: center; font-size: 11px; position: sticky; top: 45px; background-color: #f2f2f2; z-index: 90; white-space: nowrap; color: #333; border-bottom: 2px solid #004680; border-left: 2px solid #ddd;"

VAR HeaderRow2 =
    "<tr style='background-color: #f2f2f2; color: #333; font-size: 12px; height: 35px;'>" &
        "<th style='" & SubHdrStyleBorderL & " min-width: 110px;'>Vault Cash BNCTL</th>" &
        "<th style='" & SubHdrStyle & " min-width: 100px;'>Dep. With BCTL</th>" &
        "<th style='" & SubHdrStyle & " min-width: 100px;'>Dep. With BNU</th>" &
        "<th style='" & SubHdrStyle & " min-width: 110px;'>Dep. With Mandiri</th>" &
        "<th style='" & SubHdrStyle & " min-width: 100px;'>Dep. With Others</th>" &
        "<th style='" & SubHdrStyle & " min-width: 120px; background-color: #e8f0fe;'>Total HLA</th>" &
        "<th style='" & SubHdrStyleBorderL & " min-width: 130px;'>Outstanding Credit</th>" &
        "<th style='" & SubHdrStyleBorderL & " min-width: 120px;'>Demand Deposit</th>" &
        "<th style='" & SubHdrStyle & " min-width: 110px;'>Dep. Hau Nia Futuru</th>" &
        "<th style='" & SubHdrStyle & " min-width: 110px;'>Time Deposit</th>" &
        "<th style='" & SubHdrStyle & " min-width: 110px;'>Others Deposit</th>" &
        "<th style='" & SubHdrStyle & " min-width: 130px; background-color: #e8f0fe;'>Total Dep. & BG</th>" &
        "<th style='" & SubHdrStyleBorderL & " min-width: 130px;'>Total Liabilities</th>" &
        "<th style='" & SubHdrStyle & " min-width: 100px;'>Liquidity Ratio</th>" &
        "<th style='" & SubHdrStyle & " min-width: 100px;'>LDR Ratio</th>" &
    "</tr>"

-- === CELL STYLES ===
VAR CellR = "text-align: right; padding: 8px 10px; border-bottom: 1px solid #eee; font-family: Consolas; font-size: 12px;"
VAR CellRBorderL = "text-align: right; padding: 8px 10px; border-bottom: 1px solid #eee; font-family: Consolas; font-size: 12px; border-left: 2px solid #e0e0e0;"
VAR CellSubtotal = "text-align: right; padding: 8px 10px; border-bottom: 1px solid #eee; font-family: Consolas; font-size: 12px; background-color: #f7faff; font-weight: 600;"

-- === DATA ROWS (exclude TOTAL) ===
VAR BranchRows =
    CONCATENATEX(
        FILTER(rpt_liquidity, rpt_liquidity[Branch Name] <> "TOTAL"),

        VAR vBranch = rpt_liquidity[Branch Name]
        VAR vVC = rpt_liquidity[Vault Cash BNCTL]
        VAR vDCBCTL = rpt_liquidity[Deposit With BCTL]
        VAR vDCBNU = rpt_liquidity[Deposit With BNU]
        VAR vDCM = rpt_liquidity[Deposit With Mandiri]
        VAR vDCO = rpt_liquidity[Deposit With Others]
        VAR vHLA = rpt_liquidity[Total Highly Liquid Assets]
        VAR vOC = rpt_liquidity[Outstanding Credit]
        VAR vDD = rpt_liquidity[Demand Deposit]
        VAR vHNF = rpt_liquidity[Deposit Hau Nia Futuru]
        VAR vTD = rpt_liquidity[Time Deposit]
        VAR vOD = rpt_liquidity[Others Deposit]
        VAR vDEP = rpt_liquidity[Total Deposit & BG]
        VAR vLIA = rpt_liquidity[Total Liabilities]
        VAR vLR = rpt_liquidity[Liquidity Ratio]
        VAR vLDR = rpt_liquidity[LDR Ratio]

        VAR txtVC = IF(vVC = 0, "—", FORMAT(vVC, "#,##0.00"))
        VAR txtDCBCTL = IF(vDCBCTL = 0, "—", FORMAT(vDCBCTL, "#,##0.00"))
        VAR txtDCBNU = IF(vDCBNU = 0, "—", FORMAT(vDCBNU, "#,##0.00"))
        VAR txtDCM = IF(vDCM = 0, "—", FORMAT(vDCM, "#,##0.00"))
        VAR txtDCO = IF(vDCO = 0, "—", FORMAT(vDCO, "#,##0.00"))
        VAR txtHLA = IF(vHLA = 0, "—", FORMAT(vHLA, "#,##0.00"))
        VAR txtOC = IF(vOC = 0, "—", FORMAT(vOC, "#,##0.00"))
        VAR txtDD = IF(vDD = 0, "—", FORMAT(vDD, "#,##0.00"))
        VAR txtHNF = IF(vHNF = 0, "—", FORMAT(vHNF, "#,##0.00"))
        VAR txtTD = IF(vTD = 0, "—", FORMAT(vTD, "#,##0.00"))
        VAR txtOD = IF(vOD = 0, "—", FORMAT(vOD, "#,##0.00"))
        VAR txtDEP = IF(vDEP = 0, "—", FORMAT(vDEP, "#,##0.00"))
        VAR txtLIA = IF(vLIA = 0, "—", FORMAT(vLIA, "#,##0.00"))
        VAR txtLR = FORMAT(vLR * 100, "#,##0.00") & "%"
        VAR txtLDR = FORMAT(vLDR * 100, "#,##0.00") & "%"

        VAR IsHO = IF(vBranch = "HEAD OFFICE (TEMP)", "#fff8e1", "#ffffff")

        RETURN
        "<tr style='background-color: " & IsHO & ";'>" &
            "<td style='padding: 10px 12px; border-bottom: 1px solid #eee; border-right: 2px solid #d0d0d0; position: sticky; left: 0; background-color: " & IsHO & "; z-index: 40; white-space: nowrap; font-family: Segoe UI; font-size: 13px; font-weight: 600; color: #333;'>" & vBranch & "</td>" &
            "<td style='" & CellRBorderL & "'>" & txtVC & "</td>" &
            "<td style='" & CellR & "'>" & txtDCBCTL & "</td>" &
            "<td style='" & CellR & "'>" & txtDCBNU & "</td>" &
            "<td style='" & CellR & "'>" & txtDCM & "</td>" &
            "<td style='" & CellR & "'>" & txtDCO & "</td>" &
            "<td style='" & CellSubtotal & "'>" & txtHLA & "</td>" &
            "<td style='" & CellRBorderL & "'>" & txtOC & "</td>" &
            "<td style='" & CellRBorderL & "'>" & txtDD & "</td>" &
            "<td style='" & CellR & "'>" & txtHNF & "</td>" &
            "<td style='" & CellR & "'>" & txtTD & "</td>" &
            "<td style='" & CellR & "'>" & txtOD & "</td>" &
            "<td style='" & CellSubtotal & "'>" & txtDEP & "</td>" &
            "<td style='" & CellRBorderL & "'>" & txtLIA & "</td>" &
            "<td style='" & CellR & "'>" & txtLR & "</td>" &
            "<td style='" & CellR & "'>" & txtLDR & "</td>" &
        "</tr>",
        "",
        rpt_liquidity[Branch Name], ASC
    )

-- === TOTAL ROW ===
VAR TotCellStyle = "text-align: right; padding: 10px; border-top: 2px solid #003366; font-family: Consolas; font-size: 13px; font-weight: 700; color: #003366; background-color: #e8f0fe;"
VAR TotCellStyleBL = "text-align: right; padding: 10px; border-top: 2px solid #003366; font-family: Consolas; font-size: 13px; font-weight: 700; color: #003366; background-color: #e8f0fe; border-left: 2px solid #c0d0e0;"
VAR TotSubStyle = "text-align: right; padding: 10px; border-top: 2px solid #003366; font-family: Consolas; font-size: 13px; font-weight: 700; color: #003366; background-color: #dce6f5;"

VAR fmtTotVC = IF(_tVC = 0, "—", FORMAT(_tVC, "#,##0.00"))
VAR fmtTotDCBCTL = IF(_tDCBCTL = 0, "—", FORMAT(_tDCBCTL, "#,##0.00"))
VAR fmtTotDCBNU = IF(_tDCBNU = 0, "—", FORMAT(_tDCBNU, "#,##0.00"))
VAR fmtTotDCM = IF(_tDCM = 0, "—", FORMAT(_tDCM, "#,##0.00"))
VAR fmtTotDCO = IF(_tDCO = 0, "—", FORMAT(_tDCO, "#,##0.00"))
VAR fmtTotHLA = IF(_tHLA = 0, "—", FORMAT(_tHLA, "#,##0.00"))
VAR fmtTotOC = IF(_tOC = 0, "—", FORMAT(_tOC, "#,##0.00"))
VAR fmtTotDD = IF(_tDD = 0, "—", FORMAT(_tDD, "#,##0.00"))
VAR fmtTotHNF = IF(_tHNF = 0, "—", FORMAT(_tHNF, "#,##0.00"))
VAR fmtTotTD = IF(_tTD = 0, "—", FORMAT(_tTD, "#,##0.00"))
VAR fmtTotOD = IF(_tOD = 0, "—", FORMAT(_tOD, "#,##0.00"))
VAR fmtTotDEP = IF(_tDEP = 0, "—", FORMAT(_tDEP, "#,##0.00"))
VAR fmtTotLIA = IF(_tLIA = 0, "—", FORMAT(_tLIA, "#,##0.00"))
VAR fmtTotLR = FORMAT(_tLR * 100, "#,##0.00") & "%"
VAR fmtTotLDR = FORMAT(_tLDR * 100, "#,##0.00") & "%"

VAR TotalRow =
    "<tr>" &
        "<td style='padding: 10px 12px; border-top: 2px solid #003366; position: sticky; left: 0; background-color: #e8f0fe; z-index: 40; font-family: Segoe UI; font-size: 14px; font-weight: 700; color: #003366; border-right: 2px solid #c0d0e0;'>TOTAL</td>" &
        "<td style='" & TotCellStyleBL & "'>" & fmtTotVC & "</td>" &
        "<td style='" & TotCellStyle & "'>" & fmtTotDCBCTL & "</td>" &
        "<td style='" & TotCellStyle & "'>" & fmtTotDCBNU & "</td>" &
        "<td style='" & TotCellStyle & "'>" & fmtTotDCM & "</td>" &
        "<td style='" & TotCellStyle & "'>" & fmtTotDCO & "</td>" &
        "<td style='" & TotSubStyle & "'>" & fmtTotHLA & "</td>" &
        "<td style='" & TotCellStyleBL & "'>" & fmtTotOC & "</td>" &
        "<td style='" & TotCellStyleBL & "'>" & fmtTotDD & "</td>" &
        "<td style='" & TotCellStyle & "'>" & fmtTotHNF & "</td>" &
        "<td style='" & TotCellStyle & "'>" & fmtTotTD & "</td>" &
        "<td style='" & TotCellStyle & "'>" & fmtTotOD & "</td>" &
        "<td style='" & TotSubStyle & "'>" & fmtTotDEP & "</td>" &
        "<td style='" & TotCellStyleBL & "'>" & fmtTotLIA & "</td>" &
        "<td style='" & TotCellStyle & "'>" & fmtTotLR & "</td>" &
        "<td style='" & TotCellStyle & "'>" & fmtTotLDR & "</td>" &
    "</tr>"

-- === FOOTER ===
VAR FooterSection =
    "<div style='background-color: #f8fafc; border-top: 1px solid #e2e8f0; padding: 7px 15px; display: flex; justify-content: space-between;'>" &
        "<span style='font-family: Segoe UI; font-size: 10px; color: #9ca3af;'>USD | Scroll horizontally to view all columns</span>" &
        "<span style='font-family: Segoe UI; font-size: 10px; color: #9ca3af;'>BNCTL &mdash; Confidential</span>" &
    "</div>"

-- === RETURN FULL HTML ===
RETURN
"<div style='font-family: Segoe UI, sans-serif; background-color: #ffffff;'>" &
    ModernHeader &
    "<div style='overflow: auto; max-height: 850px; border: 1px solid #ccc; border-top: none;'>" &
        "<table style='width: 100%; border-collapse: collapse;'>" &
            "<thead>" & HeaderRow1 & HeaderRow2 & "</thead>" &
            "<tbody>" & BranchRows & TotalRow & "</tbody>" &
        "</table>" &
    "</div>" &
    FooterSection &
"</div>"

