MEASURE 'final_provision_report'[Provision_HTML] =
VAR SelectedYear  = SELECTEDVALUE( 'Calendar_Credit'[Year] )
VAR SelectedMonth = SELECTEDVALUE( 'Calendar_Credit'[report_month] )
VAR MaxDate       = MAX( final_provision_report[load_date] )
VAR MaxYear       = LEFT( MaxDate, 4 )
VAR ActiveYear    = IF( ISBLANK(SelectedYear),  MaxYear,  SelectedYear )
VAR ActiveMonth   = IF( ISBLANK(SelectedMonth), LEFT(MaxDate,7), SelectedMonth )

VAR MonthDirectFiltered =
    ISFILTERED('Calendar_Credit'[report_month]) ||
    ISFILTERED('Calendar_Credit'[MonthLabel])   ||
    ISFILTERED('Calendar_Credit'[MonthNum])     ||
    ISFILTERED('Calendar_Credit'[SortKey])
VAR YearOnlyMode = ISFILTERED('Calendar_Credit'[Year]) && NOT MonthDirectFiltered
VAR IsMonthMode  = NOT YearOnlyMode
VAR ModeTag      = IF(IsMonthMode, "MoM", "YoY")

VAR PeriodLabel =
    IF( MonthDirectFiltered,
        "For the Month of " & FORMAT( DATE( VALUE(LEFT(ActiveMonth,4)), VALUE(RIGHT(ActiveMonth,2)), 1 ), "MMMM YYYY" ),
        "For the Year " & ActiveYear )

VAR SnapDate =
    IF( MonthDirectFiltered,
        MAXX(FILTER(final_provision_report, LEFT([load_date],7) <= ActiveMonth), [load_date]),
    IF( YearOnlyMode,
        MAXX(FILTER(final_provision_report, LEFT([load_date],4) = ActiveYear),  [load_date]),
        MaxDate
    ))

VAR CompDate =
    IF( IsMonthMode,
        MAXX(FILTER(final_provision_report, [load_date] < SnapDate), [load_date]),
        MAXX(FILTER(final_provision_report, LEFT([load_date],4) = FORMAT(VALUE(LEFT(SnapDate,4))-1,"0000")), [load_date])
    )

VAR CurrLabel = IF(ISBLANK(SnapDate), "Current",
    FORMAT(DATE(VALUE(LEFT(SnapDate,4)),VALUE(MID(SnapDate,6,2)),1),"MMM YYYY"))
VAR CompLabel = IF(ISBLANK(CompDate), "N/A",
    FORMAT(DATE(VALUE(LEFT(CompDate,4)),VALUE(MID(CompDate,6,2)),1),"MMM YYYY"))

VAR tblCurr = FILTER(final_provision_report, [load_date] = SnapDate)
VAR tblComp = FILTER(final_provision_report, [load_date] = CompDate)

VAR TotalOutCurr   = SUMX( tblCurr, ABS( IFERROR( VALUE([outstanding]), 0 ) ) )
VAR TotalOutComp   = SUMX( tblComp, ABS( IFERROR( VALUE([outstanding]), 0 ) ) )
VAR TotalOutDelta  = TotalOutCurr - TotalOutComp
VAR TotalCommitment = SUMX( tblCurr, IFERROR( VALUE([commitment]), 0 ) )
VAR TotalProvCurr  = SUMX( tblCurr, ABS( IFERROR( VALUE([provision]), 0 ) ) )
VAR TotalProvComp  = SUMX( tblComp, ABS( IFERROR( VALUE([provision]), 0 ) ) )
VAR TotalProvDelta = TotalProvCurr - TotalProvComp
VAR RowCount       = COUNTROWS( tblCurr )

VAR Sty =
    "<style>" &
    ".pv{font-family:Segoe UI,Calibri,sans-serif;font-size:10.5px;color:#1e2d40;}" &
    ".pv-t{width:100%;border-collapse:collapse;}" &
    ".pv-t td{padding:4px 8px;border-bottom:1px solid #e8edf3;vertical-align:middle;white-space:nowrap;}" &
    ".pv-t tr:hover td{background:#f5f8ff;}" &
    ".pv-t thead th{background:#003366;color:#fff;font-weight:700;font-size:10px;text-transform:uppercase;letter-spacing:0.4px;border-bottom:3px solid #f0a500;padding:7px 8px;text-align:left;white-space:nowrap;}" &
    ".pv-t thead th.ar{text-align:right;}" &
    ".pv-t thead th.ac{text-align:center;}" &
    ".ar{text-align:right!important;font-family:Consolas,monospace;font-size:10px;}" &
    ".ac{text-align:center!important;font-size:10px;}" &
    ".nm{font-weight:500;font-size:10.5px;}" &
    ".lid{font-family:Consolas,monospace;font-size:10px;color:#374151;}" &
    ".cl-STD{background:#dcfce7;color:#166534;font-weight:700;font-size:9px;padding:2px 7px;border-radius:10px;display:inline-block;}" &
    ".cl-SUB{background:#fff7ed;color:#c2410c;font-weight:700;font-size:9px;padding:2px 7px;border-radius:10px;display:inline-block;}" &
    ".cl-DBT{background:#fef3c7;color:#b45309;font-weight:700;font-size:9px;padding:2px 7px;border-radius:10px;display:inline-block;}" &
    ".cl-LSS{background:#fee2e2;color:#dc2626;font-weight:700;font-size:9px;padding:2px 7px;border-radius:10px;display:inline-block;}" &
    ".cl-OTH{background:#f3f4f6;color:#6b7280;font-weight:700;font-size:9px;padding:2px 7px;border-radius:10px;display:inline-block;}" &
    ".st-CUR{color:#16a34a;font-weight:600;font-size:10px;}" &
    ".st-OTH{color:#dc2626;font-weight:600;font-size:10px;}" &
    ".gt td{background:#003366!important;color:#fff!important;font-weight:800;font-size:11px;border-top:2px solid #f0a500!important;}" &
    ".gt td.ar{font-family:Consolas,monospace;text-align:right;color:#f0a500!important;}" &
    ".zero{color:#d1d5db;}" &
    "</style>.pos{color:#16a34a;font-weight:700;font-family:Consolas,monospace;}.neg{color:#dc2626;font-weight:700;font-family:Consolas,monospace;}.neu{color:#6b7280;font-family:Consolas,monospace;}.nr td{background:#fefce8!important;}.ch td{background:#f0fdf4!important;}</style>"

VAR Hdr =
    "<div style='background:#003366;padding:16px 20px;border-bottom:4px solid #f0a500;display:flex;align-items:center;'>" &
    "<img src='https://i.ibb.co/rWhBLgw/image-2026-04-21-094244962.png' style='height:90px;object-fit:contain;flex-shrink:0;margin-right:20px;' /><div>" &
    "<div style='color:#fff;font-family:Segoe UI,sans-serif;font-size:17px;font-weight:700;text-transform:uppercase;letter-spacing:1px;margin-bottom:4px;'>BANCO NACIONAL DE COMERCIO DE TIMOR LESTE</div>" &
    "<div style='color:#f0a500;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:2px;margin-bottom:6px;'>PROVISION REPORT  -  PAST DUE  -  " & ModeTag & " COMPARISON</div>" &
    "<div style='color:#cbd5e1;font-size:11px;'>" & PeriodLabel & "</div>" &
    "<div style='color:#94a3b8;font-size:10px;margin-top:3px;'>Current: " & CurrLabel & " &nbsp;vs&nbsp; Previous: " & CompLabel & "</div>" &
    "</div></div>"

VAR Summary =
    "<div style='display:flex;gap:12px;flex-wrap:wrap;padding:14px 16px;background:#f8fafc;border-bottom:1px solid #e2e8f0;'>" &
    "<div style='background:#fff;border:1px solid #e2e8f0;border-radius:6px;padding:10px 16px;min-width:180px;'><div style='font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Total Outstanding</div><div style='font-size:15px;font-weight:800;color:#003366;font-family:Consolas,monospace;'>" & FORMAT(TotalOutCurr,"#,##0.00") & "</div></div>" &
    "<div style='background:#e0f2fe;border:1px solid #bae6fd;border-radius:6px;padding:10px 16px;min-width:180px;'><div style='font-size:9px;color:#0369a1;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Prev (" & CompLabel & ")</div><div style='font-size:15px;font-weight:800;color:#0369a1;font-family:Consolas,monospace;'>" & FORMAT(TotalOutComp,"#,##0.00") & "</div></div>" &
    "<div style='background:#" & IF(TotalOutDelta>0,"dcfce7",IF(TotalOutDelta<0,"fee2e2","f3f4f6")) & ";border:1px solid #e2e8f0;border-radius:6px;padding:10px 16px;min-width:140px;'><div style='font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Total Outstanding Delta</div><div style='font-size:14px;font-weight:800;" & IF(TotalOutDelta>0,"color:#16a34a",IF(TotalOutDelta<0,"color:#dc2626","color:#6b7280")) & ";font-family:Consolas,monospace;'>" & FORMAT(TotalOutDelta,"+#,##0.00;-#,##0.00;0.00") & "</div></div>" &
    "<div style='background:#fff;border:1px solid #e2e8f0;border-radius:6px;padding:10px 16px;min-width:180px;'><div style='font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Total Commitment</div><div style='font-size:15px;font-weight:800;color:#1a4a7a;font-family:Consolas,monospace;'>" & FORMAT(TotalCommitment,"#,##0.00") & "</div></div>" &
    "<div style='background:#fff;border:1px solid #e2e8f0;border-radius:6px;padding:10px 16px;min-width:180px;'><div style='font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Total Provision</div><div style='font-size:15px;font-weight:800;color:#dc2626;font-family:Consolas,monospace;'>" & FORMAT(TotalProvCurr,"#,##0.00") & "</div></div>" &
    "<div style='background:#e0f2fe;border:1px solid #bae6fd;border-radius:6px;padding:10px 16px;min-width:180px;'><div style='font-size:9px;color:#0369a1;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Prev (" & CompLabel & ")</div><div style='font-size:15px;font-weight:800;color:#dc2626;font-family:Consolas,monospace;'>" & FORMAT(TotalProvComp,"#,##0.00") & "</div></div>" &
    "<div style='background:#" & IF(TotalProvDelta>0,"dcfce7",IF(TotalProvDelta<0,"fee2e2","f3f4f6")) & ";border:1px solid #e2e8f0;border-radius:6px;padding:10px 16px;min-width:140px;'><div style='font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Total Provision Delta</div><div style='font-size:14px;font-weight:800;" & IF(TotalProvDelta>0,"color:#16a34a",IF(TotalProvDelta<0,"color:#dc2626","color:#6b7280")) & ";font-family:Consolas,monospace;'>" & FORMAT(TotalProvDelta,"+#,##0.00;-#,##0.00;0.00") & "</div></div>" &
    "</div>"

VAR TH =
    "<table class='pv-t'><thead><tr>" &
    "<th rowspan='2'>LOAN ID</th><th rowspan='2'>ORIGINAL LOAN ID</th><th rowspan='2'>ARRANGEMENT ID</th>" &
    "<th rowspan='2'>BRANCH</th><th rowspan='2'>CUST NO.</th><th rowspan='2'>CUSTOMER NAME</th>" &
    "<th rowspan='2' class='ac'>CAT</th><th rowspan='2'>PRODUCT</th><th rowspan='2' class='ac'>CCY</th>" &
    "<th rowspan='2' class='ac'>CLASSIFICATION</th><th rowspan='2' class='ar'>LOCAL CCY AMT</th><th rowspan='2' class='ar'>BASE AMOUNT</th>" &
    "<th colspan='3' class='grp' style='background:#1a4a7a;text-align:center;'>OUTSTANDING [" & ModeTag & "]</th>" &
    "<th rowspan='2' class='ac'>VALUE DATE</th><th rowspan='2' class='ar'>COMMITMENT</th>" &
    "<th rowspan='2' class='ac'>ODD</th><th rowspan='2' class='ac'>START DATE</th><th rowspan='2' class='ac'>MAT DATE</th>" &
    "<th colspan='3' class='grp' style='background:#1a4a7a;text-align:center;'>PROVISION [" & ModeTag & "]</th>" &
    "<th rowspan='2' class='ac'>STATUS</th>" &
    "</tr><tr>" &
    "<th class='ar'>" & CurrLabel & "</th><th class='ar'>" & CompLabel & "</th><th class='ar'>DELTA</th>" &
    "<th class='ar'>" & CurrLabel & "</th><th class='ar'>" & CompLabel & "</th><th class='ar'>DELTA</th>" &
    "</tr></thead><tbody>"

VAR GrandTotal =
    "<tr class='gt'><td colspan='10'>GRAND TOTAL (" & FORMAT(RowCount,"#,##0") & " loans)</td>" &
    "<td class='ar'>" & FORMAT(SUMX(tblCurr,ABS(IFERROR(VALUE([local_ccy_amt]),0))),"#,##0.00") & "</td>" &
    "<td class='ar'>" & FORMAT(SUMX(tblCurr,ABS(IFERROR(VALUE([base_amount]),0))),"#,##0.00") & "</td>" &
    "<td class='ar'>" & FORMAT(TotalOutCurr,"#,##0.00") & "</td>" &
    "<td class='ar'>" & FORMAT(TotalOutComp,"#,##0.00") & "</td>" &
    "<td class='ar'>" & FORMAT(TotalOutDelta,"+#,##0.00;-#,##0.00;0.00") & "</td>" &
    "<td class='ac'> - </td><td class='ar'>" & FORMAT(TotalCommitment,"#,##0.00") & "</td>" &
    "<td class='ac'> - </td><td class='ac'> - </td><td class='ac'> - </td>" &
    "<td class='ar'>" & FORMAT(TotalProvCurr,"#,##0.00") & "</td>" &
    "<td class='ar'>" & FORMAT(TotalProvComp,"#,##0.00") & "</td>" &
    "<td class='ar'>" & FORMAT(TotalProvDelta,"+#,##0.00;-#,##0.00;0.00") & "</td>" &
    "<td class='ac'> - </td></tr>"

VAR Ftr =
    "<div style='background:#f8fafc;border-top:1px solid #e2e8f0;padding:7px 15px;display:flex;justify-content:space-between;'>" &
    "<span style='font-size:10px;color:#9ca3af;'>All amounts in USD &nbsp;|&nbsp; Negative amounts displayed as absolute values</span>" &
    "<span style='font-size:10px;color:#9ca3af;'>BNCTL  -  Confidential</span>" &
    "</div>"


VAR _PgSize  = 30
VAR _PgNum   = SELECTEDVALUE('PageNum'[Page Number], 1)
VAR _TotRows = COUNTROWS(tblCurr)
VAR _TotPg   = MAX(1, CEILING(_TotRows / _PgSize, 1))
VAR _PgValid = MIN(MAX(1, _PgNum), _TotPg)
VAR _Skip    = (_PgValid - 1) * _PgSize
VAR tblPage  = EXCEPT(
    TOPN(_Skip + _PgSize, tblCurr, [loan_id], ASC),
    TOPN(_Skip,           tblCurr, [loan_id], ASC)
)

VAR DataRows =
    CONCATENATEX(
        tblPage,
        VAR _lid  = [loan_id]
        VAR _olid = [original_loan_id]
        VAR _arr  = [arrangement_id]
        VAR _brn  = [branch_code]
        VAR _brnm = [branch_name]
        VAR _cust = [cust_number]
        VAR _nm   = [customer_name]
        VAR _cat  = [category]
        VAR _prod = [product_name]
        VAR _ccy  = [currency]
        VAR _cls  = [classification]
        VAR _lca  = ABS(IFERROR(VALUE([local_ccy_amt]),0))
        VAR _ba   = ABS(IFERROR(VALUE([base_amount]),0))
        VAR _outC = ABS(IFERROR(VALUE([outstanding]),0))
        VAR _vd   = [value_date]
        VAR _comm = IFERROR(VALUE([commitment]),0)
        VAR _odd  = IFERROR(VALUE([over_due_days]),0)
        VAR _sd   = [start_date]
        VAR _md   = [mat_date]
        VAR _prvC = ABS(IFERROR(VALUE([provision]),0))
        VAR _sts  = [status]
        VAR _cr   = FILTER(tblComp, [loan_id] = _lid)
        VAR _outP = MAXX(_cr, ABS(IFERROR(VALUE([outstanding]),0)))
        VAR _prvP = MAXX(_cr, ABS(IFERROR(VALUE([provision]),0)))
        VAR _isN  = ISBLANK(MAXX(_cr, [loan_id]))
        VAR _outD = _outC - IF(_isN,0,_outP)
        VAR _prvD = _prvC - IF(_isN,0,_prvP)
        VAR _rCls = IF(_isN," class='nr'",IF(OR(_outD<>0,_prvD<>0)," class='ch'",""))
        VAR _oC   = IF(_outD>0," pos",IF(_outD<0," neg"," neu"))
        VAR _pC   = IF(_prvD>0," pos",IF(_prvD<0," neg"," neu"))
        VAR _clsB = SWITCH(UPPER(_cls),
            "STANDARD",    "<span class='cl-STD'>STANDARD</span>",
            "SUB-STANDARD","<span class='cl-SUB'>SUB-STD</span>",
            "SUBSTANDARD", "<span class='cl-SUB'>SUB-STD</span>",
            "DOUBTFUL",    "<span class='cl-DBT'>DOUBTFUL</span>",
            "LOSS",        "<span class='cl-LSS'>LOSS</span>",
            IF(ISBLANK(_cls),"<span class='zero'> - </span>","<span class='cl-OTH'>" & _cls & "</span>"))
        VAR _stsB = IF(UPPER(_sts)="CURRENT","<span class='st-CUR'>CURRENT</span>",
            IF(ISBLANK(_sts),"<span class='zero'> - </span>","<span class='st-OTH'>" & UPPER(_sts) & "</span>"))
        RETURN "<tr" & _rCls & ">" &
        "<td class='lid'>" & _lid & "</td>" &
        "<td class='lid'>" & IF(ISBLANK(_olid),"<span class='zero'> - </span>",_olid) & "</td>" &
        "<td class='lid'>" & _arr & "</td>" &
        "<td style='font-size:10px;color:#374151;'>" & _brn & IF(ISBLANK(_brnm),"","<div style='font-size:9px;color:#6b7280;margin-top:1px;'>" & _brnm & "</div>") & "</td>" &
        "<td class='ac' style='font-size:10px;color:#6b7280;'>" & _cust & "</td>" &
        "<td class='nm'>" & _nm & "</td>" &
        "<td class='ac' style='font-size:10px;color:#6b7280;'>" & _cat & "</td>" &
        "<td style='font-size:10px;'>" & _prod & "</td>" &
        "<td class='ac' style='font-size:10px;font-weight:600;color:#1a4a7a;'>" & _ccy & "</td>" &
        "<td class='ac'>" & _clsB & "</td>" &
        "<td class='ar'>" & IF(_lca=0,"<span class='zero'>-</span>",FORMAT(_lca,"#,##0.00")) & "</td>" &
        "<td class='ar'>" & IF(_ba=0,"<span class='zero'>-</span>",FORMAT(_ba,"#,##0.00")) & "</td>" &
        "<td class='ar' style='font-weight:600;'>" & IF(_outC=0,"<span class='zero'>-</span>",FORMAT(_outC,"#,##0.00")) & "</td>" &
        "<td class='ar'>" & IF(_isN,"<span class='zero'>NEW</span>",IF(_outP=0,"<span class='zero'>-</span>",FORMAT(_outP,"#,##0.00"))) & "</td>" &
        "<td class='ar" & _oC & "'>" & IF(_isN,"NEW",FORMAT(_outD,"+#,##0.00;-#,##0.00;0.00")) & "</td>" &
        "<td class='ac' style='font-size:10px;'>" & IF(ISBLANK(_vd),"<span class='zero'> - </span>",LEFT(_vd,4)&"-"&MID(_vd,5,2)&"-"&RIGHT(_vd,2)) & "</td>" &
        "<td class='ar'>" & IF(_comm=0,"<span class='zero'>-</span>",FORMAT(_comm,"#,##0.00")) & "</td>" &
        "<td class='ac' style='font-size:10px;" & IF(_odd>0,"color:#dc2626;font-weight:700;","color:#d1d5db;") & "'>" & IF(_odd=0," - ",FORMAT(_odd,"#,##0")&" d") & "</td>" &
        "<td class='ac' style='font-size:10px;'>" & IF(ISBLANK(_sd),"<span class='zero'> - </span>",LEFT(_sd,4)&"-"&MID(_sd,5,2)&"-"&RIGHT(_sd,2)) & "</td>" &
        "<td class='ac' style='font-size:10px;'>" & IF(ISBLANK(_md),"<span class='zero'> - </span>",LEFT(_md,4)&"-"&MID(_md,5,2)&"-"&RIGHT(_md,2)) & "</td>" &
        "<td class='ar' style='font-weight:600;" & IF(_prvC>0,"color:#dc2626;","color:#d1d5db;") & "'>" & IF(_prvC=0,"-",FORMAT(_prvC,"#,##0.00")) & "</td>" &
        "<td class='ar'>" & IF(_isN,"<span class='zero'>NEW</span>",IF(_prvP=0,"<span class='zero'>-</span>",FORMAT(_prvP,"#,##0.00"))) & "</td>" &
        "<td class='ar" & _pC & "'>" & IF(_isN,"NEW",FORMAT(_prvD,"+#,##0.00;-#,##0.00;0.00")) & "</td>" &
        "<td class='ac'>" & _stsB & "</td></tr>",
        ,
        [loan_id], ASC
    )


VAR _WinStart  = MAX(1, _PgValid - 4)
VAR _WinEnd    = MIN(_TotPg, _PgValid + 4)
VAR _ShowFirst = _WinStart > 1
VAR _ShowLast  = _WinEnd < _TotPg
VAR _PgButtons =
    IF(_ShowFirst,
        "<span style='display:inline-flex;align-items:center;justify-content:center;" &
        "min-width:26px;height:26px;padding:0 6px;border-radius:5px;font-size:12px;margin:0 2px;" &
        "background:#f1f5f9;color:#64748b;'>1</span>" &
        IF(_WinStart > 2, "<span style='color:#94a3b8;margin:0 2px;'>...</span>", ""),
        ""
    ) &
    CONCATENATEX(
        GENERATESERIES(_WinStart, _WinEnd, 1),
        VAR _p   = [Value]
        VAR _act = _p = _PgValid
        RETURN
        "<span style='display:inline-flex;align-items:center;justify-content:center;" &
        "min-width:26px;height:26px;padding:0 6px;border-radius:5px;font-size:12px;margin:0 2px;" &
        "font-weight:" & IF(_act,"700","400") & ";" &
        IF(_act,
            "background:#3b82f6;color:#fff;box-shadow:0 2px 4px rgba(59,130,246,0.35);",
            "background:#f1f5f9;color:#64748b;"
        ) & "'>" & _p & "</span>",
        "",
        [Value], ASC
    ) &
    IF(_ShowLast,
        IF(_WinEnd < _TotPg - 1, "<span style='color:#94a3b8;margin:0 2px;'>...</span>", "") &
        "<span style='display:inline-flex;align-items:center;justify-content:center;" &
        "min-width:26px;height:26px;padding:0 6px;border-radius:5px;font-size:12px;margin:0 2px;" &
        "background:#f1f5f9;color:#64748b;'>" & _TotPg & "</span>",
        ""
    )
VAR PgBar =
    "<div style='background:#f8fafc;border-top:2px solid #e2e8f0;padding:10px 16px;" &
    "display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:6px;'>" &
    "<span style='font-size:11px;color:#64748b;'>Showing " &
    "<b style='color:#1e293b;'>" & (_Skip + 1) & "</b> &ndash; " &
    "<b style='color:#1e293b;'>" & MIN(_Skip + _PgSize, _TotRows) & "</b>" &
    " of <b style='color:#1e293b;'>" & _TotRows & "</b> records</span>" &
    "<div style='display:flex;align-items:center;'>" & _PgButtons & "</div>" &
    "<span style='font-size:10px;color:#94a3b8;font-style:italic;'>Use PageNum slicer</span>" &
    "</div>"

RETURN
    "<div class='pv'>" & Sty & Hdr & Summary &
    "<div style='overflow-x:auto;'>" & TH & DataRows & GrandTotal &
    "</tbody></table></div>" & Ftr & PgBar & "</div>"
