MEASURE 'soc_assets_real_v2'[SOC_Assets_HTML] =
VAR SelectedYear  = SELECTEDVALUE( Calendar[Year] )
VAR SelectedMonth = SELECTEDVALUE( Calendar[report_month] )
VAR MaxMonth      = MAX( soc_assets_real_v2[report_month] )
VAR MaxYear       = LEFT( MaxMonth, 4 )
VAR ActiveYear    = IF( ISBLANK(SelectedYear), MaxYear, SelectedYear )
VAR ActiveMonth   = IF( ISBLANK(SelectedMonth), MaxMonth, SelectedMonth )
VAR PeriodLabel   =
    IF( NOT ISBLANK(SelectedMonth),
        "For the Month of " & FORMAT( DATE( LEFT(ActiveMonth,4), RIGHT(ActiveMonth,2), 1 ), "MMMM YYYY" ),
        "For the Year Ended " & ActiveYear )
VAR tbl = FILTER( ALL(soc_assets_real_v2),
    IF( NOT ISBLANK(SelectedMonth), [report_month]=ActiveMonth, LEFT([report_month],4)=ActiveYear ) )
VAR o1_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o1_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o1_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o1_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o1_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o1_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o1_CI = SUMX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o1_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o1_YI = SUMX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o1_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o2_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o2_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o2_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o2_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o2_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o2_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o2_CI = SUMX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o2_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o2_YI = SUMX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o2_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o3_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o3_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o3_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o3_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o3_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o3_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o3_CI = SUMX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o3_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o3_YI = SUMX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o3_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o4_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o4_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o4_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o4_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o4_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o4_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o4_CI = SUMX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o4_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o4_YI = SUMX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o4_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o5_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o5_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o5_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o5_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o5_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o5_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o5_CI = SUMX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o5_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o5_YI = SUMX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o5_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o6_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o6_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o6_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o6_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o6_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o6_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o6_CI = SUMX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o6_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o6_YI = SUMX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o6_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o7_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o7_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o7_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o7_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o7_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o7_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o7_CI = SUMX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o7_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o7_YI = SUMX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o7_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o8_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o8_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o8_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o8_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o8_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o8_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o8_CI = SUMX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o8_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o8_YI = SUMX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o8_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o9_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o9_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o9_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o9_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o9_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o9_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o9_CI = SUMX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o9_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o9_YI = SUMX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o9_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o10_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o10_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o10_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o10_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o10_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o10_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o10_CI = SUMX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o10_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o10_YI = SUMX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o10_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o11_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o11_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o11_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o11_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o11_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o11_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o11_CI = SUMX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o11_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o11_YI = SUMX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o11_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o12_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o12_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o12_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o12_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o12_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o12_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o12_CI = SUMX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o12_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o12_YI = SUMX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o12_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o13_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o13_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o13_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o13_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o13_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o13_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o13_CI = SUMX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o13_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o13_YI = SUMX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o13_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o14_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o14_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o14_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o14_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o14_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o14_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o14_CI = SUMX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o14_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o14_YI = SUMX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o14_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o15_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o15_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o15_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o15_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o15_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o15_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o15_CI = SUMX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o15_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o15_YI = SUMX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o15_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o16_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o16_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o16_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o16_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o16_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o16_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o16_CI = SUMX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o16_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o16_YI = SUMX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o16_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o17_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o17_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o17_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o17_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o17_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o17_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o17_CI = SUMX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o17_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o17_YI = SUMX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o17_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o18_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o18_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o18_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o18_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o18_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o18_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o18_CI = SUMX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o18_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o18_YI = SUMX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o18_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o19_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o19_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o19_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o19_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o19_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o19_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o19_CI = SUMX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o19_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o19_YI = SUMX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o19_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o20_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o20_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o20_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o20_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o20_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o20_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o20_CI = SUMX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o20_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o20_YI = SUMX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o20_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o21_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o21_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o21_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o21_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o21_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o21_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o21_CI = SUMX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o21_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o21_YI = SUMX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o21_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o22_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o22_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o22_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o22_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o22_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o22_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o22_CI = SUMX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o22_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o22_YI = SUMX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o22_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o23_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o23_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o23_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o23_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o23_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o23_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o23_CI = SUMX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o23_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o23_YI = SUMX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o23_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o24_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o24_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o24_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o24_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o24_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o24_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o24_CI = SUMX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o24_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o24_YI = SUMX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o24_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o25_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o25_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o25_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o25_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o25_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o25_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o25_CI = SUMX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o25_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o25_YI = SUMX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o25_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o26_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o26_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o26_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o26_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o26_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o26_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o26_CI = SUMX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o26_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o26_YI = SUMX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o26_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o27_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o27_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o27_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o27_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o27_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o27_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o27_CI = SUMX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o27_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o27_YI = SUMX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o27_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o28_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o28_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o28_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o28_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o28_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o28_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o28_CI = SUMX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o28_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o28_YI = SUMX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o28_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o29_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o29_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o29_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o29_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o29_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o29_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o29_CI = SUMX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o29_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o29_YI = SUMX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o29_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o30_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o30_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o30_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o30_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o30_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o30_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o30_CI = SUMX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o30_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o30_YI = SUMX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o30_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o31_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o31_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o31_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o31_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o31_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o31_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o31_CI = SUMX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o31_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o31_YI = SUMX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o31_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o32_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o32_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o32_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o32_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o32_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o32_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o32_CI = SUMX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o32_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o32_YI = SUMX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o32_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o33_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o33_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o33_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o33_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o33_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o33_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o33_CI = SUMX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o33_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o33_YI = SUMX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o33_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o34_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o34_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o34_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o34_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o34_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o34_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o34_CI = SUMX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o34_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o34_YI = SUMX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o34_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o35_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o35_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o35_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o35_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o35_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o35_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o35_CI = SUMX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o35_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o35_YI = SUMX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o35_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o36_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o36_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o36_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o36_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o36_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o36_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o36_CI = SUMX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o36_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o36_YI = SUMX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o36_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o37_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o37_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o37_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o37_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o37_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o37_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o37_CI = SUMX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o37_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o37_YI = SUMX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o37_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o38_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o38_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o38_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o38_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o38_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o38_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o38_CI = SUMX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o38_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o38_YI = SUMX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o38_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o39_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o39_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o39_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o39_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o39_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o39_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o39_CI = SUMX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o39_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o39_YI = SUMX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o39_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o40_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o40_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o40_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o40_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o40_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o40_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o40_CI = SUMX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o40_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o40_YI = SUMX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o40_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o41_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o41_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o41_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o41_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o41_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o41_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o41_CI = SUMX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o41_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o41_YI = SUMX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o41_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o42_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o42_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o42_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o42_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o42_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o42_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o42_CI = SUMX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o42_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o42_YI = SUMX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o42_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o43_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o43_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o43_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o43_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o43_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o43_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o43_CI = SUMX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o43_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o43_YI = SUMX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o43_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o44_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o44_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o44_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o44_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o44_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o44_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o44_CI = SUMX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o44_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o44_YI = SUMX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o44_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o45_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o45_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o45_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o45_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o45_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o45_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o45_CI = SUMX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o45_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o45_YI = SUMX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o45_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o46_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o46_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o46_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o46_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o46_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o46_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o46_CI = SUMX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o46_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o46_YI = SUMX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o46_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o47_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o47_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o47_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o47_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o47_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o47_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o47_CI = SUMX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o47_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o47_YI = SUMX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o47_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o48_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o48_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o48_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o48_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o48_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o48_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o48_CI = SUMX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o48_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o48_YI = SUMX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o48_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o49_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o49_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o49_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o49_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o49_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o49_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o49_CI = SUMX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o49_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o49_YI = SUMX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o49_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o50_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o50_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o50_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o50_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o50_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o50_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o50_CI = SUMX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o50_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o50_YI = SUMX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o50_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o51_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o51_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o51_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o51_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o51_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o51_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o51_CI = SUMX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o51_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o51_YI = SUMX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o51_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o52_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o52_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o52_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o52_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o52_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o52_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o52_CI = SUMX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o52_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o52_YI = SUMX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o52_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o53_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o53_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o53_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o53_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o53_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o53_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o53_CI = SUMX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o53_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o53_YI = SUMX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o53_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o54_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o54_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o54_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o54_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o54_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o54_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o54_CI = SUMX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o54_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o54_YI = SUMX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o54_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o55_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o55_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o55_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o55_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o55_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o55_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o55_CI = SUMX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o55_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o55_YI = SUMX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o55_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o56_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o56_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o56_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o56_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o56_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o56_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o56_CI = SUMX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o56_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o56_YI = SUMX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o56_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o57_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o57_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o57_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o57_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o57_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o57_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o57_CI = SUMX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o57_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o57_YI = SUMX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o57_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o58_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o58_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o58_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o58_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o58_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o58_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o58_CI = SUMX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o58_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o58_YI = SUMX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o58_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o59_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o59_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o59_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o59_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o59_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o59_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o59_CI = SUMX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o59_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o59_YI = SUMX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o59_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o60_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o60_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o60_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o60_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o60_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o60_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o60_CI = SUMX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o60_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o60_YI = SUMX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o60_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o61_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o61_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o61_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o61_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o61_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o61_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o61_CI = SUMX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o61_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o61_YI = SUMX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o61_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o62_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o62_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o62_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o62_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o62_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o62_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o62_CI = SUMX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o62_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o62_YI = SUMX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o62_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o63_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o63_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o63_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o63_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o63_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o63_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o63_CI = SUMX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o63_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o63_YI = SUMX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o63_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o64_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o64_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o64_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o64_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o64_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o64_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o64_CI = SUMX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o64_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o64_YI = SUMX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o64_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o65_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o65_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o65_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o65_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o65_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o65_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o65_CI = SUMX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o65_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o65_YI = SUMX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o65_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o66_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o66_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o66_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o66_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o66_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o66_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o66_CI = SUMX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o66_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o66_YI = SUMX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o66_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o67_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o67_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o67_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o67_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o67_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o67_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o67_CI = SUMX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o67_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o67_YI = SUMX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o67_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o68_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o68_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o68_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o68_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o68_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o68_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o68_CI = SUMX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o68_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o68_YI = SUMX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o68_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o69_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o69_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o69_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o69_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o69_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o69_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o69_CI = SUMX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o69_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o69_YI = SUMX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o69_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o70_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o70_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o70_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o70_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o70_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o70_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o70_CI = SUMX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o70_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o70_YI = SUMX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o70_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o71_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o71_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o71_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o71_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o71_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o71_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o71_CI = SUMX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o71_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o71_YI = SUMX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o71_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o72_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o72_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o72_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o72_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o72_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o72_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o72_CI = SUMX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o72_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o72_YI = SUMX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o72_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o73_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o73_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o73_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o73_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o73_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o73_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o73_CI = SUMX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o73_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o73_YI = SUMX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o73_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o74_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o74_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o74_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o74_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o74_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o74_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o74_CI = SUMX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o74_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o74_YI = SUMX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o74_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o75_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o75_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o75_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o75_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o75_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o75_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o75_CI = SUMX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o75_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o75_YI = SUMX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o75_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o76_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o76_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o76_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o76_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o76_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o76_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o76_CI = SUMX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o76_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o76_YI = SUMX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o76_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o77_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o77_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o77_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o77_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o77_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o77_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o77_CI = SUMX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o77_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o77_YI = SUMX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o77_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o78_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o78_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o78_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o78_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o78_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o78_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o78_CI = SUMX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o78_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o78_YI = SUMX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o78_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o79_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o79_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o79_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o79_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o79_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o79_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o79_CI = SUMX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o79_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o79_YI = SUMX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o79_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o80_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o80_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o80_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o80_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o80_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o80_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o80_CI = SUMX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o80_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o80_YI = SUMX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o80_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o81_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o81_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o81_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o81_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o81_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o81_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o81_CI = SUMX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o81_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o81_YI = SUMX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o81_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o82_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o82_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o82_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o82_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o82_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o82_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o82_CI = SUMX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o82_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o82_YI = SUMX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o82_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o83_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o83_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o83_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o83_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o83_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o83_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o83_CI = SUMX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o83_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o83_YI = SUMX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o83_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o84_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=84 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o84_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=84 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o84_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=84 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o84_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=84 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o84_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=84 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o84_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=84 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o84_CI = SUMX( FILTER(tbl, VALUE([order_id])=84 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o84_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=84 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o84_YI = SUMX( FILTER(tbl, VALUE([order_id])=84 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o84_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=84 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o85_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=85 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o85_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=85 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o85_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=85 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o85_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=85 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o85_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=85 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o85_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=85 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o85_CI = SUMX( FILTER(tbl, VALUE([order_id])=85 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o85_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=85 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o85_YI = SUMX( FILTER(tbl, VALUE([order_id])=85 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o85_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=85 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o86_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=86 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o86_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=86 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o86_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=86 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o86_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=86 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o86_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=86 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o86_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=86 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o86_CI = SUMX( FILTER(tbl, VALUE([order_id])=86 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o86_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=86 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o86_YI = SUMX( FILTER(tbl, VALUE([order_id])=86 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o86_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=86 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o87_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=87 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o87_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=87 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o87_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=87 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o87_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=87 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o87_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=87 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o87_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=87 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o87_CI = SUMX( FILTER(tbl, VALUE([order_id])=87 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o87_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=87 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o87_YI = SUMX( FILTER(tbl, VALUE([order_id])=87 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o87_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=87 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o88_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=88 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o88_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=88 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o88_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=88 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o88_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=88 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o88_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=88 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o88_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=88 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o88_CI = SUMX( FILTER(tbl, VALUE([order_id])=88 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o88_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=88 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o88_YI = SUMX( FILTER(tbl, VALUE([order_id])=88 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o88_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=88 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o89_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=89 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o89_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=89 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o89_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=89 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o89_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=89 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o89_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=89 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o89_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=89 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o89_CI = SUMX( FILTER(tbl, VALUE([order_id])=89 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o89_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=89 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o89_YI = SUMX( FILTER(tbl, VALUE([order_id])=89 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o89_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=89 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o90_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=90 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o90_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=90 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o90_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=90 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o90_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=90 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o90_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=90 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o90_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=90 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o90_CI = SUMX( FILTER(tbl, VALUE([order_id])=90 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o90_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=90 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o90_YI = SUMX( FILTER(tbl, VALUE([order_id])=90 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o90_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=90 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o91_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=91 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o91_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=91 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o91_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=91 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o91_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=91 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o91_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=91 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o91_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=91 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o91_CI = SUMX( FILTER(tbl, VALUE([order_id])=91 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o91_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=91 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o91_YI = SUMX( FILTER(tbl, VALUE([order_id])=91 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o91_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=91 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o92_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=92 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o92_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=92 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o92_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=92 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o92_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=92 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o92_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=92 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o92_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=92 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o92_CI = SUMX( FILTER(tbl, VALUE([order_id])=92 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o92_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=92 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o92_YI = SUMX( FILTER(tbl, VALUE([order_id])=92 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o92_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=92 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o93_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=93 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o93_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=93 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o93_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=93 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o93_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=93 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o93_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=93 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o93_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=93 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o93_CI = SUMX( FILTER(tbl, VALUE([order_id])=93 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o93_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=93 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o93_YI = SUMX( FILTER(tbl, VALUE([order_id])=93 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o93_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=93 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o94_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=94 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o94_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=94 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o94_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=94 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o94_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=94 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o94_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=94 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o94_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=94 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o94_CI = SUMX( FILTER(tbl, VALUE([order_id])=94 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o94_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=94 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o94_YI = SUMX( FILTER(tbl, VALUE([order_id])=94 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o94_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=94 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o95_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=95 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o95_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=95 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o95_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=95 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o95_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=95 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o95_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=95 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o95_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=95 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o95_CI = SUMX( FILTER(tbl, VALUE([order_id])=95 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o95_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=95 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o95_YI = SUMX( FILTER(tbl, VALUE([order_id])=95 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o95_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=95 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o96_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=96 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o96_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=96 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o96_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=96 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o96_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=96 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o96_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=96 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o96_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=96 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o96_CI = SUMX( FILTER(tbl, VALUE([order_id])=96 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o96_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=96 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o96_YI = SUMX( FILTER(tbl, VALUE([order_id])=96 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o96_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=96 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o97_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=97 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o97_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=97 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o97_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=97 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o97_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=97 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o97_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=97 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o97_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=97 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o97_CI = SUMX( FILTER(tbl, VALUE([order_id])=97 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o97_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=97 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o97_YI = SUMX( FILTER(tbl, VALUE([order_id])=97 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o97_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=97 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o98_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=98 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o98_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=98 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o98_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=98 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o98_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=98 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o98_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=98 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o98_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=98 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o98_CI = SUMX( FILTER(tbl, VALUE([order_id])=98 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o98_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=98 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o98_YI = SUMX( FILTER(tbl, VALUE([order_id])=98 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o98_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=98 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o99_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=99 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o99_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=99 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o99_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=99 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o99_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=99 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o99_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=99 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o99_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=99 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o99_CI = SUMX( FILTER(tbl, VALUE([order_id])=99 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o99_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=99 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o99_YI = SUMX( FILTER(tbl, VALUE([order_id])=99 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o99_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=99 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o100_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=100 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o100_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=100 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o100_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=100 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o100_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=100 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o100_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=100 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o100_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=100 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o100_CI = SUMX( FILTER(tbl, VALUE([order_id])=100 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o100_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=100 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o100_YI = SUMX( FILTER(tbl, VALUE([order_id])=100 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o100_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=100 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o101_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=101 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o101_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=101 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o101_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=101 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o101_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=101 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o101_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=101 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o101_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=101 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o101_CI = SUMX( FILTER(tbl, VALUE([order_id])=101 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o101_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=101 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o101_YI = SUMX( FILTER(tbl, VALUE([order_id])=101 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o101_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=101 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o102_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=102 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o102_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=102 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o102_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=102 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o102_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=102 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o102_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=102 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o102_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=102 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o102_CI = SUMX( FILTER(tbl, VALUE([order_id])=102 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o102_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=102 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o102_YI = SUMX( FILTER(tbl, VALUE([order_id])=102 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o102_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=102 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o103_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=103 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o103_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=103 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o103_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=103 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o103_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=103 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o103_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=103 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o103_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=103 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o103_CI = SUMX( FILTER(tbl, VALUE([order_id])=103 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o103_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=103 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o103_YI = SUMX( FILTER(tbl, VALUE([order_id])=103 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o103_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=103 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o104_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=104 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o104_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=104 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o104_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=104 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o104_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=104 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o104_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=104 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o104_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=104 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o104_CI = SUMX( FILTER(tbl, VALUE([order_id])=104 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o104_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=104 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o104_YI = SUMX( FILTER(tbl, VALUE([order_id])=104 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o104_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=104 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o105_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=105 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o105_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=105 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o105_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=105 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o105_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=105 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o105_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=105 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o105_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=105 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o105_CI = SUMX( FILTER(tbl, VALUE([order_id])=105 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o105_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=105 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o105_YI = SUMX( FILTER(tbl, VALUE([order_id])=105 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o105_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=105 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o106_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=106 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o106_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=106 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o106_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=106 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o106_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=106 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o106_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=106 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o106_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=106 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o106_CI = SUMX( FILTER(tbl, VALUE([order_id])=106 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o106_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=106 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o106_YI = SUMX( FILTER(tbl, VALUE([order_id])=106 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o106_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=106 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o107_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=107 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o107_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=107 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o107_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=107 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o107_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=107 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o107_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=107 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o107_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=107 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o107_CI = SUMX( FILTER(tbl, VALUE([order_id])=107 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o107_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=107 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o107_YI = SUMX( FILTER(tbl, VALUE([order_id])=107 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o107_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=107 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o108_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=108 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o108_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=108 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o108_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=108 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o108_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=108 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o108_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=108 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o108_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=108 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o108_CI = SUMX( FILTER(tbl, VALUE([order_id])=108 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o108_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=108 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o108_YI = SUMX( FILTER(tbl, VALUE([order_id])=108 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o108_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=108 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o109_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=109 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o109_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=109 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o109_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=109 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o109_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=109 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o109_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=109 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o109_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=109 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o109_CI = SUMX( FILTER(tbl, VALUE([order_id])=109 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o109_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=109 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o109_YI = SUMX( FILTER(tbl, VALUE([order_id])=109 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o109_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=109 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o110_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=110 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o110_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=110 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o110_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=110 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o110_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=110 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o110_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=110 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o110_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=110 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o110_CI = SUMX( FILTER(tbl, VALUE([order_id])=110 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o110_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=110 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o110_YI = SUMX( FILTER(tbl, VALUE([order_id])=110 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o110_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=110 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o111_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=111 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o111_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=111 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o111_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=111 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o111_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=111 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o111_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=111 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o111_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=111 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o111_CI = SUMX( FILTER(tbl, VALUE([order_id])=111 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o111_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=111 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o111_YI = SUMX( FILTER(tbl, VALUE([order_id])=111 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o111_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=111 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o112_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=112 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o112_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=112 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o112_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=112 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o112_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=112 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o112_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=112 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o112_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=112 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o112_CI = SUMX( FILTER(tbl, VALUE([order_id])=112 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o112_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=112 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o112_YI = SUMX( FILTER(tbl, VALUE([order_id])=112 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o112_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=112 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o113_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=113 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o113_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=113 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o113_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=113 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o113_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=113 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o113_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=113 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o113_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=113 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o113_CI = SUMX( FILTER(tbl, VALUE([order_id])=113 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o113_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=113 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o113_YI = SUMX( FILTER(tbl, VALUE([order_id])=113 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o113_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=113 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o114_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=114 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o114_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=114 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o114_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=114 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o114_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=114 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o114_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=114 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o114_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=114 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o114_CI = SUMX( FILTER(tbl, VALUE([order_id])=114 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o114_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=114 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o114_YI = SUMX( FILTER(tbl, VALUE([order_id])=114 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o114_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=114 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o115_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=115 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o115_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=115 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o115_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=115 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o115_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=115 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o115_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=115 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o115_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=115 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o115_CI = SUMX( FILTER(tbl, VALUE([order_id])=115 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o115_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=115 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o115_YI = SUMX( FILTER(tbl, VALUE([order_id])=115 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o115_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=115 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o116_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=116 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o116_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=116 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o116_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=116 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o116_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=116 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o116_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=116 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o116_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=116 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o116_CI = SUMX( FILTER(tbl, VALUE([order_id])=116 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o116_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=116 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o116_YI = SUMX( FILTER(tbl, VALUE([order_id])=116 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o116_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=116 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o117_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=117 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o117_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=117 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o117_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=117 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o117_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=117 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o117_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=117 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o117_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=117 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o117_CI = SUMX( FILTER(tbl, VALUE([order_id])=117 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o117_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=117 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o117_YI = SUMX( FILTER(tbl, VALUE([order_id])=117 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o117_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=117 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o118_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=118 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o118_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=118 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o118_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=118 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o118_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=118 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o118_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=118 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o118_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=118 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o118_CI = SUMX( FILTER(tbl, VALUE([order_id])=118 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o118_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=118 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o118_YI = SUMX( FILTER(tbl, VALUE([order_id])=118 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o118_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=118 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o119_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=119 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o119_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=119 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o119_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=119 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o119_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=119 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o119_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=119 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o119_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=119 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o119_CI = SUMX( FILTER(tbl, VALUE([order_id])=119 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o119_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=119 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o119_YI = SUMX( FILTER(tbl, VALUE([order_id])=119 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o119_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=119 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o120_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=120 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o120_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=120 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o120_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=120 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o120_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=120 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o120_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=120 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o120_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=120 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o120_CI = SUMX( FILTER(tbl, VALUE([order_id])=120 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o120_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=120 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o120_YI = SUMX( FILTER(tbl, VALUE([order_id])=120 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o120_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=120 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o121_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=121 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o121_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=121 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o121_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=121 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o121_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=121 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o121_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=121 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o121_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=121 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o121_CI = SUMX( FILTER(tbl, VALUE([order_id])=121 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o121_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=121 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o121_YI = SUMX( FILTER(tbl, VALUE([order_id])=121 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o121_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=121 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o122_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=122 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o122_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=122 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o122_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=122 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o122_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=122 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o122_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=122 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o122_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=122 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o122_CI = SUMX( FILTER(tbl, VALUE([order_id])=122 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o122_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=122 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o122_YI = SUMX( FILTER(tbl, VALUE([order_id])=122 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o122_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=122 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o123_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=123 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o123_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=123 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o123_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=123 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o123_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=123 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o123_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=123 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o123_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=123 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o123_CI = SUMX( FILTER(tbl, VALUE([order_id])=123 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o123_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=123 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o123_YI = SUMX( FILTER(tbl, VALUE([order_id])=123 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o123_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=123 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o124_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=124 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o124_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=124 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o124_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=124 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o124_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=124 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o124_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=124 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o124_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=124 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o124_CI = SUMX( FILTER(tbl, VALUE([order_id])=124 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o124_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=124 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o124_YI = SUMX( FILTER(tbl, VALUE([order_id])=124 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o124_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=124 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o125_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=125 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o125_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=125 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o125_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=125 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o125_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=125 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o125_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=125 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o125_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=125 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o125_CI = SUMX( FILTER(tbl, VALUE([order_id])=125 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o125_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=125 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o125_YI = SUMX( FILTER(tbl, VALUE([order_id])=125 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o125_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=125 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o126_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=126 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o126_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=126 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o126_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=126 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o126_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=126 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o126_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=126 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o126_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=126 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o126_CI = SUMX( FILTER(tbl, VALUE([order_id])=126 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o126_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=126 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o126_YI = SUMX( FILTER(tbl, VALUE([order_id])=126 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o126_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=126 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o127_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=127 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o127_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=127 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o127_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=127 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o127_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=127 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o127_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=127 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o127_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=127 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o127_CI = SUMX( FILTER(tbl, VALUE([order_id])=127 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o127_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=127 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o127_YI = SUMX( FILTER(tbl, VALUE([order_id])=127 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o127_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=127 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR Sty =
    "<style>" &
    ".soc{font-family:Segoe UI,Calibri,sans-serif;font-size:10.5px;color:#1e2d40;}" &
    ".soc-t{width:100%;border-collapse:collapse;}" &
    ".soc-t td{padding:3px 7px;border-bottom:1px solid #e8edf3;vertical-align:middle;white-space:nowrap;}" &
    ".soc-t tr:hover td{background:#f5f8ff;}" &
    ".h-row td{background:#003366!important;color:#fff!important;font-weight:700;font-size:11px;text-transform:uppercase;border-bottom:3px solid #f0a500!important;padding:6px 7px!important;}" &
    ".sub1 td{background:#e8f0fb!important;font-weight:700;color:#003366;border-bottom:1px solid #b8cce4!important;}" &
    ".sub2 td{background:#f0f6ff!important;font-weight:600;color:#1a4a7a;}" &
    ".tot td{background:#f0a500!important;font-weight:800;font-size:11px;color:#003366!important;border-top:2px solid #003366!important;}" &
    ".cd{color:#9ca3af;font-size:9px;min-width:80px;}" &
    ".cd-w{color:#f0a500!important;font-size:9px;min-width:80px;}" &
    ".ar{text-align:right!important;font-family:Consolas,monospace;font-size:9.5px;min-width:90px;}" &
    ".ac{text-align:center!important;font-family:Consolas,monospace;font-size:9.5px;min-width:50px;}" &
    ".pct{text-align:center!important;font-size:9.5px;min-width:60px;}" &
    ".bl{border-left:2px solid #dde4ef!important;}" &
    ".i0{padding-left:8px!important;}" &
    ".i1{padding-left:18px!important;}" &
    ".i2{padding-left:28px!important;}" &
    ".i3{padding-left:38px!important;color:#6b7280;}" &
    ".i4{padding-left:48px!important;color:#9ca3af;}" &
    "</style>"
VAR Hdr =
    "<div style='background:#003366;padding:16px 20px 12px;border-bottom:4px solid #f0a500;display:flex;align-items:center;gap:16px;'>" &
    "<img src='https://i.ibb.co/rWhBLgw/image-2026-04-21-094244962.png' style='height:90px;width:auto;flex-shrink:0;' />" &
    "<div>" &
    "<div style='color:#fff;font-family:Segoe UI,sans-serif;font-size:17px;font-weight:700;text-transform:uppercase;letter-spacing:1px;margin-bottom:4px;'>BANCO NACIONAL DE COMERCIO DE TIMOR LESTE</div>" &
    "<div style='color:#f0a500;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:1.5px;margin-bottom:3px;'>CONSOLIDATED STATEMENT OF ASSETS AND LIABILITIES (SOC)</div>" &
    "<div style='color:#f0a500;font-size:11px;font-weight:700;letter-spacing:1px;margin-bottom:3px;'>ASSETS</div>" &
    "<div style='color:#cbd5e1;font-size:11px;'>" & PeriodLabel & "</div>" &
    "</div>" &
    "</div>"
VAR ColHdr =
    "<table class='soc-t'><thead>" &
    "<tr style='background:#1a4a7a;'>" &
    "<td class='cd-w' rowspan='2' style='padding:5px 7px;'>CODE</td>" &
    "<td style='color:#fff;font-weight:700;font-size:10px;padding:5px 7px;' rowspan='2'>ACCOUNT TITLES</td>" &
    "<td style='color:#fff;font-weight:700;font-size:10px;padding:5px 7px;text-align:center;border-left:2px solid #2563eb;' colspan='2'>CURRENT PERIOD</td>" &
    "<td style='color:#fff;font-weight:700;font-size:10px;padding:5px 7px;text-align:center;border-left:2px solid #2563eb;'>PREVIOUS PERIOD</td>" &
    "<td style='color:#f0a500;font-weight:700;font-size:10px;padding:5px 7px;text-align:center;border-left:2px solid #2563eb;' colspan='2'>vs PREVIOUS</td>" &
    "<td style='color:#fff;font-weight:700;font-size:10px;padding:5px 7px;text-align:center;border-left:2px solid #2563eb;'>PREV YEAR</td>" &
    "<td style='color:#f0a500;font-weight:700;font-size:10px;padding:5px 7px;text-align:center;border-left:2px solid #2563eb;' colspan='2'>YOY CHANGE</td>" &
    "</tr>" &
    "<tr style='background:#1a4a7a;border-bottom:2px solid #f0a500;'>" &
    "<td class='ac' style='color:#d1d5db;font-size:9px;padding:3px 7px;border-left:2px solid #2563eb;'>No.Acc</td>" &
    "<td class='ar' style='color:#d1d5db;font-size:9px;padding:3px 7px;'>Amount (USD)</td>" &
    "<td class='ar bl' style='color:#d1d5db;font-size:9px;padding:3px 7px;'>Amount (USD)</td>" &
    "<td class='ar bl' style='color:#d1d5db;font-size:9px;padding:3px 7px;'>Increase (+/-)</td>" &
    "<td class='pct' style='color:#d1d5db;font-size:9px;padding:3px 7px;'>%</td>" &
    "<td class='ar bl' style='color:#d1d5db;font-size:9px;padding:3px 7px;'>Amount (USD)</td>" &
    "<td class='ar bl' style='color:#d1d5db;font-size:9px;padding:3px 7px;'>Variance</td>" &
    "<td class='pct' style='color:#d1d5db;font-size:9px;padding:3px 7px;'>%</td>" &
    "</tr></thead><tbody>"
VAR Rows_1 =
    "<tr class='sub1'><td class='cd'>1.0</td><td class='i1'>ASSETS:</td>" & "<td class='ac bl'>" & IF(o1_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o1_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o1_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o1_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o1_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o1_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o1_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o1_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o1_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o1_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o1_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o1_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o1_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o1_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o1_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o1_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o1_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o1_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o1_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o1_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o1_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o1_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o1_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o1_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub1'><td class='cd'>1.01</td><td class='i1'>LIQUID FUNDS</td>" & "<td class='ac bl'>" & IF(o2_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o2_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o2_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o2_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o2_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o2_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o2_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o2_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o2_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o2_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o2_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o2_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o2_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o2_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o2_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o2_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o2_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o2_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o2_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o2_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o2_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o2_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o2_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o2_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.1.1.1</td><td class='i4'>Cash in Vault</td>" & "<td class='ac bl'>" & IF(o3_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o3_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o3_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o3_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o3_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o3_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o3_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o3_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o3_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o3_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o3_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o3_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o3_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o3_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o3_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o3_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o3_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o3_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o3_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o3_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o3_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o3_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o3_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o3_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.1.1.2</td><td class='i4'>Cash in ATM Vault</td>" & "<td class='ac bl'>" & IF(o4_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o4_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o4_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o4_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o4_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o4_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o4_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o4_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o4_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o4_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o4_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o4_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o4_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o4_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o4_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o4_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o4_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o4_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o4_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o4_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o4_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o4_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o4_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o4_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>1.01.2</td><td class='i2'>Due from Central Bank</td>" & "<td class='ac bl'>" & IF(o5_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o5_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o5_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o5_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o5_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o5_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o5_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o5_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o5_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o5_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o5_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o5_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o5_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o5_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o5_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o5_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o5_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o5_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o5_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o5_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o5_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o5_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o5_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o5_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>1.01.3</td><td class='i2'>Items in course of collect.</td>" & "<td class='ac bl'>" & IF(o6_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o6_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o6_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o6_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o6_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o6_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o6_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o6_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o6_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o6_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o6_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o6_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o6_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o6_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o6_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o6_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o6_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o6_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o6_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o6_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o6_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o6_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o6_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o6_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>1.01.4</td><td class='i2'>Due from Com. Banks</td>" & "<td class='ac bl'>" & IF(o7_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o7_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o7_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o7_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o7_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o7_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o7_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o7_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o7_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o7_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o7_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o7_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o7_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o7_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o7_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o7_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o7_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o7_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o7_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o7_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o7_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o7_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o7_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o7_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1</td><td class='i3'>Domestic Currency</td>" & "<td class='ac bl'>" & IF(o8_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o8_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o8_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o8_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o8_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o8_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o8_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o8_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o8_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o8_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o8_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o8_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o8_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o8_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o8_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o8_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o8_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o8_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o8_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o8_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o8_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o8_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o8_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o8_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1.2</td><td class='i4'>Call Deposits</td>" & "<td class='ac bl'>" & IF(o9_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o9_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o9_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o9_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o9_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o9_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o9_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o9_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o9_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o9_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o9_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o9_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o9_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o9_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o9_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o9_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o9_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o9_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o9_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o9_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o9_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o9_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o9_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o9_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1.2.21</td><td class='i4'>LocalBankBRIDili</td>" & "<td class='ac bl'>" & IF(o10_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o10_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o10_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o10_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o10_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o10_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o10_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o10_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o10_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o10_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o10_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o10_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o10_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o10_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o10_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o10_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o10_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o10_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o10_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o10_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o10_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o10_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o10_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o10_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1.2.22</td><td class='i4'>LocalBanks:BNU</td>" & "<td class='ac bl'>" & IF(o11_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o11_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o11_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o11_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o11_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o11_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o11_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o11_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o11_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o11_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o11_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o11_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o11_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o11_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o11_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o11_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o11_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o11_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o11_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o11_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o11_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o11_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o11_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o11_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1.2.23</td><td class='i4'>LocalBanks:BRI</td>" & "<td class='ac bl'>" & IF(o12_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o12_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o12_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o12_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o12_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o12_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o12_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o12_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o12_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o12_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o12_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o12_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o12_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o12_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o12_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o12_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o12_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o12_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o12_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o12_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o12_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o12_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o12_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o12_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>"
VAR Rows_2 =
    "<tr><td class='cd'>1.01.4.1.2.21</td><td class='i4'>LocalBanks:Mandiri</td>" & "<td class='ac bl'>" & IF(o13_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o13_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o13_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o13_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o13_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o13_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o13_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o13_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o13_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o13_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o13_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o13_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o13_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o13_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o13_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o13_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o13_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o13_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o13_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o13_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o13_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o13_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o13_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o13_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1.2.3</td><td class='i4'>OverseasUSDBRI</td>" & "<td class='ac bl'>" & IF(o14_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o14_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o14_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o14_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o14_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o14_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o14_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o14_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o14_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o14_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o14_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o14_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o14_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o14_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o14_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o14_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o14_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o14_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o14_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o14_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o14_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o14_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o14_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o14_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1.2.4</td><td class='i4'>OverseasUSDBCA</td>" & "<td class='ac bl'>" & IF(o15_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o15_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o15_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o15_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o15_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o15_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o15_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o15_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o15_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o15_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o15_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o15_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o15_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o15_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o15_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o15_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o15_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o15_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o15_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o15_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o15_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o15_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o15_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o15_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1.2.5</td><td class='i4'>OverseasUSDBNINY</td>" & "<td class='ac bl'>" & IF(o16_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o16_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o16_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o16_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o16_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o16_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o16_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o16_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o16_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o16_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o16_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o16_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o16_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o16_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o16_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o16_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o16_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o16_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o16_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o16_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o16_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o16_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o16_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o16_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1.2.7</td><td class='i4'>OverseasUSDTurki</td>" & "<td class='ac bl'>" & IF(o17_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o17_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o17_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o17_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o17_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o17_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o17_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o17_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o17_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o17_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o17_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o17_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o17_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o17_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o17_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o17_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o17_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o17_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o17_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o17_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o17_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o17_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o17_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o17_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1.2.8</td><td class='i4'>OverseasBRINewYork</td>" & "<td class='ac bl'>" & IF(o18_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o18_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o18_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o18_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o18_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o18_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o18_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o18_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o18_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o18_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o18_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o18_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o18_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o18_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o18_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o18_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o18_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o18_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o18_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o18_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o18_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o18_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o18_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o18_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1.2.9</td><td class='i4'>OverseasUSDUK</td>" & "<td class='ac bl'>" & IF(o19_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o19_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o19_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o19_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o19_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o19_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o19_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o19_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o19_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o19_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o19_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o19_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o19_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o19_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o19_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o19_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o19_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o19_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o19_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o19_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o19_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o19_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o19_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o19_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1.2</td><td class='i4'>OTHERS</td>" & "<td class='ac bl'>" & IF(o20_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o20_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o20_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o20_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o20_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o20_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o20_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o20_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o20_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o20_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o20_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o20_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o20_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o20_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o20_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o20_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o20_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o20_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o20_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o20_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o20_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o20_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o20_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o20_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1.3.20</td><td class='i4'>LocalBanks:MANDIRI</td>" & "<td class='ac bl'>" & IF(o21_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o21_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o21_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o21_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o21_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o21_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o21_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o21_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o21_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o21_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o21_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o21_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o21_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o21_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o21_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o21_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o21_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o21_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o21_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o21_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o21_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o21_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o21_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o21_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1.3.21</td><td class='i4'>LocalBanks:BNU</td>" & "<td class='ac bl'>" & IF(o22_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o22_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o22_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o22_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o22_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o22_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o22_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o22_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o22_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o22_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o22_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o22_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o22_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o22_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o22_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o22_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o22_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o22_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o22_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o22_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o22_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o22_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o22_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o22_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1.3.22</td><td class='i4'>LocalBanks:BRIDILI</td>" & "<td class='ac bl'>" & IF(o23_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o23_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o23_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o23_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o23_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o23_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o23_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o23_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o23_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o23_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o23_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o23_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o23_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o23_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o23_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o23_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o23_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o23_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o23_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o23_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o23_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o23_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o23_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o23_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1.3.24</td><td class='i4'>BNITimeDepNewYork</td>" & "<td class='ac bl'>" & IF(o24_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o24_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o24_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o24_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o24_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o24_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o24_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o24_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o24_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o24_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o24_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o24_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o24_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o24_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o24_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o24_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o24_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o24_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o24_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o24_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o24_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o24_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o24_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o24_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>"
VAR Rows_3 =
    "<tr><td class='cd'>1.01.4.1.3.21</td><td class='i4'>BRITimeDepNewYork</td>" & "<td class='ac bl'>" & IF(o25_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o25_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o25_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o25_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o25_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o25_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o25_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o25_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o25_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o25_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o25_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o25_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o25_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o25_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o25_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o25_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o25_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o25_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o25_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o25_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o25_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o25_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o25_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o25_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1.3.25</td><td class='i4'>TDAktifTurkey</td>" & "<td class='ac bl'>" & IF(o26_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o26_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o26_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o26_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o26_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o26_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o26_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o26_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o26_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o26_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o26_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o26_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o26_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o26_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o26_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o26_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o26_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o26_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o26_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o26_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o26_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o26_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o26_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o26_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1.3.23</td><td class='i4'>TimeDepositBOCSingapore</td>" & "<td class='ac bl'>" & IF(o27_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o27_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o27_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o27_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o27_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o27_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o27_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o27_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o27_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o27_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o27_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o27_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o27_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o27_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o27_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o27_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o27_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o27_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o27_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o27_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o27_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o27_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o27_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o27_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.1.2.3</td><td class='i4'>Overseas</td>" & "<td class='ac bl'>" & IF(o28_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o28_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o28_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o28_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o28_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o28_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o28_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o28_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o28_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o28_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o28_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o28_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o28_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o28_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o28_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o28_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o28_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o28_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o28_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o28_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o28_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o28_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o28_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o28_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.3</td><td class='i3'>Foreign Currency</td>" & "<td class='ac bl'>" & IF(o29_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o29_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o29_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o29_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o29_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o29_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o29_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o29_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o29_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o29_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o29_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o29_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o29_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o29_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o29_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o29_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o29_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o29_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o29_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o29_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o29_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o29_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o29_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o29_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.2.2</td><td class='i4'>OverseasIDRBRI</td>" & "<td class='ac bl'>" & IF(o30_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o30_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o30_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o30_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o30_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o30_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o30_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o30_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o30_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o30_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o30_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o30_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o30_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o30_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o30_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o30_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o30_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o30_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o30_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o30_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o30_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o30_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o30_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o30_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.2.3</td><td class='i4'>OtherOverseasBanks(TD)</td>" & "<td class='ac bl'>" & IF(o31_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o31_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o31_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o31_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o31_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o31_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o31_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o31_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o31_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o31_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o31_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o31_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o31_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o31_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o31_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o31_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o31_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o31_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o31_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o31_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o31_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o31_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o31_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o31_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.2.3</td><td class='i4'>TimeDepositBRIJakarta</td>" & "<td class='ac bl'>" & IF(o32_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o32_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o32_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o32_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o32_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o32_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o32_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o32_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o32_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o32_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o32_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o32_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o32_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o32_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o32_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o32_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o32_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o32_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o32_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o32_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o32_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o32_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o32_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o32_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.2.4</td><td class='i4'>OverseasIDRBCA</td>" & "<td class='ac bl'>" & IF(o33_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o33_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o33_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o33_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o33_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o33_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o33_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o33_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o33_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o33_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o33_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o33_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o33_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o33_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o33_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o33_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o33_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o33_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o33_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o33_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o33_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o33_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o33_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o33_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.2.5</td><td class='i4'>OverseasAUDBCA</td>" & "<td class='ac bl'>" & IF(o34_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o34_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o34_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o34_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o34_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o34_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o34_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o34_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o34_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o34_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o34_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o34_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o34_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o34_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o34_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o34_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o34_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o34_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o34_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o34_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o34_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o34_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o34_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o34_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.2.6</td><td class='i4'>BCPPortugal</td>" & "<td class='ac bl'>" & IF(o35_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o35_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o35_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o35_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o35_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o35_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o35_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o35_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o35_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o35_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o35_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o35_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o35_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o35_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o35_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o35_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o35_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o35_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o35_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o35_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o35_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o35_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o35_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o35_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.2.7</td><td class='i4'>BOCSingapore</td>" & "<td class='ac bl'>" & IF(o36_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o36_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o36_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o36_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o36_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o36_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o36_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o36_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o36_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o36_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o36_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o36_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o36_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o36_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o36_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o36_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o36_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o36_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o36_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o36_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o36_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o36_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o36_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o36_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>"
VAR Rows_4 =
    "<tr><td class='cd'>1.01.4.2.8</td><td class='i4'>SGDBOCSingapore</td>" & "<td class='ac bl'>" & IF(o37_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o37_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o37_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o37_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o37_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o37_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o37_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o37_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o37_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o37_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o37_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o37_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o37_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o37_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o37_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o37_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o37_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o37_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o37_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o37_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o37_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o37_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o37_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o37_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.2.9</td><td class='i4'>OverseasEuroTurky</td>" & "<td class='ac bl'>" & IF(o38_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o38_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o38_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o38_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o38_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o38_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o38_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o38_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o38_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o38_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o38_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o38_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o38_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o38_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o38_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o38_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o38_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o38_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o38_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o38_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o38_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o38_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o38_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o38_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.3.1</td><td class='i4'>OverseasPoudsTurky</td>" & "<td class='ac bl'>" & IF(o39_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o39_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o39_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o39_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o39_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o39_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o39_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o39_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o39_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o39_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o39_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o39_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o39_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o39_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o39_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o39_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o39_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o39_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o39_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o39_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o39_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o39_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o39_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o39_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.3.2</td><td class='i4'>OverseasIDRBNIJakarta</td>" & "<td class='ac bl'>" & IF(o40_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o40_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o40_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o40_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o40_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o40_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o40_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o40_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o40_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o40_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o40_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o40_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o40_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o40_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o40_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o40_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o40_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o40_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o40_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o40_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o40_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o40_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o40_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o40_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.3.2</td><td class='i4'>OverseasGBPUK</td>" & "<td class='ac bl'>" & IF(o41_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o41_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o41_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o41_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o41_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o41_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o41_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o41_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o41_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o41_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o41_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o41_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o41_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o41_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o41_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o41_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o41_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o41_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o41_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o41_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o41_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o41_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o41_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o41_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.01.4.3.3</td><td class='i4'>OverseasEUROUK</td>" & "<td class='ac bl'>" & IF(o42_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o42_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o42_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o42_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o42_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o42_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o42_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o42_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o42_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o42_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o42_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o42_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o42_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o42_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o42_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o42_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o42_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o42_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o42_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o42_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o42_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o42_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o42_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o42_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub1'><td class='cd'>1.02</td><td class='i1'>INVESTMENT</td>" & "<td class='ac bl'>" & IF(o43_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o43_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o43_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o43_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o43_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o43_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o43_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o43_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o43_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o43_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o43_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o43_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o43_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o43_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o43_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o43_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o43_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o43_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o43_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o43_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o43_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o43_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o43_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o43_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>1.02.1</td><td class='i2'>Securities</td>" & "<td class='ac bl'>" & IF(o44_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o44_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o44_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o44_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o44_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o44_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o44_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o44_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o44_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o44_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o44_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o44_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o44_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o44_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o44_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o44_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o44_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o44_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o44_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o44_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o44_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o44_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o44_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o44_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub1'><td class='cd'>1.04</td><td class='i1'>LOAN, ADV. &amp; DISC.</td>" & "<td class='ac bl'>" & IF(o45_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o45_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o45_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o45_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o45_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o45_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o45_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o45_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o45_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o45_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o45_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o45_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o45_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o45_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o45_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o45_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o45_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o45_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o45_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o45_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o45_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o45_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o45_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o45_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>1.04.1</td><td class='i2'>CURRENT LOAN</td>" & "<td class='ac bl'>" & IF(o46_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o46_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o46_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o46_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o46_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o46_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o46_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o46_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o46_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o46_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o46_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o46_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o46_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o46_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o46_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o46_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o46_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o46_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o46_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o46_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o46_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o46_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o46_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o46_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.1.1.3.10</td><td class='i4'>MarketVendorDailyL.</td>" & "<td class='ac bl'>" & IF(o47_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o47_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o47_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o47_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o47_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o47_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o47_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o47_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o47_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o47_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o47_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o47_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o47_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o47_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o47_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o47_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o47_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o47_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o47_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o47_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o47_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o47_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o47_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o47_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.1.1.3.20</td><td class='i4'>SeasonalCropLoans</td>" & "<td class='ac bl'>" & IF(o48_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o48_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o48_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o48_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o48_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o48_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o48_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o48_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o48_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o48_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o48_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o48_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o48_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o48_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o48_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o48_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o48_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o48_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o48_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o48_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o48_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o48_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o48_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o48_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>"
VAR Rows_5 =
    "<tr><td class='cd'>1.04.1.1.3.30</td><td class='i4'>OtherBusineesLoans</td>" & "<td class='ac bl'>" & IF(o49_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o49_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o49_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o49_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o49_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o49_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o49_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o49_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o49_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o49_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o49_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o49_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o49_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o49_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o49_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o49_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o49_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o49_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o49_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o49_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o49_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o49_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o49_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o49_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.1.1.3.50</td><td class='i4'>ProjectLoan</td>" & "<td class='ac bl'>" & IF(o50_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o50_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o50_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o50_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o50_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o50_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o50_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o50_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o50_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o50_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o50_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o50_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o50_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o50_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o50_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o50_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o50_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o50_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o50_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o50_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o50_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o50_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o50_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o50_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.1.1.3.60</td><td class='i4'>InvestmentLoans</td>" & "<td class='ac bl'>" & IF(o51_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o51_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o51_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o51_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o51_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o51_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o51_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o51_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o51_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o51_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o51_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o51_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o51_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o51_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o51_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o51_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o51_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o51_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o51_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o51_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o51_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o51_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o51_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o51_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.1.1.3.80</td><td class='i4'>TransportLoan</td>" & "<td class='ac bl'>" & IF(o52_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o52_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o52_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o52_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o52_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o52_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o52_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o52_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o52_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o52_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o52_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o52_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o52_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o52_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o52_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o52_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o52_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o52_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o52_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o52_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o52_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o52_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o52_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o52_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.1.1.3.85</td><td class='i4'>AgricultorLoan</td>" & "<td class='ac bl'>" & IF(o53_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o53_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o53_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o53_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o53_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o53_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o53_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o53_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o53_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o53_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o53_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o53_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o53_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o53_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o53_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o53_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o53_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o53_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o53_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o53_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o53_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o53_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o53_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o53_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.1.1.3.70</td><td class='i4'>MicrofinanceGroupL.</td>" & "<td class='ac bl'>" & IF(o54_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o54_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o54_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o54_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o54_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o54_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o54_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o54_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o54_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o54_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o54_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o54_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o54_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o54_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o54_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o54_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o54_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o54_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o54_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o54_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o54_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o54_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o54_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o54_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.1.1.4.20</td><td class='i4'>PayrollLoans</td>" & "<td class='ac bl'>" & IF(o55_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o55_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o55_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o55_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o55_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o55_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o55_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o55_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o55_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o55_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o55_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o55_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o55_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o55_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o55_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o55_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o55_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o55_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o55_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o55_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o55_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o55_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o55_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o55_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.1.1.4.30</td><td class='i4'>LoanstoEmpl.&amp;Staff</td>" & "<td class='ac bl'>" & IF(o56_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o56_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o56_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o56_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o56_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o56_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o56_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o56_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o56_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o56_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o56_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o56_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o56_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o56_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o56_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o56_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o56_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o56_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o56_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o56_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o56_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o56_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o56_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o56_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.1.1.4.35</td><td class='i4'>InternalStaffLoan</td>" & "<td class='ac bl'>" & IF(o57_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o57_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o57_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o57_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o57_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o57_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o57_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o57_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o57_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o57_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o57_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o57_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o57_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o57_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o57_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o57_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o57_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o57_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o57_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o57_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o57_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o57_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o57_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o57_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.1.1.4.40</td><td class='i4'>AsuwainLoan</td>" & "<td class='ac bl'>" & IF(o58_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o58_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o58_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o58_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o58_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o58_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o58_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o58_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o58_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o58_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o58_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o58_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o58_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o58_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o58_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o58_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o58_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o58_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o58_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o58_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o58_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o58_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o58_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o58_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.1.1.4.50</td><td class='i4'>BukaeLoan</td>" & "<td class='ac bl'>" & IF(o59_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o59_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o59_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o59_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o59_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o59_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o59_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o59_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o59_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o59_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o59_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o59_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o59_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o59_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o59_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o59_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o59_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o59_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o59_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o59_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o59_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o59_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o59_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o59_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.1.1.4.60</td><td class='i4'>PensionLoan</td>" & "<td class='ac bl'>" & IF(o60_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o60_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o60_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o60_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o60_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o60_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o60_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o60_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o60_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o60_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o60_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o60_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o60_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o60_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o60_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o60_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o60_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o60_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o60_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o60_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o60_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o60_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o60_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o60_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>"
VAR Rows_6 =
    "<tr><td class='cd'>1.04.1.1.4.65</td><td class='i4'>FIARLoan</td>" & "<td class='ac bl'>" & IF(o61_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o61_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o61_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o61_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o61_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o61_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o61_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o61_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o61_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o61_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o61_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o61_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o61_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o61_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o61_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o61_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o61_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o61_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o61_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o61_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o61_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o61_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o61_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o61_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'></td><td class='i2'>RBLLoanOrigination</td>" & "<td class='ac bl'>" & IF(o62_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o62_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o62_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o62_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o62_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o62_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o62_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o62_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o62_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o62_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o62_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o62_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o62_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o62_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o62_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o62_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o62_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o62_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o62_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o62_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o62_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o62_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o62_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o62_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub1'><td class='cd'>1.03</td><td class='i1'>PAST DUE LOANS</td>" & "<td class='ac bl'>" & IF(o63_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o63_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o63_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o63_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o63_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o63_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o63_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o63_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o63_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o63_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o63_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o63_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o63_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o63_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o63_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o63_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o63_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o63_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o63_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o63_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o63_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o63_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o63_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o63_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.2.1.3.10</td><td class='i4'>PastDueMark.Vend.D.L.</td>" & "<td class='ac bl'>" & IF(o64_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o64_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o64_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o64_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o64_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o64_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o64_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o64_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o64_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o64_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o64_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o64_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o64_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o64_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o64_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o64_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o64_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o64_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o64_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o64_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o64_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o64_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o64_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o64_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.2.1.3.20</td><td class='i4'>PastDueSeas.C.Loans</td>" & "<td class='ac bl'>" & IF(o65_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o65_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o65_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o65_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o65_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o65_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o65_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o65_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o65_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o65_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o65_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o65_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o65_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o65_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o65_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o65_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o65_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o65_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o65_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o65_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o65_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o65_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o65_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o65_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.2.1.3.30</td><td class='i4'>PastDueOtherBusi.L.</td>" & "<td class='ac bl'>" & IF(o66_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o66_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o66_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o66_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o66_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o66_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o66_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o66_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o66_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o66_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o66_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o66_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o66_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o66_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o66_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o66_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o66_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o66_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o66_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o66_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o66_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o66_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o66_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o66_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.2.1.3.50</td><td class='i4'>PastDueProjectLoans</td>" & "<td class='ac bl'>" & IF(o67_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o67_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o67_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o67_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o67_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o67_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o67_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o67_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o67_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o67_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o67_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o67_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o67_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o67_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o67_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o67_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o67_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o67_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o67_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o67_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o67_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o67_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o67_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o67_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>10.4.2.1.3.60</td><td class='i4'>PastDueInvestmentLoan</td>" & "<td class='ac bl'>" & IF(o68_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o68_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o68_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o68_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o68_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o68_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o68_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o68_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o68_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o68_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o68_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o68_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o68_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o68_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o68_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o68_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o68_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o68_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o68_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o68_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o68_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o68_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o68_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o68_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'></td><td class='i2'>PastDueTransportLoan</td>" & "<td class='ac bl'>" & IF(o69_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o69_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o69_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o69_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o69_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o69_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o69_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o69_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o69_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o69_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o69_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o69_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o69_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o69_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o69_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o69_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o69_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o69_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o69_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o69_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o69_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o69_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o69_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o69_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.2.1.4.37</td><td class='i4'>PastDueAgricultureLO</td>" & "<td class='ac bl'>" & IF(o70_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o70_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o70_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o70_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o70_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o70_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o70_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o70_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o70_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o70_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o70_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o70_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o70_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o70_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o70_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o70_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o70_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o70_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o70_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o70_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o70_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o70_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o70_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o70_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.2.1.4.10</td><td class='i4'>PastDueMicrof.G.L.</td>" & "<td class='ac bl'>" & IF(o71_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o71_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o71_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o71_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o71_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o71_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o71_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o71_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o71_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o71_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o71_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o71_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o71_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o71_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o71_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o71_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o71_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o71_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o71_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o71_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o71_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o71_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o71_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o71_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.2.1.4.20</td><td class='i4'>PastDuePayrollLoans</td>" & "<td class='ac bl'>" & IF(o72_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o72_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o72_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o72_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o72_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o72_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o72_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o72_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o72_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o72_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o72_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o72_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o72_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o72_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o72_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o72_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o72_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o72_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o72_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o72_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o72_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o72_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o72_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o72_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>"
VAR Rows_7 =
    "<tr><td class='cd'>1.04.2.1.4.30</td><td class='i4'>PastDueL.toE.&amp;Staff</td>" & "<td class='ac bl'>" & IF(o73_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o73_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o73_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o73_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o73_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o73_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o73_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o73_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o73_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o73_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o73_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o73_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o73_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o73_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o73_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o73_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o73_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o73_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o73_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o73_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o73_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o73_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o73_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o73_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.2.1.4.35</td><td class='i4'>PastDueL.InternalStaff</td>" & "<td class='ac bl'>" & IF(o74_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o74_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o74_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o74_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o74_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o74_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o74_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o74_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o74_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o74_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o74_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o74_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o74_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o74_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o74_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o74_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o74_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o74_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o74_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o74_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o74_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o74_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o74_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o74_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.2.1.4.40</td><td class='i4'>PastDueAsuwainLoan</td>" & "<td class='ac bl'>" & IF(o75_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o75_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o75_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o75_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o75_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o75_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o75_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o75_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o75_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o75_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o75_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o75_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o75_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o75_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o75_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o75_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o75_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o75_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o75_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o75_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o75_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o75_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o75_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o75_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.2.1.4.35</td><td class='i4'>PastDueBukaeLoan</td>" & "<td class='ac bl'>" & IF(o76_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o76_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o76_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o76_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o76_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o76_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o76_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o76_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o76_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o76_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o76_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o76_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o76_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o76_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o76_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o76_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o76_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o76_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o76_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o76_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o76_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o76_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o76_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o76_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.2.1.4.36</td><td class='i4'>PastDuePensionLoan</td>" & "<td class='ac bl'>" & IF(o77_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o77_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o77_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o77_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o77_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o77_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o77_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o77_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o77_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o77_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o77_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o77_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o77_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o77_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o77_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o77_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o77_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o77_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o77_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o77_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o77_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o77_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o77_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o77_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'></td><td class='i2'>PastDueFiarLoan.Org</td>" & "<td class='ac bl'>" & IF(o78_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o78_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o78_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o78_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o78_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o78_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o78_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o78_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o78_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o78_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o78_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o78_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o78_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o78_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o78_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o78_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o78_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o78_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o78_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o78_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o78_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o78_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o78_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o78_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'></td><td class='i2'>PastDueRBLLoanOrigination</td>" & "<td class='ac bl'>" & IF(o79_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o79_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o79_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o79_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o79_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o79_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o79_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o79_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o79_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o79_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o79_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o79_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o79_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o79_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o79_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o79_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o79_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o79_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o79_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o79_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o79_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o79_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o79_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o79_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>1.04.3</td><td class='i2'>PROV. FOR L. LOSSES</td>" & "<td class='ac bl'>" & IF(o80_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o80_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o80_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o80_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o80_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o80_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o80_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o80_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o80_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o80_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o80_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o80_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o80_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o80_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o80_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o80_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o80_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o80_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o80_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o80_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o80_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o80_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o80_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o80_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.3.1.3</td><td class='i4'>BusineesInterprises</td>" & "<td class='ac bl'>" & IF(o81_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o81_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o81_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o81_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o81_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o81_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o81_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o81_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o81_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o81_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o81_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o81_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o81_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o81_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o81_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o81_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o81_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o81_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o81_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o81_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o81_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o81_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o81_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o81_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.3.1.4</td><td class='i4'>Others</td>" & "<td class='ac bl'>" & IF(o82_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o82_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o82_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o82_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o82_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o82_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o82_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o82_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o82_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o82_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o82_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o82_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o82_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o82_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o82_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o82_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o82_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o82_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o82_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o82_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o82_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o82_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o82_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o82_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.04.3.1.5</td><td class='i4'>ECLDistribuition</td>" & "<td class='ac bl'>" & IF(o83_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o83_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o83_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o83_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o83_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o83_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o83_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o83_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o83_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o83_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o83_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o83_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o83_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o83_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o83_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o83_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o83_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o83_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o83_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o83_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o83_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o83_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o83_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o83_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub1'><td class='cd'>1.05</td><td class='i1'>ACC. RECEIVABLE</td>" & "<td class='ac bl'>" & IF(o84_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o84_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o84_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o84_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o84_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o84_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o84_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o84_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o84_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o84_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o84_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o84_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o84_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o84_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o84_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o84_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o84_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o84_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o84_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o84_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o84_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o84_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o84_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o84_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>"
VAR Rows_8 =
    "<tr class='sub2'><td class='cd'>1.05.1</td><td class='i2'>InterestAccrued</td>" & "<td class='ac bl'>" & IF(o85_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o85_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o85_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o85_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o85_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o85_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o85_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o85_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o85_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o85_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o85_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o85_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o85_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o85_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o85_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o85_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o85_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o85_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o85_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o85_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o85_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o85_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o85_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o85_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.05.1.1</td><td class='i3'>DueFr.Banks&amp;OtherFin. Inst</td>" & "<td class='ac bl'>" & IF(o86_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o86_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o86_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o86_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o86_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o86_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o86_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o86_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o86_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o86_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o86_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o86_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o86_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o86_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o86_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o86_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o86_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o86_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o86_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o86_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o86_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o86_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o86_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o86_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.05.1.3.1</td><td class='i4'>PerformingLoans</td>" & "<td class='ac bl'>" & IF(o87_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o87_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o87_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o87_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o87_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o87_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o87_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o87_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o87_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o87_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o87_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o87_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o87_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o87_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o87_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o87_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o87_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o87_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o87_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o87_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o87_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o87_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o87_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o87_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.05.1.3.2</td><td class='i4'>Non-PerformingLoans</td>" & "<td class='ac bl'>" & IF(o88_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o88_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o88_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o88_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o88_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o88_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o88_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o88_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o88_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o88_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o88_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o88_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o88_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o88_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o88_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o88_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o88_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o88_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o88_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o88_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o88_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o88_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o88_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o88_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>1.05.3</td><td class='i2'>OtherReceivable</td>" & "<td class='ac bl'>" & IF(o89_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o89_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o89_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o89_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o89_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o89_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o89_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o89_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o89_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o89_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o89_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o89_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o89_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o89_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o89_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o89_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o89_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o89_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o89_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o89_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o89_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o89_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o89_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o89_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub1'><td class='cd'>1.06</td><td class='i1'>FIXED ASSETS</td>" & "<td class='ac bl'>" & IF(o90_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o90_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o90_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o90_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o90_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o90_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o90_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o90_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o90_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o90_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o90_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o90_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o90_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o90_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o90_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o90_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o90_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o90_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o90_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o90_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o90_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o90_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o90_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o90_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.06.2.1</td><td class='i3'>Offices/Buildings</td>" & "<td class='ac bl'>" & IF(o91_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o91_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o91_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o91_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o91_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o91_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o91_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o91_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o91_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o91_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o91_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o91_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o91_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o91_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o91_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o91_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o91_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o91_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o91_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o91_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o91_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o91_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o91_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o91_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.06.2.2</td><td class='i3'>OfficeUnderCunstruction</td>" & "<td class='ac bl'>" & IF(o92_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o92_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o92_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o92_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o92_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o92_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o92_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o92_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o92_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o92_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o92_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o92_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o92_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o92_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o92_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o92_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o92_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o92_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o92_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o92_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o92_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o92_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o92_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o92_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.06.2.3</td><td class='i3'>LeaseholdImprov.</td>" & "<td class='ac bl'>" & IF(o93_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o93_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o93_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o93_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o93_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o93_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o93_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o93_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o93_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o93_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o93_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o93_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o93_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o93_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o93_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o93_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o93_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o93_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o93_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o93_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o93_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o93_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o93_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o93_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>1.06.3</td><td class='i2'>FurnetureandFixtures</td>" & "<td class='ac bl'>" & IF(o94_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o94_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o94_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o94_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o94_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o94_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o94_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o94_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o94_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o94_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o94_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o94_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o94_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o94_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o94_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o94_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o94_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o94_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o94_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o94_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o94_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o94_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o94_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o94_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>1.06.4</td><td class='i2'>MachineryandEquip.</td>" & "<td class='ac bl'>" & IF(o95_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o95_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o95_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o95_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o95_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o95_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o95_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o95_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o95_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o95_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o95_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o95_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o95_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o95_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o95_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o95_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o95_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o95_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o95_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o95_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o95_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o95_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o95_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o95_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>1.06.5</td><td class='i2'>Vehicles</td>" & "<td class='ac bl'>" & IF(o96_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o96_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o96_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o96_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o96_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o96_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o96_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o96_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o96_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o96_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o96_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o96_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o96_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o96_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o96_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o96_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o96_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o96_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o96_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o96_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o96_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o96_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o96_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o96_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>"
VAR Rows_9 =
    "<tr class='sub2'><td class='cd'>1.06.6</td><td class='i2'>NonPhysicalAsset</td>" & "<td class='ac bl'>" & IF(o97_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o97_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o97_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o97_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o97_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o97_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o97_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o97_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o97_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o97_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o97_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o97_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o97_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o97_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o97_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o97_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o97_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o97_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o97_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o97_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o97_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o97_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o97_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o97_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>1.06.9</td><td class='i2'>RESERVE FOR DEPREC.</td>" & "<td class='ac bl'>" & IF(o98_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o98_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o98_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o98_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o98_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o98_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o98_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o98_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o98_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o98_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o98_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o98_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o98_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o98_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o98_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o98_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o98_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o98_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o98_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o98_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o98_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o98_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o98_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o98_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.06.9.3</td><td class='i3'>Accum.Depr.Fur.&amp;Fixt.</td>" & "<td class='ac bl'>" & IF(o99_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o99_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o99_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o99_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o99_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o99_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o99_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o99_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o99_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o99_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o99_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o99_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o99_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o99_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o99_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o99_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o99_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o99_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o99_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o99_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o99_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o99_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o99_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o99_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.06.9.4</td><td class='i3'>Accum.Depr.Mech.&amp;Eq.</td>" & "<td class='ac bl'>" & IF(o100_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o100_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o100_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o100_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o100_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o100_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o100_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o100_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o100_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o100_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o100_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o100_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o100_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o100_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o100_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o100_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o100_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o100_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o100_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o100_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o100_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o100_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o100_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o100_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.06.9.5</td><td class='i3'>Accum.Depr.Vehicles</td>" & "<td class='ac bl'>" & IF(o101_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o101_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o101_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o101_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o101_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o101_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o101_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o101_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o101_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o101_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o101_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o101_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o101_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o101_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o101_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o101_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o101_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o101_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o101_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o101_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o101_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o101_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o101_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o101_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.06.9.6</td><td class='i3'>Accum.Depr.Non-PhysicalAssets</td>" & "<td class='ac bl'>" & IF(o102_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o102_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o102_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o102_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o102_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o102_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o102_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o102_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o102_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o102_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o102_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o102_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o102_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o102_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o102_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o102_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o102_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o102_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o102_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o102_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o102_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o102_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o102_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o102_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.06.9.7</td><td class='i3'>Accum.Depr.Building</td>" & "<td class='ac bl'>" & IF(o103_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o103_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o103_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o103_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o103_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o103_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o103_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o103_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o103_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o103_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o103_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o103_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o103_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o103_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o103_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o103_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o103_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o103_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o103_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o103_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o103_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o103_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o103_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o103_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.06.9.8</td><td class='i3'>Accum.Depr.Leasehold</td>" & "<td class='ac bl'>" & IF(o104_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o104_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o104_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o104_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o104_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o104_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o104_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o104_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o104_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o104_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o104_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o104_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o104_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o104_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o104_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o104_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o104_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o104_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o104_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o104_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o104_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o104_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o104_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o104_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub1'><td class='cd'>1.09</td><td class='i1'>OTHER ASSETS</td>" & "<td class='ac bl'>" & IF(o105_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o105_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o105_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o105_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o105_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o105_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o105_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o105_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o105_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o105_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o105_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o105_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o105_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o105_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o105_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o105_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o105_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o105_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o105_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o105_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o105_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o105_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o105_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o105_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>1.09.1</td><td class='i2'>PrepaidExpenses</td>" & "<td class='ac bl'>" & IF(o106_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o106_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o106_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o106_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o106_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o106_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o106_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o106_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o106_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o106_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o106_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o106_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o106_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o106_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o106_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o106_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o106_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o106_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o106_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o106_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o106_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o106_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o106_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o106_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>1.09.1</td><td class='i2'>InterBranchTransactions(NET)</td>" & "<td class='ac bl'>" & IF(o107_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o107_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o107_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o107_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o107_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o107_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o107_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o107_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o107_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o107_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o107_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o107_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o107_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o107_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o107_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o107_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o107_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o107_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o107_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o107_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o107_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o107_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o107_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o107_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>1.09.3</td><td class='i2'>OfficeAccounts</td>" & "<td class='ac bl'>" & IF(o108_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o108_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o108_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o108_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o108_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o108_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o108_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o108_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o108_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o108_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o108_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o108_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o108_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o108_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o108_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o108_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o108_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o108_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o108_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o108_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o108_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o108_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o108_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o108_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>"
VAR Rows_10 =
    "<tr><td class='cd'>1.09.3.1</td><td class='i3'>PettyCashFund</td>" & "<td class='ac bl'>" & IF(o109_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o109_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o109_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o109_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o109_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o109_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o109_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o109_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o109_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o109_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o109_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o109_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o109_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o109_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o109_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o109_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o109_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o109_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o109_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o109_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o109_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o109_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o109_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o109_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.09.3.3</td><td class='i3'>Stationery&amp;OfficeSupp.</td>" & "<td class='ac bl'>" & IF(o110_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o110_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o110_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o110_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o110_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o110_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o110_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o110_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o110_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o110_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o110_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o110_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o110_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o110_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o110_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o110_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o110_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o110_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o110_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o110_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o110_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o110_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o110_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o110_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.09.3.5</td><td class='i3'>Shortages</td>" & "<td class='ac bl'>" & IF(o111_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o111_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o111_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o111_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o111_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o111_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o111_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o111_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o111_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o111_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o111_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o111_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o111_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o111_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o111_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o111_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o111_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o111_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o111_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o111_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o111_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o111_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o111_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o111_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>1.09.4</td><td class='i2'>AssetHeldInRes.ofDebt</td>" & "<td class='ac bl'>" & IF(o112_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o112_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o112_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o112_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o112_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o112_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o112_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o112_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o112_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o112_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o112_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o112_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o112_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o112_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o112_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o112_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o112_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o112_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o112_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o112_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o112_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o112_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o112_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o112_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.09.4.2</td><td class='i3'>AssetsHeldInRes.ofDebt</td>" & "<td class='ac bl'>" & IF(o113_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o113_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o113_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o113_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o113_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o113_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o113_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o113_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o113_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o113_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o113_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o113_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o113_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o113_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o113_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o113_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o113_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o113_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o113_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o113_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o113_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o113_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o113_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o113_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.09.4.3</td><td class='i3'>AllowanceforProbableLosses</td>" & "<td class='ac bl'>" & IF(o114_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o114_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o114_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o114_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o114_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o114_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o114_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o114_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o114_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o114_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o114_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o114_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o114_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o114_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o114_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o114_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o114_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o114_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o114_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o114_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o114_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o114_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o114_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o114_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>1.09.5</td><td class='i2'>ItemsinSuspense</td>" & "<td class='ac bl'>" & IF(o115_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o115_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o115_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o115_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o115_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o115_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o115_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o115_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o115_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o115_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o115_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o115_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o115_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o115_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o115_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o115_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o115_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o115_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o115_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o115_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o115_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o115_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o115_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o115_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>1.09.6</td><td class='i2'>MiscellaneousAssets</td>" & "<td class='ac bl'>" & IF(o116_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o116_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o116_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o116_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o116_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o116_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o116_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o116_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o116_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o116_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o116_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o116_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o116_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o116_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o116_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o116_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o116_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o116_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o116_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o116_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o116_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o116_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o116_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o116_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.09.6.9.2.1</td><td class='i4'>Right Of Use Assets IFRS</td>" & "<td class='ac bl'>" & IF(o117_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o117_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o117_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o117_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o117_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o117_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o117_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o117_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o117_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o117_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o117_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o117_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o117_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o117_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o117_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o117_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o117_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o117_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o117_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o117_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o117_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o117_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o117_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o117_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.09.6.9.2.2</td><td class='i4'>DifferedTax</td>" & "<td class='ac bl'>" & IF(o118_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o118_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o118_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o118_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o118_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o118_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o118_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o118_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o118_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o118_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o118_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o118_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o118_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o118_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o118_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o118_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o118_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o118_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o118_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o118_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o118_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o118_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o118_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o118_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.09.6.9.2</td><td class='i4'>IntangibleAssets(AssetsinProgress)</td>" & "<td class='ac bl'>" & IF(o119_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o119_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o119_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o119_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o119_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o119_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o119_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o119_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o119_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o119_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o119_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o119_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o119_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o119_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o119_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o119_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o119_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o119_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o119_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o119_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o119_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o119_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o119_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o119_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.09.6.9.4</td><td class='i4'>OtherAssets-DepsitPaymentEmp</td>" & "<td class='ac bl'>" & IF(o120_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o120_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o120_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o120_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o120_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o120_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o120_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o120_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o120_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o120_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o120_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o120_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o120_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o120_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o120_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o120_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o120_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o120_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o120_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o120_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o120_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o120_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o120_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o120_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>"
VAR Rows_11 =
    "<tr><td class='cd'>1.09.6.9.7</td><td class='i4'>DefferedCharges</td>" & "<td class='ac bl'>" & IF(o121_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o121_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o121_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o121_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o121_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o121_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o121_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o121_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o121_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o121_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o121_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o121_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o121_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o121_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o121_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o121_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o121_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o121_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o121_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o121_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o121_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o121_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o121_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o121_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>1.09.6.9.9</td><td class='i4'>SundryDebits</td>" & "<td class='ac bl'>" & IF(o122_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o122_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o122_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o122_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o122_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o122_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o122_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o122_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o122_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o122_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o122_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o122_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o122_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o122_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o122_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o122_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o122_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o122_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o122_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o122_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o122_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o122_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o122_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o122_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'></td><td class='i2'>TotalAssets:</td>" & "<td class='ac bl'>" & IF(o123_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o123_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o123_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o123_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o123_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o123_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o123_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o123_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o123_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o123_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o123_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o123_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o123_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o123_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o123_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o123_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o123_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o123_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o123_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o123_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o123_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o123_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o123_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o123_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'></td><td class='i2'>SystemIntError</td>" & "<td class='ac bl'>" & IF(o124_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o124_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o124_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o124_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o124_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o124_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o124_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o124_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o124_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o124_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o124_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o124_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o124_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o124_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o124_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o124_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o124_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o124_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o124_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o124_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o124_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o124_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o124_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o124_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'></td><td class='i2'>TotalAssetsinCRF</td>" & "<td class='ac bl'>" & IF(o125_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o125_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o125_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o125_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o125_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o125_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o125_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o125_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o125_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o125_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o125_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o125_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o125_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o125_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o125_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o125_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o125_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o125_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o125_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o125_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o125_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o125_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o125_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o125_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'></td><td class='i2'>Diference</td>" & "<td class='ac bl'>" & IF(o126_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o126_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o126_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o126_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o126_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o126_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o126_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o126_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o126_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o126_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o126_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o126_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o126_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o126_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o126_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o126_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o126_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o126_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o126_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o126_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o126_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o126_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o126_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o126_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'></td><td class='i2'>ErrorinSystem</td>" & "<td class='ac bl'>" & IF(o127_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o127_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o127_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o127_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o127_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o127_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o127_CI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o127_CI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o127_CI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o127_CI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o127_CP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o127_CP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o127_CP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o127_CP*-1)*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o127_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o127_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF((o127_YI*-1)<0.01,"<span style='color:#d1d5db'>-</span>",IF((o127_YI*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o127_YI*-1),"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT((o127_YI*-1),"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF((o127_YP*-1)<0.0001,"<span style='color:#d1d5db'>-</span>",IF((o127_YP*-1)>0,"<span style='color:#16a34a'>+" & FORMAT((o127_YP*-1)*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT((o127_YP*-1)*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='tot'><td class='cd-w'></td><td class='i0'>TOTAL ASSETS</td><td colspan='8'></td></tr>"
VAR Ftr =
    "<div style='background:#f8fafc;border-top:1px solid #e2e8f0;padding:7px 15px;display:flex;justify-content:space-between;'>" &
    "<span style='font-size:10px;color:#9ca3af;'>USD &nbsp;|&nbsp; <span style='color:#16a34a;'>+</span>=increase &nbsp;<span style='color:#dc2626;'>( )</span>=decrease</span>" &
    "<span style='font-size:10px;color:#9ca3af;'>BNCTL &mdash; Confidential</span>" &
    "</div>"
RETURN
    "<div class='soc'>" & Sty & Hdr &
    "<div style='overflow-x:auto;'>" & ColHdr &
    Rows_1 &
    Rows_2 &
    Rows_3 &
    Rows_4 &
    Rows_5 &
    Rows_6 &
    Rows_7 &
    Rows_8 &
    Rows_9 &
    Rows_10 &
    Rows_11 &
    "</tbody></table></div>" &
    Ftr & "</div>"
