MEASURE 'final_extra_accountable_report'[ExtraAccountable_HTML] =
VAR SelectedYear  = SELECTEDVALUE( 'Calendar_Credit'[Year] )
VAR SelectedMonth = SELECTEDVALUE( 'Calendar_Credit'[report_month] )
VAR MaxDate       = MAX( final_extra_accountable_report[load_date] )
VAR MaxYear       = LEFT( MaxDate, 4 )
VAR ActiveYear    = IF( ISBLANK(SelectedYear),  MaxYear,  SelectedYear )
VAR ActiveMonth   = IF( ISBLANK(SelectedMonth), LEFT(MaxDate,7), SelectedMonth )
VAR MonthDirectFiltered =
    ISFILTERED('Calendar_Credit'[report_month]) || ISFILTERED('Calendar_Credit'[MonthLabel]) ||
    ISFILTERED('Calendar_Credit'[MonthNum])     || ISFILTERED('Calendar_Credit'[SortKey])
VAR YearOnlyMode = ISFILTERED('Calendar_Credit'[Year]) && NOT MonthDirectFiltered
VAR IsMonthMode  = NOT YearOnlyMode
VAR ModeTag      = IF(IsMonthMode, "MoM", "YoY")
VAR PeriodLabel  =
    IF( MonthDirectFiltered,
        "For the Month of " & FORMAT( DATE( VALUE(LEFT(ActiveMonth,4)), VALUE(RIGHT(ActiveMonth,2)), 1 ), "MMMM YYYY" ),
        "For the Year " & ActiveYear )

VAR tblPeriod  = FILTER(final_extra_accountable_report,
    IF(MonthDirectFiltered, LEFT([load_date],7) = ActiveMonth, LEFT([load_date],4) = ActiveYear))
VAR LatestDate = MAXX( tblPeriod, [load_date] )
VAR tblCurr    = FILTER( tblPeriod, [load_date] = LatestDate )
VAR PriorYear  = FORMAT(VALUE(LEFT(LatestDate,4))-1, "0000")
VAR PrevDate   = MAXX(FILTER(final_extra_accountable_report, [load_date] < LatestDate), [load_date])
VAR CompDate   = IF(IsMonthMode, PrevDate, MAXX(FILTER(final_extra_accountable_report, LEFT([load_date],4)=PriorYear), [load_date]))
VAR tblComp    = FILTER(final_extra_accountable_report, [load_date] = CompDate)
VAR CurrLabel  = IF(ISBLANK(LatestDate), "Current", FORMAT(DATE(VALUE(LEFT(LatestDate,4)), VALUE(MID(LatestDate,6,2)), 1), "MMM YYYY"))
VAR CompLabel  = IF(ISBLANK(CompDate),   "N/A",     FORMAT(DATE(VALUE(LEFT(CompDate,4)),   VALUE(MID(CompDate,6,2)),   1), "MMM YYYY"))

VAR TotalPrincipal  = SUMX( tblCurr, IFERROR( VALUE([principal]),                          0 ) )
VAR TotalPI         = SUMX( tblCurr, IFERROR( VALUE([principal_interest]),                 0 ) )
VAR TotalPenalty    = SUMX( tblCurr, IFERROR( VALUE([penalty_interest]),                   0 ) )
VAR TotalBalance    = SUMX( tblCurr, IFERROR( VALUE([balance_principal_interest_penalty]), 0 ) )
VAR TotalBalanceP   = SUMX( tblComp, IFERROR( VALUE([balance_principal_interest_penalty]), 0 ) )
VAR TotalBalanceD   = TotalBalance - TotalBalanceP
VAR TotalWO         = SUMX( tblCurr, IFERROR( VALUE([total_write_off]),                    0 ) )
VAR TotalWOP        = SUMX( tblComp, IFERROR( VALUE([total_write_off]),                    0 ) )
VAR TotalWOD        = TotalWO - TotalWOP
VAR RowCount        = COUNTROWS( tblCurr )

VAR Sty =
    "<style>" &
    ".ea{font-family:Segoe UI,Calibri,sans-serif;font-size:11px;color:#1e2d40;}" &
    ".ea-t{width:100%;border-collapse:collapse;}" &
    ".ea-t td,.ea-t th{padding:5px 10px;border-bottom:1px solid #e8edf3;vertical-align:middle;}" &
    ".ea-t tr:hover td{background:#f5f8ff;}" &
    ".ea-t thead tr th{background:#003366;color:#fff;font-weight:700;font-size:10px;text-transform:uppercase;letter-spacing:0.5px;border-bottom:3px solid #f0a500;padding:7px 10px;text-align:left;white-space:nowrap;}" &
    ".ea-t thead tr th.ar{text-align:right;}" &
    ".nu{color:#9ca3af;font-size:9px;width:35px;text-align:center;}" &
    ".ar{text-align:right!important;font-family:Consolas,monospace;font-size:10px;white-space:nowrap;}" &
    ".ac{text-align:center!important;font-size:10px;}" &
    ".nm{font-weight:600;color:#1e2d40;max-width:220px;}" &
    ".br{color:#374151;font-size:10px;}" &
    ".ct{color:#1a4a7a;font-size:10px;}" &
    ".gt td{background:#003366!important;color:#fff!important;font-weight:800;font-size:11px;border-top:2px solid #f0a500!important;}" &
    ".gt td.ar{font-family:Consolas,monospace;text-align:right;color:#f0a500!important;}" &
    ".zero{color:#d1d5db;}" &
    ".pos{color:#16a34a;font-weight:700;font-family:Consolas,monospace;}.neg{color:#dc2626;font-weight:700;font-family:Consolas,monospace;}.neu{color:#6b7280;font-family:Consolas,monospace;}.nr td{background:#fefce8!important;}.ch td{background:#f0fdf4!important;}</style>"

VAR Hdr =
    "<div style='background:#003366;padding:16px 20px;border-bottom:4px solid #f0a500;display:flex;align-items:center;'>" &
    "<img src='https://i.ibb.co/rWhBLgw/image-2026-04-21-094244962.png' style='height:90px;object-fit:contain;flex-shrink:0;margin-right:20px;' /><div>" &
    "<div style='color:#fff;font-family:Segoe UI,sans-serif;font-size:17px;font-weight:700;text-transform:uppercase;letter-spacing:1px;margin-bottom:4px;'>BANCO NACIONAL DE COMERCIO DE TIMOR LESTE</div>" &
    "<div style='color:#f0a500;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:2px;margin-bottom:6px;'>EXTRA ACCOUNTABLE REPORT  -  " & ModeTag & " COMPARISON</div>" &
    "<div style='color:#cbd5e1;font-size:11px;'>" & PeriodLabel & "</div>" &
    "<div style='color:#94a3b8;font-size:10px;margin-top:3px;'>Current: " & CurrLabel & " &nbsp;vs&nbsp; Previous: " & CompLabel & "</div>" &
    "</div></div>"


VAR Summary =
    "<div style='display:flex;gap:12px;flex-wrap:wrap;padding:14px 16px;background:#f8fafc;border-bottom:1px solid #e2e8f0;'>" &
    "<div style='background:#fff7ed;border:1px solid #fed7aa;border-radius:6px;padding:10px 16px;min-width:120px;'><div style='font-size:9px;color:#c2410c;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Total Accounts</div><div style='font-size:14px;font-weight:800;color:#f0a500;font-family:Consolas,monospace;'>" & FORMAT(RowCount,"#,##0") & "</div></div>" &
    "<div style='background:#fff;border:1px solid #e2e8f0;border-radius:6px;padding:10px 16px;min-width:160px;'><div style='font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Balance P+I+Pen</div><div style='font-size:14px;font-weight:800;color:#003366;font-family:Consolas,monospace;'>" & FORMAT(TotalBalance,"#,##0.00") & "</div></div>" &
    "<div style='background:#e0f2fe;border:1px solid #bae6fd;border-radius:6px;padding:10px 16px;min-width:160px;'><div style='font-size:9px;color:#0369a1;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Prev (" & CompLabel & ")</div><div style='font-size:14px;font-weight:800;color:#0369a1;font-family:Consolas,monospace;'>" & FORMAT(TotalBalanceP,"#,##0.00") & "</div></div>" &
    "<div style='background:#" & IF(TotalBalanceD>0,"dcfce7",IF(TotalBalanceD<0,"fee2e2","f3f4f6")) & ";border:1px solid #e2e8f0;border-radius:6px;padding:10px 16px;min-width:120px;'><div style='font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Delta</div><div style='font-size:14px;font-weight:800;" & IF(TotalBalanceD>0,"color:#16a34a",IF(TotalBalanceD<0,"color:#dc2626","color:#6b7280")) & ";font-family:Consolas,monospace;'>" & FORMAT(TotalBalanceD,"+#,##0.00;-#,##0.00;0.00") & "</div></div>" &
    "<div style='background:#fff;border:1px solid #e2e8f0;border-radius:6px;padding:10px 16px;min-width:160px;'><div style='font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Total Write-Off</div><div style='font-size:14px;font-weight:800;color:#dc2626;font-family:Consolas,monospace;'>" & FORMAT(TotalWO,"#,##0.00") & "</div></div>" &
    "<div style='background:#e0f2fe;border:1px solid #bae6fd;border-radius:6px;padding:10px 16px;min-width:160px;'><div style='font-size:9px;color:#0369a1;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Prev (" & CompLabel & ")</div><div style='font-size:14px;font-weight:800;color:#0369a1;font-family:Consolas,monospace;'>" & FORMAT(TotalWOP,"#,##0.00") & "</div></div>" &
    "<div style='background:#" & IF(TotalWOD>0,"dcfce7",IF(TotalWOD<0,"fee2e2","f3f4f6")) & ";border:1px solid #e2e8f0;border-radius:6px;padding:10px 16px;min-width:120px;'><div style='font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Delta</div><div style='font-size:14px;font-weight:800;" & IF(TotalWOD>0,"color:#16a34a",IF(TotalWOD<0,"color:#dc2626","color:#6b7280")) & ";font-family:Consolas,monospace;'>" & FORMAT(TotalWOD,"+#,##0.00;-#,##0.00;0.00") & "</div></div>" &
    "<div style='background:#f3e8ff;border:1px solid #e9d5ff;border-radius:6px;padding:10px 16px;min-width:160px;'><div style='font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Principal</div><div style='font-size:14px;font-weight:800;color:#7c3aed;font-family:Consolas,monospace;'>" & FORMAT(TotalPrincipal,"#,##0.00") & "</div></div>" &
    "<div style='background:#fef9c3;border:1px solid #fde68a;border-radius:6px;padding:10px 16px;min-width:160px;'><div style='font-size:9px;color:#92400e;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Princ. Interest</div><div style='font-size:14px;font-weight:800;color:#d97706;font-family:Consolas,monospace;'>" & FORMAT(TotalPI,"#,##0.00") & "</div></div>" &
    "</div>"

VAR TH =
    "<table class='ea-t'><thead><tr>" &
    "<th rowspan='2' class='nu'>No.</th>" &
    "<th rowspan='2'>NAME</th>" &
    "<th rowspan='2'>CIF/CID</th>" &
    "<th rowspan='2'>BRANCH</th>" &
    "<th rowspan='2'>CREDIT TYPE</th>" &
    "<th rowspan='2'>LOAN ID</th>" &
    "<th rowspan='2'>ORIGINAL LOAN ID</th>" &
    "<th rowspan='2' class='ac'>YEAR W/O</th>" &
    "<th rowspan='2' class='ar'>PRINCIPAL</th>" &
    "<th rowspan='2' class='ar'>PRINC. INT.</th>" &
    "<th rowspan='2' class='ar'>PENALTY INT.</th>" &
    "<th colspan='3' style='background:#1a4a7a;color:#fff;text-align:center;font-size:10px;padding:7px 8px;border-bottom:2px solid #f0a500;font-style:italic;'>BALANCE P+I+PEN [" & ModeTag & "]</th>" &
    "<th colspan='3' style='background:#1a4a7a;color:#fff;text-align:center;font-size:10px;padding:7px 8px;border-bottom:2px solid #f0a500;font-style:italic;'>WRITE-OFF [" & ModeTag & "]</th>" &
    "</tr><tr>" &
    "<th class='ar'>" & CurrLabel & "</th><th class='ar'>" & CompLabel & "</th><th class='ar'>DELTA</th>" &
    "<th class='ar'>" & CurrLabel & "</th><th class='ar'>" & CompLabel & "</th><th class='ar'>DELTA</th>" &
    "</tr></thead><tbody>"

VAR GrandTotal =
    "<tr class='gt'>" &
    "<td colspan='11'>GRAND TOTAL (" & FORMAT(RowCount,"#,##0") & " accounts)</td>" &
    "<td class='ar'>" & FORMAT(TotalBalance,"#,##0.00") & "</td>" &
    "<td class='ar'>" & FORMAT(TotalBalanceP,"#,##0.00") & "</td>" &
    "<td class='ar'>" & FORMAT(TotalBalanceD,"+#,##0.00;-#,##0.00;0.00") & "</td>" &
    "<td class='ar'>" & FORMAT(TotalWO,"#,##0.00") & "</td>" &
    "<td class='ar'>" & FORMAT(TotalWOP,"#,##0.00") & "</td>" &
    "<td class='ar'>" & FORMAT(TotalWOD,"+#,##0.00;-#,##0.00;0.00") & "</td>" &
    "</tr>"


VAR _PgSize  = 30
VAR _PgNum   = SELECTEDVALUE('PageNum'[Page Number], 1)
VAR _TotRows = COUNTROWS(tblCurr)
VAR _TotPg   = MAX(1, CEILING(_TotRows / _PgSize, 1))
VAR _PgValid = MIN(MAX(1, _PgNum), _TotPg)
VAR _Skip    = (_PgValid - 1) * _PgSize
VAR tblPage  = EXCEPT(
    TOPN(_Skip + _PgSize, tblCurr, [loan_id], ASC),
    TOPN(_Skip,           tblCurr, [loan_id], ASC)
)

VAR DataRows = CONCATENATEX(
    tblPage,
    VAR _nu   = [nu]
    VAR _nm   = [name]
    VAR _cif  = [cif_cid]
    VAR _br   = [branch]
    VAR _brnm = [branch_name]
    VAR _ct   = [credit_type]
    VAR _lid  = [loan_id]
    VAR _olid = [original_loan_id]
    VAR _ywo  = [year_of_write_off]
    VAR _pri  = IFERROR(VALUE([principal]),0)
    VAR _pi   = IFERROR(VALUE([principal_interest]),0)
    VAR _pen  = IFERROR(VALUE([penalty_interest]),0)
    VAR _balC = IFERROR(VALUE([balance_principal_interest_penalty]),0)
    VAR _woC  = IFERROR(VALUE([total_write_off]),0)
    VAR _cr   = FILTER(tblComp, [loan_id] = _lid)
    VAR _balP = MAXX(_cr, IFERROR(VALUE([balance_principal_interest_penalty]),0))
    VAR _woP  = MAXX(_cr, IFERROR(VALUE([total_write_off]),0))
    VAR _isN  = ISBLANK(MAXX(_cr, [loan_id]))
    VAR _balD = _balC - IF(_isN,0,_balP)
    VAR _woD  = _woC  - IF(_isN,0,_woP)
    VAR _rCls = IF(_isN," class='nr'",IF(OR(_balD<>0,_woD<>0)," class='ch'",""))
    VAR _bC   = IF(_balD>0," pos",IF(_balD<0," neg"," neu"))
    VAR _wC   = IF(_woD>0," pos",IF(_woD<0," neg"," neu"))
    RETURN "<tr" & _rCls & ">" &
    "<td class='nu'>" & _nu & "</td>" &
    "<td class='nm'>" & _nm & "</td>" &
    "<td class='ac' style='color:#6b7280;font-size:10px;'>" & _cif & "</td>" &
    "<td class='br'>" & _br & IF(ISBLANK(_brnm),"","<div style='font-size:9px;color:#6b7280;margin-top:1px;'>" & _brnm & "</div>") & "</td>" &
    "<td class='ct'>" & IF(ISBLANK(_ct),"<span style='color:#d1d5db'>-</span>",_ct) & "</td>" &
    "<td class='ac' style='font-family:Consolas,monospace;font-size:10px;color:#374151;'>" & _lid & "</td>" &
    "<td class='ac' style='font-family:Consolas,monospace;font-size:10px;color:#374151;'>" & IF(ISBLANK(_olid),"<span class='zero'> - </span>",_olid) & "</td>" &
    "<td class='ac'>" & IF(ISBLANK(_ywo),"<span style='color:#d1d5db'>-</span>",_ywo) & "</td>" &
    "<td class='ar' style='color:#7c3aed;font-weight:700;font-family:Consolas,monospace;'>" & IF(_pri=0,"<span class='zero'>-</span>",FORMAT(_pri,"#,##0.00")) & "</td>" &
    "<td class='ar' style='color:#d97706;font-weight:700;font-family:Consolas,monospace;'>" & IF(_pi=0,"<span class='zero'>-</span>",FORMAT(_pi,"#,##0.00")) & "</td>" &
    "<td class='ar'>" & IF(_pen=0,"<span class='zero'>-</span>",FORMAT(_pen,"#,##0.00")) & "</td>" &
    "<td class='ar' style='font-weight:600;color:#003366;'>" & IF(_balC=0,"<span class='zero'>-</span>",FORMAT(_balC,"#,##0.00")) & "</td>" &
    "<td class='ar'>" & IF(_isN,"<span class='zero'>NEW</span>",IF(_balP=0,"<span class='zero'>-</span>",FORMAT(_balP,"#,##0.00"))) & "</td>" &
    "<td class='ar" & _bC & "'>" & IF(_isN,"NEW",FORMAT(_balD,"+#,##0.00;-#,##0.00;0.00")) & "</td>" &
    "<td class='ar'>" & IF(_woC=0,"<span class='zero'>-</span>",FORMAT(_woC,"#,##0.00")) & "</td>" &
    "<td class='ar'>" & IF(_isN,"<span class='zero'>NEW</span>",IF(_woP=0,"<span class='zero'>-</span>",FORMAT(_woP,"#,##0.00"))) & "</td>" &
    "<td class='ar" & _wC & "'>" & IF(_isN,"NEW",FORMAT(_woD,"+#,##0.00;-#,##0.00;0.00")) & "</td></tr>",
    ,
    [loan_id], ASC
)

VAR Ftr =
    "<div style='background:#f8fafc;border-top:1px solid #e2e8f0;padding:7px 15px;display:flex;justify-content:space-between;'>" &
    "<span style='font-size:10px;color:#9ca3af;'>All amounts in USD</span>" &
    "<span style='font-size:10px;color:#9ca3af;'>BNCTL - Confidential</span>" &
    "</div>"


VAR _WinStart  = MAX(1, _PgValid - 4)
VAR _WinEnd    = MIN(_TotPg, _PgValid + 4)
VAR _ShowFirst = _WinStart > 1
VAR _ShowLast  = _WinEnd < _TotPg
VAR _PgButtons =
    IF(_ShowFirst,
        "<span style='display:inline-flex;align-items:center;justify-content:center;" &
        "min-width:26px;height:26px;padding:0 6px;border-radius:5px;font-size:12px;margin:0 2px;" &
        "background:#f1f5f9;color:#64748b;'>1</span>" &
        IF(_WinStart > 2, "<span style='color:#94a3b8;margin:0 2px;'>...</span>", ""),
        ""
    ) &
    CONCATENATEX(
        GENERATESERIES(_WinStart, _WinEnd, 1),
        VAR _p   = [Value]
        VAR _act = _p = _PgValid
        RETURN
        "<span style='display:inline-flex;align-items:center;justify-content:center;" &
        "min-width:26px;height:26px;padding:0 6px;border-radius:5px;font-size:12px;margin:0 2px;" &
        "font-weight:" & IF(_act,"700","400") & ";" &
        IF(_act,
            "background:#3b82f6;color:#fff;box-shadow:0 2px 4px rgba(59,130,246,0.35);",
            "background:#f1f5f9;color:#64748b;"
        ) & "'>" & _p & "</span>",
        "",
        [Value], ASC
    ) &
    IF(_ShowLast,
        IF(_WinEnd < _TotPg - 1, "<span style='color:#94a3b8;margin:0 2px;'>...</span>", "") &
        "<span style='display:inline-flex;align-items:center;justify-content:center;" &
        "min-width:26px;height:26px;padding:0 6px;border-radius:5px;font-size:12px;margin:0 2px;" &
        "background:#f1f5f9;color:#64748b;'>" & _TotPg & "</span>",
        ""
    )
VAR PgBar =
    "<div style='background:#f8fafc;border-top:2px solid #e2e8f0;padding:10px 16px;" &
    "display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:6px;'>" &
    "<span style='font-size:11px;color:#64748b;'>Showing " &
    "<b style='color:#1e293b;'>" & (_Skip + 1) & "</b> &ndash; " &
    "<b style='color:#1e293b;'>" & MIN(_Skip + _PgSize, _TotRows) & "</b>" &
    " of <b style='color:#1e293b;'>" & _TotRows & "</b> records</span>" &
    "<div style='display:flex;align-items:center;'>" & _PgButtons & "</div>" &
    "<span style='font-size:10px;color:#94a3b8;font-style:italic;'>Use PageNum slicer</span>" &
    "</div>"

RETURN "<div class='ea'>" & Sty & Hdr & Summary & "<div style='overflow-x:auto;'>" & TH & DataRows & GrandTotal & "</tbody></table></div>" & Ftr & PgBar & "</div>"
