MEASURE 'final_income_report'[Income_HTML] =
VAR MaxDate        = CALCULATE( MAX( final_income_report[load_date] ), ALL(final_income_report) )
VAR SelReportMonth = SELECTEDVALUE( Calendar[report_month] )
VAR SelYear        = SELECTEDVALUE( Calendar[Year] )
VAR SelMonthNum    = SELECTEDVALUE( Calendar[MonthNum] )
VAR ActiveMonth    =
    IF( NOT ISBLANK(SelReportMonth), SelReportMonth,
    IF( NOT ISBLANK(SelYear) && NOT ISBLANK(SelMonthNum),
        SelYear & "-" & FORMAT(SelMonthNum,"00"),
    IF( NOT ISBLANK(SelYear),
        MAXX( FILTER(ALL(final_income_report), LEFT([load_date], 4)=SelYear),
              LEFT([load_date], 7) ),
        LEFT(MaxDate, 7) )))
VAR PeriodLabel    = FORMAT( DATE(VALUE(LEFT(ActiveMonth,4)),VALUE(RIGHT(ActiveMonth,2)),1), "MMMM YYYY" )

VAR tbl = FILTER(
    ALL( final_income_report ),
    LEFT( final_income_report[load_date], 7 ) = ActiveMonth
)

VAR Branches = DATATABLE("b", STRING,
    {{"UPGRADE"},{"DILI"},{"GLENO"},{"MALIANA"},{"AILEU"},{"CUSSE"},
     {"BAUCAU"},{"SAME"},{"AINARO"},{"SUAI"},{"VIQUEQUE"},{"LOSPALOS"},
     {"LIQUICA"},{"MANATUTO"}})

VAR BranchLabels = DATATABLE("bk", STRING, "bl", STRING,
    {{"UPGRADE","Head Office"},{"DILI","Dili"},{"GLENO","Gleno"},
     {"MALIANA","Maliana"},{"AILEU","Aileu"},{"CUSSE","Oe-Cusse"},
     {"BAUCAU","Baucau"},{"SAME","Same"},{"AINARO","Ainaro"},
     {"SUAI","Suai"},{"VIQUEQUE","Viqueque"},{"LOSPALOS","Lospalos"},
     {"LIQUICA","Liquica"},{"MANATUTO","Manatuto"}})

VAR Sty =
    "<style>" &
    "body,td,th{font-family:Calibri,Arial,sans-serif;font-size:11px;color:#1e2d40}" &
    ".pw{width:100%;overflow-x:auto;-webkit-overflow-scrolling:touch}" &
    ".gl{font-family:Calibri,Arial,sans-serif;font-size:11px;color:#1e2d40;min-width:1200px}" &
    ".t{width:100%;border-collapse:collapse}" &
    ".t td,.t th{padding:2px 6px;border-bottom:1px solid #e8edf3;white-space:nowrap}" &
    ".sec td{background:#cffafe!important;color:#0c4a6e!important;font-weight:700;font-size:10px;text-transform:uppercase;border-bottom:2px solid #22d3ee!important}" &
    ".s1 td{background:#ecfeff!important;color:#0c4a6e!important;font-weight:700}" &
    ".s2 td{background:#ffffff!important;color:#374151!important;font-weight:400}" &
    ".tot td{background:#a5f3fc!important;color:#0c4a6e!important;font-weight:700;border-top:2px solid #22d3ee!important}" &
    ".fix{position:sticky;left:0;z-index:2;background:#ffffff}" &
    ".fixc{position:sticky;left:180px;z-index:2;background:#ffffff}" &
    ".am{text-align:right;font-family:Consolas,monospace;font-size:10px}" &
    ".hdr-br{background:#003366!important;color:#fff!important;font-weight:700;text-align:center;padding:4px 6px;border-left:2px solid #1a4a7a}" &
    ".hdr-sub{background:#1a4a7a!important;color:#cbd5e1!important;text-align:center;font-size:10px;padding:2px 6px}" &
    ".hdr-cons{background:#92400e!important;color:#fef3c7!important;font-weight:700;text-align:center;padding:4px 6px;border-left:2px solid #f0a500}" &
    ".sticky-hdr{position:sticky;top:0;z-index:3}" &
    ".sticky-hdr2{position:sticky;top:28px;z-index:3}" &
    ".zero{color:#94a3b8}" &
    "i0{padding-left:0px} i1{padding-left:12px} i2{padding-left:24px} i3{padding-left:36px}" &
    ".fix,.fixc{background:#ffffff}.sec .fix,.sec .fixc{background:#cffafe!important}.s1 .fix,.s1 .fixc{background:#ecfeff!important}.s2 .fix,.s2 .fixc{background:#ffffff!important}.tot .fix,.tot .fixc{background:#a5f3fc!important}</style>"

VAR Logo = "https://i.ibb.co/rWhBLgw/image-2026-04-21-094244962.png"

VAR Hdr =
    "<div style='background:#003366;padding:16px 20px;border-bottom:4px solid #f0a500;display:flex;align-items:center;gap:20px;'>" &
    "<img src='https://i.ibb.co/rWhBLgw/image-2026-04-21-094244962.png' alt='BNCTL Logo' style='height:90px;width:auto;flex-shrink:0;' />" &
    "<div style='flex:1;'>" &
    "<div style='color:#fff;font-size:16px;font-weight:700;text-transform:uppercase;letter-spacing:1px;margin-bottom:4px;'>BANCO NACIONAL DE COMERCIO DE TIMOR LESTE</div>" &
    "<div style='color:#f0a500;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:2px;margin-bottom:4px;'>CONSOLIDATED STATEMENT OF INCOME</div>" &
    "<div style='color:#cbd5e1;font-size:11px;'>" & PeriodLabel & "</div>" &
    "</div>" &
    "</div>"

VAR BranchHeaderCols =
    CONCATENATEX(
        BranchLabels,
        "<th class='hdr-br sticky-hdr' style='border-left:2px solid #1a4a7a'>" & [bl] & "</th>",
        "", [bk], ASC
    )

VAR BranchSubCols =
    CONCATENATEX(
        BranchLabels,
        "<th class='hdr-sub sticky-hdr2' style='border-left:2px solid #1a4a7a'>Amount</th>",
        "", [bk], ASC
    )

VAR TH =
    "<table class='t'><thead>" &
    "<tr class='sticky-hdr'>" &
    "<th class='hdr-br fix sticky-hdr' style='min-width:180px;text-align:left'>Account Title</th>" &
    "<th class='hdr-br fixc sticky-hdr' style='min-width:80px;text-align:left'>Code</th>" &
    BranchHeaderCols &
    "<th class='hdr-cons sticky-hdr' style='border-left:3px solid #f0a500'>CONSOLIDATED</th>" &
    "</tr>" &
    "<tr class='sticky-hdr2'>" &
    "<th class='hdr-sub fix sticky-hdr2'></th>" &
    "<th class='hdr-sub fixc sticky-hdr2'></th>" &
    BranchSubCols &
    "<th class='hdr-sub sticky-hdr2' style='background:#92400e!important;color:#fef3c7!important;border-left:3px solid #f0a500'>Amount</th>" &
    "</tr>" &
    "</thead><tbody>"

VAR RowData = CONCATENATEX(
    FILTER(
        ADDCOLUMNS(
            SUMMARIZE( tbl, final_income_report[order_id], final_income_report[code], final_income_report[description] ),
            "vOid",  final_income_report[order_id],
            "vCode", final_income_report[code],
            "vDesc", final_income_report[description]
        ),
        VALUE([vOid]) >= 1
    ),

    VAR vOid  = [vOid]
    VAR vCode = [vCode]
    VAR vDesc = [vDesc]

    VAR nDots  = LEN(vCode) - LEN(SUBSTITUTE(vCode, ".", ""))
    VAR isTot  = CONTAINSSTRING(vDesc, "Total") || CONTAINSSTRING(vDesc, "TOTAL")
    VAR rowCls = IF(isTot, "tot",
                IF(nDots <= 1, "sec",
                IF(nDots = 2,  "s1",
                IF(nDots = 3,  "s2", ""))))
    VAR indent = IF(nDots <= 1, "0px", IF(nDots = 2, "12px", IF(nDots = 3, "24px", "36px")))

    VAR BranchCells = CONCATENATEX(
        Branches,
        VAR vBr = [b]
        VAR vAm = SUMX(
            FILTER( tbl, VALUE([order_id]) = VALUE(vOid) && [branch_name] = vBr ),
            IFERROR( VALUE([amount]), 0 )
        )
        VAR fAm = IF(
            vAm = 0, "<span class='zero'>-</span>",
            IF( vAm < 0,
                "<span style='color:#dc2626'>" & FORMAT(vAm,"#,##0.00") & "</span>",
                FORMAT(vAm,"#,##0.00")
            )
        )
        RETURN "<td class='am' style='border-left:1px solid #e8edf3'>" & fAm & "</td>",
        "", [b], ASC
    )

    VAR vCons = SUMX(
        FILTER( tbl, VALUE([order_id]) = VALUE(vOid) ),
        IFERROR( VALUE([amount]), 0 )
    )
    VAR fCons = IF(
        vCons = 0, "<span class='zero'>-</span>",
        IF( vCons < 0,
            "<span style='color:#dc2626'>" & FORMAT(vCons,"#,##0.00") & "</span>",
            FORMAT(vCons,"#,##0.00")
        )
    )

    RETURN
        "<tr class='" & rowCls & "'>" &
        "<td class='fix' style='padding-left:" & indent & "'>" & vDesc & "</td>" &
        "<td class='fixc' style='font-family:Consolas,monospace;font-size:10px;color:#94a3b8'>" & vCode & "</td>" &
        BranchCells &
        "<td class='am' style='border-left:3px solid #f0a500;font-weight:700'>" & fCons & "</td>" &
        "</tr>",

    "", [vOid], ASC
)

VAR Ftr =
    "<div style='background:#f8fafc;border-top:2px solid #f0a500;padding:6px 14px;" &
    "display:flex;justify-content:space-between;align-items:center'>" &
    "<span style='font-size:10px;color:#9ca3af'>USD &nbsp;|&nbsp; Scroll horizontally to view all branches &nbsp;|&nbsp; BNCTL &mdash; Confidential</span>" &
    "</div>"

RETURN
    IF( COUNTROWS(tbl) = 0,
        "<div style='padding:20px;font-family:Calibri;color:#dc2626'>&#9888; No income data for " & PeriodLabel & "</div>",
        "<div class='pw'><div class='gl'>" &
            Sty & Hdr &
            "<div style='overflow-x:auto'>" &
                TH & RowData & "</tbody></table>" &
            "</div>" & Ftr &
        "</div></div>"
    )
