MEASURE 'provision_mock'[Provision_Comparison_HTML] =
VAR SelectedYear  = SELECTEDVALUE( 'Calendar_Credit'[Year] )
VAR SelectedMonth = SELECTEDVALUE( 'Calendar_Credit'[report_month] )

VAR AllCurr = FILTER(ALL('provision_mock'), 'provision_mock'[type_period] = "CURR")
VAR AllPrev = FILTER(ALL('provision_mock'), 'provision_mock'[type_period] = "PREV")
VAR AllYoy  = FILTER(ALL('provision_mock'), 'provision_mock'[type_period] = "YOY")

VAR MaxDate    = MAXX(AllCurr, 'provision_mock'[load_date])
VAR ActiveYear  = IF( ISBLANK(SelectedYear),  LEFT(MaxDate,4), SelectedYear )
VAR ActiveMonth = IF( ISBLANK(SelectedMonth), LEFT(MaxDate,7), SelectedMonth )

VAR MonthFiltered = ISFILTERED('Calendar_Credit'[report_month])
VAR YearFiltered  = ISFILTERED('Calendar_Credit'[Year])
VAR IsMonthMode   = MonthFiltered || NOT YearFiltered

VAR SnapDate =
    IF( MonthFiltered,
        MAXX(FILTER(AllCurr, LEFT('provision_mock'[load_date],7) <= ActiveMonth), 'provision_mock'[load_date]),
    IF( YearFiltered,
        MAXX(FILTER(AllCurr, LEFT('provision_mock'[load_date],4) = ActiveYear),  'provision_mock'[load_date]),
        MaxDate
    ))

VAR HasPrev = COUNTROWS(FILTER(AllPrev, 'provision_mock'[load_date] = SnapDate)) > 0
VAR CompDateMoM = IF(HasPrev, SnapDate, MAXX(FILTER(AllCurr, 'provision_mock'[load_date] < SnapDate), 'provision_mock'[load_date]))
VAR CompTypeMoM = IF(HasPrev, "PREV", "CURR")

VAR HasYoy = COUNTROWS(FILTER(AllYoy, 'provision_mock'[load_date] = SnapDate)) > 0
VAR PriorYearStr = FORMAT(VALUE(LEFT(SnapDate,4)) - 1, "0000")
VAR CompDateYoY = IF(HasYoy, SnapDate, MAXX(FILTER(AllCurr, LEFT('provision_mock'[load_date],4) = PriorYearStr), 'provision_mock'[load_date]))
VAR CompTypeYoY = IF(HasYoy, "YOY", "CURR")

VAR CompDate = IF(IsMonthMode, CompDateMoM, CompDateYoY)
VAR CompType = IF(IsMonthMode, CompTypeMoM, CompTypeYoY)
VAR ModeTag  = IF(IsMonthMode, "MoM", "YoY")

VAR tblCurr = FILTER(ALL('provision_mock'), AND('provision_mock'[type_period] = "CURR", 'provision_mock'[load_date] = SnapDate))
VAR tblComp = FILTER(ALL('provision_mock'), AND('provision_mock'[type_period] = CompType, 'provision_mock'[load_date] = CompDate))

VAR CurrLabel = MAXX(tblCurr, 'provision_mock'[load_date_label])
VAR CompLabel = MAXX(tblComp, 'provision_mock'[load_date_label])

VAR PeriodLabel =
    IF( MonthFiltered,
        "For the Month of " & FORMAT( DATE( VALUE(LEFT(ActiveMonth,4)), VALUE(RIGHT(ActiveMonth,2)), 1 ), "MMMM YYYY" ),
        "For the Year " & ActiveYear )

VAR TotalOutCurr    = SUMX( tblCurr, ABS( IFERROR( VALUE('provision_mock'[outstanding]), 0 ) ) )
VAR TotalOutComp    = SUMX( tblComp, ABS( IFERROR( VALUE('provision_mock'[outstanding]), 0 ) ) )
VAR TotalOutDelta   = TotalOutCurr - TotalOutComp
VAR TotalCommitment = SUMX( tblCurr, IFERROR( VALUE('provision_mock'[commitment]), 0 ) )
VAR TotalProvCurr   = SUMX( tblCurr, ABS( IFERROR( VALUE('provision_mock'[provision]), 0 ) ) )
VAR TotalProvComp   = SUMX( tblComp, ABS( IFERROR( VALUE('provision_mock'[provision]), 0 ) ) )
VAR TotalProvDelta  = TotalProvCurr - TotalProvComp
VAR RowCount        = COUNTROWS( tblCurr )

VAR Sty = "<style>.pv{font-family:Segoe UI,Calibri,sans-serif;font-size:10.5px;color:#1e2d40;}.pv-t{width:100%;border-collapse:collapse;}.pv-t td{padding:4px 8px;border-bottom:1px solid #e8edf3;vertical-align:middle;white-space:nowrap;}.pv-t tr:hover td{background:#f5f8ff;}.pv-t thead th{background:#003366;color:#fff;font-weight:700;font-size:10px;text-transform:uppercase;letter-spacing:0.4px;border-bottom:3px solid #f0a500;padding:7px 8px;text-align:left;white-space:nowrap;}.pv-t thead th.ar{text-align:right;}.pv-t thead th.ac{text-align:center;}.pv-t thead th.grp{background:#1a4a7a;text-align:center;border-bottom:2px solid #f0a500;font-style:italic;}.ar{text-align:right!important;font-family:Consolas,monospace;font-size:10px;}.ac{text-align:center!important;font-size:10px;}.nm{font-weight:500;font-size:10.5px;}.lid{font-family:Consolas,monospace;font-size:10px;color:#374151;}.cl-STD{background:#dcfce7;color:#166534;font-weight:700;font-size:9px;padding:2px 7px;border-radius:10px;display:inline-block;}.cl-SUB{background:#fff7ed;color:#c2410c;font-weight:700;font-size:9px;padding:2px 7px;border-radius:10px;display:inline-block;}.cl-DBT{background:#fef3c7;color:#b45309;font-weight:700;font-size:9px;padding:2px 7px;border-radius:10px;display:inline-block;}.cl-LSS{background:#fee2e2;color:#dc2626;font-weight:700;font-size:9px;padding:2px 7px;border-radius:10px;display:inline-block;}.cl-OTH{background:#f3f4f6;color:#6b7280;font-weight:700;font-size:9px;padding:2px 7px;border-radius:10px;display:inline-block;}.st-CUR{color:#16a34a;font-weight:600;font-size:10px;}.st-OTH{color:#dc2626;font-weight:600;font-size:10px;}.gt td{background:#003366!important;color:#fff!important;font-weight:800;font-size:11px;border-top:2px solid #f0a500!important;}.gt td.ar{font-family:Consolas,monospace;text-align:right;color:#f0a500!important;}.zero{color:#d1d5db;}.pos{color:#16a34a;font-weight:700;font-family:Consolas,monospace;}.neg{color:#dc2626;font-weight:700;font-family:Consolas,monospace;}.neu{color:#6b7280;font-family:Consolas,monospace;}.nr td{background:#fefce8!important;}.ch td{background:#f0fdf4!important;}</style>"

VAR Hdr =
    "<div style='background:#003366;padding:16px 20px;border-bottom:4px solid #f0a500;display:flex;align-items:center;'><img src='https://i.ibb.co/rWhBLgw/image-2026-04-21-094244962.png' style='height:90px;object-fit:contain;flex-shrink:0;margin-right:20px;' /><div>" &
    "<div style='color:#fff;font-family:Segoe UI,sans-serif;font-size:17px;font-weight:700;text-transform:uppercase;letter-spacing:1px;margin-bottom:4px;'>BANCO NACIONAL DE COMERCIO DE TIMOR LESTE</div>" &
    "<div style='color:#f0a500;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:2px;margin-bottom:6px;'>PROVISION REPORT  -  PAST DUE  -  " & ModeTag & " COMPARISON</div>" &
    "<div style='color:#cbd5e1;font-size:11px;'>" & PeriodLabel & "</div>" &
    "<div style='color:#94a3b8;font-size:10px;margin-top:3px;'>Current: " & CurrLabel & " &nbsp;vs&nbsp; Previous: " & CompLabel & "</div>" &
    "</div></div>"

VAR Summary =
    "<div style='display:flex;gap:12px;flex-wrap:wrap;padding:14px 16px;background:#f8fafc;border-bottom:1px solid #e2e8f0;'>" &
    "<div style='background:#fff;border:1px solid #e2e8f0;border-radius:6px;padding:10px 16px;min-width:120px;'><div style='font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Total Loans</div><div style='font-size:20px;font-weight:800;color:#003366;font-family:Consolas,monospace;'>" & FORMAT(RowCount,"#,##0") & "</div></div>" &
    "<div style='background:#fff;border:1px solid #e2e8f0;border-radius:6px;padding:10px 16px;min-width:180px;'><div style='font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Total Outstanding</div><div style='font-size:15px;font-weight:800;color:#003366;font-family:Consolas,monospace;'>" & FORMAT(TotalOutCurr,"#,##0.00") & "</div></div>" &
    "<div style='background:#fff;border:1px solid #e2e8f0;border-radius:6px;padding:10px 16px;min-width:180px;'><div style='font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Total Commitment</div><div style='font-size:15px;font-weight:800;color:#1a4a7a;font-family:Consolas,monospace;'>" & FORMAT(TotalCommitment,"#,##0.00") & "</div></div>" &
    "<div style='background:#fff;border:1px solid #e2e8f0;border-radius:6px;padding:10px 16px;min-width:180px;'><div style='font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Total Provision</div><div style='font-size:15px;font-weight:800;color:#dc2626;font-family:Consolas,monospace;'>" & FORMAT(TotalProvCurr,"#,##0.00") & "</div></div>" &
    "<div style='background:#e0f2fe;border:1px solid #bae6fd;border-radius:6px;padding:10px 16px;min-width:180px;'><div style='font-size:9px;color:#0369a1;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Prev Outstanding (" & CompLabel & ")</div><div style='font-size:15px;font-weight:800;color:#0369a1;font-family:Consolas,monospace;'>" & FORMAT(TotalOutComp,"#,##0.00") & "</div></div>" &
    "<div style='background:#" & IF(TotalOutDelta>0,"dcfce7",IF(TotalOutDelta<0,"fee2e2","f3f4f6")) & ";border:1px solid #" & IF(TotalOutDelta>0,"bbf7d0",IF(TotalOutDelta<0,"fecaca","e5e7eb")) & ";border-radius:6px;padding:10px 16px;min-width:160px;'><div style='font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Outstanding Delta</div><div style='font-size:15px;font-weight:800;" & IF(TotalOutDelta>0,"color:#16a34a",IF(TotalOutDelta<0,"color:#dc2626","color:#6b7280")) & ";font-family:Consolas,monospace;'>" & FORMAT(TotalOutDelta,"+#,##0.00;-#,##0.00;0.00") & "</div></div>" &
    "<div style='background:#fff0f0;border:1px solid #fecaca;border-radius:6px;padding:10px 16px;min-width:180px;'><div style='font-size:9px;color:#9a1515;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Prev Provision (" & CompLabel & ")</div><div style='font-size:15px;font-weight:800;color:#dc2626;font-family:Consolas,monospace;'>" & FORMAT(TotalProvComp,"#,##0.00") & "</div></div>" &
    "<div style='background:#" & IF(TotalProvDelta>0,"fee2e2",IF(TotalProvDelta<0,"dcfce7","f3f4f6")) & ";border:1px solid #" & IF(TotalProvDelta>0,"fecaca",IF(TotalProvDelta<0,"bbf7d0","e5e7eb")) & ";border-radius:6px;padding:10px 16px;min-width:160px;'><div style='font-size:9px;color:#6b7280;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px;'>Provision Delta</div><div style='font-size:15px;font-weight:800;" & IF(TotalProvDelta>0,"color:#dc2626",IF(TotalProvDelta<0,"color:#16a34a","color:#6b7280")) & ";font-family:Consolas,monospace;'>" & FORMAT(TotalProvDelta,"+#,##0.00;-#,##0.00;0.00") & "</div></div>" &
    "</div>"

VAR TH =
    "<table class='pv-t'><thead><tr>" &
    "<th rowspan='2'>LOAN ID</th><th rowspan='2'>ORIGINAL LOAN ID</th><th rowspan='2'>ARRANGEMENT ID</th>" &
    "<th rowspan='2'>BRANCH</th><th rowspan='2'>CUST NO.</th><th rowspan='2'>CUSTOMER NAME</th>" &
    "<th rowspan='2' class='ac'>CAT</th><th rowspan='2'>PRODUCT</th><th rowspan='2' class='ac'>CCY</th>" &
    "<th rowspan='2' class='ac'>CLASSIFICATION</th>" &
    "<th rowspan='2' class='ar'>LOCAL CCY AMT</th><th rowspan='2' class='ar'>BASE AMOUNT</th>" &
    "<th colspan='3' class='grp'>OUTSTANDING [" & ModeTag & "] vs " & CompLabel & "</th>" &
    "<th rowspan='2' class='ac'>VALUE DATE</th><th rowspan='2' class='ar'>COMMITMENT</th>" &
    "<th rowspan='2' class='ac'>OVER DUE DAYS</th><th rowspan='2' class='ac'>START DATE</th><th rowspan='2' class='ac'>MAT DATE</th>" &
    "<th colspan='3' class='grp'>PROVISION [" & ModeTag & "] vs " & CompLabel & "</th>" &
    "<th rowspan='2' class='ac'>STATUS</th></tr><tr>" &
    "<th class='ar'>" & CurrLabel & "</th><th class='ar'>" & CompLabel & "</th><th class='ar'>DELTA</th>" &
    "<th class='ar'>" & CurrLabel & "</th><th class='ar'>" & CompLabel & "</th><th class='ar'>DELTA</th>" &
    "</tr></thead><tbody>"

VAR GrandTotal =
    "<tr class='gt'><td colspan='10'>GRAND TOTAL (" & FORMAT(RowCount,"#,##0") & " loans)</td>" &
    "<td class='ar'>" & FORMAT(SUMX(tblCurr,ABS(IFERROR(VALUE('provision_mock'[local_ccy_amt]),0))),"#,##0.00") & "</td>" &
    "<td class='ar'>" & FORMAT(SUMX(tblCurr,ABS(IFERROR(VALUE('provision_mock'[base_amount]),0))),"#,##0.00") & "</td>" &
    "<td class='ar'>" & FORMAT(TotalOutCurr,"#,##0.00") & "</td>" &
    "<td class='ar'>" & FORMAT(TotalOutComp,"#,##0.00") & "</td>" &
    "<td class='ar'>" & FORMAT(TotalOutDelta,"+#,##0.00;-#,##0.00;0.00") & "</td>" &
    "<td class='ac'> - </td><td class='ar'>" & FORMAT(TotalCommitment,"#,##0.00") & "</td>" &
    "<td class='ac'> - </td><td class='ac'> - </td><td class='ac'> - </td>" &
    "<td class='ar'>" & FORMAT(TotalProvCurr,"#,##0.00") & "</td>" &
    "<td class='ar'>" & FORMAT(TotalProvComp,"#,##0.00") & "</td>" &
    "<td class='ar'>" & FORMAT(TotalProvDelta,"+#,##0.00;-#,##0.00;0.00") & "</td>" &
    "<td class='ac'> - </td></tr>"

VAR Ftr =
    "<div style='background:#f8fafc;border-top:1px solid #e2e8f0;padding:7px 15px;display:flex;justify-content:space-between;'>" &
    "<span style='font-size:10px;color:#9ca3af;'>All amounts in USD &nbsp;|&nbsp; Negative amounts displayed as absolute values</span>" &
    "<span style='font-size:10px;color:#9ca3af;'>BNCTL  -  Confidential</span></div>"

RETURN "<div class='pv'>" & Sty & Hdr & Summary & "<div style='overflow-x:auto;'>" & TH &
CONCATENATEX(
    tblCurr,
    VAR _lid  = 'provision_mock'[loan_id]
    VAR _olid = 'provision_mock'[original_loan_id]
    VAR _arr  = 'provision_mock'[arrangement_id]
    VAR _brn  = 'provision_mock'[branch_code]
    VAR _cust = 'provision_mock'[cust_number]
    VAR _nm   = 'provision_mock'[customer_name]
    VAR _cat  = 'provision_mock'[category]
    VAR _prod = 'provision_mock'[product_name]
    VAR _ccy  = 'provision_mock'[currency]
    VAR _cls  = 'provision_mock'[classification]
    VAR _lca  = ABS( IFERROR( VALUE('provision_mock'[local_ccy_amt]), 0 ) )
    VAR _ba   = ABS( IFERROR( VALUE('provision_mock'[base_amount]),   0 ) )
    VAR _outC = ABS( IFERROR( VALUE('provision_mock'[outstanding]),   0 ) )
    VAR _vd   = 'provision_mock'[value_date]
    VAR _comm = IFERROR( VALUE('provision_mock'[commitment]), 0 )
    VAR _odd  = IFERROR( VALUE('provision_mock'[over_due_days]), 0 )
    VAR _sd   = 'provision_mock'[start_date]
    VAR _md   = 'provision_mock'[mat_date]
    VAR _prvC = ABS( IFERROR( VALUE('provision_mock'[provision]), 0 ) )
    VAR _sts  = 'provision_mock'[status]
    VAR _cr   = FILTER(tblComp, 'provision_mock'[loan_id] = _lid)
    VAR _outP = MAXX(_cr, ABS( IFERROR( VALUE('provision_mock'[outstanding]), 0 ) ))
    VAR _prvP = MAXX(_cr, ABS( IFERROR( VALUE('provision_mock'[provision]),   0 ) ))
    VAR _isN  = ISBLANK(MAXX(_cr, 'provision_mock'[loan_id]))
    VAR _outD = _outC - IF(_isN, 0, _outP)
    VAR _prvD = _prvC - IF(_isN, 0, _prvP)
    VAR _rCls = IF(_isN, " class='nr'", IF(OR(_outD<>0,_prvD<>0), " class='ch'", ""))
    VAR _oC   = IF(_outD>0," pos",IF(_outD<0," neg"," neu"))
    VAR _pC   = IF(_prvD>0," pos",IF(_prvD<0," neg"," neu"))
    VAR _clsB = SWITCH(UPPER(_cls),
        "STANDARD",    "<span class='cl-STD'>STANDARD</span>",
        "SUB-STANDARD","<span class='cl-SUB'>SUB-STD</span>",
        "SUBSTANDARD", "<span class='cl-SUB'>SUB-STD</span>",
        "DOUBTFUL",    "<span class='cl-DBT'>DOUBTFUL</span>",
        "LOSS",        "<span class='cl-LSS'>LOSS</span>",
        IF(ISBLANK(_cls),"<span class='zero'> - </span>","<span class='cl-OTH'>" & _cls & "</span>"))
    VAR _stsB = IF(UPPER(_sts)="CURRENT","<span class='st-CUR'>CURRENT</span>",
        IF(ISBLANK(_sts),"<span class='zero'> - </span>","<span class='st-OTH'>" & UPPER(_sts) & "</span>"))
    RETURN "<tr" & _rCls & ">" &
    "<td class='lid'>" & _lid & "</td>" &
    "<td class='lid'>" & IF(ISBLANK(_olid),"<span class='zero'> - </span>",_olid) & "</td>" &
    "<td class='lid'>" & _arr & "</td>" &
    "<td style='font-size:10px;color:#374151;'>" & _brn & "</td>" &
    "<td class='ac' style='font-size:10px;color:#6b7280;'>" & _cust & "</td>" &
    "<td class='nm'>" & _nm & "</td>" &
    "<td class='ac' style='font-size:10px;color:#6b7280;'>" & _cat & "</td>" &
    "<td style='font-size:10px;'>" & _prod & "</td>" &
    "<td class='ac' style='font-size:10px;font-weight:600;color:#1a4a7a;'>" & _ccy & "</td>" &
    "<td class='ac'>" & _clsB & "</td>" &
    "<td class='ar'>" & IF(_lca=0,"<span class='zero'>-</span>",FORMAT(_lca,"#,##0.00")) & "</td>" &
    "<td class='ar'>" & IF(_ba=0,"<span class='zero'>-</span>",FORMAT(_ba,"#,##0.00")) & "</td>" &
    "<td class='ar' style='font-weight:600;'>" & IF(_outC=0,"<span class='zero'>-</span>",FORMAT(_outC,"#,##0.00")) & "</td>" &
    "<td class='ar'>" & IF(_isN,"<span class='zero'>NEW</span>",IF(_outP=0,"<span class='zero'>-</span>",FORMAT(_outP,"#,##0.00"))) & "</td>" &
    "<td class='ar" & _oC & "'>" & IF(_isN,"NEW",FORMAT(_outD,"+#,##0.00;-#,##0.00;0.00")) & "</td>" &
    "<td class='ac' style='font-size:10px;'>" & IF(ISBLANK(_vd),"<span class='zero'> - </span>",LEFT(_vd,4)&"-"&MID(_vd,5,2)&"-"&RIGHT(_vd,2)) & "</td>" &
    "<td class='ar'>" & IF(_comm=0,"<span class='zero'>-</span>",FORMAT(_comm,"#,##0.00")) & "</td>" &
    "<td class='ac' style='font-size:10px;" & IF(_odd>0,"color:#dc2626;font-weight:700;","color:#d1d5db;") & "'>" & IF(_odd=0," - ",FORMAT(_odd,"#,##0")&" d") & "</td>" &
    "<td class='ac' style='font-size:10px;'>" & IF(ISBLANK(_sd),"<span class='zero'> - </span>",LEFT(_sd,4)&"-"&MID(_sd,5,2)&"-"&RIGHT(_sd,2)) & "</td>" &
    "<td class='ac' style='font-size:10px;'>" & IF(ISBLANK(_md),"<span class='zero'> - </span>",LEFT(_md,4)&"-"&MID(_md,5,2)&"-"&RIGHT(_md,2)) & "</td>" &
    "<td class='ar' style='font-weight:600;" & IF(_prvC>0,"color:#dc2626;","color:#d1d5db;") & "'>" & IF(_prvC=0,"-",FORMAT(_prvC,"#,##0.00")) & "</td>" &
    "<td class='ar'>" & IF(_isN,"<span class='zero'>NEW</span>",IF(_prvP=0,"<span class='zero'>-</span>",FORMAT(_prvP,"#,##0.00"))) & "</td>" &
    "<td class='ar" & _pC & "'>" & IF(_isN,"NEW",FORMAT(_prvD,"+#,##0.00;-#,##0.00;0.00")) & "</td>" &
    "<td class='ac'>" & _stsB & "</td></tr>",
    ,
    'provision_mock'[loan_id], ASC
) & GrandTotal & "</tbody></table></div>" & Ftr & "</div>"

