MEASURE 'final_assets_report'[Assets_HTML] =
VAR SelectedBranch = SELECTEDVALUE( final_assets_report[branch_name] )
VAR MaxDate   = CALCULATE( MAX( final_assets_report[load_date] ), ALL(final_assets_report) )
VAR SelReportMonth = SELECTEDVALUE( Calendar[report_month] )
VAR SelYear        = SELECTEDVALUE( Calendar[Year] )
VAR SelMonthNum    = SELECTEDVALUE( Calendar[MonthNum] )
VAR ActiveMonth =
    IF( NOT ISBLANK(SelReportMonth), SelReportMonth,
    IF( NOT ISBLANK(SelYear) && NOT ISBLANK(SelMonthNum),
        SelYear & "-" & FORMAT(SelMonthNum,"00"),
    IF( NOT ISBLANK(SelYear),
        MAXX( FILTER(ALL(final_assets_report), LEFT([load_date], 4)=SelYear),
              LEFT([load_date], 7) ),
        LEFT(MaxDate, 7) )))
VAR PeriodLabel = FORMAT( DATE(VALUE(LEFT(ActiveMonth,4)),VALUE(RIGHT(ActiveMonth,2)),1), "MMMM YYYY" )
VAR tbl = FILTER( ALL(final_assets_report), LEFT([load_date], 7) = ActiveMonth )

-- ============================================================
-- BRANCH FILTER HELPERS (amounts stored as negative, use ABS)
-- ============================================================
-- Branch mapping: UPGRADE=Head Office, DILI=Dili, GLENO=Gleno, MALIANA=Maliana
-- AILEU=Aileu, CUSSE=Oe-Cusse, BAUCAU=Baucau, SAME=Same, AINARO=Ainaro
-- SUAI=Suai, VIQUEQUE=Viqueque, LOSPALOS=Lospalos, LIQUICA=Liquica, MANATUTO=Manatuto
-- Consolidated = SUM all branches

-- Macro: get amount for a given order_id + branch
-- Amount stored as negative → use ABS

-- HEAD OFFICE (UPGRADE)
VAR HO3   = SUMX(FILTER(tbl,[order_id]=3   && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO4   = SUMX(FILTER(tbl,[order_id]=4   && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO5   = SUMX(FILTER(tbl,[order_id]=5   && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO6   = SUMX(FILTER(tbl,[order_id]=6   && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO7   = SUMX(FILTER(tbl,[order_id]=7   && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO8   = SUMX(FILTER(tbl,[order_id]=8   && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO9   = SUMX(FILTER(tbl,[order_id]=9   && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO10  = SUMX(FILTER(tbl,[order_id]=10  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO11  = SUMX(FILTER(tbl,[order_id]=11  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO12  = SUMX(FILTER(tbl,[order_id]=12  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO13  = SUMX(FILTER(tbl,[order_id]=13  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO14  = SUMX(FILTER(tbl,[order_id]=14  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO15  = SUMX(FILTER(tbl,[order_id]=15  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO16  = SUMX(FILTER(tbl,[order_id]=16  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO17  = SUMX(FILTER(tbl,[order_id]=17  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO18  = SUMX(FILTER(tbl,[order_id]=18  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO19  = SUMX(FILTER(tbl,[order_id]=19  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO20  = SUMX(FILTER(tbl,[order_id]=20  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO21  = SUMX(FILTER(tbl,[order_id]=21  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO22  = SUMX(FILTER(tbl,[order_id]=22  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO23  = SUMX(FILTER(tbl,[order_id]=23  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO24  = SUMX(FILTER(tbl,[order_id]=24  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO25  = SUMX(FILTER(tbl,[order_id]=25  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO26  = SUMX(FILTER(tbl,[order_id]=26  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO27  = SUMX(FILTER(tbl,[order_id]=27  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO28  = SUMX(FILTER(tbl,[order_id]=28  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO29  = SUMX(FILTER(tbl,[order_id]=29  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO30  = SUMX(FILTER(tbl,[order_id]=30  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO31  = SUMX(FILTER(tbl,[order_id]=31  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO32  = SUMX(FILTER(tbl,[order_id]=32  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO33  = SUMX(FILTER(tbl,[order_id]=33  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO34  = SUMX(FILTER(tbl,[order_id]=34  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO35  = SUMX(FILTER(tbl,[order_id]=35  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO36  = SUMX(FILTER(tbl,[order_id]=36  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO37  = SUMX(FILTER(tbl,[order_id]=37  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO38  = SUMX(FILTER(tbl,[order_id]=38  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO39  = SUMX(FILTER(tbl,[order_id]=39  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO40  = SUMX(FILTER(tbl,[order_id]=40  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO41  = SUMX(FILTER(tbl,[order_id]=41  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO42  = SUMX(FILTER(tbl,[order_id]=42  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO43  = SUMX(FILTER(tbl,[order_id]=43  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO44  = SUMX(FILTER(tbl,[order_id]=44  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO45  = SUMX(FILTER(tbl,[order_id]=45  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO46  = SUMX(FILTER(tbl,[order_id]=46  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO47  = SUMX(FILTER(tbl,[order_id]=47  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO48  = SUMX(FILTER(tbl,[order_id]=48  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO49  = SUMX(FILTER(tbl,[order_id]=49  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO50  = SUMX(FILTER(tbl,[order_id]=50  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO51  = SUMX(FILTER(tbl,[order_id]=51  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO52  = SUMX(FILTER(tbl,[order_id]=52  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO53  = SUMX(FILTER(tbl,[order_id]=53  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO54  = SUMX(FILTER(tbl,[order_id]=54  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO55  = SUMX(FILTER(tbl,[order_id]=55  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO56  = SUMX(FILTER(tbl,[order_id]=56  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO57  = SUMX(FILTER(tbl,[order_id]=57  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO58  = SUMX(FILTER(tbl,[order_id]=58  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO59  = SUMX(FILTER(tbl,[order_id]=59  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO60  = SUMX(FILTER(tbl,[order_id]=60  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO61  = SUMX(FILTER(tbl,[order_id]=61  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO62  = SUMX(FILTER(tbl,[order_id]=62  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO63  = SUMX(FILTER(tbl,[order_id]=63  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO64  = SUMX(FILTER(tbl,[order_id]=64  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO65  = SUMX(FILTER(tbl,[order_id]=65  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO66  = SUMX(FILTER(tbl,[order_id]=66  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO67  = SUMX(FILTER(tbl,[order_id]=67  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO68  = SUMX(FILTER(tbl,[order_id]=68  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO69  = SUMX(FILTER(tbl,[order_id]=69  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO70  = SUMX(FILTER(tbl,[order_id]=70  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO71  = SUMX(FILTER(tbl,[order_id]=71  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO72  = SUMX(FILTER(tbl,[order_id]=72  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO73  = SUMX(FILTER(tbl,[order_id]=73  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO74  = SUMX(FILTER(tbl,[order_id]=74  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO75  = SUMX(FILTER(tbl,[order_id]=75  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO76  = SUMX(FILTER(tbl,[order_id]=76  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO77  = SUMX(FILTER(tbl,[order_id]=77  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO78  = SUMX(FILTER(tbl,[order_id]=78  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO79  = SUMX(FILTER(tbl,[order_id]=79  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO80  = SUMX(FILTER(tbl,[order_id]=80  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO81  = SUMX(FILTER(tbl,[order_id]=81  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO82  = SUMX(FILTER(tbl,[order_id]=82  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO83  = SUMX(FILTER(tbl,[order_id]=83  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO84  = SUMX(FILTER(tbl,[order_id]=84  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO85  = SUMX(FILTER(tbl,[order_id]=85  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO86  = SUMX(FILTER(tbl,[order_id]=86  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO87  = SUMX(FILTER(tbl,[order_id]=87  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO88  = SUMX(FILTER(tbl,[order_id]=88  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO89  = SUMX(FILTER(tbl,[order_id]=89  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO90  = SUMX(FILTER(tbl,[order_id]=90  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO91  = SUMX(FILTER(tbl,[order_id]=91  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO92  = SUMX(FILTER(tbl,[order_id]=92  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO93  = SUMX(FILTER(tbl,[order_id]=93  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO94  = SUMX(FILTER(tbl,[order_id]=94  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO95  = SUMX(FILTER(tbl,[order_id]=95  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO96  = SUMX(FILTER(tbl,[order_id]=96  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO97  = SUMX(FILTER(tbl,[order_id]=97  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO98  = SUMX(FILTER(tbl,[order_id]=98  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO99  = SUMX(FILTER(tbl,[order_id]=99  && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO100 = SUMX(FILTER(tbl,[order_id]=100 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO101 = SUMX(FILTER(tbl,[order_id]=101 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO102 = SUMX(FILTER(tbl,[order_id]=102 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO103 = SUMX(FILTER(tbl,[order_id]=103 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO104 = SUMX(FILTER(tbl,[order_id]=104 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO105 = SUMX(FILTER(tbl,[order_id]=105 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO106 = SUMX(FILTER(tbl,[order_id]=106 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO107 = SUMX(FILTER(tbl,[order_id]=107 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO108 = SUMX(FILTER(tbl,[order_id]=108 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO109 = SUMX(FILTER(tbl,[order_id]=109 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO110 = SUMX(FILTER(tbl,[order_id]=110 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO111 = SUMX(FILTER(tbl,[order_id]=111 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO112 = SUMX(FILTER(tbl,[order_id]=112 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO113 = SUMX(FILTER(tbl,[order_id]=113 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO114 = SUMX(FILTER(tbl,[order_id]=114 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO115 = SUMX(FILTER(tbl,[order_id]=115 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO116 = SUMX(FILTER(tbl,[order_id]=116 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO117 = SUMX(FILTER(tbl,[order_id]=117 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO118 = SUMX(FILTER(tbl,[order_id]=118 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO119 = SUMX(FILTER(tbl,[order_id]=119 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO120 = SUMX(FILTER(tbl,[order_id]=120 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO121 = SUMX(FILTER(tbl,[order_id]=121 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO122 = SUMX(FILTER(tbl,[order_id]=122 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO123 = SUMX(FILTER(tbl,[order_id]=123 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO124 = SUMX(FILTER(tbl,[order_id]=124 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO125 = SUMX(FILTER(tbl,[order_id]=125 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO126 = SUMX(FILTER(tbl,[order_id]=126 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))
VAR HO127 = SUMX(FILTER(tbl,[order_id]=127 && [branch_name]="UPGRADE"),IFERROR(VALUE([amount]),0))

-- ============================================================
-- BRANCH AMOUNTS (ABS of stored negative values)
-- Helper: get consolidated amount = sum across ALL branches for order_id
-- ============================================================
-- We'll use CONCATENATEX approach for branch columns inside each row
-- Branches in display order (matching Excel):
-- UPGRADE=Head Office, DILI, GLENO, MALIANA, AILEU, CUSSE, BAUCAU, SAME, AINARO, SUAI, VIQUEQUE, LOSPALOS, LIQUICA, MANATUTO
-- Consolidated = SUM all branches per order_id

VAR BranchOrder = 
    DATATABLE("br", STRING, "lbl", STRING,
        {{"UPGRADE","Head Office"},{"DILI","Dili"},{"GLENO","Gleno"},{"MALIANA","Maliana"},
         {"AILEU","Aileu"},{"CUSSE","Oe-Cusse"},{"BAUCAU","Baucau"},{"SAME","Same"},
         {"AINARO","Ainaro"},{"SUAI","Suai"},{"VIQUEQUE","Viqueque"},
         {"LOSPALOS","Lospalos"},{"LIQUICA","Liquica"},{"MANATUTO","Manatuto"}})

-- ============================================================
-- STYLES
-- ============================================================
VAR Sty =
    "<style>" &
    ".as{font-family:Segoe UI,Calibri,sans-serif;font-size:9.5px;color:#1e2d40;}" &
    ".as-wrap{overflow-x:auto;overflow-y:auto;max-height:820px;border:1px solid #ccc;}" &
    ".as-t{border-collapse:collapse;white-space:nowrap;}" &
    ".as-t td,.as-t th{padding:3px 7px;border:1px solid #e0e4ea;vertical-align:middle;}" &
    ".as-t tr:hover td{background:#f5f8ff!important;}" &
    -- Section headers (dark navy)
    ".sec td{background:#cffafe!important;color:#0c4a6e!important;font-weight:700;font-size:10px;text-transform:uppercase;border-bottom:2px solid #22d3ee!important}" &
    -- Sub level 1
    ".s1 td{background:#ecfeff!important;color:#0c4a6e!important;font-weight:700}" &
    -- Sub level 2
    ".s2 td{background:#ffffff!important;color:#374151!important;font-weight:400}" &
    -- Total row
    ".tot td{background:#a5f3fc!important;color:#0c4a6e!important;font-weight:700;border-top:2px solid #22d3ee!important}" &
    -- Sticky first column (Account Title)
    ".fix{position:sticky;left:0;z-index:10;background:#ffffff;min-width:260px;max-width:260px;border-right:2px solid #b0bac9!important;}" &
    -- Sticky second column (Code)
    ".fixc{position:sticky;left:260px;z-index:10;background:#ffffff;min-width:115px;max-width:115px;border-right:2px solid #b0bac9!important;font-size:9px;color:#9ca3af;}" &
    ".fixc-hdr{position:sticky;left:260px;z-index:20;background:#004680!important;min-width:115px;max-width:115px;border-right:2px solid #b0bac9!important;}" &
    -- Amount cells
    ".am{text-align:right!important;font-family:Consolas,monospace;font-size:9px;min-width:105px;}" &
    -- Header cells
    ".hdr-br{background:#004680!important;color:#fff!important;font-weight:700;font-size:9.5px;text-align:center!important;border-color:#003366!important;}" &
    ".hdr-sub{background:#1a4a7a!important;color:#d1d5db!important;font-size:8.5px;text-align:center!important;border-bottom:2px solid #f0a500!important;}" &
    ".hdr-cons{background:#003366!important;color:#f0a500!important;font-weight:700;font-size:9.5px;text-align:center!important;border-left:2px solid #f0a500!important;}" &
    ".hdr-cons-sub{background:#003366!important;color:#f0a500!important;font-size:8.5px;text-align:center!important;border-left:2px solid #f0a500!important;border-bottom:2px solid #f0a500!important;}" &
    -- Indent
    ".i0{padding-left:8px!important;}" &
    ".i1{padding-left:18px!important;}" &
    ".i2{padding-left:28px!important;}" &
    ".i3{padding-left:38px!important;}" &
    ".i4{padding-left:48px!important;}" &
    -- Sticky header
    ".sticky-hdr{position:sticky;top:0;z-index:30;}" &
    ".sticky-hdr2{position:sticky;top:27px;z-index:30;}" &
    ".zero{color:#d1d5db;}" &
    ".fixhdr{position:sticky;left:0;z-index:40;background:#004680!important;min-width:260px;max-width:260px;border-right:2px solid #b0bac9!important;}" &
    ".fix,.fixc{background:#ffffff}.sec .fix,.sec .fixc{background:#cffafe!important}.s1 .fix,.s1 .fixc{background:#ecfeff!important}.s2 .fix,.s2 .fixc{background:#ffffff!important}.tot .fix,.tot .fixc{background:#a5f3fc!important}</style>"

-- ============================================================
-- HEADER WITH LOGO
-- ============================================================
VAR Hdr =
    "<div style='background:#003366;padding:16px 20px;border-bottom:4px solid #f0a500;display:flex;align-items:center;gap:20px;'>" &
    "<img src='https://i.ibb.co/rWhBLgw/image-2026-04-21-094244962.png' alt='BNCTL Logo' style='height:90px;width:auto;flex-shrink:0;' />" &
    "<div style='flex:1;'>" &
    "<div style='color:#fff;font-size:16px;font-weight:700;text-transform:uppercase;letter-spacing:1px;margin-bottom:4px;'>BANCO NACIONAL DE COMERCIO DE TIMOR LESTE</div>" &
    "<div style='color:#f0a500;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:2px;margin-bottom:4px;'>CONSOLIDATED STATEMENT OF ASSETS AND LIABILITIES</div>" &
    "<div style='color:#cbd5e1;font-size:11px;'>" & PeriodLabel & "</div>" &
    "</div>" &
    "</div>"

-- ============================================================
-- TABLE COLUMN HEADERS (2 rows like Excel)
-- Row 1: Account Titles | Code | Head Office | Dili Branch | ... | CONSOLIDATED
-- Row 2: (blank) | (blank) | Accts | Amounts | Accts | Amounts | ...
-- ============================================================
VAR TH =
    "<table class='as-t'><thead>" &
    -- ROW 1
    "<tr class='sticky-hdr'>" &
    "<th class='fixhdr' rowspan='2' style='text-align:left;font-size:10px;font-weight:700;color:#fff;padding:6px 8px;border-bottom:2px solid #f0a500;'>Account Titles</th>" &
    "<th class='fixc-hdr hdr-br' rowspan='2' style='text-align:center;font-size:10px;border-bottom:2px solid #f0a500;'>Code</th>" &
    "<th class='hdr-br' colspan='2' style='border-left:2px solid #1a6aaa;'>Head Office</th>" &
    "<th class='hdr-br' colspan='2' style='border-left:2px solid #1a6aaa;'>Dili Branch</th>" &
    "<th class='hdr-br' colspan='2' style='border-left:2px solid #1a6aaa;'>Gleno Branch</th>" &
    "<th class='hdr-br' colspan='2' style='border-left:2px solid #1a6aaa;'>Maliana Branch</th>" &
    "<th class='hdr-br' colspan='2' style='border-left:2px solid #1a6aaa;'>Aileu Branch</th>" &
    "<th class='hdr-br' colspan='2' style='border-left:2px solid #1a6aaa;'>Oe-Cusse Branch</th>" &
    "<th class='hdr-br' colspan='2' style='border-left:2px solid #1a6aaa;'>Baucau Branch</th>" &
    "<th class='hdr-br' colspan='2' style='border-left:2px solid #1a6aaa;'>Same Branch</th>" &
    "<th class='hdr-br' colspan='2' style='border-left:2px solid #1a6aaa;'>Ainaro Branch</th>" &
    "<th class='hdr-br' colspan='2' style='border-left:2px solid #1a6aaa;'>Suai Branch</th>" &
    "<th class='hdr-br' colspan='2' style='border-left:2px solid #1a6aaa;'>Viqueque Branch</th>" &
    "<th class='hdr-br' colspan='2' style='border-left:2px solid #1a6aaa;'>Lospalos Branch</th>" &
    "<th class='hdr-br' colspan='2' style='border-left:2px solid #1a6aaa;'>Liquica Branch</th>" &
    "<th class='hdr-br' colspan='2' style='border-left:2px solid #1a6aaa;'>Manatuto Branch</th>" &
    "<th class='hdr-cons' colspan='2' style='border-left:2px solid #f0a500;'>CONSOLIDATED</th>" &
    "</tr>" &
    -- ROW 2
    "<tr class='sticky-hdr2'>" &
    "<th class='hdr-sub' style='border-left:2px solid #1a6aaa;'>Accts</th><th class='hdr-sub'>Amounts</th>" &
    "<th class='hdr-sub' style='border-left:2px solid #1a6aaa;'>Accts</th><th class='hdr-sub'>Amounts</th>" &
    "<th class='hdr-sub' style='border-left:2px solid #1a6aaa;'>Accts</th><th class='hdr-sub'>Amounts</th>" &
    "<th class='hdr-sub' style='border-left:2px solid #1a6aaa;'>Accts</th><th class='hdr-sub'>Amounts</th>" &
    "<th class='hdr-sub' style='border-left:2px solid #1a6aaa;'>Accts</th><th class='hdr-sub'>Amounts</th>" &
    "<th class='hdr-sub' style='border-left:2px solid #1a6aaa;'>Accts</th><th class='hdr-sub'>Amounts</th>" &
    "<th class='hdr-sub' style='border-left:2px solid #1a6aaa;'>Accts</th><th class='hdr-sub'>Amounts</th>" &
    "<th class='hdr-sub' style='border-left:2px solid #1a6aaa;'>Accts</th><th class='hdr-sub'>Amounts</th>" &
    "<th class='hdr-sub' style='border-left:2px solid #1a6aaa;'>Accts</th><th class='hdr-sub'>Amounts</th>" &
    "<th class='hdr-sub' style='border-left:2px solid #1a6aaa;'>Accts</th><th class='hdr-sub'>Amounts</th>" &
    "<th class='hdr-sub' style='border-left:2px solid #1a6aaa;'>Accts</th><th class='hdr-sub'>Amounts</th>" &
    "<th class='hdr-sub' style='border-left:2px solid #1a6aaa;'>Accts</th><th class='hdr-sub'>Amounts</th>" &
    "<th class='hdr-sub' style='border-left:2px solid #1a6aaa;'>Accts</th><th class='hdr-sub'>Amounts</th>" &
    "<th class='hdr-sub' style='border-left:2px solid #1a6aaa;'>Accts</th><th class='hdr-sub'>Amounts</th>" &
    "<th class='hdr-cons-sub' style='border-left:2px solid #f0a500;'>Accts</th><th class='hdr-cons-sub'>Amounts</th>" &
    "</tr>" &
    "</thead><tbody>"

-- ============================================================
-- HELPER FUNCTIONS (inline - generate 30 branch cells per row)
-- For each order_id, get: accts + amount per each of 14 branches + consolidated
-- ============================================================

-- Row generator macro (used for each data row)
-- F(oid, desc, code_txt, indent_class, row_class)
-- Branch order: UPGRADE, DILI, GLENO, MALIANA, AILEU, CUSSE, BAUCAU, SAME, AINARO, SUAI, VIQUEQUE, LOSPALOS, LIQUICA, MANATUTO

-- ============================================================
-- REUSABLE: build 30 data cells for a given order_id
-- ============================================================
VAR _BRANCHES = {"UPGRADE","DILI","GLENO","MALIANA","AILEU","CUSSE","BAUCAU","SAME","AINARO","SUAI","VIQUEQUE","LOSPALOS","LIQUICA","MANATUTO"}

-- Helper: format number
-- F = IF(v=0, dash, FORMAT(v,"#,##0.00"))

-- ============================================================
-- DATA ROWS - each row uses CONCATENATEX over branches inline
-- ============================================================

VAR R_LIQUID_HDR =
    "<tr class='sec'>" &
    "<td class='fix i0'>A S S E T S :</td><td class='fixc'>1.0</td>" &
    "<td class='am' colspan='28'></td><td class='am' colspan='2'></td></tr>"

VAR R_LIQUID_FUNDS =
    "<tr class='sec'><td class='fix i0'>LIQUID FUNDS</td><td class='fixc'>1.01</td>" & 
    CONCATENATEX(
        SELECTCOLUMNS(DATATABLE("br",STRING,{{"UPGRADE"},{"DILI"},{"GLENO"},{"MALIANA"},{"AILEU"},{"CUSSE"},{"BAUCAU"},{"SAME"},{"AINARO"},{"SUAI"},{"VIQUEQUE"},{"LOSPALOS"},{"LIQUICA"},{"MANATUTO"}}),
        "br",[br]),
        VAR vBr = [br]
        VAR vAc = SUMX(FILTER(tbl,[order_id]=2 && [branch_name]=vBr),IFERROR(VALUE([total_accounts]),0))
        VAR vAm = SUMX(FILTER(tbl,[order_id]=2 && [branch_name]=vBr),IFERROR(VALUE([amount]),0))
        RETURN "<td class='am' style='border-left:2px solid #dde4ef;'>" & IF(vAc=0,"<span class='zero'>-</span>",FORMAT(vAc,"#,##0")) & "</td><td class='am'>" & IF(vAm<0.01,"<span class='zero'>-</span>",FORMAT(vAm,"#,##0.00")) & "</td>",
        ""
    ) &
    VAR vConsAc = SUMX(FILTER(tbl,[order_id]=2),IFERROR(VALUE([total_accounts]),0))
    VAR vConsAm = SUMX(FILTER(tbl,[order_id]=2),IFERROR(VALUE([amount]),0))
    RETURN
    "<td class='am' style='border-left:2px solid #f0a500;color:#003366;font-weight:700;'>" & IF(vConsAc=0,"<span class='zero'>-</span>",FORMAT(vConsAc,"#,##0")) & "</td><td class='am' style='color:#003366;font-weight:700;'>" & IF(vConsAm<0.01,"<span class='zero'>-</span>",FORMAT(vConsAm,"#,##0.00")) & "</td></tr>"

-- ============================================================
-- ROW BUILDER FUNCTION (reused for all 127 rows via CONCATENATEX)
-- ============================================================

VAR RowData =
    CONCATENATEX(
        FILTER(
            ADDCOLUMNS(
                SUMMARIZE(tbl,
                    final_assets_report[order_id],
                    final_assets_report[code],
                    final_assets_report[description]
                ),
                "oid", final_assets_report[order_id],
                "vCode", final_assets_report[code],
                "vDesc", final_assets_report[description]
            ),
            [oid] <= 127
        ),

        VAR vOid  = [oid]
        VAR vCode = [vCode]
        VAR vDesc = [vDesc]

        -- Row style based on order_id / code pattern
        VAR vIsSec =
            vOid=1 || vOid=2 || vOid=43 || vOid=45 || vOid=63 || vOid=80 ||
            vOid=84 || vOid=90 || vOid=98 || vOid=105
        VAR vIsS1 =
            vOid=7 || vOid=8 || vOid=29 || vOid=46 || vOid=83 || vOid=85 ||
            vOid=86 || vOid=88 || vOid=91 || vOid=94 || vOid=97 || vOid=101 ||
            vOid=108 || vOid=116 || vOid=119 || vOid=123 || vOid=124 || vOid=125 || vOid=126 || vOid=127
        VAR vIsS2 = NOT vIsSec && NOT vIsS1
        VAR vIsTot = vOid = 123

        VAR vRowClass = SWITCH(TRUE(), vIsTot, "tot", vIsSec, "sec", vIsS1, "s1", "s2")

        VAR vIndent =
            SWITCH(TRUE(),
                vIsSec, "i0",
                vOid=7 || vOid=29 || vOid=43 || vOid=44 || vOid=45 || vOid=46 ||
                vOid=63 || vOid=80 || vOid=83 || vOid=84 || vOid=90 || vOid=98 ||
                vOid=101 || vOid=105 || vOid=108, "i1",
                vOid=9 || vOid=20 || vOid=85 || vOid=86 || vOid=88 || vOid=89 ||
                vOid=91 || vOid=92 || vOid=93 || vOid=94 || vOid=95 || vOid=96 ||
                vOid=97 || vOid=99 || vOid=100 || vOid=102 || vOid=103 || vOid=104 ||
                vOid=106 || vOid=107 || vOid=109 || vOid=111 || vOid=112 || vOid=113 ||
                vOid=115 || vOid=116 || vOid=119, "i2",
                "i3"
            )

        VAR vBranchCells =
            CONCATENATEX(
                SELECTCOLUMNS(
                    DATATABLE("b",STRING,{{"UPGRADE"},{"DILI"},{"GLENO"},{"MALIANA"},{"AILEU"},{"CUSSE"},{"BAUCAU"},{"SAME"},{"AINARO"},{"SUAI"},{"VIQUEQUE"},{"LOSPALOS"},{"LIQUICA"},{"MANATUTO"}}),
                    "b",[b]
                ),
                VAR vBr = [b]
                VAR vAc = SUMX(FILTER(tbl,[order_id]=vOid && [branch_name]=vBr),IFERROR(VALUE([total_accounts]),0))
                VAR vAm = SUMX(FILTER(tbl,[order_id]=vOid && [branch_name]=vBr),IFERROR(VALUE([amount]),0))
                RETURN
                "<td class='am' style='border-left:2px solid #dde4ef;'>" &
                IF(vAc=0,"<span class='zero'>-</span>",FORMAT(vAc,"#,##0")) &
                "</td><td class='am'>" &
                IF(vAm<0.01,"<span class='zero'>-</span>",FORMAT(vAm,"#,##0.00")) &
                "</td>",
                ""
            )

        VAR vConsAc = SUMX(FILTER(tbl,[order_id]=vOid),IFERROR(VALUE([total_accounts]),0))
        VAR vConsAm = SUMX(FILTER(tbl,[order_id]=vOid),IFERROR(VALUE([amount]),0))

        RETURN
        "<tr class='" & vRowClass & "'>" &
        "<td class='fix " & vIndent & "'>" & IF(ISBLANK(vDesc),"",vDesc) & "</td>" &
        "<td class='fixc'>" & IF(ISBLANK(vCode),"",vCode) & "</td>" &
        vBranchCells &
        "<td class='am' style='border-left:2px solid #f0a500;font-weight:700;color:#003366;'>" &
        IF(vConsAc=0,"<span class='zero'>-</span>",FORMAT(vConsAc,"#,##0")) &
        "</td><td class='am' style='font-weight:700;color:#003366;'>" &
        IF(vConsAm<0.01,"<span class='zero'>-</span>",FORMAT(vConsAm,"#,##0.00")) &
        "</td></tr>",

        "",
        [oid], ASC
    )

-- ============================================================
-- FOOTER
-- ============================================================
VAR Ftr =
    "<div style='background:#f8fafc;border-top:1px solid #e2e8f0;padding:7px 15px;display:flex;justify-content:space-between;'>" &
    "<span style='font-size:10px;color:#9ca3af;'>USD | Scroll horizontally to view all branches</span>" &
    "<span style='font-size:10px;color:#9ca3af;'>BNCTL &mdash; Confidential</span>" &
    "</div>"

RETURN
    "<div class='as'>" & Sty & Hdr &
    "<div class='as-wrap'>" & TH &
    RowData &
    "</tbody></table></div>" &
    Ftr & "</div>"
