MEASURE 'final_po_sie_report'[PO_SIE_HTML] =
VAR SelectedYear  = SELECTEDVALUE( Calendar[Year] )
VAR SelectedMonth = SELECTEDVALUE( Calendar[report_month] )
VAR MaxDate      = MAX( final_po_sie_report[load_date] )
VAR MaxYear       = LEFT(MaxDate, 4)
VAR ActiveYear    = IF( ISBLANK(SelectedYear),  MaxYear,  SelectedYear )
VAR ActiveMonth   = IF( ISBLANK(SelectedMonth), LEFT(MaxDate, 7), SelectedMonth )
VAR PeriodLabel   =
    IF(
        NOT ISBLANK(SelectedMonth),
        "For the Month of " & FORMAT( DATE( LEFT(ActiveMonth,4), RIGHT(ActiveMonth,2), 1 ), "MMMM YYYY" ),
        "For the Year Ended " & ActiveYear
    )
VAR tbl =
    FILTER( ALL(final_po_sie_report),
        IF(
            NOT ISBLANK(SelectedMonth),
            LEFT([load_date], 7) = ActiveMonth,
            LEFT([load_date], 4) = ActiveYear
        )
    )
VAR r8   = SUMX( FILTER(tbl,VALUE([order_id])=8),   [amount] )
VAR r9   = SUMX( FILTER(tbl,VALUE([order_id])=9),   [amount] )
VAR r10  = SUMX( FILTER(tbl,VALUE([order_id])=10),  [amount] )
VAR r11  = SUMX( FILTER(tbl,VALUE([order_id])=11),  [amount] )
VAR r12  = SUMX( FILTER(tbl,VALUE([order_id])=12),  [amount] )
VAR r13  = SUMX( FILTER(tbl,VALUE([order_id])=13),  [amount] )
VAR r14  = SUMX( FILTER(tbl,VALUE([order_id])=14),  [amount] )
VAR r15  = SUMX( FILTER(tbl,VALUE([order_id])=15),  [amount] )
VAR r16  = SUMX( FILTER(tbl,VALUE([order_id])=16),  [amount] )
VAR r17  = SUMX( FILTER(tbl,VALUE([order_id])=17),  [amount] )
VAR r18  = SUMX( FILTER(tbl,VALUE([order_id])=18),  [amount] )
VAR r19  = SUMX( FILTER(tbl,VALUE([order_id])=19),  [amount] )
VAR r20  = SUMX( FILTER(tbl,VALUE([order_id])=20),  [amount] )
VAR r21  = SUMX( FILTER(tbl,VALUE([order_id])=21),  [amount] )
VAR r22  = SUMX( FILTER(tbl,VALUE([order_id])=22),  [amount] )
VAR r23  = SUMX( FILTER(tbl,VALUE([order_id])=23),  [amount] )
VAR r24  = SUMX( FILTER(tbl,VALUE([order_id])=24),  [amount] )
VAR r25  = SUMX( FILTER(tbl,VALUE([order_id])=25),  [amount] )
VAR r26  = SUMX( FILTER(tbl,VALUE([order_id])=26),  [amount] )
VAR r27  = SUMX( FILTER(tbl,VALUE([order_id])=27),  [amount] )
VAR r28  = SUMX( FILTER(tbl,VALUE([order_id])=28),  [amount] )
VAR r29  = SUMX( FILTER(tbl,VALUE([order_id])=29),  [amount] )
VAR r32  = SUMX( FILTER(tbl,VALUE([order_id])=32),  [amount] )
VAR r33  = SUMX( FILTER(tbl,VALUE([order_id])=33),  [amount] )
VAR r34  = SUMX( FILTER(tbl,VALUE([order_id])=34),  [amount] )
VAR r35  = SUMX( FILTER(tbl,VALUE([order_id])=35),  [amount] )
VAR r36  = SUMX( FILTER(tbl,VALUE([order_id])=36),  [amount] )
VAR r37  = SUMX( FILTER(tbl,VALUE([order_id])=37),  [amount] )
VAR r39  = SUMX( FILTER(tbl,VALUE([order_id])=39),  [amount] )
VAR r40  = SUMX( FILTER(tbl,VALUE([order_id])=40),  [amount] )
VAR r42  = SUMX( FILTER(tbl,VALUE([order_id])=42),  [amount] )
VAR r43  = SUMX( FILTER(tbl,VALUE([order_id])=43),  [amount] )
VAR r45  = SUMX( FILTER(tbl,VALUE([order_id])=45),  [amount] )
VAR r46  = SUMX( FILTER(tbl,VALUE([order_id])=46),  [amount] )
VAR r47  = SUMX( FILTER(tbl,VALUE([order_id])=47),  [amount] )
VAR r48  = SUMX( FILTER(tbl,VALUE([order_id])=48),  [amount] )
VAR r49  = SUMX( FILTER(tbl,VALUE([order_id])=49),  [amount] )
VAR r50  = SUMX( FILTER(tbl,VALUE([order_id])=50),  [amount] )
VAR r51  = SUMX( FILTER(tbl,VALUE([order_id])=51),  [amount] )
VAR r52  = SUMX( FILTER(tbl,VALUE([order_id])=52),  [amount] )
VAR r54  = SUMX( FILTER(tbl,VALUE([order_id])=54),  [amount] )
VAR r55  = SUMX( FILTER(tbl,VALUE([order_id])=55),  [amount] )
VAR r56  = SUMX( FILTER(tbl,VALUE([order_id])=56),  [amount] )
VAR r57  = SUMX( FILTER(tbl,VALUE([order_id])=57),  [amount] )
VAR r58  = SUMX( FILTER(tbl,VALUE([order_id])=58),  [amount] )
VAR r59  = SUMX( FILTER(tbl,VALUE([order_id])=59),  [amount] )
VAR r60  = SUMX( FILTER(tbl,VALUE([order_id])=60),  [amount] )
VAR r61  = SUMX( FILTER(tbl,VALUE([order_id])=61),  [amount] )
VAR r62  = SUMX( FILTER(tbl,VALUE([order_id])=62),  [amount] )
VAR r64  = SUMX( FILTER(tbl,VALUE([order_id])=64),  [amount] )
VAR r65  = SUMX( FILTER(tbl,VALUE([order_id])=65),  [amount] )
VAR r66  = SUMX( FILTER(tbl,VALUE([order_id])=66),  [amount] )
VAR r67  = SUMX( FILTER(tbl,VALUE([order_id])=67),  [amount] )
VAR r68  = SUMX( FILTER(tbl,VALUE([order_id])=68),  [amount] )
VAR r69  = SUMX( FILTER(tbl,VALUE([order_id])=69),  [amount] )
VAR r70  = SUMX( FILTER(tbl,VALUE([order_id])=70),  [amount] )
VAR r71  = SUMX( FILTER(tbl,VALUE([order_id])=71),  [amount] )
VAR r72  = SUMX( FILTER(tbl,VALUE([order_id])=72),  [amount] )
VAR r73  = SUMX( FILTER(tbl,VALUE([order_id])=73),  [amount] )
VAR r74  = SUMX( FILTER(tbl,VALUE([order_id])=74),  [amount] )
VAR r75  = SUMX( FILTER(tbl,VALUE([order_id])=75),  [amount] )
VAR r76  = SUMX( FILTER(tbl,VALUE([order_id])=76),  [amount] )
VAR r77  = SUMX( FILTER(tbl,VALUE([order_id])=77),  [amount] )
VAR r78  = SUMX( FILTER(tbl,VALUE([order_id])=78),  [amount] )
VAR r79  = SUMX( FILTER(tbl,VALUE([order_id])=79),  [amount] )
VAR r80  = SUMX( FILTER(tbl,VALUE([order_id])=80),  [amount] )
VAR r81  = SUMX( FILTER(tbl,VALUE([order_id])=81),  [amount] )
VAR r82  = SUMX( FILTER(tbl,VALUE([order_id])=82),  [amount] )
VAR r83  = SUMX( FILTER(tbl,VALUE([order_id])=83),  [amount] )
VAR r84  = SUMX( FILTER(tbl,VALUE([order_id])=84),  [amount] )
VAR r85  = SUMX( FILTER(tbl,VALUE([order_id])=85),  [amount] )
VAR r87  = SUMX( FILTER(tbl,VALUE([order_id])=87),  [amount] )
VAR r88  = SUMX( FILTER(tbl,VALUE([order_id])=88),  [amount] )
VAR r89  = SUMX( FILTER(tbl,VALUE([order_id])=89),  [amount] )
VAR r90  = SUMX( FILTER(tbl,VALUE([order_id])=90),  [amount] )
VAR r91  = SUMX( FILTER(tbl,VALUE([order_id])=91),  [amount] )
VAR r92  = SUMX( FILTER(tbl,VALUE([order_id])=92),  [amount] )
VAR r93  = SUMX( FILTER(tbl,VALUE([order_id])=93),  [amount] )
VAR r94  = SUMX( FILTER(tbl,VALUE([order_id])=94),  [amount] )
VAR r95  = SUMX( FILTER(tbl,VALUE([order_id])=95),  [amount] )
VAR r96  = SUMX( FILTER(tbl,VALUE([order_id])=96),  [amount] )
VAR r97  = SUMX( FILTER(tbl,VALUE([order_id])=97),  [amount] )
VAR r98  = SUMX( FILTER(tbl,VALUE([order_id])=98),  [amount] )
VAR r99  = SUMX( FILTER(tbl,VALUE([order_id])=99),  [amount] )
VAR r100 = SUMX( FILTER(tbl,VALUE([order_id])=100), [amount] )
VAR r101 = SUMX( FILTER(tbl,VALUE([order_id])=101), [amount] )
VAR r102 = SUMX( FILTER(tbl,VALUE([order_id])=102), [amount] )
VAR r103 = SUMX( FILTER(tbl,VALUE([order_id])=103), [amount] )
VAR r104 = SUMX( FILTER(tbl,VALUE([order_id])=104), [amount] )
VAR r105 = SUMX( FILTER(tbl,VALUE([order_id])=105), [amount] )
VAR r106 = SUMX( FILTER(tbl,VALUE([order_id])=106), [amount] )
VAR r107 = SUMX( FILTER(tbl,VALUE([order_id])=107), [amount] )
VAR r108 = SUMX( FILTER(tbl,VALUE([order_id])=108), [amount] )
VAR r109 = SUMX( FILTER(tbl,VALUE([order_id])=109), [amount] )
VAR r111 = SUMX( FILTER(tbl,VALUE([order_id])=111), [amount] )
VAR r112 = SUMX( FILTER(tbl,VALUE([order_id])=112), [amount] )
VAR r113 = SUMX( FILTER(tbl,VALUE([order_id])=113), [amount] )
VAR r114 = SUMX( FILTER(tbl,VALUE([order_id])=114), [amount] )
VAR r118 = SUMX( FILTER(tbl,VALUE([order_id])=118), [amount] )
VAR r125 = SUMX( FILTER(tbl,VALUE([order_id])=125), [amount] )
VAR r130 = SUMX( FILTER(tbl,VALUE([order_id])=130), [amount] )
VAR r133 = SUMX( FILTER(tbl,VALUE([order_id])=133), [amount] )
VAR r135 = SUMX( FILTER(tbl,VALUE([order_id])=135), [amount] )
VAR r136 = SUMX( FILTER(tbl,VALUE([order_id])=136), [amount] )
VAR r138 = SUMX( FILTER(tbl,VALUE([order_id])=138), [amount] )
VAR r139 = SUMX( FILTER(tbl,VALUE([order_id])=139), [amount] )
VAR r140 = SUMX( FILTER(tbl,VALUE([order_id])=140), [amount] )
VAR r141 = SUMX( FILTER(tbl,VALUE([order_id])=141), [amount] )
VAR r142 = SUMX( FILTER(tbl,VALUE([order_id])=142), [amount] )
VAR f = "#,##0.00"
VAR z = "<span style='color:#d1d5db'>-</span>"
VAR StyleBlock =
    "<style>" &
    ".sie{font-family:Segoe UI,Calibri,sans-serif;font-size:11px;color:#1e2d40;}" &
    ".sie-t{width:100%;border-collapse:collapse;}" &
    ".sie-t td{padding:3px 12px;border-bottom:1px solid #e8edf3;vertical-align:middle;}" &
    ".sie-t tr:hover td{background:#f5f8ff;}" &
    ".h-row td{background:#003366!important;color:#fff!important;font-weight:700;font-size:12px;text-transform:uppercase;border-bottom:3px solid #f0a500!important;padding:7px 12px!important;}" &
    ".sub1 td{background:#e8f0fb!important;font-weight:700;color:#003366;border-bottom:1px solid #b8cce4!important;}" &
    ".sub2 td{background:#f0f6ff!important;font-weight:600;color:#1a4a7a;}" &
    ".tot td{background:#f0a500!important;font-weight:800;font-size:12px;color:#003366!important;border-top:2px solid #003366!important;}" &
    ".net td{background:#003366!important;font-weight:800;font-size:13px;color:#fff!important;border-bottom:3px solid #f0a500!important;}" &
    ".tax td{background:#1a4a7a!important;font-weight:700;color:#fff!important;}" &
    ".cd{color:#9ca3af;font-size:9px;width:110px;}" &
    ".cd-w{color:#f0a500!important;font-size:9px;width:110px;}" &
    ".ar{text-align:right!important;font-family:Consolas,monospace;font-size:10px;white-space:nowrap;width:130px;}" &
    ".i1{padding-left:20px!important;}" &
    ".i2{padding-left:32px!important;}" &
    ".i3{padding-left:44px!important;color:#6b7280;}" &
    ".i4{padding-left:56px!important;color:#9ca3af;}" &
    "</style>"
VAR ModernHeader =
    "<div style='background:#003366;padding:16px 25px 12px;border-bottom:4px solid #f0a500;display:flex;align-items:center;gap:16px;'>" &
    "<img src='https://i.ibb.co/rWhBLgw/image-2026-04-21-094244962.png' style='height:90px;width:auto;flex-shrink:0;' />" &
    "<div>" &
    "<div style='color:#fff;font-family:Segoe UI,sans-serif;font-size:18px;font-weight:700;text-transform:uppercase;letter-spacing:1px;margin-bottom:4px;'>BANCO NACIONAL DE COMERCIO DE TIMOR LESTE</div>" &
    "<div style='color:#f0a500;font-family:Segoe UI,sans-serif;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:2px;margin-bottom:6px;'>CONSOLIDATED STATEMENT OF INCOME &amp; EXPENSE (PO SIE)</div>" &
    "<div style='color:#cbd5e1;font-family:Segoe UI,sans-serif;font-size:12px;'>" & PeriodLabel & "</div>" &
    "</div>" &
    "</div>"
VAR TableHTML =
    "<table class='sie-t'><thead><tr style='background:#f8fafc;'><td style='font-size:10px;font-weight:700;color:#003366;padding:6px 12px;border-bottom:2px solid #003366;width:110px;'>CODE</td><td style='font-size:10px;font-weight:700;color:#003366;padding:6px 12px;border-bottom:2px solid #003366;'>DESCRIPTION</td><td style='text-align:right;font-size:10px;font-weight:700;color:#003366;padding:6px 12px;border-bottom:2px solid #003366;width:130px;'>AMOUNT (USD)</td></tr></thead><tbody>" &
    "<tr class='h-row'><td class='cd-w'>4.0</td><td>I N C O M E</td><td class='ar'></td></tr>" &
    "<tr class='sub1'><td class='cd'>4.01</td><td class='i1'>INTEREST INCOME</td><td class='ar'>" & IF(r8=0,z,FORMAT(r8,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.1</td><td class='i2'>Interest on Due from Banks</td><td class='ar'>" & IF(r9=0,z,FORMAT(r9,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.2</td><td class='i2'>Interest on Overnight Placement</td><td class='ar'>" & IF(r10=0,z,FORMAT(r10,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.3</td><td class='i2'>Interest on Securities</td><td class='ar'>" & IF(r11=0,z,FORMAT(r11,f)) & "</td></tr>" &
    "<tr class='sub2'><td class='cd'>4.01.4</td><td class='i2'>Interest &amp; Fees on Loans &amp; Discounts</td><td class='ar'>" & IF(r12=0,z,FORMAT(r12,f)) & "</td></tr>" &
    "<tr class='sub2'><td class='cd'>4.01.4.1</td><td class='i3'>Interest Income on Loans</td><td class='ar'>" & IF(r13=0,z,FORMAT(r13,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.1.3.10</td><td class='i4'>Market Vendor Daily Loans</td><td class='ar'>" & IF(r14=0,z,FORMAT(r14,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.1.3.20</td><td class='i4'>Seasonal Crop Loans</td><td class='ar'>" & IF(r15=0,z,FORMAT(r15,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.1.3.30</td><td class='i4'>Other Business Loan</td><td class='ar'>" & IF(r16=0,z,FORMAT(r16,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.1.4.10</td><td class='i4'>Microfinance Group Loans</td><td class='ar'>" & IF(r17=0,z,FORMAT(r17,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.1.4.20</td><td class='i4'>Payroll Loans</td><td class='ar'>" & IF(r18=0,z,FORMAT(r18,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.1.4.30</td><td class='i4'>Employee and Staff Loans</td><td class='ar'>" & IF(r19=0,z,FORMAT(r19,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.1.4.60</td><td class='i4'>Asuwa'in Loan</td><td class='ar'>" & IF(r20=0,z,FORMAT(r20,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.1.4.70</td><td class='i4'>Bukae Loan</td><td class='ar'>" & IF(r21=0,z,FORMAT(r21,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.1.4.80</td><td class='i4'>Pension Loan</td><td class='ar'>" & IF(r22=0,z,FORMAT(r22,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.1.4.40</td><td class='i4'>Project Loan</td><td class='ar'>" & IF(r23=0,z,FORMAT(r23,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.1.4.50</td><td class='i4'>Investment Loan</td><td class='ar'>" & IF(r24=0,z,FORMAT(r24,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.1.4.85</td><td class='i4'>Transport Loan</td><td class='ar'>" & IF(r25=0,z,FORMAT(r25,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.1.4.90</td><td class='i4'>FIAR Loan</td><td class='ar'>" & IF(r26=0,z,FORMAT(r26,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.1.5.10</td><td class='i4'>Agricultor Loan</td><td class='ar'>" & IF(r27=0,z,FORMAT(r27,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.1.5.11</td><td class='i4'>RBL Loan Origination</td><td class='ar'>" & IF(r28=0,z,FORMAT(r28,f)) & "</td></tr>" &
    "<tr class='sub2'><td class='cd'>4.01.4.3</td><td class='i3'>Loan Fee Income</td><td class='ar'>" & IF(r29=0,z,FORMAT(r29,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.3.4</td><td class='i4'>Loan Fee - Seasonal Crop</td><td class='ar'>" & IF(r32=0,z,FORMAT(r32,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.3.5</td><td class='i4'>Loan Fee - Business Loan</td><td class='ar'>" & IF(r33=0,z,FORMAT(r33,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.3.6</td><td class='i4'>Loan Fee - Payroll</td><td class='ar'>" & IF(r34=0,z,FORMAT(r34,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.3.8</td><td class='i4'>Loan Fee - Employee &amp; Staff</td><td class='ar'>" & IF(r35=0,z,FORMAT(r35,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.3.7</td><td class='i4'>Loan Fee - Asuwa'in</td><td class='ar'>" & IF(r36=0,z,FORMAT(r36,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.3.9</td><td class='i4'>Loan Fee - Bukae</td><td class='ar'>" & IF(r37=0,z,FORMAT(r37,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.4.4-0</td><td class='i4'>Loan Fee - Project Loan</td><td class='ar'>" & IF(r39=0,z,FORMAT(r39,f)) & "</td></tr>" &
    "<tr><td class='cd'>4-01-4-4-1</td><td class='i4'>Loan Fee - Investment Loans</td><td class='ar'>" & IF(r40=0,z,FORMAT(r40,f)) & "</td></tr>" &
    "<tr><td class='cd'>4-01-4-4-6</td><td class='i4'>Loan Fee - FIAR</td><td class='ar'>" & IF(r42=0,z,FORMAT(r42,f)) & "</td></tr>" &
    "<tr><td class='cd'>4-01-4-4-7</td><td class='i4'>Loan Fee - Agricultor</td><td class='ar'>" & IF(r43=0,z,FORMAT(r43,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.01.5</td><td class='i2'>Other Interest Income</td><td class='ar'>" & IF(r45=0,z,FORMAT(r45,f)) & "</td></tr>" &
    "<tr class='sub1'><td class='cd'>4.02</td><td class='i1'>NON INTEREST INCOME</td><td class='ar'>" & IF(r46=0,z,FORMAT(r46,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.02.5</td><td class='i2'>Commission Income &amp; Transaction Fees</td><td class='ar'>" & IF(r47=0,z,FORMAT(r47,f)) & "</td></tr>" &
    "<tr class='sub2'><td class='cd'>4.02.6</td><td class='i2'>Other Non Interest Income</td><td class='ar'>" & IF(r48=0,z,FORMAT(r48,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.02.0</td><td class='i3'>ATM Fee</td><td class='ar'>" & IF(r49=0,z,FORMAT(r49,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.02.2</td><td class='i3'>MoneyGram Fees</td><td class='ar'>" & IF(r50=0,z,FORMAT(r50,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.02.1</td><td class='i3'>Foreign Transfer Fees</td><td class='ar'>" & IF(r51=0,z,FORMAT(r51,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.02.4</td><td class='i3'>Foreign Exchange Gains</td><td class='ar'>" & IF(r52=0,z,FORMAT(r52,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.02.3</td><td class='i3'>Collection Loan WO</td><td class='ar'>" & IF(r54=0,z,FORMAT(r54,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.02.7</td><td class='i3'>Fee From Government</td><td class='ar'>" & IF(r55=0,z,FORMAT(r55,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.02.8</td><td class='i3'>Fee From Bank Guarantee &amp; SI</td><td class='ar'>" & IF(r56=0,z,FORMAT(r56,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.02.9</td><td class='i3'>Initial Fee, Urgent Fee &amp; OTS Fee</td><td class='ar'>" & IF(r57=0,z,FORMAT(r57,f)) & "</td></tr>" &
    "<tr class='sub1'><td class='cd'>4.03</td><td class='i1'>EXTRAORDINARY INCOME</td><td class='ar'>" & IF(r58=0,z,FORMAT(r58,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.03.1</td><td class='i2'>Gains with disposal of Fixed Asset</td><td class='ar'>" & IF(r59=0,z,FORMAT(r59,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.3.2</td><td class='i2'>Adjustment for Prior Periods</td><td class='ar'>" & IF(r60=0,z,FORMAT(r60,f)) & "</td></tr>" &
    "<tr><td class='cd'>4.03.3.3</td><td class='i2'>Miscellaneous Income / Loss</td><td class='ar'>" & IF(r61=0,z,FORMAT(r61,f)) & "</td></tr>" &
    "<tr class='tot'><td class='cd-w'></td><td>TOTAL OPERATING INCOME</td><td class='ar'>" & IF(r62=0,z,FORMAT(r62,f)) & "</td></tr>" &
    "<tr style='height:8px;background:#f1f5f9;'><td colspan='3'></td></tr>" &
    "<tr class='h-row'><td class='cd-w'>5.0</td><td>E X P E N S E</td><td class='ar'></td></tr>" &
    "<tr class='sub1'><td class='cd'>5.01</td><td class='i1'>INTEREST EXPENSE</td><td class='ar'>" & IF(r64=0,z,FORMAT(r64,f)) & "</td></tr>" &
    "<tr class='sub2'><td class='cd'>5.01.2</td><td class='i2'>Interest by Individual Deposits</td><td class='ar'>" & IF(r65=0,z,FORMAT(r65,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.01.2.1</td><td class='i3'>Saving Deposits</td><td class='ar'>" & IF(r66=0,z,FORMAT(r66,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.01.2.2</td><td class='i3'>Time Deposits</td><td class='ar'>" & IF(r67=0,z,FORMAT(r67,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.01.2.2</td><td class='i3'>Demand Deposits</td><td class='ar'>" & IF(r68=0,z,FORMAT(r68,f)) & "</td></tr>" &
    "<tr class='sub2'><td class='cd'>5.01.3</td><td class='i2'>Interest on Legal Entities Deposits</td><td class='ar'>" & IF(r69=0,z,FORMAT(r69,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.01.3.1</td><td class='i3'>Saving Deposits (Legal)</td><td class='ar'>" & IF(r70=0,z,FORMAT(r70,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.01.5</td><td class='i2'>Interest Expense on Other Borrowing</td><td class='ar'>" & IF(r71=0,z,FORMAT(r71,f)) & "</td></tr>" &
    "<tr class='sub1'><td class='cd'>5.02</td><td class='i1'>NON INTEREST EXPENSE</td><td class='ar'>" & IF(r72=0,z,FORMAT(r72,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.02.3</td><td class='i2'>Foreign Exchanges Losses</td><td class='ar'>" & IF(r73=0,z,FORMAT(r73,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.02.4</td><td class='i2'>Commission Expense &amp; Transaction Fees</td><td class='ar'>" & IF(r74=0,z,FORMAT(r74,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.02.5</td><td class='i2'>Other Non Interest Expense (License Fee)</td><td class='ar'>" & IF(r75=0,z,FORMAT(r75,f)) & "</td></tr>" &
    "<tr class='sub1'><td class='cd'>5.03</td><td class='i1'>OPERATING EXPENSE</td><td class='ar'>" & IF(r76=0,z,FORMAT(r76,f)) & "</td></tr>" &
    "<tr class='sub2'><td class='cd'>5.03.1</td><td class='i2'>Salaries and Employee Benefits</td><td class='ar'>" & IF(r77=0,z,FORMAT(r77,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.1.1</td><td class='i3'>Remunerations of Board of Director</td><td class='ar'>" & IF(r78=0,z,FORMAT(r78,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.1.2</td><td class='i3'>Directors Fees and Honoraria</td><td class='ar'>" & IF(r79=0,z,FORMAT(r79,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.1.1</td><td class='i3'>Salaries and Wages</td><td class='ar'>" & IF(r80=0,z,FORMAT(r80,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.1.3</td><td class='i3'>Fringe Benefits - Employee</td><td class='ar'>" & IF(r81=0,z,FORMAT(r81,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.1.5</td><td class='i3'>Contribution to Retirement Fund</td><td class='ar'>" & IF(r82=0,z,FORMAT(r82,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.1.6</td><td class='i3'>Annual Leave</td><td class='ar'>" & IF(r83=0,z,FORMAT(r83,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.1.7</td><td class='i3'>Payment for Overtime</td><td class='ar'>" & IF(r84=0,z,FORMAT(r84,f)) & "</td></tr>" &
    "<tr class='sub2'><td class='cd'>5.03.2</td><td class='i2'>Administrative Expenses</td><td class='ar'>" & IF(r85=0,z,FORMAT(r85,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.2.4.1.10</td><td class='i3'>Information Tech./Automation</td><td class='ar'>" & IF(r87=0,z,FORMAT(r87,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.2.4.1.15</td><td class='i3'>Communication Expense</td><td class='ar'>" & IF(r88=0,z,FORMAT(r88,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.2.4.1.20</td><td class='i3'>Power, Light and Water</td><td class='ar'>" & IF(r89=0,z,FORMAT(r89,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.2.4.1.25</td><td class='i3'>Fuel and Lubricants</td><td class='ar'>" & IF(r90=0,z,FORMAT(r90,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.2.4.1.30</td><td class='i3'>Traveling Expenses</td><td class='ar'>" & IF(r91=0,z,FORMAT(r91,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.2.4.1.35</td><td class='i3'>Stationery and Office Supplies</td><td class='ar'>" & IF(r92=0,z,FORMAT(r92,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.2.4.1.40</td><td class='i3'>Representation and Entertainment</td><td class='ar'>" & IF(r93=0,z,FORMAT(r93,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.2.4.1.45</td><td class='i3'>Repairs and Maintenance</td><td class='ar'>" & IF(r94=0,z,FORMAT(r94,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.3</td><td class='i2'>Advertising and Public Relation</td><td class='ar'>" & IF(r95=0,z,FORMAT(r95,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.4</td><td class='i2'>Audit, Legal &amp; Professional Fees</td><td class='ar'>" & IF(r96=0,z,FORMAT(r96,f)) & "</td></tr>" &
    "<tr class='sub2'><td class='cd'>5.03.5</td><td class='i2'>Rents Paid</td><td class='ar'>" & IF(r97=0,z,FORMAT(r97,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.5.1</td><td class='i3'>Rent Paid</td><td class='ar'>" & IF(r98=0,z,FORMAT(r98,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.5.1</td><td class='i3'>Car Rents</td><td class='ar'>" & IF(r99=0,z,FORMAT(r99,f)) & "</td></tr>" &
    "<tr class='sub2'><td class='cd'>5.03.6</td><td class='i2'>Expense on Premises and Fixed Assets</td><td class='ar'>" & IF(r100=0,z,FORMAT(r100,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.6.1</td><td class='i3'>Insurance</td><td class='ar'>" & IF(r101=0,z,FORMAT(r101,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.6.3</td><td class='i3'>Building Maintenance</td><td class='ar'>" & IF(r102=0,z,FORMAT(r102,f)) & "</td></tr>" &
    "<tr class='sub2'><td class='cd'>5.03.7</td><td class='i2'>Depreciation and Amortization</td><td class='ar'>" & IF(r103=0,z,FORMAT(r103,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.7.3</td><td class='i3'>Depr. Machinery &amp; Equipment</td><td class='ar'>" & IF(r104=0,z,FORMAT(r104,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.7.4</td><td class='i3'>Depr. Furniture &amp; Fixture</td><td class='ar'>" & IF(r105=0,z,FORMAT(r105,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.7.5</td><td class='i3'>Depr. Vehicles</td><td class='ar'>" & IF(r106=0,z,FORMAT(r106,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.7.6</td><td class='i3'>Depr. Non Physical Assets</td><td class='ar'>" & IF(r107=0,z,FORMAT(r107,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.7.7</td><td class='i3'>Amort. Leasehold Right &amp; Improvement</td><td class='ar'>" & IF(r108=0,z,FORMAT(r108,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.7.8</td><td class='i3'>Amort. Building</td><td class='ar'>" & IF(r109=0,z,FORMAT(r109,f)) & "</td></tr>" &
    "<tr class='sub2'><td class='cd'>5.03.8</td><td class='i2'>Provision</td><td class='ar'>" & IF(r111=0,z,FORMAT(r111,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.8.1</td><td class='i3'>Provision for Loans Losses</td><td class='ar'>" & IF(r112=0,z,FORMAT(r112,f)) & "</td></tr>" &
    "<tr class='sub2'><td class='cd'>5.03.9</td><td class='i2'>Other Operating Expense</td><td class='ar'>" & IF(r113=0,z,FORMAT(r113,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.9.1.1.05</td><td class='i3'>Security, Janitorial &amp; Messengerial</td><td class='ar'>" & IF(r114=0,z,FORMAT(r114,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.9.1.1.66</td><td class='i3'>Health Expenses</td><td class='ar'>" & IF(r118=0,z,FORMAT(r118,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.9.1.1.75</td><td class='i3'>Training Expenses</td><td class='ar'>" & IF(r125=0,z,FORMAT(r125,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.9.1.1.82</td><td class='i3'>Miscellaneous - Contingency</td><td class='ar'>" & IF(r130=0,z,FORMAT(r130,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.03.9.1.1.78</td><td class='i3'>Miscellaneous - Others</td><td class='ar'>" & IF(r133=0,z,FORMAT(r133,f)) & "</td></tr>" &
    "<tr class='sub1'><td class='cd'>5.04</td><td class='i1'>EXTRAORDINARY EXPENSE</td><td class='ar'>" & IF(r135=0,z,FORMAT(r135,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.04.1</td><td class='i2'>Losses with disposal of Fixed Assets</td><td class='ar'>" & IF(r136=0,z,FORMAT(r136,f)) & "</td></tr>" &
    "<tr><td class='cd'>5.04.3</td><td class='i2'>Other Extraordinary Expenses</td><td class='ar'>" & IF(r138=0,z,FORMAT(r138,f)) & "</td></tr>" &
    "<tr class='tot'><td class='cd-w'></td><td>TOTAL OPERATING EXPENSES</td><td class='ar'>" & IF(r139=0,z,FORMAT(r139,f)) & "</td></tr>" &
    "<tr style='height:8px;background:#f1f5f9;'><td colspan='3'></td></tr>" &
    "<tr class='net'><td class='cd-w'></td><td>NET INCOME (LOSS) BEFORE TAX</td><td class='ar' style='color:" & IF(r140>=0,"#f0a500","#ff6b6b") & "!important;'>" & IF(r140=0,z,FORMAT(r140,f)) & "</td></tr>" &
    "<tr class='tax'><td class='cd-w'>5.09</td><td class='i1'>PROVISION FOR INCOME TAX</td><td class='ar'>" & IF(r141=0,z,FORMAT(r141,f)) & "</td></tr>" &
    "<tr class='net'><td class='cd-w'></td><td>NET INCOME (LOSS) AFTER TAX</td><td class='ar' style='color:" & IF(r142>=0,"#f0a500","#ff6b6b") & "!important;'>" & IF(r142=0,z,FORMAT(r142,f)) & "</td></tr>" &
    "</tbody></table>"
VAR FooterHTML =
    "<div style='background:#f8fafc;border-top:1px solid #e2e8f0;padding:7px 15px;display:flex;justify-content:space-between;'>" &
    "<span style='font-family:Segoe UI;font-size:10px;color:#9ca3af;'>All amounts in USD</span>" &
    "<span style='font-family:Segoe UI;font-size:10px;color:#9ca3af;'>BNCTL &mdash; Confidential</span>" &
    "</div>"
RETURN
    "<div class='sie'>" & StyleBlock & ModernHeader &
    "<div style='overflow-x:auto;'>" & TableHTML & "</div>" &
    FooterHTML & "</div>"
