MEASURE 'final_soc_liabilities_report'[SOC_Liabilities_HTML] =
VAR SelectedYear  = SELECTEDVALUE( Calendar[Year] )
VAR SelectedMonth = SELECTEDVALUE( Calendar[report_month] )
VAR MaxMonth      = MAX( soc_liabilities_real_v2[report_month] )
VAR MaxYear       = LEFT( MaxMonth, 4 )
VAR ActiveYear    = IF( ISBLANK(SelectedYear), MaxYear, SelectedYear )
VAR ActiveMonth   = IF( ISBLANK(SelectedMonth), MaxMonth, SelectedMonth )
VAR PeriodLabel   =
    IF( NOT ISBLANK(SelectedMonth),
        "For the Month of " & FORMAT( DATE( LEFT(ActiveMonth,4), RIGHT(ActiveMonth,2), 1 ), "MMMM YYYY" ),
        "For the Year Ended " & ActiveYear )
VAR tbl = FILTER( ALL(soc_liabilities_real_v2),
    IF( NOT ISBLANK(SelectedMonth), [report_month]=ActiveMonth, LEFT([report_month],4)=ActiveYear ) )

VAR o1_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o1_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o1_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o1_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o1_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o1_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o1_CI = SUMX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o1_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o1_YI = SUMX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o1_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=1 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o2_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o2_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o2_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o2_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o2_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o2_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o2_CI = SUMX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o2_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o2_YI = SUMX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o2_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=2 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o3_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o3_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o3_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o3_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o3_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o3_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o3_CI = SUMX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o3_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o3_YI = SUMX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o3_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=3 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o4_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o4_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o4_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o4_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o4_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o4_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o4_CI = SUMX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o4_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o4_YI = SUMX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o4_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=4 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o5_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o5_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o5_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o5_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o5_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o5_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o5_CI = SUMX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o5_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o5_YI = SUMX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o5_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=5 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o6_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o6_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o6_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o6_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o6_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o6_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o6_CI = SUMX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o6_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o6_YI = SUMX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o6_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=6 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o7_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o7_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o7_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o7_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o7_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o7_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o7_CI = SUMX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o7_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o7_YI = SUMX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o7_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=7 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o8_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o8_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o8_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o8_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o8_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o8_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o8_CI = SUMX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o8_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o8_YI = SUMX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o8_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=8 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o9_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o9_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o9_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o9_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o9_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o9_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o9_CI = SUMX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o9_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o9_YI = SUMX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o9_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=9 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o10_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o10_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o10_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o10_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o10_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o10_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o10_CI = SUMX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o10_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o10_YI = SUMX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o10_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=10 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o11_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o11_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o11_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o11_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o11_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o11_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o11_CI = SUMX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o11_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o11_YI = SUMX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o11_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=11 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o12_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o12_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o12_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o12_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o12_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o12_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o12_CI = SUMX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o12_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o12_YI = SUMX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o12_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=12 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o13_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o13_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o13_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o13_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o13_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o13_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o13_CI = SUMX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o13_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o13_YI = SUMX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o13_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=13 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o14_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o14_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o14_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o14_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o14_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o14_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o14_CI = SUMX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o14_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o14_YI = SUMX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o14_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=14 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o15_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o15_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o15_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o15_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o15_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o15_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o15_CI = SUMX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o15_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o15_YI = SUMX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o15_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=15 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o16_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o16_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o16_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o16_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o16_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o16_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o16_CI = SUMX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o16_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o16_YI = SUMX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o16_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=16 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o17_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o17_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o17_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o17_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o17_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o17_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o17_CI = SUMX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o17_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o17_YI = SUMX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o17_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=17 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o18_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o18_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o18_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o18_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o18_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o18_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o18_CI = SUMX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o18_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o18_YI = SUMX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o18_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=18 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o19_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o19_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o19_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o19_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o19_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o19_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o19_CI = SUMX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o19_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o19_YI = SUMX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o19_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=19 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o20_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o20_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o20_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o20_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o20_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o20_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o20_CI = SUMX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o20_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o20_YI = SUMX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o20_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=20 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o21_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o21_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o21_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o21_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o21_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o21_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o21_CI = SUMX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o21_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o21_YI = SUMX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o21_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=21 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o22_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o22_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o22_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o22_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o22_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o22_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o22_CI = SUMX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o22_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o22_YI = SUMX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o22_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=22 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o23_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o23_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o23_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o23_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o23_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o23_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o23_CI = SUMX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o23_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o23_YI = SUMX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o23_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=23 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o24_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o24_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o24_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o24_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o24_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o24_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o24_CI = SUMX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o24_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o24_YI = SUMX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o24_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=24 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o25_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o25_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o25_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o25_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o25_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o25_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o25_CI = SUMX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o25_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o25_YI = SUMX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o25_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=25 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o26_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o26_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o26_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o26_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o26_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o26_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o26_CI = SUMX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o26_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o26_YI = SUMX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o26_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=26 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o27_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o27_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o27_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o27_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o27_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o27_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o27_CI = SUMX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o27_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o27_YI = SUMX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o27_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=27 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o28_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o28_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o28_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o28_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o28_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o28_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o28_CI = SUMX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o28_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o28_YI = SUMX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o28_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=28 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o29_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o29_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o29_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o29_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o29_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o29_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o29_CI = SUMX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o29_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o29_YI = SUMX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o29_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=29 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o30_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o30_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o30_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o30_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o30_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o30_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o30_CI = SUMX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o30_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o30_YI = SUMX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o30_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=30 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o31_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o31_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o31_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o31_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o31_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o31_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o31_CI = SUMX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o31_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o31_YI = SUMX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o31_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=31 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o32_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o32_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o32_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o32_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o32_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o32_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o32_CI = SUMX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o32_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o32_YI = SUMX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o32_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=32 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o33_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o33_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o33_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o33_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o33_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o33_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o33_CI = SUMX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o33_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o33_YI = SUMX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o33_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=33 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o34_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o34_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o34_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o34_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o34_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o34_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o34_CI = SUMX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o34_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o34_YI = SUMX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o34_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=34 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o35_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o35_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o35_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o35_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o35_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o35_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o35_CI = SUMX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o35_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o35_YI = SUMX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o35_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=35 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o36_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o36_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o36_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o36_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o36_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o36_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o36_CI = SUMX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o36_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o36_YI = SUMX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o36_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=36 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o37_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o37_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o37_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o37_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o37_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o37_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o37_CI = SUMX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o37_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o37_YI = SUMX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o37_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=37 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o38_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o38_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o38_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o38_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o38_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o38_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o38_CI = SUMX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o38_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o38_YI = SUMX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o38_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=38 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o39_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o39_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o39_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o39_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o39_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o39_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o39_CI = SUMX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o39_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o39_YI = SUMX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o39_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=39 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o40_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o40_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o40_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o40_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o40_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o40_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o40_CI = SUMX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o40_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o40_YI = SUMX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o40_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=40 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o41_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o41_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o41_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o41_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o41_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o41_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o41_CI = SUMX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o41_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o41_YI = SUMX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o41_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=41 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o42_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o42_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o42_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o42_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o42_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o42_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o42_CI = SUMX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o42_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o42_YI = SUMX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o42_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=42 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o43_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o43_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o43_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o43_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o43_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o43_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o43_CI = SUMX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o43_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o43_YI = SUMX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o43_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=43 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o44_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o44_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o44_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o44_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o44_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o44_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o44_CI = SUMX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o44_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o44_YI = SUMX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o44_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=44 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o45_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o45_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o45_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o45_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o45_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o45_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o45_CI = SUMX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o45_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o45_YI = SUMX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o45_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=45 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o46_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o46_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o46_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o46_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o46_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o46_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o46_CI = SUMX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o46_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o46_YI = SUMX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o46_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=46 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o47_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o47_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o47_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o47_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o47_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o47_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o47_CI = SUMX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o47_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o47_YI = SUMX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o47_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=47 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o48_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o48_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o48_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o48_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o48_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o48_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o48_CI = SUMX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o48_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o48_YI = SUMX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o48_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=48 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o49_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o49_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o49_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o49_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o49_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o49_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o49_CI = SUMX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o49_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o49_YI = SUMX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o49_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=49 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o50_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o50_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o50_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o50_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o50_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o50_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o50_CI = SUMX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o50_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o50_YI = SUMX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o50_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=50 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o51_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o51_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o51_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o51_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o51_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o51_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o51_CI = SUMX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o51_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o51_YI = SUMX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o51_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=51 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o52_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o52_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o52_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o52_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o52_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o52_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o52_CI = SUMX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o52_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o52_YI = SUMX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o52_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=52 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o53_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o53_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o53_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o53_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o53_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o53_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o53_CI = SUMX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o53_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o53_YI = SUMX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o53_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=53 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o54_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o54_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o54_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o54_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o54_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o54_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o54_CI = SUMX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o54_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o54_YI = SUMX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o54_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=54 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o55_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o55_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o55_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o55_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o55_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o55_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o55_CI = SUMX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o55_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o55_YI = SUMX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o55_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=55 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o56_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o56_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o56_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o56_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o56_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o56_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o56_CI = SUMX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o56_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o56_YI = SUMX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o56_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=56 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o57_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o57_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o57_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o57_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o57_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o57_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o57_CI = SUMX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o57_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o57_YI = SUMX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o57_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=57 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o58_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o58_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o58_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o58_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o58_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o58_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o58_CI = SUMX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o58_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o58_YI = SUMX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o58_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=58 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o59_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o59_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o59_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o59_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o59_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o59_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o59_CI = SUMX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o59_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o59_YI = SUMX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o59_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=59 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o60_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o60_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o60_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o60_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o60_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o60_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o60_CI = SUMX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o60_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o60_YI = SUMX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o60_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=60 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o61_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o61_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o61_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o61_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o61_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o61_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o61_CI = SUMX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o61_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o61_YI = SUMX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o61_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=61 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o62_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o62_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o62_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o62_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o62_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o62_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o62_CI = SUMX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o62_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o62_YI = SUMX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o62_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=62 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o63_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o63_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o63_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o63_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o63_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o63_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o63_CI = SUMX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o63_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o63_YI = SUMX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o63_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=63 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o64_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o64_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o64_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o64_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o64_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o64_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o64_CI = SUMX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o64_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o64_YI = SUMX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o64_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=64 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o65_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o65_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o65_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o65_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o65_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o65_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o65_CI = SUMX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o65_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o65_YI = SUMX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o65_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=65 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o66_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o66_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o66_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o66_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o66_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o66_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o66_CI = SUMX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o66_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o66_YI = SUMX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o66_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=66 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o67_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o67_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o67_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o67_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o67_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o67_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o67_CI = SUMX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o67_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o67_YI = SUMX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o67_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=67 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o68_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o68_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o68_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o68_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o68_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o68_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o68_CI = SUMX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o68_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o68_YI = SUMX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o68_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=68 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o69_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o69_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o69_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o69_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o69_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o69_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o69_CI = SUMX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o69_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o69_YI = SUMX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o69_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=69 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o70_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o70_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o70_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o70_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o70_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o70_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o70_CI = SUMX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o70_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o70_YI = SUMX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o70_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=70 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o71_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o71_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o71_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o71_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o71_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o71_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o71_CI = SUMX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o71_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o71_YI = SUMX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o71_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=71 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o72_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o72_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o72_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o72_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o72_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o72_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o72_CI = SUMX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o72_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o72_YI = SUMX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o72_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=72 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o73_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o73_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o73_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o73_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o73_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o73_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o73_CI = SUMX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o73_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o73_YI = SUMX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o73_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=73 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o74_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o74_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o74_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o74_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o74_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o74_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o74_CI = SUMX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o74_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o74_YI = SUMX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o74_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=74 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o75_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o75_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o75_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o75_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o75_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o75_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o75_CI = SUMX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o75_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o75_YI = SUMX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o75_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=75 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o76_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o76_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o76_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o76_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o76_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o76_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o76_CI = SUMX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o76_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o76_YI = SUMX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o76_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=76 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o77_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o77_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o77_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o77_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o77_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o77_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o77_CI = SUMX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o77_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o77_YI = SUMX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o77_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=77 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o78_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o78_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o78_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o78_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o78_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o78_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o78_CI = SUMX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o78_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o78_YI = SUMX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o78_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=78 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o79_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o79_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o79_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o79_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o79_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o79_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o79_CI = SUMX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o79_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o79_YI = SUMX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o79_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=79 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o80_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o80_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o80_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o80_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o80_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o80_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o80_CI = SUMX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o80_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o80_YI = SUMX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o80_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=80 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o81_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o81_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o81_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o81_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o81_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o81_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o81_CI = SUMX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o81_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o81_YI = SUMX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o81_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=81 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o82_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o82_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o82_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o82_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o82_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o82_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o82_CI = SUMX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o82_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o82_YI = SUMX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o82_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=82 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o83_CURR_ac = SUMX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="CURR"), IFERROR(VALUE([accts]),0) )
VAR o83_CURR_am = SUMX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="CURR"), IFERROR(VALUE([amount]),0) )
VAR o83_PREV_ac = SUMX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="PREV"), IFERROR(VALUE([accts]),0) )
VAR o83_PREV_am = SUMX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="PREV"), IFERROR(VALUE([amount]),0) )
VAR o83_YOY_ac = SUMX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="YOY"), IFERROR(VALUE([accts]),0) )
VAR o83_YOY_am = SUMX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="YOY"), IFERROR(VALUE([amount]),0) )
VAR o83_CI = SUMX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="CURR"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o83_CP = AVERAGEX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="CURR"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR o83_YI = SUMX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="YOY"), IFERROR(VALUE([increase_prev_period]),0) )
VAR o83_YP = AVERAGEX( FILTER(tbl, VALUE([order_id])=83 && [type_period]="YOY"), IFERROR(VALUE([pct_change_prev_period]),0) )
VAR Sty =
    "<style>" &
    ".soc{font-family:Segoe UI,Calibri,sans-serif;font-size:10.5px;color:#1e2d40;}" &
    ".soc-t{width:100%;border-collapse:collapse;}" &
    ".soc-t td{padding:3px 7px;border-bottom:1px solid #e8edf3;vertical-align:middle;white-space:nowrap;}" &
    ".soc-t tr:hover td{background:#f5f8ff;}" &
    ".h-row td{background:#003366!important;color:#fff!important;font-weight:700;font-size:11px;text-transform:uppercase;border-bottom:3px solid #f0a500!important;padding:6px 7px!important;}" &
    ".sub1 td{background:#e8f0fb!important;font-weight:700;color:#003366;border-bottom:1px solid #b8cce4!important;}" &
    ".sub2 td{background:#f0f6ff!important;font-weight:600;color:#1a4a7a;}" &
    ".tot td{background:#f0a500!important;font-weight:800;font-size:11px;color:#003366!important;border-top:2px solid #003366!important;}" &
    ".cd{color:#9ca3af;font-size:9px;min-width:80px;}" &
    ".cd-w{color:#f0a500!important;font-size:9px;min-width:80px;}" &
    ".ar{text-align:right!important;font-family:Consolas,monospace;font-size:9.5px;min-width:90px;}" &
    ".ac{text-align:center!important;font-family:Consolas,monospace;font-size:9.5px;min-width:50px;}" &
    ".pct{text-align:center!important;font-size:9.5px;min-width:60px;}" &
    ".bl{border-left:2px solid #dde4ef!important;}" &
    ".i0{padding-left:8px!important;}" &
    ".i1{padding-left:18px!important;}" &
    ".i2{padding-left:28px!important;}" &
    ".i3{padding-left:38px!important;color:#6b7280;}" &
    ".i4{padding-left:48px!important;color:#9ca3af;}" &
    "</style>"
VAR Hdr =
    "<div style='background:#003366;padding:16px 20px;border-bottom:4px solid #f0a500;display:flex;align-items:center;gap:20px;'>" &
    "<img src='https://i.ibb.co/rWhBLgw/image-2026-04-21-094244962.png' alt='BNCTL Logo' style='height:90px;width:auto;flex-shrink:0;' />" &
    "<div style='flex:1;'>" &
    "<div style='color:#fff;font-family:Segoe UI,sans-serif;font-size:17px;font-weight:700;text-transform:uppercase;letter-spacing:1px;margin-bottom:4px;'>BANCO NACIONAL DE COMERCIO DE TIMOR LESTE</div>" &
    "<div style='color:#f0a500;font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:1.5px;margin-bottom:3px;'>CONSOLIDATED STATEMENT OF ASSETS AND LIABILITIES (SOC)</div>" &
    "<div style='color:#f0a500;font-size:11px;font-weight:700;letter-spacing:1px;margin-bottom:3px;'>LIABILITIES &amp; CAPITAL</div>" &
    "<div style='color:#cbd5e1;font-size:11px;'>" & PeriodLabel & "</div>" &
    "</div>" &
    "</div>"
VAR ColHdr =
    "<table class='soc-t'><thead>" &
    "<tr style='background:#1a4a7a;'>" &
    "<td class='cd-w' rowspan='2' style='padding:5px 7px;'>CODE</td>" &
    "<td style='color:#fff;font-weight:700;font-size:10px;padding:5px 7px;' rowspan='2'>ACCOUNT TITLES</td>" &
    "<td style='color:#fff;font-weight:700;font-size:10px;padding:5px 7px;text-align:center;border-left:2px solid #2563eb;' colspan='2'>CURRENT PERIOD</td>" &
    "<td style='color:#fff;font-weight:700;font-size:10px;padding:5px 7px;text-align:center;border-left:2px solid #2563eb;'>PREVIOUS PERIOD</td>" &
    "<td style='color:#f0a500;font-weight:700;font-size:10px;padding:5px 7px;text-align:center;border-left:2px solid #2563eb;' colspan='2'>vs PREVIOUS</td>" &
    "<td style='color:#fff;font-weight:700;font-size:10px;padding:5px 7px;text-align:center;border-left:2px solid #2563eb;'>PREV YEAR</td>" &
    "<td style='color:#f0a500;font-weight:700;font-size:10px;padding:5px 7px;text-align:center;border-left:2px solid #2563eb;' colspan='2'>YOY CHANGE</td>" &
    "</tr>" &
    "<tr style='background:#1a4a7a;border-bottom:2px solid #f0a500;'>" &
    "<td class='ac' style='color:#d1d5db;font-size:9px;padding:3px 7px;border-left:2px solid #2563eb;'>No.Acc</td>" &
    "<td class='ar' style='color:#d1d5db;font-size:9px;padding:3px 7px;'>Amount (USD)</td>" &
    "<td class='ar bl' style='color:#d1d5db;font-size:9px;padding:3px 7px;'>Amount (USD)</td>" &
    "<td class='ar bl' style='color:#d1d5db;font-size:9px;padding:3px 7px;'>Increase (+/-)</td>" &
    "<td class='pct' style='color:#d1d5db;font-size:9px;padding:3px 7px;'>%</td>" &
    "<td class='ar bl' style='color:#d1d5db;font-size:9px;padding:3px 7px;'>Amount (USD)</td>" &
    "<td class='ar bl' style='color:#d1d5db;font-size:9px;padding:3px 7px;'>Variance</td>" &
    "<td class='pct' style='color:#d1d5db;font-size:9px;padding:3px 7px;'>%</td>" &
    "</tr></thead><tbody>"
VAR Rows_1 =
    "<tr class='sub1'><td class='cd'>2.0</td><td class='i1'>LIABILITIES:</td>" & "<td class='ac bl'>" & IF(o1_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o1_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o1_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o1_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o1_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o1_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o1_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o1_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o1_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o1_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o1_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o1_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o1_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o1_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o1_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o1_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o1_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o1_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o1_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o1_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o1_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o1_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o1_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o1_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub1'><td class='cd'>2.04</td><td class='i1'>DEPOSITS</td>" & "<td class='ac bl'>" & IF(o2_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o2_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o2_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o2_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o2_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o2_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o2_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o2_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o2_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o2_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o2_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o2_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o2_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o2_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o2_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o2_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o2_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o2_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o2_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o2_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o2_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o2_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o2_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o2_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.04.1.1</td><td class='i3'>Demand Deposit</td>" & "<td class='ac bl'>" & IF(o3_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o3_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o3_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o3_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o3_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o3_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o3_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o3_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o3_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o3_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o3_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o3_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o3_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o3_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o3_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o3_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o3_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o3_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o3_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o3_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o3_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o3_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o3_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o3_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.4.1.1.1</td><td class='i4'>Financial Institutions</td>" & "<td class='ac bl'>" & IF(o4_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o4_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o4_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o4_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o4_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o4_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o4_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o4_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o4_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o4_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o4_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o4_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o4_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o4_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o4_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o4_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o4_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o4_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o4_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o4_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o4_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o4_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o4_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o4_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.4.1.1.2</td><td class='i4'>Government</td>" & "<td class='ac bl'>" & IF(o5_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o5_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o5_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o5_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o5_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o5_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o5_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o5_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o5_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o5_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o5_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o5_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o5_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o5_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o5_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o5_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o5_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o5_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o5_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o5_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o5_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o5_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o5_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o5_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.4.1.1.3</td><td class='i4'>Business Enterprises</td>" & "<td class='ac bl'>" & IF(o6_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o6_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o6_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o6_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o6_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o6_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o6_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o6_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o6_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o6_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o6_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o6_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o6_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o6_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o6_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o6_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o6_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o6_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o6_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o6_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o6_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o6_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o6_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o6_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.4.1.1.4</td><td class='i4'>Others</td>" & "<td class='ac bl'>" & IF(o7_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o7_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o7_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o7_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o7_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o7_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o7_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o7_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o7_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o7_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o7_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o7_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o7_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o7_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o7_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o7_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o7_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o7_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o7_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o7_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o7_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o7_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o7_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o7_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.4.1.2</td><td class='i3'>Time Deposits</td>" & "<td class='ac bl'>" & IF(o8_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o8_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o8_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o8_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o8_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o8_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o8_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o8_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o8_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o8_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o8_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o8_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o8_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o8_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o8_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o8_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o8_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o8_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o8_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o8_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o8_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o8_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o8_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o8_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.04.1.2.2</td><td class='i4'>Government</td>" & "<td class='ac bl'>" & IF(o9_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o9_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o9_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o9_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o9_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o9_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o9_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o9_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o9_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o9_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o9_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o9_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o9_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o9_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o9_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o9_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o9_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o9_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o9_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o9_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o9_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o9_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o9_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o9_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.04.1.2</td><td class='i3'>Business Enterprises</td>" & "<td class='ac bl'>" & IF(o10_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o10_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o10_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o10_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o10_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o10_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o10_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o10_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o10_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o10_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o10_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o10_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o10_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o10_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o10_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o10_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o10_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o10_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o10_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o10_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o10_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o10_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o10_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o10_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.4.1.2.4</td><td class='i4'>Others</td>" & "<td class='ac bl'>" & IF(o11_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o11_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o11_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o11_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o11_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o11_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o11_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o11_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o11_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o11_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o11_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o11_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o11_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o11_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o11_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o11_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o11_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o11_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o11_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o11_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o11_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o11_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o11_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o11_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.04.1.3</td><td class='i3'>Other (Passbook Saving)</td>" & "<td class='ac bl'>" & IF(o12_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o12_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o12_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o12_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o12_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o12_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o12_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o12_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o12_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o12_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o12_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o12_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o12_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o12_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o12_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o12_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o12_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o12_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o12_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o12_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o12_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o12_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o12_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o12_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>"
VAR Rows_2 =
    "<tr><td class='cd'>2.04.1.1</td><td class='i3'>Financial Institutions</td>" & "<td class='ac bl'>" & IF(o13_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o13_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o13_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o13_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o13_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o13_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o13_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o13_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o13_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o13_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o13_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o13_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o13_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o13_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o13_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o13_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o13_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o13_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o13_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o13_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o13_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o13_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o13_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o13_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.04.1.2</td><td class='i3'>Government</td>" & "<td class='ac bl'>" & IF(o14_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o14_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o14_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o14_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o14_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o14_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o14_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o14_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o14_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o14_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o14_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o14_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o14_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o14_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o14_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o14_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o14_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o14_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o14_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o14_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o14_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o14_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o14_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o14_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.04.1.3</td><td class='i3'>Business Enterprises</td>" & "<td class='ac bl'>" & IF(o15_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o15_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o15_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o15_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o15_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o15_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o15_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o15_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o15_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o15_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o15_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o15_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o15_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o15_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o15_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o15_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o15_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o15_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o15_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o15_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o15_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o15_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o15_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o15_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.04.1.4</td><td class='i3'>Others</td>" & "<td class='ac bl'>" & IF(o16_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o16_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o16_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o16_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o16_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o16_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o16_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o16_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o16_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o16_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o16_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o16_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o16_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o16_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o16_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o16_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o16_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o16_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o16_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o16_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o16_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o16_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o16_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o16_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.04.1.4.1</td><td class='i4'>Passbook Saving</td>" & "<td class='ac bl'>" & IF(o17_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o17_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o17_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o17_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o17_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o17_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o17_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o17_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o17_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o17_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o17_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o17_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o17_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o17_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o17_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o17_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o17_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o17_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o17_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o17_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o17_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o17_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o17_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o17_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.04.1.4.2</td><td class='i4'>Pledge Saving</td>" & "<td class='ac bl'>" & IF(o18_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o18_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o18_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o18_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o18_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o18_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o18_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o18_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o18_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o18_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o18_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o18_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o18_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o18_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o18_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o18_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o18_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o18_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o18_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o18_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o18_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o18_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o18_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o18_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.04.1.4.5</td><td class='i4'>Saving Enderly</td>" & "<td class='ac bl'>" & IF(o19_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o19_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o19_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o19_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o19_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o19_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o19_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o19_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o19_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o19_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o19_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o19_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o19_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o19_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o19_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o19_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o19_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o19_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o19_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o19_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o19_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o19_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o19_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o19_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.04.1.4.6</td><td class='i4'>Bolsa da Mae</td>" & "<td class='ac bl'>" & IF(o20_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o20_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o20_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o20_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o20_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o20_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o20_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o20_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o20_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o20_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o20_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o20_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o20_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o20_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o20_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o20_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o20_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o20_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o20_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o20_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o20_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o20_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o20_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o20_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.04.1.4.7</td><td class='i4'>Deposito Asuwain</td>" & "<td class='ac bl'>" & IF(o21_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o21_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o21_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o21_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o21_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o21_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o21_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o21_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o21_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o21_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o21_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o21_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o21_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o21_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o21_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o21_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o21_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o21_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o21_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o21_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o21_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o21_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o21_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o21_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.04.1.4.6</td><td class='i4'>Deposito Hau Nia Futuru</td>" & "<td class='ac bl'>" & IF(o22_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o22_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o22_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o22_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o22_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o22_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o22_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o22_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o22_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o22_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o22_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o22_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o22_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o22_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o22_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o22_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o22_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o22_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o22_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o22_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o22_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o22_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o22_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o22_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.04.1.4.</td><td class='i4'>Deposito Poupansa Emigrante</td>" & "<td class='ac bl'>" & IF(o23_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o23_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o23_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o23_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o23_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o23_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o23_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o23_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o23_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o23_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o23_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o23_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o23_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o23_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o23_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o23_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o23_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o23_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o23_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o23_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o23_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o23_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o23_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o23_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.04.1.4.8</td><td class='i4'>Depozitu Matenek</td>" & "<td class='ac bl'>" & IF(o24_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o24_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o24_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o24_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o24_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o24_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o24_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o24_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o24_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o24_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o24_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o24_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o24_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o24_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o24_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o24_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o24_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o24_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o24_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o24_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o24_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o24_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o24_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o24_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>"
VAR Rows_3 =
    "<tr><td class='cd'>2.04.1.4.9</td><td class='i4'>Depozitu Pensionista</td>" & "<td class='ac bl'>" & IF(o25_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o25_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o25_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o25_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o25_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o25_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o25_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o25_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o25_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o25_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o25_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o25_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o25_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o25_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o25_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o25_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o25_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o25_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o25_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o25_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o25_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o25_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o25_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o25_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.04.1.4.0</td><td class='i4'>BDM Jerasaun Foun</td>" & "<td class='ac bl'>" & IF(o26_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o26_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o26_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o26_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o26_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o26_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o26_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o26_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o26_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o26_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o26_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o26_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o26_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o26_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o26_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o26_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o26_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o26_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o26_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o26_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o26_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o26_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o26_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o26_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.04.1.5.0</td><td class='i4'>Depozitu Fiar</td>" & "<td class='ac bl'>" & IF(o27_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o27_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o27_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o27_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o27_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o27_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o27_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o27_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o27_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o27_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o27_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o27_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o27_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o27_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o27_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o27_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o27_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o27_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o27_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o27_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o27_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o27_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o27_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o27_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub1'><td class='cd'>2.06</td><td class='i1'>Other Sundry Current Liabilit.</td>" & "<td class='ac bl'>" & IF(o28_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o28_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o28_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o28_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o28_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o28_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o28_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o28_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o28_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o28_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o28_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o28_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o28_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o28_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o28_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o28_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o28_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o28_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o28_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o28_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o28_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o28_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o28_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o28_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>2.06.6</td><td class='i2'>Item In Suspens</td>" & "<td class='ac bl'>" & IF(o29_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o29_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o29_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o29_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o29_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o29_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o29_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o29_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o29_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o29_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o29_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o29_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o29_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o29_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o29_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o29_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o29_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o29_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o29_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o29_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o29_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o29_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o29_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o29_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>2.06.2</td><td class='i2'>ReserveFor Bonus &amp; Atribu BOD</td>" & "<td class='ac bl'>" & IF(o30_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o30_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o30_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o30_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o30_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o30_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o30_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o30_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o30_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o30_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o30_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o30_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o30_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o30_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o30_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o30_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o30_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o30_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o30_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o30_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o30_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o30_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o30_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o30_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>2.06.3</td><td class='i2'>Salary Payable</td>" & "<td class='ac bl'>" & IF(o31_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o31_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o31_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o31_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o31_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o31_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o31_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o31_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o31_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o31_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o31_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o31_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o31_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o31_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o31_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o31_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o31_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o31_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o31_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o31_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o31_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o31_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o31_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o31_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>2.06.4</td><td class='i2'>Loan Suspense Migration</td>" & "<td class='ac bl'>" & IF(o32_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o32_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o32_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o32_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o32_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o32_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o32_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o32_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o32_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o32_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o32_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o32_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o32_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o32_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o32_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o32_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o32_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o32_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o32_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o32_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o32_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o32_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o32_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o32_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>2.06.5</td><td class='i2'>Lease Liability IFRS</td>" & "<td class='ac bl'>" & IF(o33_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o33_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o33_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o33_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o33_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o33_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o33_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o33_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o33_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o33_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o33_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o33_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o33_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o33_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o33_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o33_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o33_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o33_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o33_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o33_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o33_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o33_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o33_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o33_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.3.1</td><td class='i3'>Income Tax</td>" & "<td class='ac bl'>" & IF(o34_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o34_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o34_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o34_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o34_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o34_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o34_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o34_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o34_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o34_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o34_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o34_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o34_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o34_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o34_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o34_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o34_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o34_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o34_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o34_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o34_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o34_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o34_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o34_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'></td><td class='i2'>Income Tax (5182)</td>" & "<td class='ac bl'>" & IF(o35_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o35_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o35_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o35_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o35_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o35_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o35_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o35_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o35_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o35_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o35_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o35_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o35_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o35_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o35_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o35_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o35_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o35_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o35_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o35_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o35_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o35_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o35_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o35_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.3.2</td><td class='i3'>Other Taxes</td>" & "<td class='ac bl'>" & IF(o36_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o36_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o36_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o36_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o36_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o36_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o36_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o36_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o36_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o36_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o36_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o36_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o36_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o36_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o36_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o36_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o36_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o36_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o36_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o36_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o36_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o36_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o36_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o36_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>"
VAR Rows_4 =
    "<tr><td class='cd'>2.06.4.2</td><td class='i3'>Collected Tax</td>" & "<td class='ac bl'>" & IF(o37_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o37_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o37_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o37_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o37_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o37_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o37_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o37_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o37_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o37_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o37_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o37_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o37_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o37_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o37_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o37_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o37_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o37_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o37_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o37_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o37_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o37_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o37_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o37_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>2.06.5</td><td class='i2'>Interest Accrued</td>" & "<td class='ac bl'>" & IF(o38_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o38_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o38_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o38_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o38_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o38_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o38_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o38_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o38_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o38_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o38_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o38_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o38_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o38_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o38_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o38_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o38_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o38_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o38_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o38_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o38_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o38_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o38_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o38_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.5.1.1</td><td class='i4'>Domestic Currency</td>" & "<td class='ac bl'>" & IF(o39_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o39_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o39_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o39_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o39_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o39_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o39_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o39_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o39_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o39_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o39_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o39_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o39_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o39_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o39_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o39_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o39_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o39_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o39_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o39_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o39_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o39_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o39_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o39_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.5.2</td><td class='i3'>Others Interest Accrued</td>" & "<td class='ac bl'>" & IF(o40_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o40_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o40_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o40_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o40_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o40_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o40_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o40_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o40_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o40_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o40_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o40_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o40_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o40_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o40_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o40_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o40_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o40_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o40_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o40_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o40_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o40_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o40_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o40_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>2.06.8</td><td class='i2'>RESTRICTED DEPOSIT</td>" & "<td class='ac bl'>" & IF(o41_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o41_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o41_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o41_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o41_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o41_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o41_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o41_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o41_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o41_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o41_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o41_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o41_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o41_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o41_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o41_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o41_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o41_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o41_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o41_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o41_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o41_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o41_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o41_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.8.1</td><td class='i3'>Resident</td>" & "<td class='ac bl'>" & IF(o42_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o42_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o42_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o42_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o42_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o42_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o42_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o42_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o42_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o42_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o42_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o42_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o42_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o42_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o42_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o42_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o42_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o42_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o42_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o42_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o42_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o42_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o42_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o42_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.8.2</td><td class='i3'>Non Resident L/C</td>" & "<td class='ac bl'>" & IF(o43_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o43_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o43_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o43_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o43_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o43_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o43_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o43_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o43_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o43_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o43_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o43_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o43_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o43_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o43_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o43_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o43_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o43_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o43_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o43_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o43_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o43_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o43_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o43_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>2.06.9</td><td class='i2'>Unearned Interest</td>" & "<td class='ac bl'>" & IF(o44_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o44_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o44_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o44_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o44_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o44_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o44_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o44_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o44_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o44_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o44_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o44_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o44_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o44_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o44_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o44_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o44_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o44_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o44_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o44_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o44_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o44_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o44_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o44_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.2.4</td><td class='i4'>Loan Fee Recheduling in Advance</td>" & "<td class='ac bl'>" & IF(o45_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o45_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o45_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o45_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o45_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o45_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o45_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o45_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o45_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o45_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o45_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o45_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o45_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o45_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o45_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o45_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o45_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o45_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o45_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o45_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o45_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o45_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o45_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o45_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.5</td><td class='i3'>Loan Collec. Fee in Advance</td>" & "<td class='ac bl'>" & IF(o46_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o46_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o46_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o46_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o46_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o46_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o46_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o46_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o46_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o46_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o46_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o46_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o46_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o46_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o46_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o46_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o46_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o46_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o46_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o46_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o46_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o46_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o46_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o46_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.5.1</td><td class='i4'>Loan Fee In Adv Micro Fin Group</td>" & "<td class='ac bl'>" & IF(o47_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o47_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o47_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o47_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o47_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o47_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o47_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o47_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o47_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o47_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o47_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o47_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o47_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o47_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o47_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o47_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o47_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o47_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o47_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o47_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o47_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o47_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o47_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o47_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.5.3</td><td class='i4'>Loan Fee In Adv Market Vendor</td>" & "<td class='ac bl'>" & IF(o48_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o48_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o48_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o48_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o48_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o48_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o48_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o48_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o48_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o48_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o48_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o48_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o48_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o48_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o48_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o48_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o48_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o48_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o48_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o48_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o48_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o48_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o48_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o48_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>"
VAR Rows_5 =
    "<tr><td class='cd'>2.06.9.5.4</td><td class='i4'>Loan Fee In Adv Seasonal Crop</td>" & "<td class='ac bl'>" & IF(o49_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o49_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o49_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o49_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o49_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o49_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o49_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o49_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o49_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o49_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o49_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o49_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o49_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o49_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o49_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o49_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o49_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o49_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o49_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o49_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o49_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o49_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o49_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o49_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.5.5</td><td class='i4'>Loan Fee In Adv Business Loan</td>" & "<td class='ac bl'>" & IF(o50_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o50_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o50_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o50_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o50_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o50_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o50_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o50_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o50_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o50_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o50_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o50_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o50_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o50_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o50_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o50_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o50_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o50_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o50_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o50_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o50_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o50_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o50_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o50_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.5.6</td><td class='i4'>Loan Fee In Adv Payroll Loan</td>" & "<td class='ac bl'>" & IF(o51_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o51_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o51_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o51_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o51_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o51_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o51_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o51_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o51_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o51_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o51_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o51_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o51_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o51_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o51_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o51_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o51_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o51_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o51_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o51_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o51_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o51_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o51_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o51_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.5.7</td><td class='i4'>Loan Fee In Adv Empl.and Staff Loan</td>" & "<td class='ac bl'>" & IF(o52_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o52_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o52_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o52_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o52_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o52_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o52_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o52_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o52_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o52_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o52_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o52_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o52_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o52_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o52_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o52_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o52_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o52_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o52_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o52_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o52_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o52_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o52_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o52_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.5.8</td><td class='i4'>Loan Fee In Adv Internal Staff Loan</td>" & "<td class='ac bl'>" & IF(o53_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o53_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o53_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o53_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o53_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o53_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o53_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o53_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o53_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o53_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o53_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o53_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o53_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o53_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o53_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o53_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o53_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o53_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o53_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o53_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o53_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o53_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o53_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o53_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.5.9</td><td class='i4'>Loan Fee In Adv Project Loan</td>" & "<td class='ac bl'>" & IF(o54_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o54_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o54_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o54_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o54_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o54_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o54_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o54_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o54_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o54_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o54_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o54_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o54_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o54_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o54_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o54_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o54_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o54_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o54_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o54_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o54_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o54_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o54_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o54_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'></td><td class='i2'>Loan Fee In Advance Morten</td>" & "<td class='ac bl'>" & IF(o55_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o55_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o55_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o55_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o55_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o55_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o55_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o55_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o55_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o55_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o55_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o55_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o55_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o55_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o55_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o55_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o55_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o55_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o55_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o55_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o55_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o55_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o55_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o55_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.6.0</td><td class='i4'>Loan fee In Adv Investment Loan</td>" & "<td class='ac bl'>" & IF(o56_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o56_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o56_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o56_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o56_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o56_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o56_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o56_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o56_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o56_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o56_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o56_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o56_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o56_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o56_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o56_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o56_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o56_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o56_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o56_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o56_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o56_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o56_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o56_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.6.1</td><td class='i4'>Loan Fee in Adv Asuwa&#39;in Loan</td>" & "<td class='ac bl'>" & IF(o57_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o57_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o57_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o57_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o57_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o57_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o57_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o57_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o57_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o57_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o57_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o57_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o57_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o57_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o57_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o57_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o57_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o57_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o57_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o57_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o57_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o57_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o57_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o57_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.6.2</td><td class='i4'>Loan Fee in Adv Bukae Loan</td>" & "<td class='ac bl'>" & IF(o58_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o58_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o58_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o58_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o58_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o58_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o58_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o58_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o58_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o58_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o58_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o58_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o58_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o58_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o58_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o58_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o58_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o58_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o58_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o58_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o58_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o58_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o58_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o58_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.6.3</td><td class='i4'>Loan Fee in Adv Pension Loan</td>" & "<td class='ac bl'>" & IF(o59_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o59_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o59_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o59_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o59_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o59_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o59_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o59_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o59_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o59_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o59_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o59_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o59_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o59_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o59_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o59_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o59_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o59_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o59_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o59_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o59_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o59_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o59_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o59_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.6.4</td><td class='i4'>Loan Fee in Adv Commercial Transport Lo</td>" & "<td class='ac bl'>" & IF(o60_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o60_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o60_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o60_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o60_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o60_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o60_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o60_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o60_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o60_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o60_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o60_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o60_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o60_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o60_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o60_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o60_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o60_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o60_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o60_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o60_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o60_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o60_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o60_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>"
VAR Rows_6 =
    "<tr><td class='cd'>2.06.9.6.5</td><td class='i4'>Loan Fee in Adv LO Multiuzu</td>" & "<td class='ac bl'>" & IF(o61_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o61_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o61_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o61_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o61_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o61_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o61_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o61_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o61_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o61_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o61_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o61_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o61_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o61_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o61_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o61_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o61_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o61_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o61_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o61_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o61_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o61_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o61_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o61_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.6.6</td><td class='i4'>Fee in Adv LO Asuwain Loan</td>" & "<td class='ac bl'>" & IF(o62_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o62_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o62_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o62_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o62_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o62_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o62_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o62_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o62_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o62_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o62_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o62_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o62_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o62_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o62_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o62_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o62_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o62_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o62_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o62_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o62_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o62_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o62_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o62_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.6.9</td><td class='i4'>Loan Fee in Adv LO FIAR</td>" & "<td class='ac bl'>" & IF(o63_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o63_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o63_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o63_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o63_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o63_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o63_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o63_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o63_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o63_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o63_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o63_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o63_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o63_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o63_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o63_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o63_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o63_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o63_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o63_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o63_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o63_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o63_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o63_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.7.1</td><td class='i4'>Loan Fee in Adv Agricultor LO</td>" & "<td class='ac bl'>" & IF(o64_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o64_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o64_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o64_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o64_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o64_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o64_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o64_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o64_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o64_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o64_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o64_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o64_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o64_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o64_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o64_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o64_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o64_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o64_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o64_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o64_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o64_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o64_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o64_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.6.7</td><td class='i4'>Loan Fee in Adv LO Bukae</td>" & "<td class='ac bl'>" & IF(o65_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o65_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o65_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o65_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o65_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o65_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o65_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o65_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o65_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o65_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o65_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o65_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o65_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o65_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o65_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o65_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o65_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o65_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o65_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o65_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o65_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o65_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o65_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o65_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2.06.9.6.8</td><td class='i4'>Loan Fee in Adv LO Pension</td>" & "<td class='ac bl'>" & IF(o66_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o66_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o66_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o66_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o66_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o66_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o66_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o66_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o66_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o66_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o66_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o66_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o66_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o66_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o66_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o66_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o66_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o66_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o66_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o66_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o66_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o66_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o66_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o66_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'></td><td class='i2'>Loan Fee RBL Origination</td>" & "<td class='ac bl'>" & IF(o67_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o67_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o67_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o67_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o67_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o67_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o67_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o67_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o67_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o67_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o67_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o67_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o67_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o67_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o67_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o67_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o67_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o67_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o67_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o67_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o67_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o67_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o67_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o67_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub1'><td class='cd'>2.08</td><td class='i1'>Other Liabilit/Due To Branch</td>" & "<td class='ac bl'>" & IF(o68_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o68_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o68_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o68_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o68_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o68_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o68_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o68_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o68_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o68_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o68_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o68_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o68_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o68_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o68_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o68_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o68_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o68_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o68_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o68_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o68_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o68_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o68_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o68_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>2-08-1-1</td><td class='i3'>Inter Branch Transac (Net)</td>" & "<td class='ac bl'>" & IF(o69_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o69_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o69_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o69_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o69_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o69_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o69_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o69_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o69_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o69_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o69_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o69_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o69_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o69_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o69_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o69_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o69_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o69_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o69_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o69_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o69_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o69_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o69_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o69_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>2-08-1</td><td class='i2'>Others/Overages</td>" & "<td class='ac bl'>" & IF(o70_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o70_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o70_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o70_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o70_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o70_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o70_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o70_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o70_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o70_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o70_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o70_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o70_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o70_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o70_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o70_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o70_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o70_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o70_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o70_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o70_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o70_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o70_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o70_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>2-08-2</td><td class='i2'>Overages ATM</td>" & "<td class='ac bl'>" & IF(o71_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o71_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o71_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o71_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o71_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o71_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o71_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o71_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o71_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o71_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o71_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o71_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o71_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o71_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o71_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o71_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o71_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o71_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o71_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o71_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o71_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o71_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o71_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o71_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub1'><td class='cd'>3.0</td><td class='i1'>CAPITAL ACCOUNTS:</td>" & "<td class='ac bl'>" & IF(o72_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o72_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o72_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o72_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o72_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o72_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o72_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o72_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o72_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o72_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o72_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o72_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o72_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o72_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o72_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o72_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o72_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o72_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o72_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o72_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o72_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o72_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o72_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o72_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>"
VAR Rows_7 =
    "<tr class='sub1'><td class='cd'>3.01</td><td class='i1'>Provisioning</td>" & "<td class='ac bl'>" & IF(o73_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o73_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o73_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o73_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o73_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o73_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o73_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o73_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o73_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o73_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o73_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o73_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o73_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o73_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o73_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o73_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o73_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o73_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o73_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o73_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o73_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o73_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o73_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o73_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub1'><td class='cd'>3.02</td><td class='i1'>Capital Paid-Up &amp; Assigned</td>" & "<td class='ac bl'>" & IF(o74_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o74_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o74_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o74_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o74_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o74_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o74_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o74_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o74_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o74_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o74_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o74_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o74_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o74_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o74_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o74_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o74_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o74_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o74_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o74_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o74_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o74_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o74_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o74_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'>3-04-3-2</td><td class='i3'>Capital Reserve/Reserve Legais</td>" & "<td class='ac bl'>" & IF(o75_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o75_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o75_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o75_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o75_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o75_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o75_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o75_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o75_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o75_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o75_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o75_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o75_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o75_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o75_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o75_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o75_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o75_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o75_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o75_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o75_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o75_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o75_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o75_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub1'><td class='cd'>3.06</td><td class='i1'>Profits / Losses</td>" & "<td class='ac bl'>" & IF(o76_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o76_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o76_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o76_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o76_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o76_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o76_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o76_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o76_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o76_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o76_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o76_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o76_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o76_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o76_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o76_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o76_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o76_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o76_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o76_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o76_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o76_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o76_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o76_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>3.06.1</td><td class='i2'>Previeous Financial Year</td>" & "<td class='ac bl'>" & IF(o77_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o77_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o77_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o77_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o77_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o77_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o77_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o77_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o77_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o77_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o77_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o77_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o77_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o77_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o77_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o77_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o77_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o77_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o77_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o77_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o77_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o77_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o77_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o77_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='sub2'><td class='cd'>3.06.2</td><td class='i2'>Current Financial Year</td>" & "<td class='ac bl'>" & IF(o78_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o78_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o78_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o78_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o78_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o78_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o78_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o78_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o78_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o78_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o78_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o78_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o78_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o78_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o78_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o78_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o78_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o78_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o78_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o78_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o78_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o78_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o78_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o78_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'></td><td class='i2'>Total Liabilities &amp; Capital</td>" & "<td class='ac bl'>" & IF(o79_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o79_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o79_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o79_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o79_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o79_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o79_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o79_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o79_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o79_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o79_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o79_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o79_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o79_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o79_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o79_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o79_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o79_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o79_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o79_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o79_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o79_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o79_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o79_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'></td><td class='i2'>Total Liability in CRF</td>" & "<td class='ac bl'>" & IF(o80_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o80_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o80_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o80_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o80_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o80_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o80_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o80_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o80_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o80_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o80_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o80_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o80_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o80_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o80_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o80_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o80_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o80_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o80_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o80_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o80_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o80_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o80_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o80_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'></td><td class='i2'>Total Capital in CRF</td>" & "<td class='ac bl'>" & IF(o81_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o81_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o81_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o81_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o81_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o81_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o81_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o81_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o81_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o81_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o81_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o81_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o81_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o81_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o81_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o81_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o81_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o81_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o81_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o81_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o81_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o81_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o81_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o81_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr><td class='cd'></td><td class='i2'>Diference Assent and Liability</td>" & "<td class='ac bl'>" & IF(o82_CURR_ac=0,"<span style='color:#d1d5db'>-</span>",FORMAT(o82_CURR_ac,"#,##0")) & "</td>" & "<td class='ar'>" & IF(o82_CURR_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o82_CURR_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o82_PREV_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o82_PREV_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o82_CI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o82_CI>0,"<span style='color:#16a34a'>+" & FORMAT(o82_CI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o82_CI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o82_CP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o82_CP>0,"<span style='color:#16a34a'>+" & FORMAT(o82_CP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o82_CP*100,"0.00") & "%</span>")) & "</td>" & "<td class='ar bl'>" & IF(o82_YOY_am<0.01,"<span style='color:#d1d5db'>-</span>",FORMAT(o82_YOY_am,"#,##0.00")) & "</td>" & "<td class='ar bl'>" & IF(o82_YI<0.01,"<span style='color:#d1d5db'>-</span>",IF(o82_YI>0,"<span style='color:#16a34a'>+" & FORMAT(o82_YI,"#,##0.00") & "</span>","<span style='color:#dc2626'>(" & FORMAT(o82_YI,"#,##0.00") & ")</span>")) & "</td>" & "<td class='pct'>" & IF(o82_YP<0.0001,"<span style='color:#d1d5db'>-</span>",IF(o82_YP>0,"<span style='color:#16a34a'>+" & FORMAT(o82_YP*100,"0.00") & "%</span>","<span style='color:#dc2626'>" & FORMAT(o82_YP*100,"0.00") & "%</span>")) & "</td>" & "</tr>" &
    "<tr class='h-row'><td class='cd-w'>9999</td><td class='i0'>Sistem Internal Error Account</td><td colspan='8'></td></tr>" &
    "<tr class='tot'><td class='cd-w'></td><td class='i0'>TOTAL LIABILITIES &amp; CAPITAL ACCOUNTS</td><td colspan='8'></td></tr>"
VAR Ftr =
    "<div style='background:#f8fafc;border-top:1px solid #e2e8f0;padding:7px 15px;display:flex;justify-content:space-between;'>" &
    "<span style='font-size:10px;color:#9ca3af;'>USD &nbsp;|&nbsp; <span style='color:#16a34a;'>+</span>=increase &nbsp;<span style='color:#dc2626;'>( )</span>=decrease</span>" &
    "<span style='font-size:10px;color:#9ca3af;'>BNCTL &mdash; Confidential</span>" &
    "</div>"
RETURN
    "<div class='soc'>" & Sty & Hdr &
    "<div style='overflow-x:auto;'>" & ColHdr &
    Rows_1 &
    Rows_2 &
    Rows_3 &
    Rows_4 &
    Rows_5 &
    Rows_6 &
    Rows_7 &
    "</tbody></table></div>" &
    Ftr & "</div>"
