MEASURE 'final_disbursement_consolidation'[Disbursement_Summary_HTML] =

VAR SelectedYear   = SELECTEDVALUE( 'Calendar_Disbursement'[Year] )
VAR SelectedBranch = SELECTEDVALUE( final_disbursement_consolidation[Branch] )
VAR MaxYear      = MAXX( FILTER(final_disbursement_consolidation,[amount_total]>0), FORMAT([report_year],"0") )
VAR ActiveYear   = IF( ISBLANK(SelectedYear), MaxYear, SelectedYear )
VAR AYN          = VALUE( ActiveYear )
VAR tbl = FILTER( final_disbursement_consolidation, [report_year]=AYN && [Credit_Product]<>"TOTAL" && NOT ISBLANK([Branch]) )
VAR ttl = FILTER( final_disbursement_consolidation, [report_year]=AYN && [Credit_Product]="TOTAL" )

VAR s1_jana = SUMX(FILTER(ttl,[Branch]="DILI"),[amount_jan])
VAR s1_jann = SUMX(FILTER(ttl,[Branch]="DILI"),[acct_jan])
VAR s1_feba = SUMX(FILTER(ttl,[Branch]="DILI"),[amount_feb])
VAR s1_febn = SUMX(FILTER(ttl,[Branch]="DILI"),[acct_feb])
VAR s1_mara = SUMX(FILTER(ttl,[Branch]="DILI"),[amount_mar])
VAR s1_marn = SUMX(FILTER(ttl,[Branch]="DILI"),[acct_mar])
VAR s1_apra = SUMX(FILTER(ttl,[Branch]="DILI"),[amount_apr])
VAR s1_aprn = SUMX(FILTER(ttl,[Branch]="DILI"),[acct_apr])
VAR s1_maya = SUMX(FILTER(ttl,[Branch]="DILI"),[amount_may])
VAR s1_mayn = SUMX(FILTER(ttl,[Branch]="DILI"),[acct_may])
VAR s1_juna = SUMX(FILTER(ttl,[Branch]="DILI"),[amount_jun])
VAR s1_junn = SUMX(FILTER(ttl,[Branch]="DILI"),[acct_jun])
VAR s1_jula = SUMX(FILTER(ttl,[Branch]="DILI"),[amount_jul])
VAR s1_juln = SUMX(FILTER(ttl,[Branch]="DILI"),[acct_jul])
VAR s1_auga = SUMX(FILTER(ttl,[Branch]="DILI"),[amount_aug])
VAR s1_augn = SUMX(FILTER(ttl,[Branch]="DILI"),[acct_aug])
VAR s1_sepa = SUMX(FILTER(ttl,[Branch]="DILI"),[amount_sep])
VAR s1_sepn = SUMX(FILTER(ttl,[Branch]="DILI"),[acct_sep])
VAR s1_octa = SUMX(FILTER(ttl,[Branch]="DILI"),[amount_oct])
VAR s1_octn = SUMX(FILTER(ttl,[Branch]="DILI"),[acct_oct])
VAR s1_nova = SUMX(FILTER(ttl,[Branch]="DILI"),[amount_nov])
VAR s1_novn = SUMX(FILTER(ttl,[Branch]="DILI"),[acct_nov])
VAR s1_deca = SUMX(FILTER(ttl,[Branch]="DILI"),[amount_dec])
VAR s1_decn = SUMX(FILTER(ttl,[Branch]="DILI"),[acct_dec])
VAR s1_tota = SUMX(FILTER(ttl,[Branch]="DILI"),[amount_total])
VAR s1_totn = SUMX(FILTER(ttl,[Branch]="DILI"),[account_total])
VAR s2_jana = SUMX(FILTER(ttl,[Branch]="GLENO"),[amount_jan])
VAR s2_jann = SUMX(FILTER(ttl,[Branch]="GLENO"),[acct_jan])
VAR s2_feba = SUMX(FILTER(ttl,[Branch]="GLENO"),[amount_feb])
VAR s2_febn = SUMX(FILTER(ttl,[Branch]="GLENO"),[acct_feb])
VAR s2_mara = SUMX(FILTER(ttl,[Branch]="GLENO"),[amount_mar])
VAR s2_marn = SUMX(FILTER(ttl,[Branch]="GLENO"),[acct_mar])
VAR s2_apra = SUMX(FILTER(ttl,[Branch]="GLENO"),[amount_apr])
VAR s2_aprn = SUMX(FILTER(ttl,[Branch]="GLENO"),[acct_apr])
VAR s2_maya = SUMX(FILTER(ttl,[Branch]="GLENO"),[amount_may])
VAR s2_mayn = SUMX(FILTER(ttl,[Branch]="GLENO"),[acct_may])
VAR s2_juna = SUMX(FILTER(ttl,[Branch]="GLENO"),[amount_jun])
VAR s2_junn = SUMX(FILTER(ttl,[Branch]="GLENO"),[acct_jun])
VAR s2_jula = SUMX(FILTER(ttl,[Branch]="GLENO"),[amount_jul])
VAR s2_juln = SUMX(FILTER(ttl,[Branch]="GLENO"),[acct_jul])
VAR s2_auga = SUMX(FILTER(ttl,[Branch]="GLENO"),[amount_aug])
VAR s2_augn = SUMX(FILTER(ttl,[Branch]="GLENO"),[acct_aug])
VAR s2_sepa = SUMX(FILTER(ttl,[Branch]="GLENO"),[amount_sep])
VAR s2_sepn = SUMX(FILTER(ttl,[Branch]="GLENO"),[acct_sep])
VAR s2_octa = SUMX(FILTER(ttl,[Branch]="GLENO"),[amount_oct])
VAR s2_octn = SUMX(FILTER(ttl,[Branch]="GLENO"),[acct_oct])
VAR s2_nova = SUMX(FILTER(ttl,[Branch]="GLENO"),[amount_nov])
VAR s2_novn = SUMX(FILTER(ttl,[Branch]="GLENO"),[acct_nov])
VAR s2_deca = SUMX(FILTER(ttl,[Branch]="GLENO"),[amount_dec])
VAR s2_decn = SUMX(FILTER(ttl,[Branch]="GLENO"),[acct_dec])
VAR s2_tota = SUMX(FILTER(ttl,[Branch]="GLENO"),[amount_total])
VAR s2_totn = SUMX(FILTER(ttl,[Branch]="GLENO"),[account_total])
VAR s3_jana = SUMX(FILTER(ttl,[Branch]="MALIANA"),[amount_jan])
VAR s3_jann = SUMX(FILTER(ttl,[Branch]="MALIANA"),[acct_jan])
VAR s3_feba = SUMX(FILTER(ttl,[Branch]="MALIANA"),[amount_feb])
VAR s3_febn = SUMX(FILTER(ttl,[Branch]="MALIANA"),[acct_feb])
VAR s3_mara = SUMX(FILTER(ttl,[Branch]="MALIANA"),[amount_mar])
VAR s3_marn = SUMX(FILTER(ttl,[Branch]="MALIANA"),[acct_mar])
VAR s3_apra = SUMX(FILTER(ttl,[Branch]="MALIANA"),[amount_apr])
VAR s3_aprn = SUMX(FILTER(ttl,[Branch]="MALIANA"),[acct_apr])
VAR s3_maya = SUMX(FILTER(ttl,[Branch]="MALIANA"),[amount_may])
VAR s3_mayn = SUMX(FILTER(ttl,[Branch]="MALIANA"),[acct_may])
VAR s3_juna = SUMX(FILTER(ttl,[Branch]="MALIANA"),[amount_jun])
VAR s3_junn = SUMX(FILTER(ttl,[Branch]="MALIANA"),[acct_jun])
VAR s3_jula = SUMX(FILTER(ttl,[Branch]="MALIANA"),[amount_jul])
VAR s3_juln = SUMX(FILTER(ttl,[Branch]="MALIANA"),[acct_jul])
VAR s3_auga = SUMX(FILTER(ttl,[Branch]="MALIANA"),[amount_aug])
VAR s3_augn = SUMX(FILTER(ttl,[Branch]="MALIANA"),[acct_aug])
VAR s3_sepa = SUMX(FILTER(ttl,[Branch]="MALIANA"),[amount_sep])
VAR s3_sepn = SUMX(FILTER(ttl,[Branch]="MALIANA"),[acct_sep])
VAR s3_octa = SUMX(FILTER(ttl,[Branch]="MALIANA"),[amount_oct])
VAR s3_octn = SUMX(FILTER(ttl,[Branch]="MALIANA"),[acct_oct])
VAR s3_nova = SUMX(FILTER(ttl,[Branch]="MALIANA"),[amount_nov])
VAR s3_novn = SUMX(FILTER(ttl,[Branch]="MALIANA"),[acct_nov])
VAR s3_deca = SUMX(FILTER(ttl,[Branch]="MALIANA"),[amount_dec])
VAR s3_decn = SUMX(FILTER(ttl,[Branch]="MALIANA"),[acct_dec])
VAR s3_tota = SUMX(FILTER(ttl,[Branch]="MALIANA"),[amount_total])
VAR s3_totn = SUMX(FILTER(ttl,[Branch]="MALIANA"),[account_total])
VAR s4_jana = SUMX(FILTER(ttl,[Branch]="AILEU"),[amount_jan])
VAR s4_jann = SUMX(FILTER(ttl,[Branch]="AILEU"),[acct_jan])
VAR s4_feba = SUMX(FILTER(ttl,[Branch]="AILEU"),[amount_feb])
VAR s4_febn = SUMX(FILTER(ttl,[Branch]="AILEU"),[acct_feb])
VAR s4_mara = SUMX(FILTER(ttl,[Branch]="AILEU"),[amount_mar])
VAR s4_marn = SUMX(FILTER(ttl,[Branch]="AILEU"),[acct_mar])
VAR s4_apra = SUMX(FILTER(ttl,[Branch]="AILEU"),[amount_apr])
VAR s4_aprn = SUMX(FILTER(ttl,[Branch]="AILEU"),[acct_apr])
VAR s4_maya = SUMX(FILTER(ttl,[Branch]="AILEU"),[amount_may])
VAR s4_mayn = SUMX(FILTER(ttl,[Branch]="AILEU"),[acct_may])
VAR s4_juna = SUMX(FILTER(ttl,[Branch]="AILEU"),[amount_jun])
VAR s4_junn = SUMX(FILTER(ttl,[Branch]="AILEU"),[acct_jun])
VAR s4_jula = SUMX(FILTER(ttl,[Branch]="AILEU"),[amount_jul])
VAR s4_juln = SUMX(FILTER(ttl,[Branch]="AILEU"),[acct_jul])
VAR s4_auga = SUMX(FILTER(ttl,[Branch]="AILEU"),[amount_aug])
VAR s4_augn = SUMX(FILTER(ttl,[Branch]="AILEU"),[acct_aug])
VAR s4_sepa = SUMX(FILTER(ttl,[Branch]="AILEU"),[amount_sep])
VAR s4_sepn = SUMX(FILTER(ttl,[Branch]="AILEU"),[acct_sep])
VAR s4_octa = SUMX(FILTER(ttl,[Branch]="AILEU"),[amount_oct])
VAR s4_octn = SUMX(FILTER(ttl,[Branch]="AILEU"),[acct_oct])
VAR s4_nova = SUMX(FILTER(ttl,[Branch]="AILEU"),[amount_nov])
VAR s4_novn = SUMX(FILTER(ttl,[Branch]="AILEU"),[acct_nov])
VAR s4_deca = SUMX(FILTER(ttl,[Branch]="AILEU"),[amount_dec])
VAR s4_decn = SUMX(FILTER(ttl,[Branch]="AILEU"),[acct_dec])
VAR s4_tota = SUMX(FILTER(ttl,[Branch]="AILEU"),[amount_total])
VAR s4_totn = SUMX(FILTER(ttl,[Branch]="AILEU"),[account_total])
VAR s5_jana = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[amount_jan])
VAR s5_jann = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[acct_jan])
VAR s5_feba = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[amount_feb])
VAR s5_febn = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[acct_feb])
VAR s5_mara = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[amount_mar])
VAR s5_marn = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[acct_mar])
VAR s5_apra = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[amount_apr])
VAR s5_aprn = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[acct_apr])
VAR s5_maya = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[amount_may])
VAR s5_mayn = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[acct_may])
VAR s5_juna = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[amount_jun])
VAR s5_junn = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[acct_jun])
VAR s5_jula = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[amount_jul])
VAR s5_juln = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[acct_jul])
VAR s5_auga = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[amount_aug])
VAR s5_augn = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[acct_aug])
VAR s5_sepa = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[amount_sep])
VAR s5_sepn = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[acct_sep])
VAR s5_octa = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[amount_oct])
VAR s5_octn = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[acct_oct])
VAR s5_nova = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[amount_nov])
VAR s5_novn = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[acct_nov])
VAR s5_deca = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[amount_dec])
VAR s5_decn = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[acct_dec])
VAR s5_tota = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[amount_total])
VAR s5_totn = SUMX(FILTER(ttl,[Branch]="OECUSSE"),[account_total])
VAR s6_jana = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[amount_jan])
VAR s6_jann = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[acct_jan])
VAR s6_feba = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[amount_feb])
VAR s6_febn = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[acct_feb])
VAR s6_mara = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[amount_mar])
VAR s6_marn = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[acct_mar])
VAR s6_apra = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[amount_apr])
VAR s6_aprn = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[acct_apr])
VAR s6_maya = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[amount_may])
VAR s6_mayn = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[acct_may])
VAR s6_juna = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[amount_jun])
VAR s6_junn = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[acct_jun])
VAR s6_jula = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[amount_jul])
VAR s6_juln = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[acct_jul])
VAR s6_auga = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[amount_aug])
VAR s6_augn = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[acct_aug])
VAR s6_sepa = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[amount_sep])
VAR s6_sepn = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[acct_sep])
VAR s6_octa = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[amount_oct])
VAR s6_octn = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[acct_oct])
VAR s6_nova = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[amount_nov])
VAR s6_novn = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[acct_nov])
VAR s6_deca = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[amount_dec])
VAR s6_decn = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[acct_dec])
VAR s6_tota = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[amount_total])
VAR s6_totn = SUMX(FILTER(ttl,[Branch]="BAUCAU"),[account_total])
VAR s7_jana = SUMX(FILTER(ttl,[Branch]="SAME"),[amount_jan])
VAR s7_jann = SUMX(FILTER(ttl,[Branch]="SAME"),[acct_jan])
VAR s7_feba = SUMX(FILTER(ttl,[Branch]="SAME"),[amount_feb])
VAR s7_febn = SUMX(FILTER(ttl,[Branch]="SAME"),[acct_feb])
VAR s7_mara = SUMX(FILTER(ttl,[Branch]="SAME"),[amount_mar])
VAR s7_marn = SUMX(FILTER(ttl,[Branch]="SAME"),[acct_mar])
VAR s7_apra = SUMX(FILTER(ttl,[Branch]="SAME"),[amount_apr])
VAR s7_aprn = SUMX(FILTER(ttl,[Branch]="SAME"),[acct_apr])
VAR s7_maya = SUMX(FILTER(ttl,[Branch]="SAME"),[amount_may])
VAR s7_mayn = SUMX(FILTER(ttl,[Branch]="SAME"),[acct_may])
VAR s7_juna = SUMX(FILTER(ttl,[Branch]="SAME"),[amount_jun])
VAR s7_junn = SUMX(FILTER(ttl,[Branch]="SAME"),[acct_jun])
VAR s7_jula = SUMX(FILTER(ttl,[Branch]="SAME"),[amount_jul])
VAR s7_juln = SUMX(FILTER(ttl,[Branch]="SAME"),[acct_jul])
VAR s7_auga = SUMX(FILTER(ttl,[Branch]="SAME"),[amount_aug])
VAR s7_augn = SUMX(FILTER(ttl,[Branch]="SAME"),[acct_aug])
VAR s7_sepa = SUMX(FILTER(ttl,[Branch]="SAME"),[amount_sep])
VAR s7_sepn = SUMX(FILTER(ttl,[Branch]="SAME"),[acct_sep])
VAR s7_octa = SUMX(FILTER(ttl,[Branch]="SAME"),[amount_oct])
VAR s7_octn = SUMX(FILTER(ttl,[Branch]="SAME"),[acct_oct])
VAR s7_nova = SUMX(FILTER(ttl,[Branch]="SAME"),[amount_nov])
VAR s7_novn = SUMX(FILTER(ttl,[Branch]="SAME"),[acct_nov])
VAR s7_deca = SUMX(FILTER(ttl,[Branch]="SAME"),[amount_dec])
VAR s7_decn = SUMX(FILTER(ttl,[Branch]="SAME"),[acct_dec])
VAR s7_tota = SUMX(FILTER(ttl,[Branch]="SAME"),[amount_total])
VAR s7_totn = SUMX(FILTER(ttl,[Branch]="SAME"),[account_total])

VAR s8_jana = SUMX(FILTER(ttl,[Branch]="AINARO"),[amount_jan])
VAR s8_jann = SUMX(FILTER(ttl,[Branch]="AINARO"),[acct_jan])
VAR s8_feba = SUMX(FILTER(ttl,[Branch]="AINARO"),[amount_feb])
VAR s8_febn = SUMX(FILTER(ttl,[Branch]="AINARO"),[acct_feb])
VAR s8_mara = SUMX(FILTER(ttl,[Branch]="AINARO"),[amount_mar])
VAR s8_marn = SUMX(FILTER(ttl,[Branch]="AINARO"),[acct_mar])
VAR s8_apra = SUMX(FILTER(ttl,[Branch]="AINARO"),[amount_apr])
VAR s8_aprn = SUMX(FILTER(ttl,[Branch]="AINARO"),[acct_apr])
VAR s8_maya = SUMX(FILTER(ttl,[Branch]="AINARO"),[amount_may])
VAR s8_mayn = SUMX(FILTER(ttl,[Branch]="AINARO"),[acct_may])
VAR s8_juna = SUMX(FILTER(ttl,[Branch]="AINARO"),[amount_jun])
VAR s8_junn = SUMX(FILTER(ttl,[Branch]="AINARO"),[acct_jun])
VAR s8_jula = SUMX(FILTER(ttl,[Branch]="AINARO"),[amount_jul])
VAR s8_juln = SUMX(FILTER(ttl,[Branch]="AINARO"),[acct_jul])
VAR s8_auga = SUMX(FILTER(ttl,[Branch]="AINARO"),[amount_aug])
VAR s8_augn = SUMX(FILTER(ttl,[Branch]="AINARO"),[acct_aug])
VAR s8_sepa = SUMX(FILTER(ttl,[Branch]="AINARO"),[amount_sep])
VAR s8_sepn = SUMX(FILTER(ttl,[Branch]="AINARO"),[acct_sep])
VAR s8_octa = SUMX(FILTER(ttl,[Branch]="AINARO"),[amount_oct])
VAR s8_octn = SUMX(FILTER(ttl,[Branch]="AINARO"),[acct_oct])
VAR s8_nova = SUMX(FILTER(ttl,[Branch]="AINARO"),[amount_nov])
VAR s8_novn = SUMX(FILTER(ttl,[Branch]="AINARO"),[acct_nov])
VAR s8_deca = SUMX(FILTER(ttl,[Branch]="AINARO"),[amount_dec])
VAR s8_decn = SUMX(FILTER(ttl,[Branch]="AINARO"),[acct_dec])
VAR s8_tota = SUMX(FILTER(ttl,[Branch]="AINARO"),[amount_total])
VAR s8_totn = SUMX(FILTER(ttl,[Branch]="AINARO"),[account_total])
VAR s9_jana = SUMX(FILTER(ttl,[Branch]="SUAI"),[amount_jan])
VAR s9_jann = SUMX(FILTER(ttl,[Branch]="SUAI"),[acct_jan])
VAR s9_feba = SUMX(FILTER(ttl,[Branch]="SUAI"),[amount_feb])
VAR s9_febn = SUMX(FILTER(ttl,[Branch]="SUAI"),[acct_feb])
VAR s9_mara = SUMX(FILTER(ttl,[Branch]="SUAI"),[amount_mar])
VAR s9_marn = SUMX(FILTER(ttl,[Branch]="SUAI"),[acct_mar])
VAR s9_apra = SUMX(FILTER(ttl,[Branch]="SUAI"),[amount_apr])
VAR s9_aprn = SUMX(FILTER(ttl,[Branch]="SUAI"),[acct_apr])
VAR s9_maya = SUMX(FILTER(ttl,[Branch]="SUAI"),[amount_may])
VAR s9_mayn = SUMX(FILTER(ttl,[Branch]="SUAI"),[acct_may])
VAR s9_juna = SUMX(FILTER(ttl,[Branch]="SUAI"),[amount_jun])
VAR s9_junn = SUMX(FILTER(ttl,[Branch]="SUAI"),[acct_jun])
VAR s9_jula = SUMX(FILTER(ttl,[Branch]="SUAI"),[amount_jul])
VAR s9_juln = SUMX(FILTER(ttl,[Branch]="SUAI"),[acct_jul])
VAR s9_auga = SUMX(FILTER(ttl,[Branch]="SUAI"),[amount_aug])
VAR s9_augn = SUMX(FILTER(ttl,[Branch]="SUAI"),[acct_aug])
VAR s9_sepa = SUMX(FILTER(ttl,[Branch]="SUAI"),[amount_sep])
VAR s9_sepn = SUMX(FILTER(ttl,[Branch]="SUAI"),[acct_sep])
VAR s9_octa = SUMX(FILTER(ttl,[Branch]="SUAI"),[amount_oct])
VAR s9_octn = SUMX(FILTER(ttl,[Branch]="SUAI"),[acct_oct])
VAR s9_nova = SUMX(FILTER(ttl,[Branch]="SUAI"),[amount_nov])
VAR s9_novn = SUMX(FILTER(ttl,[Branch]="SUAI"),[acct_nov])
VAR s9_deca = SUMX(FILTER(ttl,[Branch]="SUAI"),[amount_dec])
VAR s9_decn = SUMX(FILTER(ttl,[Branch]="SUAI"),[acct_dec])
VAR s9_tota = SUMX(FILTER(ttl,[Branch]="SUAI"),[amount_total])
VAR s9_totn = SUMX(FILTER(ttl,[Branch]="SUAI"),[account_total])
VAR s10_jana = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[amount_jan])
VAR s10_jann = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[acct_jan])
VAR s10_feba = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[amount_feb])
VAR s10_febn = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[acct_feb])
VAR s10_mara = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[amount_mar])
VAR s10_marn = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[acct_mar])
VAR s10_apra = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[amount_apr])
VAR s10_aprn = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[acct_apr])
VAR s10_maya = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[amount_may])
VAR s10_mayn = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[acct_may])
VAR s10_juna = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[amount_jun])
VAR s10_junn = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[acct_jun])
VAR s10_jula = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[amount_jul])
VAR s10_juln = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[acct_jul])
VAR s10_auga = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[amount_aug])
VAR s10_augn = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[acct_aug])
VAR s10_sepa = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[amount_sep])
VAR s10_sepn = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[acct_sep])
VAR s10_octa = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[amount_oct])
VAR s10_octn = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[acct_oct])
VAR s10_nova = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[amount_nov])
VAR s10_novn = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[acct_nov])
VAR s10_deca = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[amount_dec])
VAR s10_decn = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[acct_dec])
VAR s10_tota = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[amount_total])
VAR s10_totn = SUMX(FILTER(ttl,[Branch]="VIQUEQUE"),[account_total])
VAR s11_jana = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[amount_jan])
VAR s11_jann = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[acct_jan])
VAR s11_feba = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[amount_feb])
VAR s11_febn = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[acct_feb])
VAR s11_mara = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[amount_mar])
VAR s11_marn = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[acct_mar])
VAR s11_apra = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[amount_apr])
VAR s11_aprn = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[acct_apr])
VAR s11_maya = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[amount_may])
VAR s11_mayn = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[acct_may])
VAR s11_juna = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[amount_jun])
VAR s11_junn = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[acct_jun])
VAR s11_jula = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[amount_jul])
VAR s11_juln = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[acct_jul])
VAR s11_auga = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[amount_aug])
VAR s11_augn = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[acct_aug])
VAR s11_sepa = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[amount_sep])
VAR s11_sepn = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[acct_sep])
VAR s11_octa = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[amount_oct])
VAR s11_octn = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[acct_oct])
VAR s11_nova = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[amount_nov])
VAR s11_novn = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[acct_nov])
VAR s11_deca = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[amount_dec])
VAR s11_decn = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[acct_dec])
VAR s11_tota = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[amount_total])
VAR s11_totn = SUMX(FILTER(ttl,[Branch]="LOSPALOS"),[account_total])
VAR s12_jana = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[amount_jan])
VAR s12_jann = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[acct_jan])
VAR s12_feba = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[amount_feb])
VAR s12_febn = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[acct_feb])
VAR s12_mara = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[amount_mar])
VAR s12_marn = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[acct_mar])
VAR s12_apra = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[amount_apr])
VAR s12_aprn = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[acct_apr])
VAR s12_maya = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[amount_may])
VAR s12_mayn = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[acct_may])
VAR s12_juna = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[amount_jun])
VAR s12_junn = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[acct_jun])
VAR s12_jula = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[amount_jul])
VAR s12_juln = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[acct_jul])
VAR s12_auga = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[amount_aug])
VAR s12_augn = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[acct_aug])
VAR s12_sepa = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[amount_sep])
VAR s12_sepn = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[acct_sep])
VAR s12_octa = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[amount_oct])
VAR s12_octn = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[acct_oct])
VAR s12_nova = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[amount_nov])
VAR s12_novn = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[acct_nov])
VAR s12_deca = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[amount_dec])
VAR s12_decn = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[acct_dec])
VAR s12_tota = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[amount_total])
VAR s12_totn = SUMX(FILTER(ttl,[Branch]="LIQUICA"),[account_total])
VAR s13_jana = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[amount_jan])
VAR s13_jann = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[acct_jan])
VAR s13_feba = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[amount_feb])
VAR s13_febn = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[acct_feb])
VAR s13_mara = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[amount_mar])
VAR s13_marn = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[acct_mar])
VAR s13_apra = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[amount_apr])
VAR s13_aprn = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[acct_apr])
VAR s13_maya = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[amount_may])
VAR s13_mayn = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[acct_may])
VAR s13_juna = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[amount_jun])
VAR s13_junn = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[acct_jun])
VAR s13_jula = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[amount_jul])
VAR s13_juln = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[acct_jul])
VAR s13_auga = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[amount_aug])
VAR s13_augn = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[acct_aug])
VAR s13_sepa = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[amount_sep])
VAR s13_sepn = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[acct_sep])
VAR s13_octa = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[amount_oct])
VAR s13_octn = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[acct_oct])
VAR s13_nova = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[amount_nov])
VAR s13_novn = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[acct_nov])
VAR s13_deca = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[amount_dec])
VAR s13_decn = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[acct_dec])
VAR s13_tota = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[amount_total])
VAR s13_totn = SUMX(FILTER(ttl,[Branch]="MANATUTO"),[account_total])

VAR GT_jana = SUMX(ttl,[amount_jan])
VAR GT_jann = SUMX(ttl,[acct_jan])
VAR GT_feba = SUMX(ttl,[amount_feb])
VAR GT_febn = SUMX(ttl,[acct_feb])
VAR GT_mara = SUMX(ttl,[amount_mar])
VAR GT_marn = SUMX(ttl,[acct_mar])
VAR GT_apra = SUMX(ttl,[amount_apr])
VAR GT_aprn = SUMX(ttl,[acct_apr])
VAR GT_maya = SUMX(ttl,[amount_may])
VAR GT_mayn = SUMX(ttl,[acct_may])
VAR GT_juna = SUMX(ttl,[amount_jun])
VAR GT_junn = SUMX(ttl,[acct_jun])
VAR GT_jula = SUMX(ttl,[amount_jul])
VAR GT_juln = SUMX(ttl,[acct_jul])
VAR GT_auga = SUMX(ttl,[amount_aug])
VAR GT_augn = SUMX(ttl,[acct_aug])
VAR GT_sepa = SUMX(ttl,[amount_sep])
VAR GT_sepn = SUMX(ttl,[acct_sep])
VAR GT_octa = SUMX(ttl,[amount_oct])
VAR GT_octn = SUMX(ttl,[acct_oct])
VAR GT_nova = SUMX(ttl,[amount_nov])
VAR GT_novn = SUMX(ttl,[acct_nov])
VAR GT_deca = SUMX(ttl,[amount_dec])
VAR GT_decn = SUMX(ttl,[acct_dec])
VAR GT_tota = SUMX(ttl,[amount_total])
VAR GT_totn = SUMX(ttl,[account_total])

VAR BH1 = "<tr class='bh'><td class='no'>1</td><td colspan='29'>DILI</td></tr>"
VAR PR1 = CONCATENATEX( FILTER(tbl,[Branch]="DILI"&&NOT ISBLANK([Credit_Product_No])), "<tr class='pr'><td class='no'>" & [Credit_Product_No] & "</td><td class='br'></td><td class='pn'>" & [Credit_Product_No] & "</td><td class='nm'>" & [Credit_Product] & "</td>" & "<td class='ar bl'>" & IF([amount_jan]=0,"<span class='zero'>-</span>",FORMAT([amount_jan],"#,##0")) & "</td><td class='ac'>" & IF([acct_jan]=0,"<span class='zero'>-</span>",FORMAT([acct_jan],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_feb]=0,"<span class='zero'>-</span>",FORMAT([amount_feb],"#,##0")) & "</td><td class='ac'>" & IF([acct_feb]=0,"<span class='zero'>-</span>",FORMAT([acct_feb],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_mar]=0,"<span class='zero'>-</span>",FORMAT([amount_mar],"#,##0")) & "</td><td class='ac'>" & IF([acct_mar]=0,"<span class='zero'>-</span>",FORMAT([acct_mar],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_apr]=0,"<span class='zero'>-</span>",FORMAT([amount_apr],"#,##0")) & "</td><td class='ac'>" & IF([acct_apr]=0,"<span class='zero'>-</span>",FORMAT([acct_apr],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_may]=0,"<span class='zero'>-</span>",FORMAT([amount_may],"#,##0")) & "</td><td class='ac'>" & IF([acct_may]=0,"<span class='zero'>-</span>",FORMAT([acct_may],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jun]=0,"<span class='zero'>-</span>",FORMAT([amount_jun],"#,##0")) & "</td><td class='ac'>" & IF([acct_jun]=0,"<span class='zero'>-</span>",FORMAT([acct_jun],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jul]=0,"<span class='zero'>-</span>",FORMAT([amount_jul],"#,##0")) & "</td><td class='ac'>" & IF([acct_jul]=0,"<span class='zero'>-</span>",FORMAT([acct_jul],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_aug]=0,"<span class='zero'>-</span>",FORMAT([amount_aug],"#,##0")) & "</td><td class='ac'>" & IF([acct_aug]=0,"<span class='zero'>-</span>",FORMAT([acct_aug],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_sep]=0,"<span class='zero'>-</span>",FORMAT([amount_sep],"#,##0")) & "</td><td class='ac'>" & IF([acct_sep]=0,"<span class='zero'>-</span>",FORMAT([acct_sep],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_oct]=0,"<span class='zero'>-</span>",FORMAT([amount_oct],"#,##0")) & "</td><td class='ac'>" & IF([acct_oct]=0,"<span class='zero'>-</span>",FORMAT([acct_oct],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_nov]=0,"<span class='zero'>-</span>",FORMAT([amount_nov],"#,##0")) & "</td><td class='ac'>" & IF([acct_nov]=0,"<span class='zero'>-</span>",FORMAT([acct_nov],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_dec]=0,"<span class='zero'>-</span>",FORMAT([amount_dec],"#,##0")) & "</td><td class='ac'>" & IF([acct_dec]=0,"<span class='zero'>-</span>",FORMAT([acct_dec],"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF([amount_total]=0,"<span class='zero'>-</span>",FORMAT([amount_total],"#,##0")) & "</td><td class='ac fw'>" & IF([account_total]=0,"<span class='zero'>-</span>",FORMAT([account_total],"#,##0")) & "</td>" & "</tr>", , VALUE([Credit_Product_No]), ASC )
VAR ST1 = "<tr class='st'><td></td><td class='br'></td><td></td><td style='font-weight:700;'>TOTAL</td>" & "<td class='ar bl'>" & IF(s1_jana=0,"<span class='zero'>-</span>",FORMAT(s1_jana,"#,##0")) & "</td><td class='ac'>" & IF(s1_jann=0,"<span class='zero'>-</span>",FORMAT(s1_jann,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s1_feba=0,"<span class='zero'>-</span>",FORMAT(s1_feba,"#,##0")) & "</td><td class='ac'>" & IF(s1_febn=0,"<span class='zero'>-</span>",FORMAT(s1_febn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s1_mara=0,"<span class='zero'>-</span>",FORMAT(s1_mara,"#,##0")) & "</td><td class='ac'>" & IF(s1_marn=0,"<span class='zero'>-</span>",FORMAT(s1_marn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s1_apra=0,"<span class='zero'>-</span>",FORMAT(s1_apra,"#,##0")) & "</td><td class='ac'>" & IF(s1_aprn=0,"<span class='zero'>-</span>",FORMAT(s1_aprn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s1_maya=0,"<span class='zero'>-</span>",FORMAT(s1_maya,"#,##0")) & "</td><td class='ac'>" & IF(s1_mayn=0,"<span class='zero'>-</span>",FORMAT(s1_mayn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s1_juna=0,"<span class='zero'>-</span>",FORMAT(s1_juna,"#,##0")) & "</td><td class='ac'>" & IF(s1_junn=0,"<span class='zero'>-</span>",FORMAT(s1_junn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s1_jula=0,"<span class='zero'>-</span>",FORMAT(s1_jula,"#,##0")) & "</td><td class='ac'>" & IF(s1_juln=0,"<span class='zero'>-</span>",FORMAT(s1_juln,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s1_auga=0,"<span class='zero'>-</span>",FORMAT(s1_auga,"#,##0")) & "</td><td class='ac'>" & IF(s1_augn=0,"<span class='zero'>-</span>",FORMAT(s1_augn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s1_sepa=0,"<span class='zero'>-</span>",FORMAT(s1_sepa,"#,##0")) & "</td><td class='ac'>" & IF(s1_sepn=0,"<span class='zero'>-</span>",FORMAT(s1_sepn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s1_octa=0,"<span class='zero'>-</span>",FORMAT(s1_octa,"#,##0")) & "</td><td class='ac'>" & IF(s1_octn=0,"<span class='zero'>-</span>",FORMAT(s1_octn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s1_nova=0,"<span class='zero'>-</span>",FORMAT(s1_nova,"#,##0")) & "</td><td class='ac'>" & IF(s1_novn=0,"<span class='zero'>-</span>",FORMAT(s1_novn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s1_deca=0,"<span class='zero'>-</span>",FORMAT(s1_deca,"#,##0")) & "</td><td class='ac'>" & IF(s1_decn=0,"<span class='zero'>-</span>",FORMAT(s1_decn,"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF(s1_tota=0,"<span class='zero'>-</span>",FORMAT(s1_tota,"#,##0")) & "</td><td class='ac fw'>" & IF(s1_totn=0,"<span class='zero'>-</span>",FORMAT(s1_totn,"#,##0")) & "</td>" & "</tr>"
VAR BH2 = "<tr class='bh'><td class='no'>2</td><td colspan='29'>GLENO</td></tr>"
VAR PR2 = CONCATENATEX( FILTER(tbl,[Branch]="GLENO"&&NOT ISBLANK([Credit_Product_No])), "<tr class='pr'><td class='no'>" & [Credit_Product_No] & "</td><td class='br'></td><td class='pn'>" & [Credit_Product_No] & "</td><td class='nm'>" & [Credit_Product] & "</td>" & "<td class='ar bl'>" & IF([amount_jan]=0,"<span class='zero'>-</span>",FORMAT([amount_jan],"#,##0")) & "</td><td class='ac'>" & IF([acct_jan]=0,"<span class='zero'>-</span>",FORMAT([acct_jan],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_feb]=0,"<span class='zero'>-</span>",FORMAT([amount_feb],"#,##0")) & "</td><td class='ac'>" & IF([acct_feb]=0,"<span class='zero'>-</span>",FORMAT([acct_feb],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_mar]=0,"<span class='zero'>-</span>",FORMAT([amount_mar],"#,##0")) & "</td><td class='ac'>" & IF([acct_mar]=0,"<span class='zero'>-</span>",FORMAT([acct_mar],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_apr]=0,"<span class='zero'>-</span>",FORMAT([amount_apr],"#,##0")) & "</td><td class='ac'>" & IF([acct_apr]=0,"<span class='zero'>-</span>",FORMAT([acct_apr],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_may]=0,"<span class='zero'>-</span>",FORMAT([amount_may],"#,##0")) & "</td><td class='ac'>" & IF([acct_may]=0,"<span class='zero'>-</span>",FORMAT([acct_may],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jun]=0,"<span class='zero'>-</span>",FORMAT([amount_jun],"#,##0")) & "</td><td class='ac'>" & IF([acct_jun]=0,"<span class='zero'>-</span>",FORMAT([acct_jun],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jul]=0,"<span class='zero'>-</span>",FORMAT([amount_jul],"#,##0")) & "</td><td class='ac'>" & IF([acct_jul]=0,"<span class='zero'>-</span>",FORMAT([acct_jul],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_aug]=0,"<span class='zero'>-</span>",FORMAT([amount_aug],"#,##0")) & "</td><td class='ac'>" & IF([acct_aug]=0,"<span class='zero'>-</span>",FORMAT([acct_aug],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_sep]=0,"<span class='zero'>-</span>",FORMAT([amount_sep],"#,##0")) & "</td><td class='ac'>" & IF([acct_sep]=0,"<span class='zero'>-</span>",FORMAT([acct_sep],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_oct]=0,"<span class='zero'>-</span>",FORMAT([amount_oct],"#,##0")) & "</td><td class='ac'>" & IF([acct_oct]=0,"<span class='zero'>-</span>",FORMAT([acct_oct],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_nov]=0,"<span class='zero'>-</span>",FORMAT([amount_nov],"#,##0")) & "</td><td class='ac'>" & IF([acct_nov]=0,"<span class='zero'>-</span>",FORMAT([acct_nov],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_dec]=0,"<span class='zero'>-</span>",FORMAT([amount_dec],"#,##0")) & "</td><td class='ac'>" & IF([acct_dec]=0,"<span class='zero'>-</span>",FORMAT([acct_dec],"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF([amount_total]=0,"<span class='zero'>-</span>",FORMAT([amount_total],"#,##0")) & "</td><td class='ac fw'>" & IF([account_total]=0,"<span class='zero'>-</span>",FORMAT([account_total],"#,##0")) & "</td>" & "</tr>", , VALUE([Credit_Product_No]), ASC )
VAR ST2 = "<tr class='st'><td></td><td class='br'></td><td></td><td style='font-weight:700;'>TOTAL</td>" & "<td class='ar bl'>" & IF(s2_jana=0,"<span class='zero'>-</span>",FORMAT(s2_jana,"#,##0")) & "</td><td class='ac'>" & IF(s2_jann=0,"<span class='zero'>-</span>",FORMAT(s2_jann,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s2_feba=0,"<span class='zero'>-</span>",FORMAT(s2_feba,"#,##0")) & "</td><td class='ac'>" & IF(s2_febn=0,"<span class='zero'>-</span>",FORMAT(s2_febn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s2_mara=0,"<span class='zero'>-</span>",FORMAT(s2_mara,"#,##0")) & "</td><td class='ac'>" & IF(s2_marn=0,"<span class='zero'>-</span>",FORMAT(s2_marn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s2_apra=0,"<span class='zero'>-</span>",FORMAT(s2_apra,"#,##0")) & "</td><td class='ac'>" & IF(s2_aprn=0,"<span class='zero'>-</span>",FORMAT(s2_aprn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s2_maya=0,"<span class='zero'>-</span>",FORMAT(s2_maya,"#,##0")) & "</td><td class='ac'>" & IF(s2_mayn=0,"<span class='zero'>-</span>",FORMAT(s2_mayn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s2_juna=0,"<span class='zero'>-</span>",FORMAT(s2_juna,"#,##0")) & "</td><td class='ac'>" & IF(s2_junn=0,"<span class='zero'>-</span>",FORMAT(s2_junn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s2_jula=0,"<span class='zero'>-</span>",FORMAT(s2_jula,"#,##0")) & "</td><td class='ac'>" & IF(s2_juln=0,"<span class='zero'>-</span>",FORMAT(s2_juln,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s2_auga=0,"<span class='zero'>-</span>",FORMAT(s2_auga,"#,##0")) & "</td><td class='ac'>" & IF(s2_augn=0,"<span class='zero'>-</span>",FORMAT(s2_augn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s2_sepa=0,"<span class='zero'>-</span>",FORMAT(s2_sepa,"#,##0")) & "</td><td class='ac'>" & IF(s2_sepn=0,"<span class='zero'>-</span>",FORMAT(s2_sepn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s2_octa=0,"<span class='zero'>-</span>",FORMAT(s2_octa,"#,##0")) & "</td><td class='ac'>" & IF(s2_octn=0,"<span class='zero'>-</span>",FORMAT(s2_octn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s2_nova=0,"<span class='zero'>-</span>",FORMAT(s2_nova,"#,##0")) & "</td><td class='ac'>" & IF(s2_novn=0,"<span class='zero'>-</span>",FORMAT(s2_novn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s2_deca=0,"<span class='zero'>-</span>",FORMAT(s2_deca,"#,##0")) & "</td><td class='ac'>" & IF(s2_decn=0,"<span class='zero'>-</span>",FORMAT(s2_decn,"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF(s2_tota=0,"<span class='zero'>-</span>",FORMAT(s2_tota,"#,##0")) & "</td><td class='ac fw'>" & IF(s2_totn=0,"<span class='zero'>-</span>",FORMAT(s2_totn,"#,##0")) & "</td>" & "</tr>"
VAR BH3 = "<tr class='bh'><td class='no'>3</td><td colspan='29'>MALIANA</td></tr>"
VAR PR3 = CONCATENATEX( FILTER(tbl,[Branch]="MALIANA"&&NOT ISBLANK([Credit_Product_No])), "<tr class='pr'><td class='no'>" & [Credit_Product_No] & "</td><td class='br'></td><td class='pn'>" & [Credit_Product_No] & "</td><td class='nm'>" & [Credit_Product] & "</td>" & "<td class='ar bl'>" & IF([amount_jan]=0,"<span class='zero'>-</span>",FORMAT([amount_jan],"#,##0")) & "</td><td class='ac'>" & IF([acct_jan]=0,"<span class='zero'>-</span>",FORMAT([acct_jan],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_feb]=0,"<span class='zero'>-</span>",FORMAT([amount_feb],"#,##0")) & "</td><td class='ac'>" & IF([acct_feb]=0,"<span class='zero'>-</span>",FORMAT([acct_feb],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_mar]=0,"<span class='zero'>-</span>",FORMAT([amount_mar],"#,##0")) & "</td><td class='ac'>" & IF([acct_mar]=0,"<span class='zero'>-</span>",FORMAT([acct_mar],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_apr]=0,"<span class='zero'>-</span>",FORMAT([amount_apr],"#,##0")) & "</td><td class='ac'>" & IF([acct_apr]=0,"<span class='zero'>-</span>",FORMAT([acct_apr],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_may]=0,"<span class='zero'>-</span>",FORMAT([amount_may],"#,##0")) & "</td><td class='ac'>" & IF([acct_may]=0,"<span class='zero'>-</span>",FORMAT([acct_may],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jun]=0,"<span class='zero'>-</span>",FORMAT([amount_jun],"#,##0")) & "</td><td class='ac'>" & IF([acct_jun]=0,"<span class='zero'>-</span>",FORMAT([acct_jun],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jul]=0,"<span class='zero'>-</span>",FORMAT([amount_jul],"#,##0")) & "</td><td class='ac'>" & IF([acct_jul]=0,"<span class='zero'>-</span>",FORMAT([acct_jul],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_aug]=0,"<span class='zero'>-</span>",FORMAT([amount_aug],"#,##0")) & "</td><td class='ac'>" & IF([acct_aug]=0,"<span class='zero'>-</span>",FORMAT([acct_aug],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_sep]=0,"<span class='zero'>-</span>",FORMAT([amount_sep],"#,##0")) & "</td><td class='ac'>" & IF([acct_sep]=0,"<span class='zero'>-</span>",FORMAT([acct_sep],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_oct]=0,"<span class='zero'>-</span>",FORMAT([amount_oct],"#,##0")) & "</td><td class='ac'>" & IF([acct_oct]=0,"<span class='zero'>-</span>",FORMAT([acct_oct],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_nov]=0,"<span class='zero'>-</span>",FORMAT([amount_nov],"#,##0")) & "</td><td class='ac'>" & IF([acct_nov]=0,"<span class='zero'>-</span>",FORMAT([acct_nov],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_dec]=0,"<span class='zero'>-</span>",FORMAT([amount_dec],"#,##0")) & "</td><td class='ac'>" & IF([acct_dec]=0,"<span class='zero'>-</span>",FORMAT([acct_dec],"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF([amount_total]=0,"<span class='zero'>-</span>",FORMAT([amount_total],"#,##0")) & "</td><td class='ac fw'>" & IF([account_total]=0,"<span class='zero'>-</span>",FORMAT([account_total],"#,##0")) & "</td>" & "</tr>", , VALUE([Credit_Product_No]), ASC )
VAR ST3 = "<tr class='st'><td></td><td class='br'></td><td></td><td style='font-weight:700;'>TOTAL</td>" & "<td class='ar bl'>" & IF(s3_jana=0,"<span class='zero'>-</span>",FORMAT(s3_jana,"#,##0")) & "</td><td class='ac'>" & IF(s3_jann=0,"<span class='zero'>-</span>",FORMAT(s3_jann,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s3_feba=0,"<span class='zero'>-</span>",FORMAT(s3_feba,"#,##0")) & "</td><td class='ac'>" & IF(s3_febn=0,"<span class='zero'>-</span>",FORMAT(s3_febn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s3_mara=0,"<span class='zero'>-</span>",FORMAT(s3_mara,"#,##0")) & "</td><td class='ac'>" & IF(s3_marn=0,"<span class='zero'>-</span>",FORMAT(s3_marn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s3_apra=0,"<span class='zero'>-</span>",FORMAT(s3_apra,"#,##0")) & "</td><td class='ac'>" & IF(s3_aprn=0,"<span class='zero'>-</span>",FORMAT(s3_aprn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s3_maya=0,"<span class='zero'>-</span>",FORMAT(s3_maya,"#,##0")) & "</td><td class='ac'>" & IF(s3_mayn=0,"<span class='zero'>-</span>",FORMAT(s3_mayn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s3_juna=0,"<span class='zero'>-</span>",FORMAT(s3_juna,"#,##0")) & "</td><td class='ac'>" & IF(s3_junn=0,"<span class='zero'>-</span>",FORMAT(s3_junn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s3_jula=0,"<span class='zero'>-</span>",FORMAT(s3_jula,"#,##0")) & "</td><td class='ac'>" & IF(s3_juln=0,"<span class='zero'>-</span>",FORMAT(s3_juln,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s3_auga=0,"<span class='zero'>-</span>",FORMAT(s3_auga,"#,##0")) & "</td><td class='ac'>" & IF(s3_augn=0,"<span class='zero'>-</span>",FORMAT(s3_augn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s3_sepa=0,"<span class='zero'>-</span>",FORMAT(s3_sepa,"#,##0")) & "</td><td class='ac'>" & IF(s3_sepn=0,"<span class='zero'>-</span>",FORMAT(s3_sepn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s3_octa=0,"<span class='zero'>-</span>",FORMAT(s3_octa,"#,##0")) & "</td><td class='ac'>" & IF(s3_octn=0,"<span class='zero'>-</span>",FORMAT(s3_octn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s3_nova=0,"<span class='zero'>-</span>",FORMAT(s3_nova,"#,##0")) & "</td><td class='ac'>" & IF(s3_novn=0,"<span class='zero'>-</span>",FORMAT(s3_novn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s3_deca=0,"<span class='zero'>-</span>",FORMAT(s3_deca,"#,##0")) & "</td><td class='ac'>" & IF(s3_decn=0,"<span class='zero'>-</span>",FORMAT(s3_decn,"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF(s3_tota=0,"<span class='zero'>-</span>",FORMAT(s3_tota,"#,##0")) & "</td><td class='ac fw'>" & IF(s3_totn=0,"<span class='zero'>-</span>",FORMAT(s3_totn,"#,##0")) & "</td>" & "</tr>"
VAR BH4 = "<tr class='bh'><td class='no'>4</td><td colspan='29'>AILEU</td></tr>"
VAR PR4 = CONCATENATEX( FILTER(tbl,[Branch]="AILEU"&&NOT ISBLANK([Credit_Product_No])), "<tr class='pr'><td class='no'>" & [Credit_Product_No] & "</td><td class='br'></td><td class='pn'>" & [Credit_Product_No] & "</td><td class='nm'>" & [Credit_Product] & "</td>" & "<td class='ar bl'>" & IF([amount_jan]=0,"<span class='zero'>-</span>",FORMAT([amount_jan],"#,##0")) & "</td><td class='ac'>" & IF([acct_jan]=0,"<span class='zero'>-</span>",FORMAT([acct_jan],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_feb]=0,"<span class='zero'>-</span>",FORMAT([amount_feb],"#,##0")) & "</td><td class='ac'>" & IF([acct_feb]=0,"<span class='zero'>-</span>",FORMAT([acct_feb],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_mar]=0,"<span class='zero'>-</span>",FORMAT([amount_mar],"#,##0")) & "</td><td class='ac'>" & IF([acct_mar]=0,"<span class='zero'>-</span>",FORMAT([acct_mar],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_apr]=0,"<span class='zero'>-</span>",FORMAT([amount_apr],"#,##0")) & "</td><td class='ac'>" & IF([acct_apr]=0,"<span class='zero'>-</span>",FORMAT([acct_apr],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_may]=0,"<span class='zero'>-</span>",FORMAT([amount_may],"#,##0")) & "</td><td class='ac'>" & IF([acct_may]=0,"<span class='zero'>-</span>",FORMAT([acct_may],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jun]=0,"<span class='zero'>-</span>",FORMAT([amount_jun],"#,##0")) & "</td><td class='ac'>" & IF([acct_jun]=0,"<span class='zero'>-</span>",FORMAT([acct_jun],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jul]=0,"<span class='zero'>-</span>",FORMAT([amount_jul],"#,##0")) & "</td><td class='ac'>" & IF([acct_jul]=0,"<span class='zero'>-</span>",FORMAT([acct_jul],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_aug]=0,"<span class='zero'>-</span>",FORMAT([amount_aug],"#,##0")) & "</td><td class='ac'>" & IF([acct_aug]=0,"<span class='zero'>-</span>",FORMAT([acct_aug],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_sep]=0,"<span class='zero'>-</span>",FORMAT([amount_sep],"#,##0")) & "</td><td class='ac'>" & IF([acct_sep]=0,"<span class='zero'>-</span>",FORMAT([acct_sep],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_oct]=0,"<span class='zero'>-</span>",FORMAT([amount_oct],"#,##0")) & "</td><td class='ac'>" & IF([acct_oct]=0,"<span class='zero'>-</span>",FORMAT([acct_oct],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_nov]=0,"<span class='zero'>-</span>",FORMAT([amount_nov],"#,##0")) & "</td><td class='ac'>" & IF([acct_nov]=0,"<span class='zero'>-</span>",FORMAT([acct_nov],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_dec]=0,"<span class='zero'>-</span>",FORMAT([amount_dec],"#,##0")) & "</td><td class='ac'>" & IF([acct_dec]=0,"<span class='zero'>-</span>",FORMAT([acct_dec],"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF([amount_total]=0,"<span class='zero'>-</span>",FORMAT([amount_total],"#,##0")) & "</td><td class='ac fw'>" & IF([account_total]=0,"<span class='zero'>-</span>",FORMAT([account_total],"#,##0")) & "</td>" & "</tr>", , VALUE([Credit_Product_No]), ASC )
VAR ST4 = "<tr class='st'><td></td><td class='br'></td><td></td><td style='font-weight:700;'>TOTAL</td>" & "<td class='ar bl'>" & IF(s4_jana=0,"<span class='zero'>-</span>",FORMAT(s4_jana,"#,##0")) & "</td><td class='ac'>" & IF(s4_jann=0,"<span class='zero'>-</span>",FORMAT(s4_jann,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s4_feba=0,"<span class='zero'>-</span>",FORMAT(s4_feba,"#,##0")) & "</td><td class='ac'>" & IF(s4_febn=0,"<span class='zero'>-</span>",FORMAT(s4_febn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s4_mara=0,"<span class='zero'>-</span>",FORMAT(s4_mara,"#,##0")) & "</td><td class='ac'>" & IF(s4_marn=0,"<span class='zero'>-</span>",FORMAT(s4_marn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s4_apra=0,"<span class='zero'>-</span>",FORMAT(s4_apra,"#,##0")) & "</td><td class='ac'>" & IF(s4_aprn=0,"<span class='zero'>-</span>",FORMAT(s4_aprn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s4_maya=0,"<span class='zero'>-</span>",FORMAT(s4_maya,"#,##0")) & "</td><td class='ac'>" & IF(s4_mayn=0,"<span class='zero'>-</span>",FORMAT(s4_mayn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s4_juna=0,"<span class='zero'>-</span>",FORMAT(s4_juna,"#,##0")) & "</td><td class='ac'>" & IF(s4_junn=0,"<span class='zero'>-</span>",FORMAT(s4_junn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s4_jula=0,"<span class='zero'>-</span>",FORMAT(s4_jula,"#,##0")) & "</td><td class='ac'>" & IF(s4_juln=0,"<span class='zero'>-</span>",FORMAT(s4_juln,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s4_auga=0,"<span class='zero'>-</span>",FORMAT(s4_auga,"#,##0")) & "</td><td class='ac'>" & IF(s4_augn=0,"<span class='zero'>-</span>",FORMAT(s4_augn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s4_sepa=0,"<span class='zero'>-</span>",FORMAT(s4_sepa,"#,##0")) & "</td><td class='ac'>" & IF(s4_sepn=0,"<span class='zero'>-</span>",FORMAT(s4_sepn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s4_octa=0,"<span class='zero'>-</span>",FORMAT(s4_octa,"#,##0")) & "</td><td class='ac'>" & IF(s4_octn=0,"<span class='zero'>-</span>",FORMAT(s4_octn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s4_nova=0,"<span class='zero'>-</span>",FORMAT(s4_nova,"#,##0")) & "</td><td class='ac'>" & IF(s4_novn=0,"<span class='zero'>-</span>",FORMAT(s4_novn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s4_deca=0,"<span class='zero'>-</span>",FORMAT(s4_deca,"#,##0")) & "</td><td class='ac'>" & IF(s4_decn=0,"<span class='zero'>-</span>",FORMAT(s4_decn,"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF(s4_tota=0,"<span class='zero'>-</span>",FORMAT(s4_tota,"#,##0")) & "</td><td class='ac fw'>" & IF(s4_totn=0,"<span class='zero'>-</span>",FORMAT(s4_totn,"#,##0")) & "</td>" & "</tr>"
VAR BH5 = "<tr class='bh'><td class='no'>5</td><td colspan='29'>OECUSSE</td></tr>"
VAR PR5 = CONCATENATEX( FILTER(tbl,[Branch]="OECUSSE"&&NOT ISBLANK([Credit_Product_No])), "<tr class='pr'><td class='no'>" & [Credit_Product_No] & "</td><td class='br'></td><td class='pn'>" & [Credit_Product_No] & "</td><td class='nm'>" & [Credit_Product] & "</td>" & "<td class='ar bl'>" & IF([amount_jan]=0,"<span class='zero'>-</span>",FORMAT([amount_jan],"#,##0")) & "</td><td class='ac'>" & IF([acct_jan]=0,"<span class='zero'>-</span>",FORMAT([acct_jan],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_feb]=0,"<span class='zero'>-</span>",FORMAT([amount_feb],"#,##0")) & "</td><td class='ac'>" & IF([acct_feb]=0,"<span class='zero'>-</span>",FORMAT([acct_feb],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_mar]=0,"<span class='zero'>-</span>",FORMAT([amount_mar],"#,##0")) & "</td><td class='ac'>" & IF([acct_mar]=0,"<span class='zero'>-</span>",FORMAT([acct_mar],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_apr]=0,"<span class='zero'>-</span>",FORMAT([amount_apr],"#,##0")) & "</td><td class='ac'>" & IF([acct_apr]=0,"<span class='zero'>-</span>",FORMAT([acct_apr],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_may]=0,"<span class='zero'>-</span>",FORMAT([amount_may],"#,##0")) & "</td><td class='ac'>" & IF([acct_may]=0,"<span class='zero'>-</span>",FORMAT([acct_may],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jun]=0,"<span class='zero'>-</span>",FORMAT([amount_jun],"#,##0")) & "</td><td class='ac'>" & IF([acct_jun]=0,"<span class='zero'>-</span>",FORMAT([acct_jun],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jul]=0,"<span class='zero'>-</span>",FORMAT([amount_jul],"#,##0")) & "</td><td class='ac'>" & IF([acct_jul]=0,"<span class='zero'>-</span>",FORMAT([acct_jul],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_aug]=0,"<span class='zero'>-</span>",FORMAT([amount_aug],"#,##0")) & "</td><td class='ac'>" & IF([acct_aug]=0,"<span class='zero'>-</span>",FORMAT([acct_aug],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_sep]=0,"<span class='zero'>-</span>",FORMAT([amount_sep],"#,##0")) & "</td><td class='ac'>" & IF([acct_sep]=0,"<span class='zero'>-</span>",FORMAT([acct_sep],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_oct]=0,"<span class='zero'>-</span>",FORMAT([amount_oct],"#,##0")) & "</td><td class='ac'>" & IF([acct_oct]=0,"<span class='zero'>-</span>",FORMAT([acct_oct],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_nov]=0,"<span class='zero'>-</span>",FORMAT([amount_nov],"#,##0")) & "</td><td class='ac'>" & IF([acct_nov]=0,"<span class='zero'>-</span>",FORMAT([acct_nov],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_dec]=0,"<span class='zero'>-</span>",FORMAT([amount_dec],"#,##0")) & "</td><td class='ac'>" & IF([acct_dec]=0,"<span class='zero'>-</span>",FORMAT([acct_dec],"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF([amount_total]=0,"<span class='zero'>-</span>",FORMAT([amount_total],"#,##0")) & "</td><td class='ac fw'>" & IF([account_total]=0,"<span class='zero'>-</span>",FORMAT([account_total],"#,##0")) & "</td>" & "</tr>", , VALUE([Credit_Product_No]), ASC )
VAR ST5 = "<tr class='st'><td></td><td class='br'></td><td></td><td style='font-weight:700;'>TOTAL</td>" & "<td class='ar bl'>" & IF(s5_jana=0,"<span class='zero'>-</span>",FORMAT(s5_jana,"#,##0")) & "</td><td class='ac'>" & IF(s5_jann=0,"<span class='zero'>-</span>",FORMAT(s5_jann,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s5_feba=0,"<span class='zero'>-</span>",FORMAT(s5_feba,"#,##0")) & "</td><td class='ac'>" & IF(s5_febn=0,"<span class='zero'>-</span>",FORMAT(s5_febn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s5_mara=0,"<span class='zero'>-</span>",FORMAT(s5_mara,"#,##0")) & "</td><td class='ac'>" & IF(s5_marn=0,"<span class='zero'>-</span>",FORMAT(s5_marn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s5_apra=0,"<span class='zero'>-</span>",FORMAT(s5_apra,"#,##0")) & "</td><td class='ac'>" & IF(s5_aprn=0,"<span class='zero'>-</span>",FORMAT(s5_aprn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s5_maya=0,"<span class='zero'>-</span>",FORMAT(s5_maya,"#,##0")) & "</td><td class='ac'>" & IF(s5_mayn=0,"<span class='zero'>-</span>",FORMAT(s5_mayn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s5_juna=0,"<span class='zero'>-</span>",FORMAT(s5_juna,"#,##0")) & "</td><td class='ac'>" & IF(s5_junn=0,"<span class='zero'>-</span>",FORMAT(s5_junn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s5_jula=0,"<span class='zero'>-</span>",FORMAT(s5_jula,"#,##0")) & "</td><td class='ac'>" & IF(s5_juln=0,"<span class='zero'>-</span>",FORMAT(s5_juln,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s5_auga=0,"<span class='zero'>-</span>",FORMAT(s5_auga,"#,##0")) & "</td><td class='ac'>" & IF(s5_augn=0,"<span class='zero'>-</span>",FORMAT(s5_augn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s5_sepa=0,"<span class='zero'>-</span>",FORMAT(s5_sepa,"#,##0")) & "</td><td class='ac'>" & IF(s5_sepn=0,"<span class='zero'>-</span>",FORMAT(s5_sepn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s5_octa=0,"<span class='zero'>-</span>",FORMAT(s5_octa,"#,##0")) & "</td><td class='ac'>" & IF(s5_octn=0,"<span class='zero'>-</span>",FORMAT(s5_octn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s5_nova=0,"<span class='zero'>-</span>",FORMAT(s5_nova,"#,##0")) & "</td><td class='ac'>" & IF(s5_novn=0,"<span class='zero'>-</span>",FORMAT(s5_novn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s5_deca=0,"<span class='zero'>-</span>",FORMAT(s5_deca,"#,##0")) & "</td><td class='ac'>" & IF(s5_decn=0,"<span class='zero'>-</span>",FORMAT(s5_decn,"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF(s5_tota=0,"<span class='zero'>-</span>",FORMAT(s5_tota,"#,##0")) & "</td><td class='ac fw'>" & IF(s5_totn=0,"<span class='zero'>-</span>",FORMAT(s5_totn,"#,##0")) & "</td>" & "</tr>"
VAR BH6 = "<tr class='bh'><td class='no'>6</td><td colspan='29'>BAUCAU</td></tr>"
VAR PR6 = CONCATENATEX( FILTER(tbl,[Branch]="BAUCAU"&&NOT ISBLANK([Credit_Product_No])), "<tr class='pr'><td class='no'>" & [Credit_Product_No] & "</td><td class='br'></td><td class='pn'>" & [Credit_Product_No] & "</td><td class='nm'>" & [Credit_Product] & "</td>" & "<td class='ar bl'>" & IF([amount_jan]=0,"<span class='zero'>-</span>",FORMAT([amount_jan],"#,##0")) & "</td><td class='ac'>" & IF([acct_jan]=0,"<span class='zero'>-</span>",FORMAT([acct_jan],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_feb]=0,"<span class='zero'>-</span>",FORMAT([amount_feb],"#,##0")) & "</td><td class='ac'>" & IF([acct_feb]=0,"<span class='zero'>-</span>",FORMAT([acct_feb],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_mar]=0,"<span class='zero'>-</span>",FORMAT([amount_mar],"#,##0")) & "</td><td class='ac'>" & IF([acct_mar]=0,"<span class='zero'>-</span>",FORMAT([acct_mar],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_apr]=0,"<span class='zero'>-</span>",FORMAT([amount_apr],"#,##0")) & "</td><td class='ac'>" & IF([acct_apr]=0,"<span class='zero'>-</span>",FORMAT([acct_apr],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_may]=0,"<span class='zero'>-</span>",FORMAT([amount_may],"#,##0")) & "</td><td class='ac'>" & IF([acct_may]=0,"<span class='zero'>-</span>",FORMAT([acct_may],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jun]=0,"<span class='zero'>-</span>",FORMAT([amount_jun],"#,##0")) & "</td><td class='ac'>" & IF([acct_jun]=0,"<span class='zero'>-</span>",FORMAT([acct_jun],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jul]=0,"<span class='zero'>-</span>",FORMAT([amount_jul],"#,##0")) & "</td><td class='ac'>" & IF([acct_jul]=0,"<span class='zero'>-</span>",FORMAT([acct_jul],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_aug]=0,"<span class='zero'>-</span>",FORMAT([amount_aug],"#,##0")) & "</td><td class='ac'>" & IF([acct_aug]=0,"<span class='zero'>-</span>",FORMAT([acct_aug],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_sep]=0,"<span class='zero'>-</span>",FORMAT([amount_sep],"#,##0")) & "</td><td class='ac'>" & IF([acct_sep]=0,"<span class='zero'>-</span>",FORMAT([acct_sep],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_oct]=0,"<span class='zero'>-</span>",FORMAT([amount_oct],"#,##0")) & "</td><td class='ac'>" & IF([acct_oct]=0,"<span class='zero'>-</span>",FORMAT([acct_oct],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_nov]=0,"<span class='zero'>-</span>",FORMAT([amount_nov],"#,##0")) & "</td><td class='ac'>" & IF([acct_nov]=0,"<span class='zero'>-</span>",FORMAT([acct_nov],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_dec]=0,"<span class='zero'>-</span>",FORMAT([amount_dec],"#,##0")) & "</td><td class='ac'>" & IF([acct_dec]=0,"<span class='zero'>-</span>",FORMAT([acct_dec],"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF([amount_total]=0,"<span class='zero'>-</span>",FORMAT([amount_total],"#,##0")) & "</td><td class='ac fw'>" & IF([account_total]=0,"<span class='zero'>-</span>",FORMAT([account_total],"#,##0")) & "</td>" & "</tr>", , VALUE([Credit_Product_No]), ASC )
VAR ST6 = "<tr class='st'><td></td><td class='br'></td><td></td><td style='font-weight:700;'>TOTAL</td>" & "<td class='ar bl'>" & IF(s6_jana=0,"<span class='zero'>-</span>",FORMAT(s6_jana,"#,##0")) & "</td><td class='ac'>" & IF(s6_jann=0,"<span class='zero'>-</span>",FORMAT(s6_jann,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s6_feba=0,"<span class='zero'>-</span>",FORMAT(s6_feba,"#,##0")) & "</td><td class='ac'>" & IF(s6_febn=0,"<span class='zero'>-</span>",FORMAT(s6_febn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s6_mara=0,"<span class='zero'>-</span>",FORMAT(s6_mara,"#,##0")) & "</td><td class='ac'>" & IF(s6_marn=0,"<span class='zero'>-</span>",FORMAT(s6_marn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s6_apra=0,"<span class='zero'>-</span>",FORMAT(s6_apra,"#,##0")) & "</td><td class='ac'>" & IF(s6_aprn=0,"<span class='zero'>-</span>",FORMAT(s6_aprn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s6_maya=0,"<span class='zero'>-</span>",FORMAT(s6_maya,"#,##0")) & "</td><td class='ac'>" & IF(s6_mayn=0,"<span class='zero'>-</span>",FORMAT(s6_mayn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s6_juna=0,"<span class='zero'>-</span>",FORMAT(s6_juna,"#,##0")) & "</td><td class='ac'>" & IF(s6_junn=0,"<span class='zero'>-</span>",FORMAT(s6_junn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s6_jula=0,"<span class='zero'>-</span>",FORMAT(s6_jula,"#,##0")) & "</td><td class='ac'>" & IF(s6_juln=0,"<span class='zero'>-</span>",FORMAT(s6_juln,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s6_auga=0,"<span class='zero'>-</span>",FORMAT(s6_auga,"#,##0")) & "</td><td class='ac'>" & IF(s6_augn=0,"<span class='zero'>-</span>",FORMAT(s6_augn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s6_sepa=0,"<span class='zero'>-</span>",FORMAT(s6_sepa,"#,##0")) & "</td><td class='ac'>" & IF(s6_sepn=0,"<span class='zero'>-</span>",FORMAT(s6_sepn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s6_octa=0,"<span class='zero'>-</span>",FORMAT(s6_octa,"#,##0")) & "</td><td class='ac'>" & IF(s6_octn=0,"<span class='zero'>-</span>",FORMAT(s6_octn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s6_nova=0,"<span class='zero'>-</span>",FORMAT(s6_nova,"#,##0")) & "</td><td class='ac'>" & IF(s6_novn=0,"<span class='zero'>-</span>",FORMAT(s6_novn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s6_deca=0,"<span class='zero'>-</span>",FORMAT(s6_deca,"#,##0")) & "</td><td class='ac'>" & IF(s6_decn=0,"<span class='zero'>-</span>",FORMAT(s6_decn,"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF(s6_tota=0,"<span class='zero'>-</span>",FORMAT(s6_tota,"#,##0")) & "</td><td class='ac fw'>" & IF(s6_totn=0,"<span class='zero'>-</span>",FORMAT(s6_totn,"#,##0")) & "</td>" & "</tr>"
VAR BH7 = "<tr class='bh'><td class='no'>7</td><td colspan='29'>SAME</td></tr>"
VAR PR7 = CONCATENATEX( FILTER(tbl,[Branch]="SAME"&&NOT ISBLANK([Credit_Product_No])), "<tr class='pr'><td class='no'>" & [Credit_Product_No] & "</td><td class='br'></td><td class='pn'>" & [Credit_Product_No] & "</td><td class='nm'>" & [Credit_Product] & "</td>" & "<td class='ar bl'>" & IF([amount_jan]=0,"<span class='zero'>-</span>",FORMAT([amount_jan],"#,##0")) & "</td><td class='ac'>" & IF([acct_jan]=0,"<span class='zero'>-</span>",FORMAT([acct_jan],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_feb]=0,"<span class='zero'>-</span>",FORMAT([amount_feb],"#,##0")) & "</td><td class='ac'>" & IF([acct_feb]=0,"<span class='zero'>-</span>",FORMAT([acct_feb],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_mar]=0,"<span class='zero'>-</span>",FORMAT([amount_mar],"#,##0")) & "</td><td class='ac'>" & IF([acct_mar]=0,"<span class='zero'>-</span>",FORMAT([acct_mar],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_apr]=0,"<span class='zero'>-</span>",FORMAT([amount_apr],"#,##0")) & "</td><td class='ac'>" & IF([acct_apr]=0,"<span class='zero'>-</span>",FORMAT([acct_apr],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_may]=0,"<span class='zero'>-</span>",FORMAT([amount_may],"#,##0")) & "</td><td class='ac'>" & IF([acct_may]=0,"<span class='zero'>-</span>",FORMAT([acct_may],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jun]=0,"<span class='zero'>-</span>",FORMAT([amount_jun],"#,##0")) & "</td><td class='ac'>" & IF([acct_jun]=0,"<span class='zero'>-</span>",FORMAT([acct_jun],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jul]=0,"<span class='zero'>-</span>",FORMAT([amount_jul],"#,##0")) & "</td><td class='ac'>" & IF([acct_jul]=0,"<span class='zero'>-</span>",FORMAT([acct_jul],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_aug]=0,"<span class='zero'>-</span>",FORMAT([amount_aug],"#,##0")) & "</td><td class='ac'>" & IF([acct_aug]=0,"<span class='zero'>-</span>",FORMAT([acct_aug],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_sep]=0,"<span class='zero'>-</span>",FORMAT([amount_sep],"#,##0")) & "</td><td class='ac'>" & IF([acct_sep]=0,"<span class='zero'>-</span>",FORMAT([acct_sep],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_oct]=0,"<span class='zero'>-</span>",FORMAT([amount_oct],"#,##0")) & "</td><td class='ac'>" & IF([acct_oct]=0,"<span class='zero'>-</span>",FORMAT([acct_oct],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_nov]=0,"<span class='zero'>-</span>",FORMAT([amount_nov],"#,##0")) & "</td><td class='ac'>" & IF([acct_nov]=0,"<span class='zero'>-</span>",FORMAT([acct_nov],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_dec]=0,"<span class='zero'>-</span>",FORMAT([amount_dec],"#,##0")) & "</td><td class='ac'>" & IF([acct_dec]=0,"<span class='zero'>-</span>",FORMAT([acct_dec],"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF([amount_total]=0,"<span class='zero'>-</span>",FORMAT([amount_total],"#,##0")) & "</td><td class='ac fw'>" & IF([account_total]=0,"<span class='zero'>-</span>",FORMAT([account_total],"#,##0")) & "</td>" & "</tr>", , VALUE([Credit_Product_No]), ASC )
VAR ST7 = "<tr class='st'><td></td><td class='br'></td><td></td><td style='font-weight:700;'>TOTAL</td>" & "<td class='ar bl'>" & IF(s7_jana=0,"<span class='zero'>-</span>",FORMAT(s7_jana,"#,##0")) & "</td><td class='ac'>" & IF(s7_jann=0,"<span class='zero'>-</span>",FORMAT(s7_jann,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s7_feba=0,"<span class='zero'>-</span>",FORMAT(s7_feba,"#,##0")) & "</td><td class='ac'>" & IF(s7_febn=0,"<span class='zero'>-</span>",FORMAT(s7_febn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s7_mara=0,"<span class='zero'>-</span>",FORMAT(s7_mara,"#,##0")) & "</td><td class='ac'>" & IF(s7_marn=0,"<span class='zero'>-</span>",FORMAT(s7_marn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s7_apra=0,"<span class='zero'>-</span>",FORMAT(s7_apra,"#,##0")) & "</td><td class='ac'>" & IF(s7_aprn=0,"<span class='zero'>-</span>",FORMAT(s7_aprn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s7_maya=0,"<span class='zero'>-</span>",FORMAT(s7_maya,"#,##0")) & "</td><td class='ac'>" & IF(s7_mayn=0,"<span class='zero'>-</span>",FORMAT(s7_mayn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s7_juna=0,"<span class='zero'>-</span>",FORMAT(s7_juna,"#,##0")) & "</td><td class='ac'>" & IF(s7_junn=0,"<span class='zero'>-</span>",FORMAT(s7_junn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s7_jula=0,"<span class='zero'>-</span>",FORMAT(s7_jula,"#,##0")) & "</td><td class='ac'>" & IF(s7_juln=0,"<span class='zero'>-</span>",FORMAT(s7_juln,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s7_auga=0,"<span class='zero'>-</span>",FORMAT(s7_auga,"#,##0")) & "</td><td class='ac'>" & IF(s7_augn=0,"<span class='zero'>-</span>",FORMAT(s7_augn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s7_sepa=0,"<span class='zero'>-</span>",FORMAT(s7_sepa,"#,##0")) & "</td><td class='ac'>" & IF(s7_sepn=0,"<span class='zero'>-</span>",FORMAT(s7_sepn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s7_octa=0,"<span class='zero'>-</span>",FORMAT(s7_octa,"#,##0")) & "</td><td class='ac'>" & IF(s7_octn=0,"<span class='zero'>-</span>",FORMAT(s7_octn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s7_nova=0,"<span class='zero'>-</span>",FORMAT(s7_nova,"#,##0")) & "</td><td class='ac'>" & IF(s7_novn=0,"<span class='zero'>-</span>",FORMAT(s7_novn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s7_deca=0,"<span class='zero'>-</span>",FORMAT(s7_deca,"#,##0")) & "</td><td class='ac'>" & IF(s7_decn=0,"<span class='zero'>-</span>",FORMAT(s7_decn,"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF(s7_tota=0,"<span class='zero'>-</span>",FORMAT(s7_tota,"#,##0")) & "</td><td class='ac fw'>" & IF(s7_totn=0,"<span class='zero'>-</span>",FORMAT(s7_totn,"#,##0")) & "</td>" & "</tr>"

VAR BH8 = "<tr class='bh'><td class='no'>8</td><td colspan='29'>AINARO</td></tr>"
VAR PR8 = CONCATENATEX( FILTER(tbl,[Branch]="AINARO"&&NOT ISBLANK([Credit_Product_No])), "<tr class='pr'><td class='no'>" & [Credit_Product_No] & "</td><td class='br'></td><td class='pn'>" & [Credit_Product_No] & "</td><td class='nm'>" & [Credit_Product] & "</td>" & "<td class='ar bl'>" & IF([amount_jan]=0,"<span class='zero'>-</span>",FORMAT([amount_jan],"#,##0")) & "</td><td class='ac'>" & IF([acct_jan]=0,"<span class='zero'>-</span>",FORMAT([acct_jan],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_feb]=0,"<span class='zero'>-</span>",FORMAT([amount_feb],"#,##0")) & "</td><td class='ac'>" & IF([acct_feb]=0,"<span class='zero'>-</span>",FORMAT([acct_feb],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_mar]=0,"<span class='zero'>-</span>",FORMAT([amount_mar],"#,##0")) & "</td><td class='ac'>" & IF([acct_mar]=0,"<span class='zero'>-</span>",FORMAT([acct_mar],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_apr]=0,"<span class='zero'>-</span>",FORMAT([amount_apr],"#,##0")) & "</td><td class='ac'>" & IF([acct_apr]=0,"<span class='zero'>-</span>",FORMAT([acct_apr],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_may]=0,"<span class='zero'>-</span>",FORMAT([amount_may],"#,##0")) & "</td><td class='ac'>" & IF([acct_may]=0,"<span class='zero'>-</span>",FORMAT([acct_may],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jun]=0,"<span class='zero'>-</span>",FORMAT([amount_jun],"#,##0")) & "</td><td class='ac'>" & IF([acct_jun]=0,"<span class='zero'>-</span>",FORMAT([acct_jun],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jul]=0,"<span class='zero'>-</span>",FORMAT([amount_jul],"#,##0")) & "</td><td class='ac'>" & IF([acct_jul]=0,"<span class='zero'>-</span>",FORMAT([acct_jul],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_aug]=0,"<span class='zero'>-</span>",FORMAT([amount_aug],"#,##0")) & "</td><td class='ac'>" & IF([acct_aug]=0,"<span class='zero'>-</span>",FORMAT([acct_aug],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_sep]=0,"<span class='zero'>-</span>",FORMAT([amount_sep],"#,##0")) & "</td><td class='ac'>" & IF([acct_sep]=0,"<span class='zero'>-</span>",FORMAT([acct_sep],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_oct]=0,"<span class='zero'>-</span>",FORMAT([amount_oct],"#,##0")) & "</td><td class='ac'>" & IF([acct_oct]=0,"<span class='zero'>-</span>",FORMAT([acct_oct],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_nov]=0,"<span class='zero'>-</span>",FORMAT([amount_nov],"#,##0")) & "</td><td class='ac'>" & IF([acct_nov]=0,"<span class='zero'>-</span>",FORMAT([acct_nov],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_dec]=0,"<span class='zero'>-</span>",FORMAT([amount_dec],"#,##0")) & "</td><td class='ac'>" & IF([acct_dec]=0,"<span class='zero'>-</span>",FORMAT([acct_dec],"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF([amount_total]=0,"<span class='zero'>-</span>",FORMAT([amount_total],"#,##0")) & "</td><td class='ac fw'>" & IF([account_total]=0,"<span class='zero'>-</span>",FORMAT([account_total],"#,##0")) & "</td>" & "</tr>", , VALUE([Credit_Product_No]), ASC )
VAR ST8 = "<tr class='st'><td></td><td class='br'></td><td></td><td style='font-weight:700;'>TOTAL</td>" & "<td class='ar bl'>" & IF(s8_jana=0,"<span class='zero'>-</span>",FORMAT(s8_jana,"#,##0")) & "</td><td class='ac'>" & IF(s8_jann=0,"<span class='zero'>-</span>",FORMAT(s8_jann,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s8_feba=0,"<span class='zero'>-</span>",FORMAT(s8_feba,"#,##0")) & "</td><td class='ac'>" & IF(s8_febn=0,"<span class='zero'>-</span>",FORMAT(s8_febn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s8_mara=0,"<span class='zero'>-</span>",FORMAT(s8_mara,"#,##0")) & "</td><td class='ac'>" & IF(s8_marn=0,"<span class='zero'>-</span>",FORMAT(s8_marn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s8_apra=0,"<span class='zero'>-</span>",FORMAT(s8_apra,"#,##0")) & "</td><td class='ac'>" & IF(s8_aprn=0,"<span class='zero'>-</span>",FORMAT(s8_aprn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s8_maya=0,"<span class='zero'>-</span>",FORMAT(s8_maya,"#,##0")) & "</td><td class='ac'>" & IF(s8_mayn=0,"<span class='zero'>-</span>",FORMAT(s8_mayn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s8_juna=0,"<span class='zero'>-</span>",FORMAT(s8_juna,"#,##0")) & "</td><td class='ac'>" & IF(s8_junn=0,"<span class='zero'>-</span>",FORMAT(s8_junn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s8_jula=0,"<span class='zero'>-</span>",FORMAT(s8_jula,"#,##0")) & "</td><td class='ac'>" & IF(s8_juln=0,"<span class='zero'>-</span>",FORMAT(s8_juln,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s8_auga=0,"<span class='zero'>-</span>",FORMAT(s8_auga,"#,##0")) & "</td><td class='ac'>" & IF(s8_augn=0,"<span class='zero'>-</span>",FORMAT(s8_augn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s8_sepa=0,"<span class='zero'>-</span>",FORMAT(s8_sepa,"#,##0")) & "</td><td class='ac'>" & IF(s8_sepn=0,"<span class='zero'>-</span>",FORMAT(s8_sepn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s8_octa=0,"<span class='zero'>-</span>",FORMAT(s8_octa,"#,##0")) & "</td><td class='ac'>" & IF(s8_octn=0,"<span class='zero'>-</span>",FORMAT(s8_octn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s8_nova=0,"<span class='zero'>-</span>",FORMAT(s8_nova,"#,##0")) & "</td><td class='ac'>" & IF(s8_novn=0,"<span class='zero'>-</span>",FORMAT(s8_novn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s8_deca=0,"<span class='zero'>-</span>",FORMAT(s8_deca,"#,##0")) & "</td><td class='ac'>" & IF(s8_decn=0,"<span class='zero'>-</span>",FORMAT(s8_decn,"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF(s8_tota=0,"<span class='zero'>-</span>",FORMAT(s8_tota,"#,##0")) & "</td><td class='ac fw'>" & IF(s8_totn=0,"<span class='zero'>-</span>",FORMAT(s8_totn,"#,##0")) & "</td>" & "</tr>"
VAR BH9 = "<tr class='bh'><td class='no'>9</td><td colspan='29'>SUAI</td></tr>"
VAR PR9 = CONCATENATEX( FILTER(tbl,[Branch]="SUAI"&&NOT ISBLANK([Credit_Product_No])), "<tr class='pr'><td class='no'>" & [Credit_Product_No] & "</td><td class='br'></td><td class='pn'>" & [Credit_Product_No] & "</td><td class='nm'>" & [Credit_Product] & "</td>" & "<td class='ar bl'>" & IF([amount_jan]=0,"<span class='zero'>-</span>",FORMAT([amount_jan],"#,##0")) & "</td><td class='ac'>" & IF([acct_jan]=0,"<span class='zero'>-</span>",FORMAT([acct_jan],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_feb]=0,"<span class='zero'>-</span>",FORMAT([amount_feb],"#,##0")) & "</td><td class='ac'>" & IF([acct_feb]=0,"<span class='zero'>-</span>",FORMAT([acct_feb],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_mar]=0,"<span class='zero'>-</span>",FORMAT([amount_mar],"#,##0")) & "</td><td class='ac'>" & IF([acct_mar]=0,"<span class='zero'>-</span>",FORMAT([acct_mar],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_apr]=0,"<span class='zero'>-</span>",FORMAT([amount_apr],"#,##0")) & "</td><td class='ac'>" & IF([acct_apr]=0,"<span class='zero'>-</span>",FORMAT([acct_apr],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_may]=0,"<span class='zero'>-</span>",FORMAT([amount_may],"#,##0")) & "</td><td class='ac'>" & IF([acct_may]=0,"<span class='zero'>-</span>",FORMAT([acct_may],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jun]=0,"<span class='zero'>-</span>",FORMAT([amount_jun],"#,##0")) & "</td><td class='ac'>" & IF([acct_jun]=0,"<span class='zero'>-</span>",FORMAT([acct_jun],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jul]=0,"<span class='zero'>-</span>",FORMAT([amount_jul],"#,##0")) & "</td><td class='ac'>" & IF([acct_jul]=0,"<span class='zero'>-</span>",FORMAT([acct_jul],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_aug]=0,"<span class='zero'>-</span>",FORMAT([amount_aug],"#,##0")) & "</td><td class='ac'>" & IF([acct_aug]=0,"<span class='zero'>-</span>",FORMAT([acct_aug],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_sep]=0,"<span class='zero'>-</span>",FORMAT([amount_sep],"#,##0")) & "</td><td class='ac'>" & IF([acct_sep]=0,"<span class='zero'>-</span>",FORMAT([acct_sep],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_oct]=0,"<span class='zero'>-</span>",FORMAT([amount_oct],"#,##0")) & "</td><td class='ac'>" & IF([acct_oct]=0,"<span class='zero'>-</span>",FORMAT([acct_oct],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_nov]=0,"<span class='zero'>-</span>",FORMAT([amount_nov],"#,##0")) & "</td><td class='ac'>" & IF([acct_nov]=0,"<span class='zero'>-</span>",FORMAT([acct_nov],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_dec]=0,"<span class='zero'>-</span>",FORMAT([amount_dec],"#,##0")) & "</td><td class='ac'>" & IF([acct_dec]=0,"<span class='zero'>-</span>",FORMAT([acct_dec],"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF([amount_total]=0,"<span class='zero'>-</span>",FORMAT([amount_total],"#,##0")) & "</td><td class='ac fw'>" & IF([account_total]=0,"<span class='zero'>-</span>",FORMAT([account_total],"#,##0")) & "</td>" & "</tr>", , VALUE([Credit_Product_No]), ASC )
VAR ST9 = "<tr class='st'><td></td><td class='br'></td><td></td><td style='font-weight:700;'>TOTAL</td>" & "<td class='ar bl'>" & IF(s9_jana=0,"<span class='zero'>-</span>",FORMAT(s9_jana,"#,##0")) & "</td><td class='ac'>" & IF(s9_jann=0,"<span class='zero'>-</span>",FORMAT(s9_jann,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s9_feba=0,"<span class='zero'>-</span>",FORMAT(s9_feba,"#,##0")) & "</td><td class='ac'>" & IF(s9_febn=0,"<span class='zero'>-</span>",FORMAT(s9_febn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s9_mara=0,"<span class='zero'>-</span>",FORMAT(s9_mara,"#,##0")) & "</td><td class='ac'>" & IF(s9_marn=0,"<span class='zero'>-</span>",FORMAT(s9_marn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s9_apra=0,"<span class='zero'>-</span>",FORMAT(s9_apra,"#,##0")) & "</td><td class='ac'>" & IF(s9_aprn=0,"<span class='zero'>-</span>",FORMAT(s9_aprn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s9_maya=0,"<span class='zero'>-</span>",FORMAT(s9_maya,"#,##0")) & "</td><td class='ac'>" & IF(s9_mayn=0,"<span class='zero'>-</span>",FORMAT(s9_mayn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s9_juna=0,"<span class='zero'>-</span>",FORMAT(s9_juna,"#,##0")) & "</td><td class='ac'>" & IF(s9_junn=0,"<span class='zero'>-</span>",FORMAT(s9_junn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s9_jula=0,"<span class='zero'>-</span>",FORMAT(s9_jula,"#,##0")) & "</td><td class='ac'>" & IF(s9_juln=0,"<span class='zero'>-</span>",FORMAT(s9_juln,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s9_auga=0,"<span class='zero'>-</span>",FORMAT(s9_auga,"#,##0")) & "</td><td class='ac'>" & IF(s9_augn=0,"<span class='zero'>-</span>",FORMAT(s9_augn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s9_sepa=0,"<span class='zero'>-</span>",FORMAT(s9_sepa,"#,##0")) & "</td><td class='ac'>" & IF(s9_sepn=0,"<span class='zero'>-</span>",FORMAT(s9_sepn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s9_octa=0,"<span class='zero'>-</span>",FORMAT(s9_octa,"#,##0")) & "</td><td class='ac'>" & IF(s9_octn=0,"<span class='zero'>-</span>",FORMAT(s9_octn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s9_nova=0,"<span class='zero'>-</span>",FORMAT(s9_nova,"#,##0")) & "</td><td class='ac'>" & IF(s9_novn=0,"<span class='zero'>-</span>",FORMAT(s9_novn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s9_deca=0,"<span class='zero'>-</span>",FORMAT(s9_deca,"#,##0")) & "</td><td class='ac'>" & IF(s9_decn=0,"<span class='zero'>-</span>",FORMAT(s9_decn,"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF(s9_tota=0,"<span class='zero'>-</span>",FORMAT(s9_tota,"#,##0")) & "</td><td class='ac fw'>" & IF(s9_totn=0,"<span class='zero'>-</span>",FORMAT(s9_totn,"#,##0")) & "</td>" & "</tr>"
VAR BH10 = "<tr class='bh'><td class='no'>10</td><td colspan='29'>VIQUEQUE</td></tr>"
VAR PR10 = CONCATENATEX( FILTER(tbl,[Branch]="VIQUEQUE"&&NOT ISBLANK([Credit_Product_No])), "<tr class='pr'><td class='no'>" & [Credit_Product_No] & "</td><td class='br'></td><td class='pn'>" & [Credit_Product_No] & "</td><td class='nm'>" & [Credit_Product] & "</td>" & "<td class='ar bl'>" & IF([amount_jan]=0,"<span class='zero'>-</span>",FORMAT([amount_jan],"#,##0")) & "</td><td class='ac'>" & IF([acct_jan]=0,"<span class='zero'>-</span>",FORMAT([acct_jan],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_feb]=0,"<span class='zero'>-</span>",FORMAT([amount_feb],"#,##0")) & "</td><td class='ac'>" & IF([acct_feb]=0,"<span class='zero'>-</span>",FORMAT([acct_feb],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_mar]=0,"<span class='zero'>-</span>",FORMAT([amount_mar],"#,##0")) & "</td><td class='ac'>" & IF([acct_mar]=0,"<span class='zero'>-</span>",FORMAT([acct_mar],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_apr]=0,"<span class='zero'>-</span>",FORMAT([amount_apr],"#,##0")) & "</td><td class='ac'>" & IF([acct_apr]=0,"<span class='zero'>-</span>",FORMAT([acct_apr],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_may]=0,"<span class='zero'>-</span>",FORMAT([amount_may],"#,##0")) & "</td><td class='ac'>" & IF([acct_may]=0,"<span class='zero'>-</span>",FORMAT([acct_may],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jun]=0,"<span class='zero'>-</span>",FORMAT([amount_jun],"#,##0")) & "</td><td class='ac'>" & IF([acct_jun]=0,"<span class='zero'>-</span>",FORMAT([acct_jun],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jul]=0,"<span class='zero'>-</span>",FORMAT([amount_jul],"#,##0")) & "</td><td class='ac'>" & IF([acct_jul]=0,"<span class='zero'>-</span>",FORMAT([acct_jul],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_aug]=0,"<span class='zero'>-</span>",FORMAT([amount_aug],"#,##0")) & "</td><td class='ac'>" & IF([acct_aug]=0,"<span class='zero'>-</span>",FORMAT([acct_aug],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_sep]=0,"<span class='zero'>-</span>",FORMAT([amount_sep],"#,##0")) & "</td><td class='ac'>" & IF([acct_sep]=0,"<span class='zero'>-</span>",FORMAT([acct_sep],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_oct]=0,"<span class='zero'>-</span>",FORMAT([amount_oct],"#,##0")) & "</td><td class='ac'>" & IF([acct_oct]=0,"<span class='zero'>-</span>",FORMAT([acct_oct],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_nov]=0,"<span class='zero'>-</span>",FORMAT([amount_nov],"#,##0")) & "</td><td class='ac'>" & IF([acct_nov]=0,"<span class='zero'>-</span>",FORMAT([acct_nov],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_dec]=0,"<span class='zero'>-</span>",FORMAT([amount_dec],"#,##0")) & "</td><td class='ac'>" & IF([acct_dec]=0,"<span class='zero'>-</span>",FORMAT([acct_dec],"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF([amount_total]=0,"<span class='zero'>-</span>",FORMAT([amount_total],"#,##0")) & "</td><td class='ac fw'>" & IF([account_total]=0,"<span class='zero'>-</span>",FORMAT([account_total],"#,##0")) & "</td>" & "</tr>", , VALUE([Credit_Product_No]), ASC )
VAR ST10 = "<tr class='st'><td></td><td class='br'></td><td></td><td style='font-weight:700;'>TOTAL</td>" & "<td class='ar bl'>" & IF(s10_jana=0,"<span class='zero'>-</span>",FORMAT(s10_jana,"#,##0")) & "</td><td class='ac'>" & IF(s10_jann=0,"<span class='zero'>-</span>",FORMAT(s10_jann,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s10_feba=0,"<span class='zero'>-</span>",FORMAT(s10_feba,"#,##0")) & "</td><td class='ac'>" & IF(s10_febn=0,"<span class='zero'>-</span>",FORMAT(s10_febn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s10_mara=0,"<span class='zero'>-</span>",FORMAT(s10_mara,"#,##0")) & "</td><td class='ac'>" & IF(s10_marn=0,"<span class='zero'>-</span>",FORMAT(s10_marn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s10_apra=0,"<span class='zero'>-</span>",FORMAT(s10_apra,"#,##0")) & "</td><td class='ac'>" & IF(s10_aprn=0,"<span class='zero'>-</span>",FORMAT(s10_aprn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s10_maya=0,"<span class='zero'>-</span>",FORMAT(s10_maya,"#,##0")) & "</td><td class='ac'>" & IF(s10_mayn=0,"<span class='zero'>-</span>",FORMAT(s10_mayn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s10_juna=0,"<span class='zero'>-</span>",FORMAT(s10_juna,"#,##0")) & "</td><td class='ac'>" & IF(s10_junn=0,"<span class='zero'>-</span>",FORMAT(s10_junn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s10_jula=0,"<span class='zero'>-</span>",FORMAT(s10_jula,"#,##0")) & "</td><td class='ac'>" & IF(s10_juln=0,"<span class='zero'>-</span>",FORMAT(s10_juln,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s10_auga=0,"<span class='zero'>-</span>",FORMAT(s10_auga,"#,##0")) & "</td><td class='ac'>" & IF(s10_augn=0,"<span class='zero'>-</span>",FORMAT(s10_augn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s10_sepa=0,"<span class='zero'>-</span>",FORMAT(s10_sepa,"#,##0")) & "</td><td class='ac'>" & IF(s10_sepn=0,"<span class='zero'>-</span>",FORMAT(s10_sepn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s10_octa=0,"<span class='zero'>-</span>",FORMAT(s10_octa,"#,##0")) & "</td><td class='ac'>" & IF(s10_octn=0,"<span class='zero'>-</span>",FORMAT(s10_octn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s10_nova=0,"<span class='zero'>-</span>",FORMAT(s10_nova,"#,##0")) & "</td><td class='ac'>" & IF(s10_novn=0,"<span class='zero'>-</span>",FORMAT(s10_novn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s10_deca=0,"<span class='zero'>-</span>",FORMAT(s10_deca,"#,##0")) & "</td><td class='ac'>" & IF(s10_decn=0,"<span class='zero'>-</span>",FORMAT(s10_decn,"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF(s10_tota=0,"<span class='zero'>-</span>",FORMAT(s10_tota,"#,##0")) & "</td><td class='ac fw'>" & IF(s10_totn=0,"<span class='zero'>-</span>",FORMAT(s10_totn,"#,##0")) & "</td>" & "</tr>"
VAR BH11 = "<tr class='bh'><td class='no'>11</td><td colspan='29'>LOSPALOS</td></tr>"
VAR PR11 = CONCATENATEX( FILTER(tbl,[Branch]="LOSPALOS"&&NOT ISBLANK([Credit_Product_No])), "<tr class='pr'><td class='no'>" & [Credit_Product_No] & "</td><td class='br'></td><td class='pn'>" & [Credit_Product_No] & "</td><td class='nm'>" & [Credit_Product] & "</td>" & "<td class='ar bl'>" & IF([amount_jan]=0,"<span class='zero'>-</span>",FORMAT([amount_jan],"#,##0")) & "</td><td class='ac'>" & IF([acct_jan]=0,"<span class='zero'>-</span>",FORMAT([acct_jan],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_feb]=0,"<span class='zero'>-</span>",FORMAT([amount_feb],"#,##0")) & "</td><td class='ac'>" & IF([acct_feb]=0,"<span class='zero'>-</span>",FORMAT([acct_feb],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_mar]=0,"<span class='zero'>-</span>",FORMAT([amount_mar],"#,##0")) & "</td><td class='ac'>" & IF([acct_mar]=0,"<span class='zero'>-</span>",FORMAT([acct_mar],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_apr]=0,"<span class='zero'>-</span>",FORMAT([amount_apr],"#,##0")) & "</td><td class='ac'>" & IF([acct_apr]=0,"<span class='zero'>-</span>",FORMAT([acct_apr],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_may]=0,"<span class='zero'>-</span>",FORMAT([amount_may],"#,##0")) & "</td><td class='ac'>" & IF([acct_may]=0,"<span class='zero'>-</span>",FORMAT([acct_may],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jun]=0,"<span class='zero'>-</span>",FORMAT([amount_jun],"#,##0")) & "</td><td class='ac'>" & IF([acct_jun]=0,"<span class='zero'>-</span>",FORMAT([acct_jun],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jul]=0,"<span class='zero'>-</span>",FORMAT([amount_jul],"#,##0")) & "</td><td class='ac'>" & IF([acct_jul]=0,"<span class='zero'>-</span>",FORMAT([acct_jul],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_aug]=0,"<span class='zero'>-</span>",FORMAT([amount_aug],"#,##0")) & "</td><td class='ac'>" & IF([acct_aug]=0,"<span class='zero'>-</span>",FORMAT([acct_aug],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_sep]=0,"<span class='zero'>-</span>",FORMAT([amount_sep],"#,##0")) & "</td><td class='ac'>" & IF([acct_sep]=0,"<span class='zero'>-</span>",FORMAT([acct_sep],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_oct]=0,"<span class='zero'>-</span>",FORMAT([amount_oct],"#,##0")) & "</td><td class='ac'>" & IF([acct_oct]=0,"<span class='zero'>-</span>",FORMAT([acct_oct],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_nov]=0,"<span class='zero'>-</span>",FORMAT([amount_nov],"#,##0")) & "</td><td class='ac'>" & IF([acct_nov]=0,"<span class='zero'>-</span>",FORMAT([acct_nov],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_dec]=0,"<span class='zero'>-</span>",FORMAT([amount_dec],"#,##0")) & "</td><td class='ac'>" & IF([acct_dec]=0,"<span class='zero'>-</span>",FORMAT([acct_dec],"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF([amount_total]=0,"<span class='zero'>-</span>",FORMAT([amount_total],"#,##0")) & "</td><td class='ac fw'>" & IF([account_total]=0,"<span class='zero'>-</span>",FORMAT([account_total],"#,##0")) & "</td>" & "</tr>", , VALUE([Credit_Product_No]), ASC )
VAR ST11 = "<tr class='st'><td></td><td class='br'></td><td></td><td style='font-weight:700;'>TOTAL</td>" & "<td class='ar bl'>" & IF(s11_jana=0,"<span class='zero'>-</span>",FORMAT(s11_jana,"#,##0")) & "</td><td class='ac'>" & IF(s11_jann=0,"<span class='zero'>-</span>",FORMAT(s11_jann,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s11_feba=0,"<span class='zero'>-</span>",FORMAT(s11_feba,"#,##0")) & "</td><td class='ac'>" & IF(s11_febn=0,"<span class='zero'>-</span>",FORMAT(s11_febn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s11_mara=0,"<span class='zero'>-</span>",FORMAT(s11_mara,"#,##0")) & "</td><td class='ac'>" & IF(s11_marn=0,"<span class='zero'>-</span>",FORMAT(s11_marn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s11_apra=0,"<span class='zero'>-</span>",FORMAT(s11_apra,"#,##0")) & "</td><td class='ac'>" & IF(s11_aprn=0,"<span class='zero'>-</span>",FORMAT(s11_aprn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s11_maya=0,"<span class='zero'>-</span>",FORMAT(s11_maya,"#,##0")) & "</td><td class='ac'>" & IF(s11_mayn=0,"<span class='zero'>-</span>",FORMAT(s11_mayn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s11_juna=0,"<span class='zero'>-</span>",FORMAT(s11_juna,"#,##0")) & "</td><td class='ac'>" & IF(s11_junn=0,"<span class='zero'>-</span>",FORMAT(s11_junn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s11_jula=0,"<span class='zero'>-</span>",FORMAT(s11_jula,"#,##0")) & "</td><td class='ac'>" & IF(s11_juln=0,"<span class='zero'>-</span>",FORMAT(s11_juln,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s11_auga=0,"<span class='zero'>-</span>",FORMAT(s11_auga,"#,##0")) & "</td><td class='ac'>" & IF(s11_augn=0,"<span class='zero'>-</span>",FORMAT(s11_augn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s11_sepa=0,"<span class='zero'>-</span>",FORMAT(s11_sepa,"#,##0")) & "</td><td class='ac'>" & IF(s11_sepn=0,"<span class='zero'>-</span>",FORMAT(s11_sepn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s11_octa=0,"<span class='zero'>-</span>",FORMAT(s11_octa,"#,##0")) & "</td><td class='ac'>" & IF(s11_octn=0,"<span class='zero'>-</span>",FORMAT(s11_octn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s11_nova=0,"<span class='zero'>-</span>",FORMAT(s11_nova,"#,##0")) & "</td><td class='ac'>" & IF(s11_novn=0,"<span class='zero'>-</span>",FORMAT(s11_novn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s11_deca=0,"<span class='zero'>-</span>",FORMAT(s11_deca,"#,##0")) & "</td><td class='ac'>" & IF(s11_decn=0,"<span class='zero'>-</span>",FORMAT(s11_decn,"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF(s11_tota=0,"<span class='zero'>-</span>",FORMAT(s11_tota,"#,##0")) & "</td><td class='ac fw'>" & IF(s11_totn=0,"<span class='zero'>-</span>",FORMAT(s11_totn,"#,##0")) & "</td>" & "</tr>"
VAR BH12 = "<tr class='bh'><td class='no'>12</td><td colspan='29'>LIQUICA</td></tr>"
VAR PR12 = CONCATENATEX( FILTER(tbl,[Branch]="LIQUICA"&&NOT ISBLANK([Credit_Product_No])), "<tr class='pr'><td class='no'>" & [Credit_Product_No] & "</td><td class='br'></td><td class='pn'>" & [Credit_Product_No] & "</td><td class='nm'>" & [Credit_Product] & "</td>" & "<td class='ar bl'>" & IF([amount_jan]=0,"<span class='zero'>-</span>",FORMAT([amount_jan],"#,##0")) & "</td><td class='ac'>" & IF([acct_jan]=0,"<span class='zero'>-</span>",FORMAT([acct_jan],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_feb]=0,"<span class='zero'>-</span>",FORMAT([amount_feb],"#,##0")) & "</td><td class='ac'>" & IF([acct_feb]=0,"<span class='zero'>-</span>",FORMAT([acct_feb],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_mar]=0,"<span class='zero'>-</span>",FORMAT([amount_mar],"#,##0")) & "</td><td class='ac'>" & IF([acct_mar]=0,"<span class='zero'>-</span>",FORMAT([acct_mar],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_apr]=0,"<span class='zero'>-</span>",FORMAT([amount_apr],"#,##0")) & "</td><td class='ac'>" & IF([acct_apr]=0,"<span class='zero'>-</span>",FORMAT([acct_apr],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_may]=0,"<span class='zero'>-</span>",FORMAT([amount_may],"#,##0")) & "</td><td class='ac'>" & IF([acct_may]=0,"<span class='zero'>-</span>",FORMAT([acct_may],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jun]=0,"<span class='zero'>-</span>",FORMAT([amount_jun],"#,##0")) & "</td><td class='ac'>" & IF([acct_jun]=0,"<span class='zero'>-</span>",FORMAT([acct_jun],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jul]=0,"<span class='zero'>-</span>",FORMAT([amount_jul],"#,##0")) & "</td><td class='ac'>" & IF([acct_jul]=0,"<span class='zero'>-</span>",FORMAT([acct_jul],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_aug]=0,"<span class='zero'>-</span>",FORMAT([amount_aug],"#,##0")) & "</td><td class='ac'>" & IF([acct_aug]=0,"<span class='zero'>-</span>",FORMAT([acct_aug],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_sep]=0,"<span class='zero'>-</span>",FORMAT([amount_sep],"#,##0")) & "</td><td class='ac'>" & IF([acct_sep]=0,"<span class='zero'>-</span>",FORMAT([acct_sep],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_oct]=0,"<span class='zero'>-</span>",FORMAT([amount_oct],"#,##0")) & "</td><td class='ac'>" & IF([acct_oct]=0,"<span class='zero'>-</span>",FORMAT([acct_oct],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_nov]=0,"<span class='zero'>-</span>",FORMAT([amount_nov],"#,##0")) & "</td><td class='ac'>" & IF([acct_nov]=0,"<span class='zero'>-</span>",FORMAT([acct_nov],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_dec]=0,"<span class='zero'>-</span>",FORMAT([amount_dec],"#,##0")) & "</td><td class='ac'>" & IF([acct_dec]=0,"<span class='zero'>-</span>",FORMAT([acct_dec],"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF([amount_total]=0,"<span class='zero'>-</span>",FORMAT([amount_total],"#,##0")) & "</td><td class='ac fw'>" & IF([account_total]=0,"<span class='zero'>-</span>",FORMAT([account_total],"#,##0")) & "</td>" & "</tr>", , VALUE([Credit_Product_No]), ASC )
VAR ST12 = "<tr class='st'><td></td><td class='br'></td><td></td><td style='font-weight:700;'>TOTAL</td>" & "<td class='ar bl'>" & IF(s12_jana=0,"<span class='zero'>-</span>",FORMAT(s12_jana,"#,##0")) & "</td><td class='ac'>" & IF(s12_jann=0,"<span class='zero'>-</span>",FORMAT(s12_jann,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s12_feba=0,"<span class='zero'>-</span>",FORMAT(s12_feba,"#,##0")) & "</td><td class='ac'>" & IF(s12_febn=0,"<span class='zero'>-</span>",FORMAT(s12_febn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s12_mara=0,"<span class='zero'>-</span>",FORMAT(s12_mara,"#,##0")) & "</td><td class='ac'>" & IF(s12_marn=0,"<span class='zero'>-</span>",FORMAT(s12_marn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s12_apra=0,"<span class='zero'>-</span>",FORMAT(s12_apra,"#,##0")) & "</td><td class='ac'>" & IF(s12_aprn=0,"<span class='zero'>-</span>",FORMAT(s12_aprn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s12_maya=0,"<span class='zero'>-</span>",FORMAT(s12_maya,"#,##0")) & "</td><td class='ac'>" & IF(s12_mayn=0,"<span class='zero'>-</span>",FORMAT(s12_mayn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s12_juna=0,"<span class='zero'>-</span>",FORMAT(s12_juna,"#,##0")) & "</td><td class='ac'>" & IF(s12_junn=0,"<span class='zero'>-</span>",FORMAT(s12_junn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s12_jula=0,"<span class='zero'>-</span>",FORMAT(s12_jula,"#,##0")) & "</td><td class='ac'>" & IF(s12_juln=0,"<span class='zero'>-</span>",FORMAT(s12_juln,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s12_auga=0,"<span class='zero'>-</span>",FORMAT(s12_auga,"#,##0")) & "</td><td class='ac'>" & IF(s12_augn=0,"<span class='zero'>-</span>",FORMAT(s12_augn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s12_sepa=0,"<span class='zero'>-</span>",FORMAT(s12_sepa,"#,##0")) & "</td><td class='ac'>" & IF(s12_sepn=0,"<span class='zero'>-</span>",FORMAT(s12_sepn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s12_octa=0,"<span class='zero'>-</span>",FORMAT(s12_octa,"#,##0")) & "</td><td class='ac'>" & IF(s12_octn=0,"<span class='zero'>-</span>",FORMAT(s12_octn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s12_nova=0,"<span class='zero'>-</span>",FORMAT(s12_nova,"#,##0")) & "</td><td class='ac'>" & IF(s12_novn=0,"<span class='zero'>-</span>",FORMAT(s12_novn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s12_deca=0,"<span class='zero'>-</span>",FORMAT(s12_deca,"#,##0")) & "</td><td class='ac'>" & IF(s12_decn=0,"<span class='zero'>-</span>",FORMAT(s12_decn,"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF(s12_tota=0,"<span class='zero'>-</span>",FORMAT(s12_tota,"#,##0")) & "</td><td class='ac fw'>" & IF(s12_totn=0,"<span class='zero'>-</span>",FORMAT(s12_totn,"#,##0")) & "</td>" & "</tr>"
VAR BH13 = "<tr class='bh'><td class='no'>13</td><td colspan='29'>MANATUTO</td></tr>"
VAR PR13 = CONCATENATEX( FILTER(tbl,[Branch]="MANATUTO"&&NOT ISBLANK([Credit_Product_No])), "<tr class='pr'><td class='no'>" & [Credit_Product_No] & "</td><td class='br'></td><td class='pn'>" & [Credit_Product_No] & "</td><td class='nm'>" & [Credit_Product] & "</td>" & "<td class='ar bl'>" & IF([amount_jan]=0,"<span class='zero'>-</span>",FORMAT([amount_jan],"#,##0")) & "</td><td class='ac'>" & IF([acct_jan]=0,"<span class='zero'>-</span>",FORMAT([acct_jan],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_feb]=0,"<span class='zero'>-</span>",FORMAT([amount_feb],"#,##0")) & "</td><td class='ac'>" & IF([acct_feb]=0,"<span class='zero'>-</span>",FORMAT([acct_feb],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_mar]=0,"<span class='zero'>-</span>",FORMAT([amount_mar],"#,##0")) & "</td><td class='ac'>" & IF([acct_mar]=0,"<span class='zero'>-</span>",FORMAT([acct_mar],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_apr]=0,"<span class='zero'>-</span>",FORMAT([amount_apr],"#,##0")) & "</td><td class='ac'>" & IF([acct_apr]=0,"<span class='zero'>-</span>",FORMAT([acct_apr],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_may]=0,"<span class='zero'>-</span>",FORMAT([amount_may],"#,##0")) & "</td><td class='ac'>" & IF([acct_may]=0,"<span class='zero'>-</span>",FORMAT([acct_may],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jun]=0,"<span class='zero'>-</span>",FORMAT([amount_jun],"#,##0")) & "</td><td class='ac'>" & IF([acct_jun]=0,"<span class='zero'>-</span>",FORMAT([acct_jun],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_jul]=0,"<span class='zero'>-</span>",FORMAT([amount_jul],"#,##0")) & "</td><td class='ac'>" & IF([acct_jul]=0,"<span class='zero'>-</span>",FORMAT([acct_jul],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_aug]=0,"<span class='zero'>-</span>",FORMAT([amount_aug],"#,##0")) & "</td><td class='ac'>" & IF([acct_aug]=0,"<span class='zero'>-</span>",FORMAT([acct_aug],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_sep]=0,"<span class='zero'>-</span>",FORMAT([amount_sep],"#,##0")) & "</td><td class='ac'>" & IF([acct_sep]=0,"<span class='zero'>-</span>",FORMAT([acct_sep],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_oct]=0,"<span class='zero'>-</span>",FORMAT([amount_oct],"#,##0")) & "</td><td class='ac'>" & IF([acct_oct]=0,"<span class='zero'>-</span>",FORMAT([acct_oct],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_nov]=0,"<span class='zero'>-</span>",FORMAT([amount_nov],"#,##0")) & "</td><td class='ac'>" & IF([acct_nov]=0,"<span class='zero'>-</span>",FORMAT([acct_nov],"#,##0")) & "</td>" & "<td class='ar bl'>" & IF([amount_dec]=0,"<span class='zero'>-</span>",FORMAT([amount_dec],"#,##0")) & "</td><td class='ac'>" & IF([acct_dec]=0,"<span class='zero'>-</span>",FORMAT([acct_dec],"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF([amount_total]=0,"<span class='zero'>-</span>",FORMAT([amount_total],"#,##0")) & "</td><td class='ac fw'>" & IF([account_total]=0,"<span class='zero'>-</span>",FORMAT([account_total],"#,##0")) & "</td>" & "</tr>", , VALUE([Credit_Product_No]), ASC )
VAR ST13 = "<tr class='st'><td></td><td class='br'></td><td></td><td style='font-weight:700;'>TOTAL</td>" & "<td class='ar bl'>" & IF(s13_jana=0,"<span class='zero'>-</span>",FORMAT(s13_jana,"#,##0")) & "</td><td class='ac'>" & IF(s13_jann=0,"<span class='zero'>-</span>",FORMAT(s13_jann,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s13_feba=0,"<span class='zero'>-</span>",FORMAT(s13_feba,"#,##0")) & "</td><td class='ac'>" & IF(s13_febn=0,"<span class='zero'>-</span>",FORMAT(s13_febn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s13_mara=0,"<span class='zero'>-</span>",FORMAT(s13_mara,"#,##0")) & "</td><td class='ac'>" & IF(s13_marn=0,"<span class='zero'>-</span>",FORMAT(s13_marn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s13_apra=0,"<span class='zero'>-</span>",FORMAT(s13_apra,"#,##0")) & "</td><td class='ac'>" & IF(s13_aprn=0,"<span class='zero'>-</span>",FORMAT(s13_aprn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s13_maya=0,"<span class='zero'>-</span>",FORMAT(s13_maya,"#,##0")) & "</td><td class='ac'>" & IF(s13_mayn=0,"<span class='zero'>-</span>",FORMAT(s13_mayn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s13_juna=0,"<span class='zero'>-</span>",FORMAT(s13_juna,"#,##0")) & "</td><td class='ac'>" & IF(s13_junn=0,"<span class='zero'>-</span>",FORMAT(s13_junn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s13_jula=0,"<span class='zero'>-</span>",FORMAT(s13_jula,"#,##0")) & "</td><td class='ac'>" & IF(s13_juln=0,"<span class='zero'>-</span>",FORMAT(s13_juln,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s13_auga=0,"<span class='zero'>-</span>",FORMAT(s13_auga,"#,##0")) & "</td><td class='ac'>" & IF(s13_augn=0,"<span class='zero'>-</span>",FORMAT(s13_augn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s13_sepa=0,"<span class='zero'>-</span>",FORMAT(s13_sepa,"#,##0")) & "</td><td class='ac'>" & IF(s13_sepn=0,"<span class='zero'>-</span>",FORMAT(s13_sepn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s13_octa=0,"<span class='zero'>-</span>",FORMAT(s13_octa,"#,##0")) & "</td><td class='ac'>" & IF(s13_octn=0,"<span class='zero'>-</span>",FORMAT(s13_octn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s13_nova=0,"<span class='zero'>-</span>",FORMAT(s13_nova,"#,##0")) & "</td><td class='ac'>" & IF(s13_novn=0,"<span class='zero'>-</span>",FORMAT(s13_novn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(s13_deca=0,"<span class='zero'>-</span>",FORMAT(s13_deca,"#,##0")) & "</td><td class='ac'>" & IF(s13_decn=0,"<span class='zero'>-</span>",FORMAT(s13_decn,"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF(s13_tota=0,"<span class='zero'>-</span>",FORMAT(s13_tota,"#,##0")) & "</td><td class='ac fw'>" & IF(s13_totn=0,"<span class='zero'>-</span>",FORMAT(s13_totn,"#,##0")) & "</td>" & "</tr>"

VAR GT = "<tr class='gt'><td></td><td colspan='3' style='font-weight:800;'>GRAND TOTAL</td>" & "<td class='ar bl'>" & IF(GT_jana=0," - ",FORMAT(GT_jana,"#,##0")) & "</td><td class='ac'>" & IF(GT_jann=0," - ",FORMAT(GT_jann,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(GT_feba=0," - ",FORMAT(GT_feba,"#,##0")) & "</td><td class='ac'>" & IF(GT_febn=0," - ",FORMAT(GT_febn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(GT_mara=0," - ",FORMAT(GT_mara,"#,##0")) & "</td><td class='ac'>" & IF(GT_marn=0," - ",FORMAT(GT_marn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(GT_apra=0," - ",FORMAT(GT_apra,"#,##0")) & "</td><td class='ac'>" & IF(GT_aprn=0," - ",FORMAT(GT_aprn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(GT_maya=0," - ",FORMAT(GT_maya,"#,##0")) & "</td><td class='ac'>" & IF(GT_mayn=0," - ",FORMAT(GT_mayn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(GT_juna=0," - ",FORMAT(GT_juna,"#,##0")) & "</td><td class='ac'>" & IF(GT_junn=0," - ",FORMAT(GT_junn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(GT_jula=0," - ",FORMAT(GT_jula,"#,##0")) & "</td><td class='ac'>" & IF(GT_juln=0," - ",FORMAT(GT_juln,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(GT_auga=0," - ",FORMAT(GT_auga,"#,##0")) & "</td><td class='ac'>" & IF(GT_augn=0," - ",FORMAT(GT_augn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(GT_sepa=0," - ",FORMAT(GT_sepa,"#,##0")) & "</td><td class='ac'>" & IF(GT_sepn=0," - ",FORMAT(GT_sepn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(GT_octa=0," - ",FORMAT(GT_octa,"#,##0")) & "</td><td class='ac'>" & IF(GT_octn=0," - ",FORMAT(GT_octn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(GT_nova=0," - ",FORMAT(GT_nova,"#,##0")) & "</td><td class='ac'>" & IF(GT_novn=0," - ",FORMAT(GT_novn,"#,##0")) & "</td>" & "<td class='ar bl'>" & IF(GT_deca=0," - ",FORMAT(GT_deca,"#,##0")) & "</td><td class='ac'>" & IF(GT_decn=0," - ",FORMAT(GT_decn,"#,##0")) & "</td>" & "<td class='ar bl fw'>" & IF(GT_tota=0," - ",FORMAT(GT_tota,"#,##0")) & "</td><td class='ac fw'>" & IF(GT_totn=0," - ",FORMAT(GT_totn,"#,##0")) & "</td>" & "</tr>"
VAR Ftr = "<div style='background:#f8fafc;border-top:1px solid #e2e8f0;padding:6px 14px;font-size:10px;color:#9ca3af;'>Amt=Amount(USD) | Acct=Number of Accounts &mdash; BNCTL Confidential</div>"
VAR Sty = "<style>.ds{font-family:Segoe UI,Calibri,sans-serif;font-size:9.5px;color:#1e2d40;}.ds-t{width:100%;border-collapse:collapse;}.ds-t td{padding:3px 5px;border-bottom:1px solid #e8edf3;vertical-align:middle;white-space:nowrap;}.ds-t tr:hover td{background:#f5f8ff;}.th{background:#003366!important;color:#fff!important;font-weight:700;font-size:9px;text-transform:uppercase;border-bottom:3px solid #f0a500!important;padding:5px 5px!important;text-align:center;}.thl{text-align:left!important;}.mh{background:#1a4a7a!important;color:#fff!important;font-weight:700;font-size:8.5px;text-align:center;border-bottom:1px solid #f0a500!important;padding:3px 5px!important;}.bh td{background:#1a4a7a!important;color:#fff!important;font-weight:700;font-size:11px;border-bottom:2px solid #f0a500!important;padding:5px 10px!important;}.pr td{background:#f8fafc;}.st td{background:#e8f0fb!important;font-weight:700;color:#003366;border-top:1px solid #b8cce4!important;}.gt td{background:#003366!important;color:#fff!important;font-weight:800;font-size:10px;border-top:3px solid #f0a500!important;}.gt td.ar{font-family:Consolas,monospace;text-align:right;color:#f0a500!important;}.ar{text-align:right!important;font-family:Consolas,monospace;font-size:9px;min-width:65px;}.ac{text-align:center!important;font-size:9px;color:#6b7280;min-width:28px;}.bl{border-left:2px solid #dde4ef!important;}.fw{font-weight:700;}.no{font-size:9px;color:#9ca3af;text-align:center;width:22px;}.br{width:14px;}.pn{width:25px;text-align:center;font-size:9px;color:#9ca3af;}.nm{min-width:120px;}.zero{color:#d1d5db;}</style>"
VAR Hdr = "<div style='background:#003366;padding:14px 18px;border-bottom:4px solid #f0a500;display:flex;align-items:center;'><img src='https://i.ibb.co/rWhBLgw/image-2026-04-21-094244962.png' style='height:90px;object-fit:contain;flex-shrink:0;margin-right:20px;' /><div><div style='color:#fff;font-size:16px;font-weight:700;text-transform:uppercase;letter-spacing:1px;margin-bottom:3px;'>BANCO NACIONAL DE COMERCIO DE TIMOR LESTE</div><div style='color:#f0a500;font-size:11px;font-weight:600;text-transform:uppercase;margin-bottom:3px;'>REKAPITULASAUN DESEMBOLSU PRODUTU KREDITU HUSI SUCURSAL HOTU</div><div style='color:#cbd5e1;font-size:11px;'>" & ActiveYear & "</div></div></div>"
VAR TH = "<table class='ds-t'><thead><tr><td class='th thl' rowspan='2'>Nu.</td><td class='th thl' rowspan='2'>Sukursal</td><td class='th' rowspan='2'>Nu.<br>Prod.</td><td class='th thl' rowspan='2'>Produtu Kreditu</td><td class='th' colspan='2'>JANEIRU</td><td class='th' colspan='2'>FEVEREIRU</td><td class='th' colspan='2'>MARSU</td><td class='th' colspan='2'>ABRIL</td><td class='th' colspan='2'>MAIU</td><td class='th' colspan='2'>JUNU</td><td class='th' colspan='2'>JULLU</td><td class='th' colspan='2'>AGOSTU</td><td class='th' colspan='2'>SETEMBRU</td><td class='th' colspan='2'>OUTUBRU</td><td class='th' colspan='2'>NOVEMBRU</td><td class='th' colspan='2'>DEZEMBRU</td><td class='th' colspan='2' style='background:#f0a500!important;color:#003366!important;'>AKUMULASAUN</td></tr><tr><td class='mh bl'>Amt</td><td class='mh'>Acct</td><td class='mh bl'>Amt</td><td class='mh'>Acct</td><td class='mh bl'>Amt</td><td class='mh'>Acct</td><td class='mh bl'>Amt</td><td class='mh'>Acct</td><td class='mh bl'>Amt</td><td class='mh'>Acct</td><td class='mh bl'>Amt</td><td class='mh'>Acct</td><td class='mh bl'>Amt</td><td class='mh'>Acct</td><td class='mh bl'>Amt</td><td class='mh'>Acct</td><td class='mh bl'>Amt</td><td class='mh'>Acct</td><td class='mh bl'>Amt</td><td class='mh'>Acct</td><td class='mh bl'>Amt</td><td class='mh'>Acct</td><td class='mh bl'>Amt</td><td class='mh'>Acct</td><td class='mh bl'>Amt</td><td class='mh'>Acct</td></tr></thead><tbody>"

RETURN
    "<div class='ds'>" & Sty & Hdr & "<div style='overflow-x:auto;'>" & TH &
    IF(ISBLANK(SelectedBranch) || SelectedBranch = "DILI", BH1 & PR1 & ST1, "") &
    IF(ISBLANK(SelectedBranch) || SelectedBranch = "GLENO", BH2 & PR2 & ST2, "") &
    IF(ISBLANK(SelectedBranch) || SelectedBranch = "MALIANA", BH3 & PR3 & ST3, "") &
    IF(ISBLANK(SelectedBranch) || SelectedBranch = "AILEU", BH4 & PR4 & ST4, "") &
    IF(ISBLANK(SelectedBranch) || SelectedBranch = "OECUSSE", BH5 & PR5 & ST5, "") &
    IF(ISBLANK(SelectedBranch) || SelectedBranch = "BAUCAU", BH6 & PR6 & ST6, "") &
    IF(ISBLANK(SelectedBranch) || SelectedBranch = "SAME", BH7 & PR7 & ST7, "") &
    IF(ISBLANK(SelectedBranch) || SelectedBranch = "AINARO", BH8 & PR8 & ST8, "") &
    IF(ISBLANK(SelectedBranch) || SelectedBranch = "SUAI", BH9 & PR9 & ST9, "") &
    IF(ISBLANK(SelectedBranch) || SelectedBranch = "VIQUEQUE", BH10 & PR10 & ST10, "") &
    IF(ISBLANK(SelectedBranch) || SelectedBranch = "LOSPALOS", BH11 & PR11 & ST11, "") &
    IF(ISBLANK(SelectedBranch) || SelectedBranch = "LIQUICA", BH12 & PR12 & ST12, "") &
    IF(ISBLANK(SelectedBranch) || SelectedBranch = "MANATUTO", BH13 & PR13 & ST13, "") &
    IF(ISBLANK(SelectedBranch), GT, "") &
    "</tbody></table></div>" & Ftr & "</div></div>"

